### ISSUE TITLE
Issues with composite transforms in ANTS

### ISSUE THREAD

**Issue by hjmjohnson** [stnava/ANTs#120]
@aghayoor  Ali Ghayoor is working on this.  I'm posting here to keep track of it

(for Ali: https://www.icts.uiowa.edu/jira/browse/PREDICTIMG-3753)

You will need the HDFViewer to diagnose and debug these issues.
http://www.hdfgroup.org/products/java/release/download.html
Here is the test directory with test script and example data:
/Shared/johnsonhj/HDNI/20141019_AntsCompositeTransformOptimization/
This is a 4 stage registration.
Initialize with translation T ( --initial-moving-transform)
Apply Rigid R (--transform Rigid[...])
Apply Affine A (--transform Affine[...])
Apply SyN S (--transform SyN[.....])
==CONDITION A==
When the --write-composite-transform 1
It should produce two .h5 files
composite.h5 contains (T o R o A o S)
composite_inverse.h5 should contain ( inv(S) o inv(A) o inv(R) o inv(T) )
==CONDITION B==
When the --collapse-output-transforms 1 option is used, it should produce:
L = ( T o R o A ) (an affine transform)
composite.h5 contains (L o S)
composite_inverse.h5 should contain ( inv(S) o inv(L) )
BUGS: CONDITION B does not occur. It produces the same output as CONDITION A.
--collapse-output-transforms has no effect on the composite transform!
BUGS: If you investigate the T and inv(T) or the A and inv(A) transforms with the HDFViewer, you will notice that the fixed parameters were not properly propagated. the inv(A) and inv(T) transforms have zero vector fixed parameters. This is incorrect!

**Comment by stnava** [comment]
i believe this can be closed.  happy to reopen if need be.
