### ISSUE TITLE
ITK-build not inheriting Superbuild prefix

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#133]
I set CMAKE_INSTALL_PREFIX in the superbuild but when I run ``make install`` in ITKv4-build the install ends up in ../ITKv4-install instead of the prefix I specified.

Confirmed by examining the ccmake output in ITKv4-build

**Comment by gdevenyi** [comment]
Figured out the issue, superbuild is specifying these things:
in ANTS-build/CMakeCache.txt:
```
//No help, variable specified on the command line.
ANTS_CLI_INSTALL_ARCHIVE_DESTINATION:PATH=lib

//No help, variable specified on the command line.
ANTS_CLI_INSTALL_LIBRARY_DESTINATION:PATH=lib
```

And in ITKv4-build/CMakeCache.txt
```
CMAKE_LIBRARY_OUTPUT_DIRECTORY:PATH=/opt/quarantine/ANTs/2.1.0/src/superbuild/lib
CMAKE_RUNTIME_OUTPUT_DIRECTORY:PATH=/opt/quarantine/ANTs/2.1.0/src/superbuild/bin
```

Both these variables should be set to $PREFIX/bin and $PREFIX/lib so that ``make install`` will copy them there.

**Comment by stnava** [comment]
do you have a patch that we might be able to integrate?

or are you suggesting to just fix on your end?


brian

**Comment by gdevenyi** [comment]
I'm learning cmake right now, once I understand how this works a bit better I'll have a patch for this and for #159

**Comment by stnava** [comment]
thx


brian
