### ISSUE TITLE
ANTS_CC_3_WARP_METRIC_0 fails on 32bit with v2.1.0rc2-3-g9103999

### ISSUE THREAD

**Issue by yarikoptic** [stnava/ANTs#135]
as reported
https://buildd.debian.org/status/fetch.php?pkg=ants&arch=i386&ver=2.1.0~rc2%2Bgit3-g9103999-3&stamp=1415314134

before jumping into troubleshooting etc I thought to ask if that might sound like something known/fixed? or hints on how to troubleshoot/address ;-)

**Comment by yarikoptic** [comment]
so it is closed with a fix? (which commit) or just closed? ;-) @ntustison 

thanks

**Comment by ntustison** [comment]
Obviously we can reopen the issue.  Did you test Brian's suggestion?

**Comment by yarikoptic** [comment]
haven't yet... will do now... but was precision adjusted in your code?... checking it seems to be not, so issue is indeed still outstanding?

**Comment by ntustison** [comment]
Nope, we haven't done anything.  Since this seems to be specific to something that you're trying to do, any solution would have to come from your end.  And since this issue hadn't seen any action for about a year, I closed the issue in an effort to do some minor house cleaning.

**Comment by yarikoptic** [comment]
ha -- actually I did apply that patch

```
$> cat debian/patches/up_lower_cc_3_test_i386_precision
--- a/Examples/TestSuite/ANTS_CC_3_test.cmake
+++ b/Examples/TestSuite/ANTS_CC_3_test.cmake
@@ -23,7 +23,7 @@ set_property(TEST ${THIS_TEST_NAME}_JPG
 add_test(NAME ${THIS_TEST_NAME}_WARP_METRIC_0 COMMAND $<TARGET_FILE:MeasureImageSimilarity> 2 0
  ${R16_IMAGE} ${WARP_IMAGE}
  ${OUTPUT_PREFIX}log.txt ${OUTPUT_PREFIX}metric.nii.gz
- 14.3283 0.05)
+ 14.3283 0.1)
 set_property(TEST ${THIS_TEST_NAME}_WARP_METRIC_0 APPEND PROPERTY DEPENDS ${THIS_TEST_NAME}_WARP)
 
 add_test(NAME ${THIS_TEST_NAME}_WARP_METRIC_1 COMMAND $<TARGET_FILE:MeasureImageSimilarity> 2 1
```
and it did help: build succeded https://buildd.debian.org/status/package.php?p=ants

**Comment by yarikoptic** [comment]
it is not specific to what I am doing, but specific to the architecture (32bit) on which ants is built/tested.
