### ISSUE TITLE
RPI to LPI

### ISSUE THREAD

**Issue by elisewicks** [stnava/ANTs#143]
Hello developers,

Are there any tools to convert between these?

Thanks!
Elise

**Comment by vfonov** [comment]
c3d input.img -orient LPI -o output.img

http://www.itksnap.org/pmwiki/pmwiki.php?n=Convert3D.Documentation

**Comment by elisewicks** [comment]
Thanks so much for the feedback!

Due to large number of images, a command line approach is needed... I will
check if ITK-SNAP runs in batch mode.

On the other hand, it seems that c3d only changed the header info...

For MHD formats, I learned that c3d ignores the "AnatomicalOrientation"
tag, but rather uses the TransformMatrix to determine orientation; i.e.

[-1 0 0 0 -1 0 0 0 1]
vs.
[1 0 0 0 1 0 0 0 1]

Please let me know if you have other suggestions/thoughts.
Elise

**Comment by vfonov** [comment]
c3d documentation says "This command has the same behavior as the 'Reorient Image' menu option in ITK-SNAP."
