### ISSUE TITLE
ANTs official versions

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTs#144]
We are having difficulty in Nipype to stay up to date with regard to the command line changes in ANTs. I'm wondering whether it would be possible to have more regular official versions of ANTs to reduce the confusion, see for example  nipy/nipype#1014 . I'm really happy to compile ANTs every once in a while from Github, however, it makes communicating changes a bit difficult.

**Comment by stnava** [comment]
i would be happy to delegate this responsibility to someone - any takers?

just ask that we email / discuss / confirm when a release needs to happen.


brian

**Comment by satra** [comment]
@stnava - i think the only weird component is going to be ITK releases. i think if @armaneshaghi takes on the ants building could we try to convince the ITK crowd to make a minor release whenever we rebuild ants? 

i also see that 2.1.0 never got released it got stuck at rc2. and there are too many changes that has happened since then. perhaps we can to get things started by making an itk + ants release now with all the changes.

**Comment by stnava** [comment]
that's fine with me ... itk releases are on a regular schedule (quarterly,
i think) and have been for a long time.   we could simply follow the itk
releases.  however, one problem w/that is that itk releases lag itk
development.  so if we have anything in dev itk that we use in ants,
divergence occurs.   at times, it can be difficult to "match" the versions.
 right now, it's probably not an issue though.   i've added arman as
collaborator.


brian

**Comment by armaneshaghi** [comment]
I'm more than happy to help here, we would also need to add a file named "CHANGES" and require new PRs to add their changes into this file. I will rebuild ANTs and provide binaries for major linux distros and current OS Xs (Yosemite for now ) with each release. 


Exampel of CHANGES

Next release
============

* ENH: Updated N4BiasCorrection input spec to include weight image and spline order. Made 
	   argument formatting consistent. Cleaned ants.segmentation according to PEP8.
	   (https://github.com/nipy/nipype/pull/990/files)
* ENH: SPM12 Normalize interface (https://github.com/nipy/nipype/pull/986)

**Comment by satra** [comment]
@stnava - sounds good on the itk front. we can map on to the itk releases except for emergencies with bugs. 

is there an easy way to run the test-suite? i think one of the things that should happen is to enable a travis checker through a `.travis.yml` file and hook with travis. also travis now supports both ubuntu and os x, and windows for those that care.

**Comment by stnava** [comment]
yes - you just run "make test" or something like that ... maybe call ctest
directly.  i dont recall offhand:

http://www.cmake.org/cmake/help/v2.8.8/ctest.html


brian

**Comment by armaneshaghi** [comment]
I'll add travis support. Shall I make a final 2.1.0 now? The latest is rc3.

**Comment by stnava** [comment]
i am fine with that ...


brian

**Comment by ntustison** [comment]
Hi Brian,

A related topic is the windows release---perhaps an underserved segment of the population.  I've been told that the most recent one is from 2012.  Is there somebody that is capable of including this in the releases?

Thanks,
Nick

**Comment by stnava** [comment]
yes - dorian ( @dorianps ) has windows builds ... but a windows release
requires more than just building.  have to make the package - not sure if
dorian has gotten this far.


brian

**Comment by ntustison** [comment]
Hey, thanks Brian.  And thanks to everybody else for helping on this.

**Comment by dorianps** [comment]
The Windows version can be downloaded here:
https://www.dropbox.com/s/b3eydq338nol40s/ANTsBinaries-ShellScripts.zip?dl=0

This contains the executables and the scripts from the original scripts folder. One could just use the binaries to run commands in command line, but the full set of tools that include scripts require installation of Cygwin. After that I believe ANTs can be used in Windows just like in linux (not sure if Cygwin can run the ANTs perl scripts though).

Please note that I don't use ANTs for Windows, so cannot guarantee everything will be perfect. This said, I have run antsCorticalThickness.sh and buildparalleltemplate.sh which worked fine and with similar speed as in linux. More testing can be done by groups that will use the windows version regularly.

@stnava we can talk together how to create a package. My idea was to through everything in a zip file, including instructions, and provide that at a regular basis.

**Comment by stnava** [comment]
by package i mean an installer, i think they are in exe form on windows.
 this requires using cpack.   also, you should not need full cygwin for
this. git bash should be sufficient.


brian

**Comment by ntustison** [comment]
Thanks Dorian.  Somebody that's trying to use the package you built says that the following dll is missing:

MSVCP120.dll

Nick

**Comment by dorianps** [comment]
Apparently this is a problem that can be resolved by getting the Visual Studio Redistrib. Package (6Mb):
http://www.microsoft.com/en-us/download/details.aspx?id=40784

Choose the x64 for 64bit Windows, or x86 for 32bit. Don't choose "arm", that should be for phones and tablets. Several software that had the same error point to this download as the solution.

Will see if in the future we can create an installer package with everything included.

Dorian

**Comment by bkandel** [comment]
SNAP includes downloading a VS redistributable as part of the setup.exe
installer.  Might be something to look into.

**Comment by ntustison** [comment]
Thanks Dorian.

**Comment by ntustison** [comment]
According to my Windows colleague, that solution worked.  Thanks again, Dorian.

**Comment by stnava** [comment]
here are some scripts that octavian put together for building windows
installers ... not sure if things have changed since this time but might
provide some insight:  http://we.tl/1UUh00mD2B


brian

**Comment by armaneshaghi** [comment]
I will close this as we have had very good responses from everyone. Next release is coming next week.
