### ISSUE TITLE
travis support

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTs#146]
For travis support and automatic builds we need to add `.travis.yml` that can be hooked to travis only by the owner, @stnava . I can do the rest once the repo is hooked to travis. Please see https://travis-ci.org/getting_started and http://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator

**Comment by stnava** [comment]
i think this is done - let me know if something else is needed...


brian

**Comment by armaneshaghi** [comment]
Thanks Brian, @satra our build fails, because of the 50-minute limit on travis VMs. Do you have any ideas how to split the build process? Shall I split Cmake files? it is not going to be an easy task I think...

**Comment by stnava** [comment]
you might disable long tests and / or split the code building and the
testing ... not sure that will remedy entirely but should help


brian

**Comment by armaneshaghi** [comment]
`cmake -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=OFF` was more than 50 minutes, and when I tried to parallelize with make -j 2 ,  travis VM crashed half way though. I think the memory for these VMs is 3GB. I will keep this open in case anyone has a better idea.

**Comment by satra** [comment]
would it be possible to use a pre-compiled ITK/VTK? to reduce time?

**Comment by stnava** [comment]
yes.  possible but adds another layer of maintenance ... shouldnt be too
bad, if making releases anyway.

maybe use a faster machine?


brian

**Comment by armaneshaghi** [comment]
My only goal of adding this is to keep track PRs that break the build, and not for releases. I will build ANTs on Amazon EC2 instances, so there won't be any problem for releases. For travis VMs, however, there is not much that we can do, each VM has 1.5 CPU with 3GB of RAM

**Comment by satra** [comment]
another possibility is to use one of the following (i.e. running on one's own servers):

https://zapier.com/engineering/continuous-integration-jenkins-docker-github/
http://blog.drone.io/2014/2/5/open-source-ci-docker.html

@stnava - any chance of a machine at upenn to be available for running drone or jenkins?

**Comment by bkandel** [comment]
If ANTs builds are taking too long, maybe it's time for some housekeeping
anyway.  How about moving a bunch of the .cxx's from the Examples dir to
the ExternalApplications dir?  I imagine that 95% of the use of ANTs is for
about 10% of the programs in the Examples folder, and having all of the
other ones in the same directory increases the size of compiled ANTs (the
ANTs bin directory is 2.7GB on my machine) and compile time.  Maybe we
should have a "core" ANTs, including ANTS, antsRegistration,
N3/4BiasFieldCorrection, antsApplyTransforms, antsApplyTransformsToPoints,
ImageMath, and KellyKapowski/Slater, and move everything else to the
ExternalApplications dir.  (Feel free to quibble with the list, but those
are the ones I use mostly.)  A lot of the other programs are not all that
necessary now that we have ANTsR, and most of the image manipulation
programs can be taken care of by c3d and so are not really necessary for
most users of ANTs.

**Comment by armaneshaghi** [comment]
Found a "memory-friendly" compiler. Build passing. 
![ants_build](https://cloud.githubusercontent.com/assets/4290297/5838934/0500c18e-a1a0-11e4-9302-cb94bb3877c5.png)

**Comment by satra** [comment]
nice!

**Comment by satra** [comment]
perhaps also enable multi-os (linux and osx for now).

http://docs.travis-ci.com/user/multi-os/

**Comment by armaneshaghi** [comment]
I will close this issue as the issue is now resolved, mac support for travis is also on my to-do list.
