### ISSUE TITLE
Resample diffusion images (4D)

### ISSUE THREAD

**Issue by MarcRamos** [stnava/ANTs#147]
Hi guys!
I was trying to resample a 4 dimensional image with this function but I saw that it just accepts 2-3 dimensional image. I have modified the cxx (just added a new if case) and I tested and it works. How can I send this update to you? (Or maybe you are already working on a better solution for that :P)

Cheers,
Marc.

**Comment by MarcRamos** [comment]
this function - > ResampleImagebySpacing

**Comment by armaneshaghi** [comment]
Please send a pull request, and we will investigate. This might help: https://help.github.com/articles/using-pull-requests/
