### ISSUE TITLE
Version 2.2.0 Milestones

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTs#156]
Please define milestones for the next release here: 

  - Add auto versioning to all command line programs

Some ideas:

  - Add surface maps, and gyrification index to output of antsCorticalThickness.sh

please add ideas here...

**Comment by armaneshaghi** [comment]
@stnava @ntustison will you be happy to have more cortical indices (surface, gyrification, etc) similar to Freesurfer, in ANTs? I know we could get surface `LabelGeometryMeasures`, but I think we need to:

  - make it more user friendly, it means that the user runs only the script and gets those indices along with cortical thickness map

  - After the above step, I'm more than happy to validate it similar to Nick's paper, and based on my preliminary analyses on patients with multiple sclerosis, it is very likely that we could find that ANTs gives more "valid" measures compared to Freesurfer, for example. This will be a manuscript similar to Nick's.

  - Also we need to have a standard atlas, (like Desikan_Killiany in FS) to use by default. An inexperienced user, who just wants to get things done, will prefer to run `recon-all`.

I'm happy to spend a few months on this. Ideas?

**Comment by armaneshaghi** [comment]
My motivation to get this done ASAP:

In a patient with multiple sclerosis:

Green: Gray matter surface (or Pial surface)  by Freesurfer
Blue: White matter surface by Freesurfer
Read ribbon: ANTs cortical thickness map

![mail attachment](https://cloud.githubusercontent.com/assets/4290297/5903708/7d86ba5e-a598-11e4-9d96-0d191de5b84a.png)

**Comment by stnava** [comment]
i guess the concern is that FS is missing the temporal pole?  i see some
problems w/ants too but that's perhaps not as critical a failure ...

regardless, i've also been thinking about this and meaning to coordinate
with @ntustison ... we indeed have a (for us) standard *multi*atlas that we
are using in several different projects and would serve a similar purpose
as the DK FS atlas ...

i think there is a good solution that might follow the lines of

* template construction

* template multi-atlas labeling

* pseudo-geodesic jlf for each subject

* surface measurements ... note also that
https://github.com/stnava/ANTs/blob/master/Examples/SurfaceCurvature.cxx is
a powerful function that produces several types of geometric primitive
measurements & which is very flexible but hasnt been applied at large-scale

in brief, agree that we should develop a "put data in box get data out"
(including template) procedure.



brian

**Comment by armaneshaghi** [comment]
yes the problem is with temporal lobes, where FS's intensity normalizaition has failed. It happens a lot, at least in my patients (MS).

**Comment by stnava** [comment]
Would running n4 before fs help?

**Comment by armaneshaghi** [comment]
Don't know about n4, but n3 bias field correction is part of recon-all (so
it has been run here). The point however is that prior based segmentation
may be superior to what fs does. FS's problem could be due to intensity
normalisation,GM lesions, etc.

**Comment by ntustison** [comment]
N3BiasFieldCorrection in ANTs is not the same as N3 used in FS.

**Comment by armaneshaghi** [comment]
Sure, how about GM lesions?

**Comment by ntustison** [comment]
I wouldn't know.

**Comment by armaneshaghi** [comment]
So that was the motivation.

**Comment by armaneshaghi** [comment]
Talk is cheap, I will show you my code soon
