### ISSUE TITLE
Command line use of N4 in MacOS terminal

### ISSUE THREAD

**Issue by CommanderCody** [stnava/ANTs#160]
Hi,

I have recently started to use N4 as a command line installation and the bias field correction works great in general. I am trying to figure out how to configure the flags for best performance on our 3T T1, 1.5T T1 & T2 MR images. 

When trying the rescale intensities I get the error message "segmentation fault 11" for both options ( -r 1  as well as -r 0). It works fine in the default mode but do anyone use the -r flag with success?
I also have a problem with the bspline fitting flag which in my test-runs with e.g. -b [50,3] "destroys" the image. The default configuration works fine but I want to try out if different configurations works better for different field strengths and scan sequences so I wonder what a typical configuration of -b can look like?

**Comment by ntustison** [comment]
I would need to see the images along with the exact command line you're using which produces the problem.

**Comment by cookpa** [comment]
It's working for me on Mac OS X.

The spline distance starts out with the original spacing and then decreased by a factor of 2 at each level. So if you do

-b [50] 

with the default convergence (50x50x50x50), it will use spacing at 50, 25, 12.5, and 6.25 mm. A very high resolution spline might overfit. I think the default starting spacing is 200 mm.

**Comment by ntustison** [comment]
Thanks Phil.  I'm wondering if there's something specific to the images that @CommanderCody is using.

**Comment by CommanderCody** [comment]
Hi,
thanks Nick & Phil for your rapid response!

The first command below works fine and gives a fast but good biascorrection: 
bash-3.2$ N4BiasFieldCorrection  -i Thyro_003_601_T1W_3D_TFE.nii -s 2 —d 3 -c [20x20x20x40,0.0005] -o [003spline100b.nii,003bias_spline100b.nii]

but errors occur when using:

bash-3.2$ N4BiasFieldCorrection  -i Thyro_003_601_T1W_3D_TFE.nii -s 2 —d 3 —b [100] -o [003spline100c.nii,003bias_spline100c.nii]

Running N4 for 3-dimensional images.

Mask not read.  Creating Otsu mask.
libc++abi.dylib: terminating with uncaught exception of type itk::ExceptionObject: /Users/stnava/code/ants-src/ANTs/Examples/../Utilities/antsCommandLineParser.h:129:
itk::ERROR: CommandLineParser(0x7fd2b3010ce0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '' to type 'i' as signed int

Abort trap: 6

or:

bash-3.2$ N4BiasFieldCorrection  -i Thyro_003_601_T1W_3D_TFE.nii -s 2 —d 3 —b [100,3] -o [003spline100c.nii,003bias_spline100c.nii]

Running N4 for 3-dimensional images.

Mask not read.  Creating Otsu mask.
libc++abi.dylib: terminating with uncaught exception of type itk::ExceptionObject: /Users/stnava/code/ants-src/ANTs/Examples/../Utilities/antsCommandLineParser.h:129:
itk::ERROR: CommandLineParser(0x7fcfe87198d0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '' to type 'i' as signed int

Abort trap: 6


When using both -b and -c flags the process goes through the first iteration level to 100 and stops: 

bash-3.2$ N4BiasFieldCorrection  -i Thyro_003_601_T1W_3D_TFE.nii -s 2 —d 3 -c [20x20x20x40,0.0005] —b [100] -o [003spline100d.nii,003bias_spline100d.nii]

Running N4 for 3-dimensional images.

Mask not read.  Creating Otsu mask.
Current level = 1
  Iteration 1 (of 100).   Current convergence value = 0.000350994 (threshold = 0)

when using -b flag with both grid and spline order:

bash-3.2$ N4BiasFieldCorrection  -i Thyro_003_601_T1W_3D_TFE.nii -s 2 —d 3 -c [20x20x20x40,0.0005] —b [50,0.00004] -o [003spline100e.nii,003bias_spline100e.nii]

Running N4 for 3-dimensional images.

Mask not read.  Creating Otsu mask.
Current level = 1
  Iteration 1 (of 50).   Current convergence value = 0.000350994 (threshold = 4e-05)

the process iterates 50 times and stops. If I run -b [48x48,0.00004] it runs 48 iterations 2 times and stops in advance if the second value is higher than the current convergence value. Hence it seems like the values in the -b flag is interpreted as iteration number and convergence threshold respectively (overriding the values in the -c flag). 


Could my problems depend on my specific images? Below is a printout of header data for the 3T T1 image:

filename       Thyro_003_601_T1W_3D_TFE.nii

sizeof_hdr     348
data_type      INT16
dim0           3
dim1           352
dim2           352
dim3           170
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     Unknown
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        0.681818
pixdim2        0.681818
pixdim3        0.999893
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      10.281075
scl_inter      0.000000
phase_dim      1
freq_dim       2
slice_dim      3
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      169
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -0.001383  -0.009634  0.999791  -79.779991
qto_xyz:2      -0.681817  0.000613  -0.002016  125.390907
qto_xyz:3      0.000594  0.681750  0.014131  -106.223961
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Anterior-to-Posterior
qform_yorient  Inferior-to-Superior
qform_zorient  Left-to-Right
sform_name     Unknown
sform_code     0
sto_xyz:1      0.000000  0.000000  0.000000  0.000000
sto_xyz:2      0.000000  0.000000  0.000000  0.000000
sto_xyz:3      0.000000  0.000000  0.000000  0.000000
sto_xyz:4      0.000000  0.000000  0.000000  0.000000
sform_xorient  Unknown
sform_yorient  Unknown
sform_zorient  Unknown
file_type      NIFTI-1+
file_code      1
descrip        T1W_3D_TFE
aux_file       

The nifti-file is to large to upload also in gz compression so I have attached two slices exported from from ITK-snap, (they turned up stretched in the z-axis for some reason in the export format) the second slice is the N4 corrected:

![coronal_slice_0177](https://cloud.githubusercontent.com/assets/10727457/5935968/62c484f0-a6e0-11e4-9ca6-79bc6291c413.png)
![coronal_slice_0177n4corr](https://cloud.githubusercontent.com/assets/10727457/5935975/6f1af98c-a6e0-11e4-9abc-4d788325089f.png)

**Comment by ntustison** [comment]
Why are your dashes different on the command line?

**Comment by CommanderCody** [comment]
Thanks a lot Nick,
I saw the dash differences yesterday when I pasted the commands into this forum, but in the terminal window the dash differences were not visible. But when I type them carefully again all seem to work fine so this typo must be a result from my pasting from a txt document to the terminal window. Sorry for that.

Further I have questions about overfitting and finding an accurate level of the bias correction: 
If I remember right the tissue placed in the bore of a 3T scanner affects the bias field more than in 1.5T. I have attached some pictures of the bias field for the 3T images for spline distance 100 (with  3 iteration levels in -c ), default 200 (4 iteration levels), 300 (4 iteration levels) and 300 (with 3 iteration levels in -c) from left to right below.  I realise more investigations is needed to determine an appropriate correction, however I would appreciate some comments on the following sentences: The leftmost image window seems to be overfitted and the rightmost is underfitted. In the middle is the bias field close to the default values for the N4 command - should the default bias detection be regarded as closest or is it also overfitted? Could an accurate bias field for 1.5T images be expected to be more rightshifted in respect to my ordering below?
![skarmavbild 2015-01-28 kl 22 25 57](https://cloud.githubusercontent.com/assets/10727457/5947995/ac188ece-a741-11e4-914d-1c93e477425d.png)

**Comment by ntustison** [comment]
I'm guessing that's probably the case.

**Comment by cookpa** [comment]
The bias field is going to depend on more than just the magnet strength. The number and position of the receiver coils, for example. The bias field can be quite different with a different head coil, even on the same scanner.

I eyeball the bias field by opening the image in ITK-SNAP and adjusting the contrast. As you narrow the contrast window you will see that tissue contrast appears / disappears in some regions before others. After correction the intensity of similar tissues should be more even, but if too much correction is applied you will start to "correct" biological sources of contrast.

One other thing I would pay attention to is the masking - by default an Otsu segmentation is done but this is an uncontrolled variable in your experiments, maybe this masking behaves differently on 1.5T vs 3T data, for example. If you have a brain mask available you can pass it with -x, then you know exactly what's getting included.

**Comment by stnava** [comment]
looks resolved
