### ISSUE TITLE
normalizing variance images results in negative numbers

### ISSUE THREAD

**Issue by satra** [stnava/ANTs#164]
asking just in case one of you know the answer to this. for analyzing some task data, we use FSL which generates contrast and variance images in individual space. we then transform these through a field derived from a combination of freesurfer and ants based on mean functional to structural and structural to template registration.

however, we are noticing negative numbers in the brain of the variance images. we are using BSpline as the interpolation method to antsApplyTransforms. and that's causing issues.

**Comment by stnava** [comment]
Yes that is a known issue with the b-spline interpolator.  I suppose this
is technically an itk bug.

**Comment by satra** [comment]
is there a particular interpolator you would suggest/recommend?

**Comment by stnava** [comment]
linear has received the most attention


brian
