### ISSUE TITLE
expected file does not exist warning

### ISSUE THREAD

**Issue by satra** [stnava/ANTs#165]
i'm receiving this warning with antsCorticalThickness, and later on it crashes because the Posteriors don't exist.

could this come from a mismatch say in using skull-stripped images with templates? i'm using Nick's ADNI templates here.

 - any suggestions?

```
BEGIN >>>>>>>>>>>>>>>>>>>>
rm antsCT_BrainSegmentationWeightMask.nii.gz
END   <<<<<<<<<<<<<<<<<<<<


WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPosteriorsPreviousIteration01.nii.gz
WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPosteriorsPreviousIteration02.nii.gz
WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPosteriorsPreviousIteration03.nii.gz
WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPosteriorsPreviousIteration04.nii.gz
WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPosteriorsPreviousIteration05.nii.gz
WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPosteriorsPreviousIteration06.nii.gz
WARNING: expected temp file doesn't exist: antsCT_BrainSegmentationPreviousIteration.nii.gz

--------------------------------------------------------------------------------------
 Done with segmentation (exceeded max. iterations):  0h 0m 22s
--------------------------------------------------------------------------------------
```

**Comment by ntustison** [comment]
Hi Satra,

If I understand what you're asking, you can't use the antsCT script with pre-skull stripped images.  I've done it before but I had to modify the script.

Nick

**Comment by satra** [comment]
@ntustison - i took a look at the images (i was running them blindly before). they do have skull - so i thought they were skullstripped, but they aren't. so that's not the issue, they do have enlarged ventricles.

the fact that max iterations were exceeded, does that provide any clue.

**Comment by ntustison** [comment]
No, sorry, that doesn't help.  The fact that it only took 22 seconds tells me that the segmentation wasn't set up correctly.  Did the brain extraction complete as expected?

**Comment by satra** [comment]
here is the full output: http://pastebin.com/4mYL9Fqt

**Comment by ntustison** [comment]
One thing that's odd to me is that you get the expected output for certain programs early on but I don't see the output later in the routine.  For example, starting on line 84 we see the convergence information for N4 and later in the brain extraction step on line 1667 we see the expected output for Atropos.  But then during the brain segmentation step, those outputs are missing, e.g. lines 3881--, lines 3900--.  However, I don't see anywhere previous where something obviously went wrong.

**Comment by satra** [comment]
the strange thing is i used that exact same script for about 2900 images prior to this and that went fine - yet in this different dataset everyone fails. i'll keep looking. i'll try resetting the environment and see if that helps.

does antsct use /tmp for this? or does it create local tmp directories?

**Comment by ntustison** [comment]
It creates local tmp directories.  It dumps everything in the directory specified by the -o flag and then removes the temporary files at the end of each of the major steps.

**Comment by cookpa** [comment]
Might be worth running with -k 1 to keep all the intermediate output. 

Could memory be an issue? If commands fail on our cluster because of memory, the program often dies with no error message but the outputs don't appear

**Comment by satra** [comment]
@cookpa - changing the memory configuration and trying again. will post back in 12 hours!

**Comment by armaneshaghi** [comment]
@satra please use r3.4xlarge with less number of jobs than CPUs if on EC2.

**Comment by satra** [comment]
i'm still struggling with this one - i ran just one antsCT without SGE on one node. 

this is the file that doesn't seem to exist. where/when should this file be created?

antsCT_BrainSegmentation0N4.nii.gz

```
BEGIN >>>>>>>>>>>>>>>>>>>>
/data/software/ANTS//antsAtroposN4.sh -d 3 -b Socrates[1] -a /data/mdd/data/SUBJ/SUBJ_anatomical.nii.gz -x antsCT_BrainExtractionMask.nii.gz -m 3 -n 5 -c 6 -y 2 -y 3 -y 4 -y 5 -y 6 -p antsCT_BrainSegmentationPriorWarped%
02d.nii.gz -w 0.25 -o antsCT_Brain -u 1 -k 1 -s nii.gz -z 0
---------------------  Running antsAtroposN4.sh on master  ---------------------
BEGIN >>>>>>>>>>>>>>>>>>>>
/data/software/ANTS//ImageMath 3 antsCT_BrainSegmentationWeightMask.nii.gz PureTissueN4WeightMask antsCT_BrainSegmentationPriorWarped02.nii.gz antsCT_BrainSegmentationPriorWarped03.nii.gz antsCT_BrainSegmentationPriorWar
ped04.nii.gz antsCT_BrainSegmentationPriorWarped05.nii.gz antsCT_BrainSegmentationPriorWarped06.nii.gz
END   <<<<<<<<<<<<<<<<<<<<


BEGIN >>>>>>>>>>>>>>>>>>>>
/data/software/ANTS//ImageMath 3 antsCT_BrainSegmentation0N4.nii.gz TruncateImageIntensity /data/mdd/data/SUBJ/SUBJ_anatomical.nii.gz 0.025 0.995 256 antsCT_BrainExtractionMask.nii.gz
END   <<<<<<<<<<<<<<<<<<<<


BEGIN >>>>>>>>>>>>>>>>>>>>
/data/software/ANTS//N4BiasFieldCorrection -d 3 -i antsCT_BrainSegmentation0N4.nii.gz -x antsCT_BrainExtractionMask.nii.gz -s 2 -c [50x50x50x50,0.0000000001] -b [200] -o antsCT_BrainSegmentation0N4.nii.gz -w antsCT_Brain
SegmentationWeightMask.nii.gz

Running N4 for 3-dimensional images.

END   <<<<<<<<<<<<<<<<<<<<
```

**Comment by ntustison** [comment]
`antsCT_BrainSegmentation0N4.nii.gz` is created during the brain segmentation step in the call to `antsAtroposN4.sh`.

**Comment by satra** [comment]
@ntustison - so the second command above should produce it right?

**Comment by ntustison** [comment]
Yes.

**Comment by satra** [comment]
aha, so this is what i'm seeing:

```
/data/software/ANTS//ImageMath 3 antsCT_BrainSegmentation0N4.nii.gz TruncateImageIntensity /data/mdd/data/SUBJ/SUBJ_anatomical.nii.gz 0.025 0.995 256 antsCT_BrainExtractionMask.nii.gz
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /data/software/sources/build/ITKv4-install/include/ITK-4.7/itkImageToImageFilter.hxx:248:
itk::ERROR: LabelStatisticsImageFilter(0x4295690): Inputs do not occupy the same physical space! 
InputImage Direction: 9.9976785e-01 -2.1393690e-02 -2.6946968e-03
-2.1546298e-02 -9.9137759e-01 -1.2924989e-01
-9.1553782e-05 -1.2927795e-01 9.9160839e-01
, InputImage_1 Direction: 9.9976765e-01 -2.1384420e-02 -2.7114300e-03
-2.1555497e-02 -9.9137776e-01 -1.2924971e-01
-7.5878650e-05 -1.2927813e-01 9.9160837e-01

        Tolerance: 1.0000000e-06

Aborted (core dumped)
```

**Comment by satra** [comment]
@ntustison - any ideas for a fix to the imagemath problem? i'm seeing this on a different system now with  the current ants release.

**Comment by ntustison** [comment]
I haven't seen that error for awhile now.  A hack could be to add a [CopyImageHeaderInformation](https://github.com/stnava/ANTs/blob/master/Examples/CopyImageHeaderInformation.cxx) step to ensure that the header information for both input files are the same.  Brian and I have discussed compiling ANTs and upping the global tolerance for the image geometric differences but haven't done it yet.

**Comment by cookpa** [comment]
CopyImageHeaderInformation is one option. Beware though that the copy is itself subject to precision errors. The solution I proposed in this thread:

https://github.com/stnava/ANTs/issues/74#issuecomment-58901783

has helped others when encountering this error in the template building scripts. Basically, do something like

  CopyImageHeaderInformation t1.nii.gz t1.nii.gz t1_headerFix.nii.gz 1 1 1 0
  antsCorticalThickness ... -a t1_headerFix.nii.gz

**Comment by satra** [comment]
thanks @cookpa - i'll close this issue and continue on the other one.
