### ISSUE TITLE
ANTs compile error on windows 7(64bit) visual studio 2012(professional)

### ISSUE THREAD

**Issue by yinglilu** [stnava/ANTs#167]
I tried to compile ANTs on windows 7 (64bit) with visual studio 2012(professional version), Here are the steps:
1. download ZLib and install it. http://gnuwin32.sourceforge.net/packages/zlib.htm
2. git clone git://github.com/stnava/ANTs.git  (I believe it is the newest version, 2015/02/17)
3. mkdir antsbin
4. run cmake: source directory is c:\ANTs, binaries directory is c:\ANTsbin
    USE_SYSTEM_ITK is turned on
    tell cmake where ZLIB was installed.
5. get SuperBuild_ANTS.sln under c:\ANTsbin
6. open SuperBuild_ANTS.sln and click Build solution. Long wait...

I got some errors then, could you please take a look at it? It seems that the errors were caused by  'timedim' : undeclared identifier.

Here is the error list:
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(929): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(929): error C2227: left of '->GetOrigin' must point to class/struct/union/generic type [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(930): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(930): error C2227: left of '->GetBufferedRegion' must point to class/struct/union/generic type [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(930): error C2228: left of '.GetIndex' must have class/struct/union [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(931): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(931): error C2227: left of '->GetBufferedRegion' must point to class/struct/union/generic type [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(931): error C2228: left of '.GetSize' must have class/struct/union [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(932): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(932): error C2227: left of '->GetSpacing' must point to class/struct/union/generic type [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(933): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(933): error C2227: left of '->GetDirection' must point to class/struct/union/generic type [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(936): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(936): error C2227: left of '->GetInverse' must point to class/struct/union/generic type [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(944): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(946): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(947): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
8>C:\ANTS\Examples\antsSliceRegularizedRegistration.cxx(965): error C2065: 'timedim' : undeclared identifier [C:\antsbin\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]

**Comment by dorianps** [comment]
The errors you show seem to be in the Examples section, which also fails for me. You should have the binaries anyway, check the bin folder.

Did you use to have successfull build of Examples before, or is this the first time you are trying?

What I do to get a successful build of binaries is:
1. Don't set USE_SYSTEM_ITK
2. Don't move any files, whatever cmake is outputtting is ready for compile in VS.
3. I use VS 2013.
4. MOST IMPORTANT: I have recently noticed that there is a missing file CMake/ProjectSourceVersionVars.cmake
which you can get by copying ProjectSourceVersionVars.cmake.in without '.in'

Dorian

**Comment by stnava** [comment]
This is on my to do list but I am sure that you can fix yourself.  Errors
seem clear and localized.  I don't have a windows machine so will make a
guess about the issue.

**Comment by yinglilu** [comment]
Thank you so much for the quick response.

This is the line 924-974 from antsSliceRegularizedRegistration.cxx
--------
// now apply to the inverse mapﬁ
      for( unsigned int timedim = 0; timedim < timedims; timedim++ )
        {
		typedef typename itk::TransformToDisplacementFieldFilter<DisplacementFieldType, RealType> 
			_ConverterType;
        typename _ConverterType::Pointer converter = _ConverterType::New();
        converter->SetOutputOrigin( movingSliceList[timedim]->GetOrigin() );
        converter->SetOutputStartIndex( movingSliceList[timedim]->GetBufferedRegion().GetIndex() );
        converter->SetSize( movingSliceList[timedim]->GetBufferedRegion().GetSize() );
        converter->SetOutputSpacing( movingSliceList[timedim]->GetSpacing() );
        converter->SetOutputDirection( movingSliceList[timedim]->GetDirection() );
        typename TranslationTransformType::Pointer invtx = TranslationTransformType::New();
        invtx->SetIdentity();
        transformList[timedim]->GetInverse( invtx );
        converter->SetTransform( invtx );
        converter->Update();

        // resample the moving image and then put it in its place
        typedef itk::ResampleImageFilter<FixedImageType, FixedImageType> ResampleFilterType;
        typename ResampleFilterType::Pointer resampler = ResampleFilterType::New();
        resampler->SetTransform( invtx );
        interpolator->SetInputImage( fixedSliceList[timedim] );
        resampler->SetInterpolator( interpolator );
        resampler->SetInput( fixedSliceList[timedim] );
        resampler->SetOutputParametersFromImage( movingSliceList[timedim] );
        resampler->SetDefaultPixelValue( 0 );
        resampler->Update();

        /** Here, we put the resampled 2D image into the 3D volume */
        typedef itk::ImageRegionIteratorWithIndex<FixedImageType> Iterator;
        Iterator vfIter2(  resampler->GetOutput(), resampler->GetOutput()->GetLargestPossibleRegion() );
        for(  vfIter2.GoToBegin(); !vfIter2.IsAtEnd(); ++vfIter2 )
          {
          VectorType vec = converter->GetOutput()->GetPixel( vfIter2.GetIndex() );
          VectorIOType vecout;
          vecout.Fill( 0 );
          typename MovingIOImageType::IndexType ind;
          for( unsigned int xx = 0; xx < ImageDimension; xx++ )
            {
            ind[xx] = vfIter2.GetIndex()[xx];
            vecout[xx] = vec[xx];
            }
          unsigned int tdim = timedim;
          if( tdim > ( timedims - 1 ) )
            {
            tdim = timedims - 1;
            }
          ind[ImageDimension-1] = tdim;
          displacementinv->SetPixel( ind, vecout );
          }
        }
----

I tried to  comment everything in the brace, then compile it, nothing wrong,
 for( unsigned int timedim = 0; timedim < timedims; timedim++ )
        {
          //comment everything in the brace
        }

Then, add one sentence, compile it, got the same error: error C2065: 'timedim' : undeclared identifier 
 for( unsigned int timedim = 0; timedim < timedims; timedim++ )
        {
         timedim = timedim + 1;
        }

**Comment by yinglilu** [comment]
@dorianps 

USE_SYSTEM_ITK is turned off.
Did not moving anything of the cmake output. 
opened SuperBuild_ANTS.sln to build.
ProjectSourceVersionVars.cmake is already in there, since I git clone the source code this morning.

**Comment by dorianps** [comment]
@yinglilu 
Do you get the binaries out of the build?

**Comment by yinglilu** [comment]
Yes. But missing antsSliceRegularizedRegistration.exe

**Comment by dorianps** [comment]
Just checked, that is missing from my build as well.

**Comment by yinglilu** [comment]
I got that file on Linux.

**Comment by stnava** [comment]
i attempted a fix for this - though i cant see why there is a problem
anyway ... the attempt is to define timedim outside of the loop.   let me
know if this helps.


brian

**Comment by stnava** [comment]
here:
https://github.com/stnava/ANTs/commit/83a849bca0301500df43b19e76ef83efeba0f233#diff-9d6665617c350055b25ec00ed71013a1R925


brian

**Comment by yinglilu** [comment]
@stnava 

Tried to define timedim outside of the loop. Got same errors as define timedim in the loop.

**Comment by yinglilu** [comment]
@stnava 
This is really weird. There is nothing wrong with g++.

**Comment by stnava** [comment]
chalk it up to windows being a real piece of s***


brian

**Comment by stnava** [comment]
made another attempt but am guessing that someone w/a windows machine will
need to figure out the trick


brian

**Comment by yinglilu** [comment]
here is the line 874-922, the usage of timedim is exactly same, but nothing wrong.
//
for(unsigned int timedim = 0; timedim < timedims; timedim++ )
      {
      typedef typename itk::TransformToDisplacementFieldFilter<DisplacementFieldType, RealType>
               _ConverterType;
      typename _ConverterType::Pointer converter = _ConverterType::New();
      converter->SetOutputOrigin( fixedSliceList[timedim]->GetOrigin() );
      converter->SetOutputStartIndex( fixedSliceList[timedim]->GetBufferedRegion().GetIndex() );
      converter->SetSize( fixedSliceList[timedim]->GetBufferedRegion().GetSize() );
      converter->SetOutputSpacing( fixedSliceList[timedim]->GetSpacing() );
      converter->SetOutputDirection( fixedSliceList[timedim]->GetDirection() );
      converter->SetTransform( transformList[timedim] );
      converter->Update();

      // resample the moving image and then put it in its place
      interpolator->SetInputImage( movingSliceList[timedim] );
      typedef itk::ResampleImageFilter<FixedImageType, FixedImageType> ResampleFilterType;
      typename ResampleFilterType::Pointer resampler = ResampleFilterType::New();
      resampler->SetTransform( transformList[timedim] );
      resampler->SetInterpolator( interpolator );
      resampler->SetInput( movingSliceList[timedim] );
      resampler->SetOutputParametersFromImage( fixedSliceList[timedim] );
      resampler->SetDefaultPixelValue( 0 );
      resampler->Update();

      /** Here, we put the resampled 2D image into the 3D volume */
      typedef itk::ImageRegionIteratorWithIndex<FixedImageType> Iterator;
      Iterator vfIter2(  resampler->GetOutput(), resampler->GetOutput()->GetLargestPossibleRegion() );
      for(  vfIter2.GoToBegin(); !vfIter2.IsAtEnd(); ++vfIter2 )
        {
        typename FixedImageType::PixelType  fval = vfIter2.Get();
        VectorType vec = converter->GetOutput()->GetPixel( vfIter2.GetIndex() );
	      VectorIOType vecout;
	      vecout.Fill( 0 );
        typename MovingIOImageType::IndexType ind;
        for( unsigned int xx = 0; xx < ImageDimension; xx++ )
          {
          ind[xx] = vfIter2.GetIndex()[xx];
          vecout[xx] = vec[xx];
          }
        unsigned int tdim = timedim;
        if( tdim > ( timedims - 1 ) )
          {
          tdim = timedims - 1;
          }
        ind[ImageDimension-1] = tdim;
        outputImage->SetPixel(ind, fval);
        displacementout->SetPixel( ind, vecout );
        }
      }

**Comment by stnava** [comment]
bizarre - what did you change?

does the current version (in git) compile for you?


brian

**Comment by yinglilu** [comment]
I didn't change anything. I git cloned the source code from github this morning.

**Comment by stnava** [comment]
i just made a commit a few minutes ago ... you can update via "git pull"
and then try to compile to see if the current "fix" helps windows
understand what's happening.


brian

**Comment by yinglilu** [comment]
Please give me 15-20mins...

**Comment by yinglilu** [comment]
Bingo!!! Succeed.

**Comment by yinglilu** [comment]
Stnava & dorianps,

Thank you so much for your help.

**Comment by dorianps** [comment]
@stnava shall I build this latest varion and upload it with 2.1.0 binaries?

**Comment by stnava** [comment]
Probably no need for that ....
