### ISSUE TITLE
Structures for deep GM probability map for cortical thickness

### ISSUE THREAD

**Issue by chrisadamsonmcri** [stnava/ANTs#169]
What are the structures that should be used for the "Deep GM" probability map in antsCorticalThickness.sh?

I'm trying to use Freesurfer labels to construct the prior maps but I can't get my maps to match up with the ones in the ANTSR template list, so the OASIS, IXI etc...

Thank you in advance.

**Comment by ntustison** [comment]
This directory 

https://drive.google.com/folderview?id=0B4SvObeEfaRyZGhlUlJOcmItTVU&usp=sharing

contains the OASIS template and derivative images used for the paper.  This is the template

https://drive.google.com/file/d/0B4SvObeEfaRyMWFReHA5eW9tbFk/view?usp=sharing

and this is the label image 

https://drive.google.com/file/d/0B4SvObeEfaRyTVg4TTVvTFdRYUk/view?usp=sharing

where label 4 denotes the deep gm structure.

**Comment by ntustison** [comment]
Oops, sorry, label 3 denotes deep gm.

**Comment by chrisadamsonmcri** [comment]
Thank you for the quick reply. I am still unable to find a list of specific structures included in the label, but I think I can work with this.
