### ISSUE TITLE
Apply Transform between 3D images to 3D image stack (4D)

### ISSUE THREAD

**Issue by gkiar** [stnava/ANTs#170]
I am using ANTs to register structural and diffusion MRI data. When computing the transform mapping my diffusion data to the structural space, I am using the first scan of diffusion data (termed B0) since it is most similar to the structural data. Then, once the transform is computed, I would like to apply the .mat matrix returned to the stack of diffusion images. By "stack", I mean that the diffusion image file consists of a series of 3D volumes, all of which should be transformed. Is there an easy way to achieve this in ANTs? Does the antsApplyTransform function have capability for this?
Many thanks, G.

**Comment by cookpa** [comment]
Hi,

If your images are stored as a 4D stack, you should be able to apply it with 

  antsApplyTransforms -d 3 -e 3 -t yourAffine.mat ...
