### ISSUE TITLE
Longitudinal cortical thickness

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTs#172]
@ntustison In `antsLongitunalCorticalThickness` I've noticed the script  assumes that there is already a group based template (which takes as an option), and then tries to construct the subject specific template and so on. I wonder if we should first make subject specific templates, and then based on that construct a group wise template to get the most symmetric group-wise template (e.g., when some time-points are missing for some subjects)?

**Comment by ntustison** [comment]
The group template is only used to propagate priors to the single subject template and that process is pretty robust to choice of group template.  If necessary, you could build your own group template from your study data and create priors for that group template which would probably produce similar, if not identical, results as the scheme you've described.  Besides, the changes you've proposed would take the longitudinal script with application to an individual subject (with multiple time points) to an application across the entire cohort.  That's different than what is currently intended.

**Comment by armaneshaghi** [comment]
Thanks, let me know if I can help there.

**Comment by ntustison** [comment]
Thanks.  Just as an FYI, we've liked the results that we've seen so far with this script.  We processed the entire ADNI cohort but are still working on the manuscript.  The only major question that remains is the proper prior weighting value for segmenting the priors in the individual time points from the SST (-w option).  In the original cortical thickness paper, we use a weighting of 0.25 and we continue to use that value for segmenting the SST from the group template (-v option).  Brian's intuition based on our cross sectional work was to use 0.5 for segmenting the individual time points but we haven't done any large-scale testing of that particular value.

**Comment by armaneshaghi** [comment]
happy to help, so here again in the absence of the ground truth we need to
do linear regression to see for example which prior weighting better
correlates with the cognitive scores? Because this is longitudinal we
perhaps need to do mixed effects analysis, subjects with random effects and
groups with fixed effects. Then we can compare each prior weighting.

**Comment by stnava** [comment]
yes - we've been using mixed effects.

the short story is that with noisier data, you may need a stronger prior to
get consistent estimates across time.  however, the strong prior may also
reduce sensitivity in the case of less noisy data (e.g. adni, most
pediatric).  so choose 0.5 in the former case and 0.25 in the latter.

as nick said, though, havent tested 0.25 vs 0.5 yet in the less noisy case
(only in the noisy case).


brian

**Comment by armaneshaghi** [comment]
I'm happy to do the testing for this as part of your main project (if
desired).
