### ISSUE TITLE
antsApplyTransforms adds extra dimension in header

### ISSUE THREAD

**Issue by satra** [stnava/ANTs#173]
antsApplyTransforms appears to leave an redundant time dimension = 1 in the header when applying the transform to 3d images.

**Comment by ntustison** [comment]
I can't verify that.  Can you explain a bit more?  e.g., what tools are you using to verify an extra dimension?

**Comment by satra** [comment]
@ntustison - nibabel which simply reads it from the header as well as fslhd

from fslhd:
```
filename       fmri_results/individual/model01/task001/SAD_019/copes/mni/cope01.nii.gz

sizeof_hdr     348
data_type      FLOAT32
dim0           4
dim1           91
dim2           109
dim3           91
dim4           1
```

the fact that dim0 == 4 (indicates the file has 4 dimensions)

**Comment by ntustison** [comment]
Is this image-specific?  Also, is the input a 3-D image?  The output appears to be a 4-D image + extra dim.  

Anyway, I just ran a 3-D image through antsApplyTransforms, read the header using PrintHeader and ITK appears to be reading the output as a 3-D image.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ntustison@Mactatus-Logico-Philosophicus Tue Mar 17 12:46:47] $ PrintHeader test.nii.gz 
 Spacing [1.2, 1, 1]
 Origin [202.8, 0, 0]
 Direction 
-1 0 0
0 1 0
0 0 1

 Size : 170 256  256

  Image Dimensions   : [170, 256, 256]
  Bounding Box       : {[202.8 0 0], [406.8 256 256]}
  Voxel Spacing      : [1.2, 1, 1]
  Intensity Range    : [0.0185521, 6.92085]
  Mean Intensity     : 1.02122
  Direction Cos Mtx. : 
-1 0 0
0 1 0
0 0 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by satra** [comment]
it seems anything i run through antsapplytransforms has this, not the image before this.

could you check bytes of the uncompressed file following the header:

http://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h

for example:

```
hexdump -n 41 cope01.nii 
0000000 015c 0000 0000 0000 0000 0000 0000 0000
0000010 0000 0000 0000 0000 0000 0000 0000 0000
0000020 0000 0000 0000 0072 0004               
0000029
```

the last 4 indicates that there are four dimensions

**Comment by stnava** [comment]
hexdump -n 41 T_template0.nii

0000000 5c 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0000020 00 00 00 00 00 00 72 00 03

0000029


brian

**Comment by ntustison** [comment]
~~~~~~~~~~~~~~~~~~~~
[ntustison@Mactatus-Logico-Philosophicus Tue Mar 17 13:38:18] $ hexdump -n 41 test.nii 
0000000 5c 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000020 00 00 00 00 00 00 72 00 03                     
0000029
~~~~~~~~~~~~~~~~~~~~

**Comment by satra** [comment]
hmmm - obviously there is something special about my pipeline. it could be a specific version of ants + itk - i'll check some more.

**Comment by satra** [comment]
just to note that i'm not insane:

ants version: 2.1.0

```
$ cat command.txt 
antsApplyTransforms --float --default-value 0 --input cope1.nii.gz --input-image-type 3 
--interpolation Linear --output cope1_trans.nii.gz --reference-image OASIS-30_Atropos_template_in_MNI152_2mm.nii.gz --transform [antsRegister/output_Composite.h5,0] 
--transform [convert2itk/affine.txt,0]

$ fslhd cope1_trans.nii.gz | grep dim0
dim0           4

$ fslhd cope1.nii.gz | grep dim0
dim0           3

$ fslhd OASIS-30_Atropos_template_in_MNI152_2mm.nii.gz | grep dim0
dim0           3
```

**Comment by ntustison** [comment]
Try replacing all your transforms with just "-t identity".  Then see if the output image dimension is the same.  That would rule out the transform file(s) itself as a possible cause.

**Comment by satra** [comment]
that didn't work but gave a clue - i specified image-input-type as 3 (i'll have to check where this comes from), but that refers to a time series and their output uses that even though the input dim is 3. so ants is trusting image input type over the dimension in the file itself.

**Comment by satra** [comment]
ok - so changing the `--image-input-type` fixed the issue, but i think it would be nice for ants to check the dimension of the image and overwrite the `--image-input-type` if it's a 3d image.
