### ISSUE TITLE
Remove compiler warnings: TransformType

### ISSUE THREAD

**Issue by stnava** [stnava/ANTs#176]
lots of these on linux gcc (GCC) 4.4.6

/home/avants/ANTsR/src/ants/Examples/antsRegistration4DDouble.cxx:8:   instantiated from here
/home/avants/ANTsR/src/ants/Examples/itkantsRegistrationHelper.h:818: warning: declaration of ‘TransformType’ shadows a member of 'this'

**Comment by ntustison** [comment]
Right.  I fixed that this morning.  Have you tried to compile since about 11 am your time?

**Comment by stnava** [comment]
yes - but probably using an older version of ants, i.e. whatever is in
github antsr gittag.

so will close.


brian
