### ISSUE TITLE
itkWarpImageMultiTransformFilter EdgePaddingValue Bug

### ISSUE THREAD

**Issue by mwoletz** [stnava/ANTs#177]
There seems to be a bug in the itkWarpImageMultiTransformFilter. Even though the header file says the EdgePaddingValue will be used for pixels outside the original image, it will use the value in the zeroth pixel for these pixels.
The relevant lines seem to be lines 328-331 in https://github.com/stnava/ANTs/blob/master/Utilities/itkWarpImageMultiTransformFilter.hxx, where any value set from the outside (such as used by the program WarpImageMultiTransform) will be replaced by this value.
```C++
IndexType index;

index.Fill(0);
this->m_EdgePaddingValue = inputPtr->GetPixel(index);
```

**Comment by stnava** [comment]
yes - we suggest using antsApplyTransforms .... this is the program that
replaces WIMT with more complete functionality and better implementation.


brian

**Comment by bkandel** [comment]
I just had another question from a different user about a WIMT bug.  Should
we remove it from ANTs to force use of antsApplyTx?

2015-04-08 11:54 GMT-04:00 stnava <notifications@github.com>:

> yes - we suggest using antsApplyTransforms .... this is the program that
> replaces WIMT with more complete functionality and better implementation.
>
>
> brian
>
>
>

**Comment by stnava** [comment]
we should add a note to the documentation that suggests using
antsApplyTransforms and warns that WIMT is not maintained.  longer term, we
can move toward a release that does major clean up.  but that will take
some careful consideration for which we will need to make time.


brian
