### ISSUE TITLE
Normalization of brain images with inflated ventricles

### ISSUE THREAD

**Issue by dicaincadi** [stnava/ANTs#178]
High experts,

We are performing ANTS transformation of T1-weighted brain MRI from subject space to standard MNI space. While checking the transformation, in the back projection, we observe that gray matter tissue has moved into the ventricles (see attached snapshots)

![screen shot 2015-04-08 at 14 18 29](https://cloud.githubusercontent.com/assets/11926613/7118962/8d2fc9cc-e1d0-11e4-9244-ddfc60ec94af.png)

The diffeomorphic mapping employed was SyN and affine transformation. We have employed either CC or MI as fitness metric, and we have varied the radius, obtaining a better result with larger radius (>5). However we always have issues within the ventricles.

What would you reccomend us to face this?
This is the code line we were employing.
ANTS 3 -m CC[$templateName,$movingIM,1,7] -t SyN[0.25] -r Gauss[3,0] -o $normAnatOutDir/T1_fov_denoised -i 100x100x100x30 --use-Histogram-Matching  --number-of-affine-iterations 10000x10000x10000

Any advide will be really appreciated.

Thanks

José

**Comment by stnava** [comment]
hi jose

i think this question needs to be clearer.  the picture doesn't tell us
much except that the registration is largely in the right zone.  i doubt
that gray matter is, as you say, "moving into the ventricles".  the
diffeomorphic transformation prevents that.  you may be seeing some
interpolation artifacts or something else.

please try to clarify your question.


brian

**Comment by stnava** [comment]
will reopen issue if the user has further input.
