### ISSUE TITLE
N4BiasFieldCorrection masking

### ISSUE THREAD

**Issue by katherinegray** [stnava/ANTs#181]
Hi,

When running N4BiasFieldCorrection with a mask specified using the -x option, I'm seeing that voxel intensities outside of the masked region are changed as well as those within the masked region in the output corrected image. Could you let me know if this is an expected behaviour? From the documentation, I had understood that if a mask is applied this is used both for bias field estimation, and also as the region over which the bias field correction is applied

Many thanks!

Kat

**Comment by ntustison** [comment]
I just did a quick check using a 2-D slice available from [here](https://github.com/ntustison/antsBrainExtractionExample) and I'm not seeing the behavior you describe:

```
N4BiasFieldCorrection -d 2 -i KKI2009-01-MPRAGE_slice150.nii.gz -x Output/exampleBrainExtractionMask.nii.gz -o test.nii.gz
```

Making the data available and the command line call available would be helpful.

**Comment by katherinegray** [comment]
Hi,

Many thanks for the fast response!

I've just run the command as above with the images downloaded from the above directory as:
N4BiasFieldCorrection -d 2 -i KKI2009-01-MPRAGE_slice150.nii.gz -x exampleBrainExtractionMask.nii.gz -o N4out.nii.gz

And I'm still seeing the same behaviour - very strange! I've copied my output file to:
https://github.com/katherinegray/TestImages

The bias correction itself looks good, just wondering why the intensities outside the mask are also changing - it would be great if you could take a look!

Kat

**Comment by ntustison** [comment]
Your output values are completely different from mine.  When was the last time you updated your repo?

**Comment by katherinegray** [comment]
Hmm good point, it seems that this copy I've been using is not so recent, sorry I didn't notice that before asking, but thanks very much for taking a look!

Just thinking that perhaps I should expect that the bias correction will cause changes in intensity across the whole image (not only within the masked region) to avoid discontinuities at the boundary - does that make sense?

**Comment by ntustison** [comment]
The expected behavior is as described by the help menu.  Please update and see for yourself.

**Comment by ntustison** [comment]
Closing this issue for now.  Might need to reopen if the suggestion doesn't fix the problem.

**Comment by katherinegray** [comment]
Updated and all looking as expected now, thanks very much for your help with what turned out to be a bit of a stupid question!

**Comment by ntustison** [comment]
Perfect.  Glad it worked.
