### ISSUE TITLE
CreateTiledMosaic fails with no overlay

### ISSUE THREAD

**Issue by spinicist** [stnava/ANTs#182]
Hello,

If I call CreateTiledMosaic without an overlay, e.g.:
CreateTiledMosaic -i input_file.nii -o test_mosaic.png -t 5x5

I receive the following exception:
libc++abi.dylib: terminating with uncaught exception of type itk::ExceptionObject: /Users/Tobias/Code/ANTs-build/ITKv4/Modules/IO/PNG/src/itkPNGImageIO.cxx:519:
PNG supports unsigned char and unsigned short

I have used ConvertImagePixelType to try pixel formats of unsigned char (UINT8), unsigned short (UINT16) and float, but all generate the same error. Trying to output in JPG gives a similar error. If I add an overlay, CreateTiledMosaic runs fine, even with a float image as the input.

This is with the master branch, updated today.

Toby

**Comment by ntustison** [comment]
The output has to be .nii.gz, .mhd, etc. (not .png or .jpg) format if you don't use an overlay.

**Comment by spinicist** [comment]
Okay - could this restriction be added to the usage string please?

**Comment by ntustison** [comment]
Sure, I'll get to it.  However, please know that we always welcome contributions from users in the form of git pull requests.

**Comment by cookpa** [comment]
Fixed by #1849

**Comment by spinicist** [comment]
⏳👀😳🎉😅
