### ISSUE TITLE
antsApplyTransforms in verbose

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTs#184]
Dear Nick,

Thanks for the toolkit.  Unfortunately, `antsApplyTransforms` is, by default, in verbose mode.  Please correct as soon as possible.

Thanks,
Nick

**Comment by FrancoisRheaultUS** [comment]
Great presentation in McGill, same issue here.
Please fix as soon as possible ;)

Francois R.

**Comment by ntustison** [comment]
Hey, thanks for this.  I will asap.

**Comment by ntustison** [comment]
Okay, this was taken care of a couple months ago.  Will update the binaries at some point to reflect this change.
