### ISSUE TITLE
itkAvantsMutualInformationRegistrationFunction occasionally seg faults

### ISSUE THREAD

**Issue by pnlbwh** [stnava/ANTs#185]
I'm using this class to compute the mutual information between two images and occasionally
it seg faults.  Any idea why this might be?

**Comment by stnava** [comment]
hi - i personally haven't used that function for some time .... the v4
version of the mattes metric

http://www.itk.org/Doxygen/html/classitk_1_1MattesMutualInformationImageToImageMetricv4.html

is much better and i would recommend that.



brian

**Comment by pnlbwh** [comment]
Hi Brian,

Thanks for the tip.  I can't find any examples that don't also use registration, do you know how to just get the mutual information between two images?  (with AvantsMutualInformation I'm calling `metricptr->ComputeMutualInformation()`)

**Comment by stnava** [comment]
typedef itk::MattesMutualInformationImageToImageMetricv4 <ImageType,
ImageType, ImageType> MetricType; unsigned int bins = 32; typename
MetricType::Pointer metric = MetricType::New(); metric->SetFixedImage(
image1 ); metric->SetMovingImage( image2 ); metric->SetNumberOfHistogramBins(
bins ); metric->Initialize(); mi = metric->GetValue(); return mi;


brian

**Comment by pnlbwh** [comment]
Great, thanks!
