### ISSUE TITLE
Enhancement: Masks should apply on a per-stage basis in antsRegistration

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#186]
When I specify a mask via ``"--masks [fixedmask,movingmask]`` can I do so on a per-stage basis?

The documentation states:
```
     -x, --masks [fixedImageMask,movingImageMask]
          Image masks to limit voxels considered by the metric. 
```

This hints to me that it is per-stage, is that true?

**Comment by ntustison** [comment]
Not yet.  I've been meaning to fix this for awhile.  I'll try to get to it soon.

**Comment by gdevenyi** [comment]
Thanks for the clarification, the addition of a per-stage mask would be awesome.

**Comment by ntustison** [comment]
Let's go ahead and keep this open to serve as a reminder.  I don't think there's another issue open pertaining to the mask per level.

**Comment by ntustison** [comment]
Okay, this should be complete with this [commit](https://github.com/stnava/ANTs/commit/27a23b4590411ae59a7157aa378827e8ac53e8dd).   I'll close this but let me know if anything needs to be fixed.

**Comment by gdevenyi** [comment]
Nice! Thanks very much!

**Comment by gdevenyi** [comment]
Quick clarification, what if I wanted stages without a mask and stages with, is it possible to implement that in this structure? Maybe specify "NULL" for a mask?

**Comment by gdevenyi** [comment]
It looks like this implementation will use a mask if it is specified anywhere on the command line. I would like to request a modification:

If masks are specified outside the stages, the same mask is used for all stages. If a mask is specified within a stage, it is only used within that stage.

This is particularly important if you want to make calls with something like Rigid -> Affine -> Affine (with mask) -> Syn (with mask).

**Comment by ntustison** [comment]
Did you see the help menu?

>     -x, --masks [fixedImageMask,movingImageMask]
>          Image masks to limit voxels considered by the metric. Two options are allowed 
>          for mask specification: 1) Either the user specifies a single mask to be used 
>          for all stages or 2) the user specifies a mask for each stage. Note that we 
>          handle the fixed and moving masks separately to enforce this constraint.

**Comment by gdevenyi** [comment]
Okay, I'll restate my case slightly, what if I want to do:
Rigid -> Affine -> Syn (with mask)

As I understand the help, my mask would apply at all stages, or is there a way I can specify a null mask?

**Comment by ntustison** [comment]
Okay, I understand now.  I'll have to think about that since there isn't a straightforward solution with the way the command line works.  However, for now, you can simply create a mask the size of your image with all ones to use for the affine and rigid stages which would be equivalent to what you want.

Rigid (with maskOnes) -> Affine (with maskOnes) -> SyN (with mask)

**Comment by gdevenyi** [comment]
Okay, I see the currently implementation would make such a request difficult. The all-ones mask easy to manage. Thanks for your help!

**Comment by ntustison** [comment]
Okay, Gabriel, I think the latest [commit](https://github.com/stnava/ANTs/commit/385431398cc127178c66fd7c4d61c1a4552726ac) should do what you want without having to create masks of all ones.  You still have to specify a place holder on the command line (per the help menu).  Let me know if you run into any problems.

**Comment by gdevenyi** [comment]
Looks like exactly what I'm looking for, now I can say NULL for a mask! Thanks!

**Comment by gdevenyi** [comment]
I had a chance to rebuild ANTs with the new masking and I'm testing, and I think I'm running into a bug:

```
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=16 antsRegistration --dimensionality 3 --float 0 --collapse-output-transforms 1 --verbose \
  --output [$outputdir/$(basename $movingfile)-$(basename $fixedfile)] \
  --winsorize-image-intensities [0.01,0.99] --use-histogram-matching 1 \
  --initial-moving-transform [$fixedfile,$movingfile,1] \
  --transform Rigid[0.2] --metric Mattes[$fixedfile,$movingfile,1,32,Random,0.25] --convergence [2000x2000x2000x2000,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --masks [NULL,NULL] \
  --transform Affine[0.5] --metric Mattes[$fixedfile,$movingfile,1,32,Random,0.30] --convergence [2000x2000x2000x2000x2000,1e-6,10] --shrink-factors 8x8x4x2x1 --smoothing-sigmas 4x3x2x1x0vox --masks [NULL,NULL] \
  --transform Affine[0.1] --metric Mattes[$fixedfile,$movingfile,1,64,Random,0.30] --convergence [2000x2000x2000x2000x2000,1e-8,10] --shrink-factors 8x6x4x2x1 --smoothing-sigmas 4x3x2x1x0vox --masks [$fixedmask,$movingmask] \
  --transform BSplineSyN[0.5,48,0] --metric CC[$fixedfile,$movingfile,1,4] --convergence [2000x1000x1000x100x40,1e-6,10] --shrink-factors 8x6x4x2x1 --smoothing-sigmas 4x3x2x1x0vox --masks [$fixedmask,$movingmask] \
  --transform BSplineSyN[0.1,48,0] --metric CC[$fixedfile,$movingfile,1,6] --convergence [20,1e-6,10] --shrink-factors 1 --smoothing-sigmas 0vox --masks [$fixedmask,$movingmask]
```

Based on the call, I think I'm doing
- No masking for stage 0
- No masking for stage 1
- Masking for stage 2
- Masking for stage 3
- Masking for stage 4


However, this isn't what I get, instead:
And the beginning of the output:
```
  Reading mask(s).
    Registration stage 0
      Fixed mask = input/template/ad_ADNI_002_S_0816_S19532_I40726_mask.mnc
      Moving mask = input/atlas/brain1_mask.mnc
    Registration stage 1
      Fixed mask = input/template/ad_ADNI_002_S_0816_S19532_I40726_mask.mnc
      Moving mask = input/atlas/brain1_mask.mnc
    Registration stage 2
      Fixed mask = input/template/ad_ADNI_002_S_0816_S19532_I40726_mask.mnc
      Moving mask = input/atlas/brain1_mask.mnc
    Registration stage 3
 file NULL does not exist . 
      No fixed mask
 file NULL does not exist . 
      No moving mask
    Registration stage 4
 file NULL does not exist . 
      No fixed mask
 file NULL does not exist . 
      No moving mask
```

This is the reverse of what I expected.

Should I specifying this differently? Or is this a bug?

**Comment by gdevenyi** [comment]
I'm guessing that the GetFunction call works like a stack, so it's getting the last specified first and going backwards.

Looks like it should count down like:
```
for( int currentMetricNumber = numberOfMetrics - 1; currentMetricNumber >= 0; currentMetricNumber-- )
      {
<SNIP>
```

**Comment by ntustison** [comment]
Yeah, I designed it that way but apparently forgot as I was putting the modified mask option together.  Why don't you try the recent commit

https://github.com/stnava/ANTs/commit/59efa592f9692ceaebed258221e48b9ab34d1f04

and let me know if that works.  The ordering in reading the masks is all found here in this section of code so if there's still a problem, why don't you submit a pull request and I'll merge it.

**Comment by gdevenyi** [comment]
Thanks for the quick fix, that's exactly what I changed in my code (still compiling...).

I'll report back after testing.

**Comment by gdevenyi** [comment]
All seems good now! Thanks!
