### ISSUE TITLE
antsRegistration blur levels reports warning with GaussianOperator

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#187]
Ran the following command:

```ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=12 antsRegistration --dimensionality 3 --float 0 --collapse-output-transforms 1  --write-composite-transform 1   --output [output/transforms/atlas-template/brain1_t1.mnc-OAS1_0001_MR1_mpr_n4_anon_sbj_111.n4correct_t1.mnc]   --winsorize-image-intensities [0.005,0.995] --use-histogram-matching 1   --initial-moving-transform [input/template/OAS1_0001_MR1_mpr_n4_anon_sbj_111.n4correct_t1.mnc,input/atlas/brain1_t1.mnc,1]   --transform Rigid[0.1] --metric MI[input/template/OAS1_0001_MR1_mpr_n4_anon_sbj_111.n4correct_t1.mnc,input/atlas/brain1_t1.mnc,1,32,Regular,0.25] --convergence [1000x500x250x200,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox   --transform Affine[0.1] --metric MI[input/template/OAS1_0001_MR1_mpr_n4_anon_sbj_111.n4correct_t1.mnc,input/atlas/brain1_t1.mnc,1,32,Regular,0.25] --convergence [2000x1000x500x250x200,1e-6,10] --shrink-factors 8x8x4x2x1 --smoothing-sigmas 4x3x2x1x0vox    --transform SyN[0.1,3,0] --metric CC[input/template/OAS1_0001_MR1_mpr_n4_anon_sbj_111.n4correct_t1.mnc,input/atlas/brain1_t1.mnc,1,4] --convergence [400x200x100x10x10x10,1e-6,10] --shrink-factors 32x16x8x4x2x1 --smoothing-sigmas 5x4x3x2x1x0vox```

Gave the following warnings at every iteration of the first Syn stage
```
*** Running SyN registration (varianceForUpdateField = 3.0000e+00, varianceForTotalField = 0.0000e+00) ***

WARNING: In /opt/quarantine/ANTs/2.1.0/src/superbuild/ITKv4-install/include/ITK-4.7/itkGaussianOperator.hxx, line 61
GaussianOperator (0x7ffdf3d4d510): Kernel size has exceeded the specified maximum width of 5 and has been truncated to 6 elements.  You can raise the maximum width using the SetMaximumKernelWidth method.
```

I'm guessing my blur is too aggressive? Or is there something else going on?

**Comment by ntustison** [comment]
This warning will pop up occasionally.  The [Gaussian convolution filter](http://www.itk.org/Doxygen/html/classitk_1_1DiscreteGaussianImageFilter.html) takes several inputs of which only the variance is exposed to the user.   If the Gaussian kernel discretization parameters are mutually incompatible, then this warning will be thrown.  For example, if your fixed image is a 3-D slab, your maximum error constraint might mean you need a greater kernel size than is actually allowed by your image size.  This can't be changed.

**Comment by tina-ebi** [comment]
Hi there,
I would like to register a quantitative floating 3D map  to a structural template.  But at every iteration, it gives an error. finally, the result of registration is not good. Could you please help me to do the correct registration for a quantitative map? (I should mention that I was registering two structural T1 images very well. once, I closed terminal page while running. After that time, I receive these many warning in running antsregistration.sh)
Thanks for any comment.

![error_running2](https://user-images.githubusercontent.com/62328344/79631511-0dbc0400-816f-11ea-8e16-ebef4e86423f.JPG)
![register_result](https://user-images.githubusercontent.com/62328344/79631988-b3707280-8171-11ea-8f7f-58fb6b00c118.JPG)

**Comment by gdevenyi** [comment]
Do not post on long closed (2015!) Issues
