### ISSUE TITLE
BUG: mask mallo in antsSliceRegularizedRegistration

### ISSUE THREAD

**Issue by stnava** [stnava/ANTs#189]
via j cohen-adad

I am experiencing errors when using a mask with the function antsSliceRegularizedRegistration.

Data:
https://dl.dropboxusercontent.com/u/20592661/data_ants.zip

Syntax:

antsSliceRegularizedRegistration -t Translation[0.5] -m MeanSquares[data_dest.nii.gz,data_src.nii.gz,1,4,Regular,0.2] -p 3 -i 10 -f 1 -s 0 -v 1 -x mask.nii.gz -o reg
Error:

antsSliceRegularizedRegistration(15177,0x105fd8000) malloc: *** error for object 0x7fecd3f19210: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug Abort trap: 6

**Comment by stnava** [comment]
i was unable to to recreate this issue ... there have been a few changes in the masks in ITK and in ANTs ... maybe your ITK version is out of date?   what OS are you using?   i tested on OSX.

**Comment by stnava** [comment]
```
g=0.5

echo MI
antsSliceRegularizedRegistration -t Translation[${g}] -m MI[data_dest.nii.gz,data_src.nii.gz,1,16,Regular,0.2] -p 3 -i 10 -f 1 -s 0 -v 1 -x mask.nii.gz -o [zMI,zMI.nii.gz]

echo CC
antsSliceRegularizedRegistration -t Translation[${g}] -m CC[data_dest.nii.gz,data_src.nii.gz,1,2] -p 3 -i 10 -f 1 -s 0 -v 1 -x mask.nii.gz -o [zCC,zCC.nii.gz]

echo MSQ
antsSliceRegularizedRegistration -t Translation[${g}] -m MeanSquares[data_dest.nii.gz,data_src.nii.gz,1,16,Regular,0.2] -p 3 -i 10 -f 1 -s 0 -v 1 -x mask.nii.gz -o [zMSQ,zMSQ.nii.gz]

```

**Comment by jcohenadad** [comment]
ok, with the new binaries, the issue is solved. Thanks!
