### ISSUE TITLE
CompCor

### ISSUE THREAD

**Issue by Zhisen** [stnava/ANTs#194]
It seems my original issue regarding CompCorAuto was closed. I have an follow up question here regarding the output of CompCor. I am trying to extract the time series of csf and white matter from my functional mri data. The goal of doing that is to regress those two confounds out before doing other analyses. With help from the ANTS team, now I can extract the time series, using the following command, but my question is, is there a way to set the output to be the cleaned fmri data, that is, fmri data that had the csf and white matter time series extracted out already. With the codes below, the output is the time series of the mask, either it is a csf or a white matter mask. Thanks a lot!

img<-antsImageRead("fm_run1_al.nii") 
maskImg<-antsImageRead("anat_3.5.nii")
mask<-getMask(maskImg)
mat<-timeseries2matrix(img, mask)
compcorrdf<-compcor(mat)

**Comment by stnava** [comment]
you might want to use `preprocessfMRI` ... type `?preprocessfMRI` in R and read the help.   alternatively, see code below.  

```
avgbold = getAverageOfTimeSeries( bold )
mk  = getMask( avgbold )
mat = timeseries2matrix( bold, mk )
cc = compcor( mat )
rmat=residuals( lm( mat ~ cc ) )
rimg=matrix2timeseries( bold, mk, rmat )
```

**Comment by stnava** [comment]
just note: compcor does not "  extract the time series of csf and white matter from ... functional mri data "

instead, it extracts the principal vectors from a timeseries matrix derived from high-variance voxels.  this may or may not be similar to csf and white matter signal.

from example above, you can do
```
plot( ts(cc) )
```
to look at the components.
