### ISSUE TITLE
BUG: ANTs resources stored on SourceForge

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#195]
SourceForge is now considered a malware distributor:
https://blog.l0cal.com/2015/06/02/what-happened-to-sourceforge/
https://notepad-plus-plus.org/news/notepad-plus-plus-leaves-sf.html
http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/
http://arstechnica.com/information-technology/2015/06/black-mirror-sourceforge-has-now-siezed-nmap-audit-tool-project/

**Comment by stnava** [comment]
thanks for the heads up ... very interesting.  i've always wondered when/if
something like this would happen - even to github. so what is the
recommended procedure?  should we just "close" our sourceforge account with
a redirect to github?  while the number is diminishing, some people still
go to that site for help and there is a largish archive of information on
the growth of the project over the years.

any ideas/suggestions welcome.


brian

**Comment by gdevenyi** [comment]
There are some tools people have developed to archive content: http://archiveteam.org/index.php?title=SourceForge

In the meantime, I would probably remove the windows downloads, since they're susceptible to malware injection.

I guess what's missing right now is a non-sourceforge forum (their forum system was abysmal anyways..)

Perhaps open up a google group for ANTs? Or a subreddit?

**Comment by bkandel** [comment]
I'm not sure how big a deal this is yet.  I think most people who would use
ANTs have enough general technology sophistication to know not to click on
random ads on the side of the download bar.  If they actually start
packaging malware with Windows ANTs this would obviously change, but as
long as that hasn't happened, I think we can leave it as is.

Are the malwares obvious?  Can we just check every once in a while to make
sure they aren't doing funny things?  We could also put a notice up on the
download page pointing people to github.  It's just that old habits die
hard and I'd be worried about pushing people away if we remove SF entirely
too quickly.

2015-06-18 10:17 GMT-04:00 Gabriel A. Devenyi <notifications@github.com>:

**Comment by cookpa** [comment]
Yes it should be clear if you go look, SF hijacks old repos and changes the owner and downloads.

**Comment by bkandel** [comment]
Right, but they haven't done it to us and are less likely to do it to a
small-time scientific software project than a big general-purpose
application with millions of users and ten thousand weekly downloads.  The
thing is that according to their stats, over 100 people used SF to download
ANTs in the past week alone, so I would be hesitant to take that away
without lots of warning and lead-in time.

2015-06-18 10:47 GMT-04:00 Philip Cook <notifications@github.com>:

> Yes it should be clear if you go look, SF hijacks old repos and changes
> the owner and downloads.
>
>
> Sent from my iPhone
>
