### ISSUE TITLE
Kernel size can only be set as integers

### ISSUE THREAD

**Issue by wendyuu** [stnava/ANTs#197]
When kernel size is set to a float for the newest version, a bug was reported.

**Comment by stnava** [comment]
you really need to say a bit more here.   am guessing that you are commenting on something that is neither a bug nor new, nor related to float / integer.

**Comment by wendyuu** [comment]
Sorry.

What is causing a bug is the radius that's set, e.g. using CC[fixedImage,movingImage,weight,radius]

When I used a float (0.75 here), it was fine but since I updated to the newest version, it causes a bug as:
Exception caught in ANTS: 
/tools/devel/linux/ANTS/ANTs_git/Utilities/antsCommandLineParser.h:126:
itk::ERROR: CommandLineParser(0x22274b0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '0.75' to type 'j' as unsigned int 

When I tried the same command using an older version of ANTS, it's still working.

**Comment by stnava** [comment]
the bug was in the older version - i.e. allowing you to set a float.  the CC radius is a voxel measurement.  you can thank @hjmjohnson for correcting this previous bug.

**Comment by wendyuu** [comment]
Is it possible to add in the help file, which values are set in mm and which values are in "voxel"

**Comment by stnava** [comment]
yes - feel free to make the additions yourself and create a pull request.


brian

**Comment by wendyuu** [comment]
cool. thanks for clearing the issue for me
