### ISSUE TITLE
Expose more options of ITK in SuperBuild CMake

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#199]
Given that I figured out how to get MINC support working in the SuperBuild in #198 , I'm going to track here my efforts in exposing other options in the underlying ITK build.

**Comment by stnava** [comment]
Thanks. These contributions are much appreciated.

**Comment by gdevenyi** [comment]
Followup:

Do you think there's any problem with just turning on any other modules in ITK that don't require external tools? Or would you rather them exposed via the config?

**Comment by stnava** [comment]
we prefer to minimize compile time when possible.  i.e. avoid compiling
extra libraries that we never use and which may take substantial disk space
as well.


brian
