### ISSUE TITLE
n4 bias blurring out images

### ISSUE THREAD

**Issue by varghesealex90** [stnava/ANTs#201]
I find applying N4FieldBiasCorrection is blurring the images. I find some hyper intensities at the background even after applying mask.

Steps followed where:

1. truncate the Highest and Lowest .1 values , done using:
    os.system(ANTSPATH+'ImageMath 3 '+output_file+' TruncateImageIntensity '+input_file+' 0.01 0.99 200')
2. Create Mask for Image:
        os.system(ANTSPATH+'ImageMath 3 '+mask_file+' Normalize '+input_file)
        os.system(ANTSPATH+'ThresholdImage 3 '+mask_file+' '+mask_file+' 0.005 1')
        os.system(ANTSPATH+'ImageMath 3 '+mask_file+' MD '+mask_file+' 2')
        os.system(ANTSPATH+'ImageMath 3 '+mask_file+' ME '+mask_file+' 1')
        os.system(ANTSPATH+'CopyImageHeaderInformation '+input_file+' '+mask_file+' '+mask_file+' 1 1 1')

3. Apply N4 Bias Field Correction on t1 and t1 post contrast images using 
os.system(ANTSPATH+'N4BiasFieldCorrection -d 3 -i '+input_file+' -x '+mask_file+' -s 2 -c [50x50x50x50,0.0000000001] -b [200] -o '+output_file

I have attached a screenshot of T1 weighted images of 2 different patients after N4 bias. The cursor of ITK-SNAP  was placed on the background(Non-Brain region), it is quite clear that the intensity values one of them is twice of that of the other, moreover the image on the right seems to have a Blurred or smoothened effect at the edges of the brain.

Is such performance quite normal when performing N4 bias. If not, can you let me know what is that I am doing wrong.

![n4_bias](https://cloud.githubusercontent.com/assets/10129358/8470294/4f9fb5a8-20a6-11e5-9e53-a52264860317.png)

**Comment by gdevenyi** [comment]
What do you mean by "hyper intensities"?

**Comment by varghesealex90** [comment]
When an object looks brighter than the surrounding  pixels, we call it
hyper intensities
