### ISSUE TITLE
ANTs 1.9 vs latest

### ISSUE THREAD

**Issue by reckbo** [stnava/ANTs#203]
I'm using ANTs to perform a registration along one axis only (for DWI EPI distortion correction) 
but it only works nicely using ANTs 1.9.  The github versions produce nonsense output using the same
command:

`ANTs-1.9.y-Linux/bin//ANTS 3 -m CC[/tmp/tmp.EUXIanZlDL/01010-t2w-restore-in-bse-rigid.nrrd,/tmp/tmp.EUXIanZlDL/01010-dwi-Ed-maskedbse.nrrd,1,5] -i 50x20x10 -r Gauss[3,0] -t SyN[1] -o /tmp/tmp.EUXIanZlDL/01010-dwi-Ed-maskedbse_in_01010-t2w-restore-in-bse-rigid_warp --Restrict-Deformation 0x1x0 --do-rigid`

I'd like to use the latest version of ANTs though, any suggestions?

**Comment by stnava** [comment]
SyN[1]  is not recommended ... SyN[0.25] or less is ... also  0.1x1x0.1
might be closer to the realities of distortion though this may depend on
your specific sequence.

also - use antsRegistration which is our standard registration tool ... it
has analogous options but is implemented much more generally and cleanly.


brian

**Comment by reckbo** [comment]
SyN[0.25] has no effect and SyN[0.5] gives a similar bad result as before.

I tried `antsRegistration` with but it seg faults:

antsRegistration -d 3 --metric "CC[/tmp/tmp.pVSzoyMd22/01010-t2w-restore-in-bse-rigid.nrrd,/tmp/tmp.pVSzoyMd22/01010-dwi-Ed-maskedbse.nrrd,1,5]" --convergence 50x20x10 -t "SyN[0.25]" -o /tmp/tmp.pVSzoyMd22/01010-dwi-Ed-maskedbse_in_01010-t2w-restore-in-bse-rigid_warp --restrict-deformation 0x1x0

**Comment by stnava** [comment]
at this point, you might want to share data with us.  otherwise, we cannot
reproduce your results.  if we can reproduce your results, then we can
diagnose whatever problem might exist.

if you don't want to share data then i'd suggest:

1.  installing the latest ants version

2.  learning how to use antsRegistration with easy data beforehand

3.  reading documentation and testing with simple examples before moving on
to your bug

comments such as "SyN[0.25] has no effect" suggest there is something odd
happening on your end because SyN[0.25] almost always does *something*.

finally, we always like when people read documentation and start with
recommended usage of the programs before moving on to more advanced
applications.

**Comment by pnlbwh** [comment]
Hi Brian,

I've made a repo with some example data and two test scripts:

    https://github.com/pnlbwh/ants-epi-test

When I run them, I get a good result with `test19.sh` but seems there is no effect
when I run `test.sh` (Syn[0.25] with latest ants).

Let me know if you need anything else, thanks so much for your help.
Ryan

**Comment by stnava** [comment]
great - thanks.  we don't really support the old ANTS program ... but here
is an antsRegistration solution that appears to work fine:

##########################################################
source SetUpData.sh
pre=ants_
epiwarp=epiwarp.nii.gz
out=bse-epi.nrrd
## get the rigid part
antsRegistrationSyN.sh -d 3 -f $fixed -m $moving -t r -o rigid_init
## get the deformable part
antsRegistration -d 3 --initial-moving-transform
rigid_init0GenericAffine.mat \
  -m cc[$fixed,$moving,1,2] -t SyN[0.25,3,0] -c 50x50x0 -f 4x2x1 \
  -s 2x1x0  --restrict-deformation 0.2x1x0.2  -v 1 \
  -o
[/tmp/ants-epi-test/syn,/tmp/ants-epi-test/synw.nii.gz,/tmp/ants-epi-test/synwi.nii.gz]
##########################################################


if you would like to debug the old ANTS program, we would be happy to
accept any suggested changes/bug fixes.  but it is unlikely we will be
maintaining that code, long term.


brian

**Comment by pnlbwh** [comment]
Great, using this it works even better than before, thanks!
