### ISSUE TITLE
BUG? xfms and mat files have inverse relationship

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#206]
Just tested out the xfm writing of antsRegistration and it works properly *however* I ran into a weird caveat.

If I run antsRegistration to generate the xfm, and then use antsApplyTransforms with the xfm to transform  the moving file, all works as expected. *if* however I use mincresample to apply the transform, I find that it only works if I transform the fixed image to the moving image, i.e. it acts like an inverse transform.

From what I can gleam, this is because xfms transform the coordinate system while mats transform the image data.

@vfonov can you perhaps chime in here? antsRegistration and antsApplyTransforms are internally consistent but shouldn't they both be the other way so that fixed and moving are defined properly?

**Comment by vfonov** [comment]
to resample image one actually have to calculate the inverse of the transform. So tools like mincresample and itk_resample do it as the first step. antsApplyTransforms uses different logic - you have to provide inverse transform to resample the image.

**Comment by gdevenyi** [comment]
Perhaps the ITK xfm IO should compute the inverse for writing/reading so that the files on disk are consistent with the standard interpretation?

This would make moving/fixed consistent between minc-toolkit and ITK

**Comment by ntustison** [comment]
We compute the inverse for linear transforms within antsApplyTransforms on the fly when requested by the user but not deformable transforms as the necessary computation would be much more involved and there's no guarantee that an inverse exists for the general deformable case.

**Comment by vfonov** [comment]
right now the output.xfm - provides transformation from fixed to moving and output_inverse.xfm - from moving to fixed. And it's been like that since I mincified old ANTS tool
