### ISSUE TITLE
BUG: --minc flag in antsRegistration fails to write transform for combined Affine/Nonlinear Reigstration

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#207]
My antsRegistration call:
```
antsRegistration --dimensionality 3 --float 0 --collapse-output-transforms 1 --verbose --minc 1 --output [./OAS1_0001_MR1.mnc-mni_icbm152_t1_tal_nlin_sym_09c.mnc] --winsorize-image-intensities [0.01,0.99] --use-histogram-matching 1 --initial-moving-transform [/opt/quarantine/resources/mni_icbm152_nlin_sym_09c_minc2/mni_icbm152_t1_tal_nlin_sym_09c.mnc,OAS1_0001_MR1.mnc,1] --transform Rigid[0.2] --metric Mattes[/opt/quarantine/resources/mni_icbm152_nlin_sym_09c_minc2/mni_icbm152_t1_tal_nlin_sym_09c.mnc,OAS1_0001_MR1.mnc,1,32,Random,0.25] --convergence [2000x2000x2000x2000,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.5] --metric Mattes[/opt/quarantine/resources/mni_icbm152_nlin_sym_09c_minc2/mni_icbm152_t1_tal_nlin_sym_09c.mnc,OAS1_0001_MR1.mnc,1,32,Random,0.30] --convergence [2000x2000x2000x2000x2000,1e-6,10] --shrink-factors 8x8x4x2x1 --smoothing-sigmas 4x3x2x1x0vox --transform Affine[0.1] --metric Mattes[/opt/quarantine/resources/mni_icbm152_nlin_sym_09c_minc2/mni_icbm152_t1_tal_nlin_sym_09c.mnc,OAS1_0001_MR1.mnc,1,64,Random,0.30] --convergence [2000x2000x2000,1e-6,10] --shrink-factors 4x2x1 --smoothing-sigmas 2x1x0vox --transform SyN[0.5,3,0] --metric CC[/opt/quarantine/resources/mni_icbm152_nlin_sym_09c_minc2/mni_icbm152_t1_tal_nlin_sym_09c.mnc,OAS1_0001_MR1.mnc,1,4] --convergence [2000x1000x1000x100x20,1e-5,10] --shrink-factors 8x6x4x2x1 --smoothing-sigmas 4x3x2x1x0vox
```

The output at the very end of the registration:
```
Can't write transform file ./OAS1_0001_MR1.mnc-mni_icbm152_t1_tal_nlin_sym_09c.mnc1.xfm
Exception Object caught: 

itk::ImageFileWriterException (0x17ff210)
Location: "unknown" 
File: /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.9/itkImageFileWriter.hxx
Line: 151
Description:  Could not create IO object for writing file ./OAS1_0001_MR1.mnc-mni_icbm152_t1_tal_nlin_sym_09c.mnc1.xfm
  Tried to create one of the following:
    NiftiImageIO
    NrrdImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    GDCMImageIO
    BMPImageIO
    LSMImageIO
    PNGImageIO
    TIFFImageIO
    VTKImageIO
    StimulateImageIO
    BioRadImageIO
    MetaImageIO
    MRCImageIO
    GE4ImageIO
    GE5ImageIO
    MINCImageIO
    MGHImageIO
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.



Can't write transform file ./OAS1_0001_MR1.mnc-mni_icbm152_t1_tal_nlin_sym_09c.mnc1_inverse.xfm
Exception Object caught: 

itk::ImageFileWriterException (0x17ff210)
Location: "unknown" 
File: /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.9/itkImageFileWriter.hxx
Line: 151
Description:  Could not create IO object for writing file ./OAS1_0001_MR1.mnc-mni_icbm152_t1_tal_nlin_sym_09c.mnc1_inverse.xfm
  Tried to create one of the following:
    NiftiImageIO
    NrrdImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    GDCMImageIO
    BMPImageIO
    LSMImageIO
    PNGImageIO
    TIFFImageIO
    VTKImageIO
    StimulateImageIO
    BioRadImageIO
    MetaImageIO
    MRCImageIO
    GE4ImageIO
    GE5ImageIO
    MINCImageIO
    MGHImageIO
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.
```

**Comment by gdevenyi** [comment]
I suspect something in commit 270432e8105eb748f7a9fc500dbbe715e1ebb776

Warp.nii.gz gets changed to .xfm in RegTypeToFileName however I don't think that's being handled properly higher up in the call to generate a combined affine/nonlinear xfm file

**Comment by vfonov** [comment]
this works:
antsRegistration -d 3 -a --minc \
    --smoothing-sigmas 4x2x1  \
    --shrink-factors 4x2x1  \
    -m mattes[  $icbm_t1,  $ace_t1 , 1 , 32, regular, 0.3 ] \
    -m mattes[  $icbm_t2,  $ace_t2 , 1 , 32, regular, 0.3 ] \
    -x [ $icbm_mask , $ace_mask ] \
    -t affine[ 0.1 ] \
    -c [10000x111110x11110,1.e-8,20]  \
    -m mattes[  $icbm_t1,  $ace_t1 , 1 , 32, regular, 0.3 ] \
    -m mattes[  $icbm_t2,  $ace_t2 , 1 , 32, regular, 0.3 ] \
    -t SyN[ .20, 3, 0 ] \
    -c [ 100x100x50 ]  \
    --smoothing-sigmas 4x2x1  \
    --shrink-factors 4x2x1 \
    -o v2_to_icbm_asym_bimodal

**Comment by gdevenyi** [comment]
Followup: I get a .xfm file which contains the linear component of the transformation, the nonlinear is missing.

@vfonov I am running your example now except I removed the t2 component, since I don't have a paired set of scans available

**Comment by vfonov** [comment]
I am running with -a flag - it puts all transformation into a single file

**Comment by gdevenyi** [comment]
Yes, I am too, its the --collapse long form command.

**Comment by gdevenyi** [comment]
**correction** I confused --collapse-output-transforms with --write-composite-transform.

antsRegistration fails to write out a minc-style transform without --write-composite-transform

I.e. my test case above works when I add "--write-composite-transform 1" to it.

I suspect this may be an issue with antsRegistration only expecting to write a warp image but the --minc flag forcing .xfm as the file format.

**Comment by gdevenyi** [comment]
So will --minc support always reqire "--write-composite-transform" or can it write out affine/nonlinear components into separate xfms?

**Comment by vfonov** [comment]
I'll try to fix it

**Comment by gdevenyi** [comment]
Hi @vfonov just as a followup, can you please test ``--collapse-output-transforms 0`` as well. I'd like to be able to do something like:
```
--transform Rigid[xxx]
--transform Affine[xxx]
```
And get two separate xfms from that out of a single registration call.

**Comment by gdevenyi** [comment]
Hi @vfonov I have one more test case, can you check that running a pure nonlinear (SyN for example) registration works? Right now antsRegistration in minc-toolkit-v2 segfaults.

**Comment by vfonov** [comment]
works for me, what's your command line?

On Wed, Jul 22, 2015 at 11:04 AM, Gabriel A. Devenyi <
notifications@github.com> wrote:

> Hi @vfonov <https://github.com/vfonov> I have one more test case, can you
> check that running a pure nonlinear (SyN for example) registration works?
> Right now antsRegistration in minc-toolkit-v2 segfaults.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stnava/ANTs/issues/207#issuecomment-123751988>.
>



-- 
Best regards,

 Vladimir S. Fonov ~ vladimir <dot> fonov <at> gmail <dot> com

**Comment by gdevenyi** [comment]
```
antsRegistration --dimensionality 3 --float 0 --collapse-output-transforms 1 --minc --write-composite-transform --verbose --output $(dirname $TA_nl_xfm)/$(basename $TA_nl_xfm .xfm) --winsorize-image-intensities [0.01,0.99] --use-histogram-matching 1 --transform SyN[0.5,3,0] --metric CC[$target,$atlas_res,1,6] --convergence [100x100x100x100x20,1e-6,10] --masks [NULL,$atlas_res_mask]
```
antsRegistratio[29216]: segfault at 0 ip 00000000017479f4 sp 00007fffffff84d0 error 4 in antsRegistration[400000+2765000]

Files are very well matched affine-wise (checked in register) and the mask correctly defines the area of interest. mincANTS runs file on the files

**Comment by vfonov** [comment]
Adding   --shrink-factors 8x6x4x2x1  --smoothing-sigmas 4x3x2x1x0vox makes it work

**Comment by gdevenyi** [comment]
Good to know, forking a new issue re: documentation/default arguments
