### ISSUE TITLE
LabelOverlapMeasures produces csv file with garbled label id

### ISSUE THREAD

**Issue by vfonov** [stnava/ANTs#208]
There is a bug in generating label names in https://github.com/stnava/ANTs/blob/master/Examples/LabelOverlapMeasures.cxx#L91

the contents of  convert is reused to generate label titles 1, second 12, third 123 etc

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/fd89a011b2394af4dc7035e0e9e552cf6612f956
