### ISSUE TITLE
providing initial transformation for Exponential transform

### ISSUE THREAD

**Issue by vfonov** [stnava/ANTs#210]
If i run antsRegistration with --transform Exponential , the output Warp file is in log space, but then there is no way to specify this type of transform as initial-moving-transform or initial-fixed-transform

**Comment by ntustison** [comment]
> the output Warp file is in log space

Can you elaborate further?  Why do you think the output warp file is in log space?  It's been a long time since I've looked at this so I'd like to know what you're looking at.  Thanks.

**Comment by ntustison** [comment]
Also, just to follow-up, the warp field shouldn't be in log space.  If it is, we'll need to correct it probably going all the way into ITK.

**Comment by vfonov** [comment]
ok, right now it is in log space - currently antsRegistration uses GaussianExponentialDiffeomorphicTransform , which is cast to DisplacementFieldTransform like here: https://github.com/stnava/ANTs/blob/master/Examples/antsRegistrationTemplateHeader.h#L1292

**Comment by ntustison** [comment]
I'm still not clear as to why you think it's in log space.  The "transform" contained by the exponential transform is an actual displacement field describing the transform between spaces as in all the other displacement field transforms.  This field is a result of integrating the class member constant velocity field (cf https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/DisplacementField/include/itkConstantVelocityFieldTransform.hxx).

**Comment by stnava** [comment]
​might be good to write out both the velocity field and the result of
integration (which is standard displacement).​


brian

**Comment by ntustison** [comment]
Yeah, we do it for the time varying cases

https://github.com/stnava/ANTs/blob/master/Examples/antsRegistrationTemplateHeader.cxx#L27-L35

Would be just as easy to do it for the constant velocity field cases.

**Comment by vfonov** [comment]
Ok, I might have got confused....
I will make changes to save velocity field

**Comment by ntustison** [comment]
Closing this for now.  Might want to revisit.
