### ISSUE TITLE
antsRegistration is unclear about default arguments re shrink/smoothing

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#211]
I was expecting that if I just set "--convergence" values for antsRegistration I'd get some default set of shrinking/smoothing however this is not the case. Instead antsRegistration segfaults.

With ANTS it used some "built in" scaling. Perhaps the defaults for shrink/smooth should match how ANTS acted?

**Comment by ntustison** [comment]
In the documentation, we write

>         This program is a user-level registration application meant to utilize 
>          ITKv4-only classes. The user can specify any number of "stages" where a stage 
>          consists of a transform; an image metric; and iterations, shrink factors, and 
>          smoothing sigmas for each level.Note that dimensionality, metric, transform, 
>          output, convergence, shrink-factors and smoothing-sigmas parameters are 
>          mandatory. 

I'll have to think about putting in default values for antsRegistration and discuss with Brian.  For right now, 
I'll put in a check to make sure the user explicitly sets those two options.

**Comment by vfonov** [comment]
right now it crashes if either shrink-factors or smoothing-sigmas is missing. Can print an error message at least.

**Comment by ntustison** [comment]
See my previous message.

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/1735522c23be15e490135b5ea347576b6c3b7e8b

**Comment by gdevenyi** [comment]
Cheers thanks.

**Comment by cookpa** [comment]
Yes thanks Nick. I think it's fine to require users to specify these parameters, as they are important. But seg faults are bad.

**Comment by ntustison** [comment]
Definitely agree.

**Comment by gdevenyi** [comment]
One more quick question, what would equivalent shrink/smooth settings be to how ANTS ran?

**Comment by cookpa** [comment]
I think this is where the defaults were set:


if( this->m_SubsamplingFactors.Size() == 0 )
        {
        this->m_ScaleFactor = vcl_pow( 2.0, (int)static_cast<RealType>( this->m_NumberOfLevels - currentLevel - 1 ) );
        }


https://github.com/stnava/ANTs/blob/30da0c8e7c27a3e93f6473c0277e75b5548347a4/ImageRegistration/itkANTSImageRegistrationOptimizer.h#L1285-L1288


 if( this->m_GaussianSmoothingSigmas.size() == 0 )
          {
          this->m_SmoothFixedImages[metricCount] = this->SmoothImageToScale(
              this->m_SimilarityMetrics[metricCount]->GetFixedImage(), this->m_ScaleFactor );
          this->m_SmoothMovingImages[metricCount] = this->SmoothImageToScale(
              this->m_SimilarityMetrics[metricCount]->GetMovingImage(), this->m_ScaleFactor );
          }


https://github.com/stnava/ANTs/blob/30da0c8e7c27a3e93f6473c0277e75b5548347a4/ImageRegistration/itkANTSImageRegistrationOptimizer.h#L1312-L1318


So I think the levels went 16x8x4x2x1, and smoothing was the same. So if you set iterations as AxBxCxD, the default levels were 8x4x2x1 and the smoothing was the same. I'm not sure if it was in voxels or mm.


There are a bunch of other differences between ANTS and antsRegistration, so if anyone's reading this looking for guidance on default parameters, I recommend looking at recent antsRegistration examples.

**Comment by gdevenyi** [comment]
Thanks, not looking for defaults per-se, just trying to get a close as possible to a one-to-one comparison of my old toolchain with ANTS to my new toolchain with antsRegistration
