### ISSUE TITLE
Building from GitHub zip of latest master fails

### ISSUE THREAD

**Issue by raudabaugh** [stnava/ANTs#213]
https://github.com/stnava/ANTs/blob/master/CMake/ProjectSourceVersion.cmake#L38

This line in the make flow assumes that ProjectSourceVersionVars.cmake exists if a git repo is not found. However, using GitHub's "Download ZIP" button provides user with a repo-less snapshot of master which does not include this file.

**Comment by ignatenkobrain** [comment]
I have the same problem in #235

**Comment by stnava** [comment]
do you have a proposed solution?


brian

**Comment by ignatenkobrain** [comment]
Add configure() a bit earlier. I will send patch in this evening

**Comment by ignatenkobrain** [comment]
Fixed in #236. Please close.
