### ISSUE TITLE
Clarification on restrict deformation

### ISSUE THREAD

**Issue by spinicist** [stnava/ANTs#216]
Hello,
Can someone clarify what the last sentence of the restrict-deformation help string means please?

"Low-dimensional restriction only works if there are no preceding transformations."

Does this mean if I tell antsRegistration to do a Rigid, then a SyN stage and give a --restrict-deformation 1x1x0.1 argument after the SyN specification that restrict-deformation will not work?

Thanks.

**Comment by ntustison** [comment]
"Low-dimensional" refers to e.g., linear transforms.  You can't combine linear transform restrictions.
