### ISSUE TITLE
Connection Time out

### ISSUE THREAD

**Issue by sujithnairsl** [stnava/ANTs#218]
I am getting the following error when I run make

[  5%] Performing download step (git clone) for 'ITKv4'
itk.org[0: 66.194.253.19]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Initialized empty Git repository in /home/snair/antsBin/ITKv4/.git/
itk.org[0: 66.194.253.19]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Initialized empty Git repository in /home/snair/antsBin/ITKv4/.git/
itk.org[0: 66.194.253.19]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Initialized empty Git repository in /home/snair/antsBin/ITKv4/.git/
-- Had to git clone more than once:
          3 times.
CMake Error at ITKv4-prefix/tmp/ITKv4-gitclone.cmake:40 (message):
  Failed to clone repository: 'git://itk.org/ITK.git' 
make[2]: *** [ITKv4-prefix/src/ITKv4-stamp/ITKv4-download] Error 1
make[1]: *** [CMakeFiles/ITKv4.dir/all] Error 2
make: *** [all] Error 2

**Comment by cookpa** [comment]
Git is sometimes blocked by firewalls. Try setting

ANTS_USE_GIT_PROTOCOL

to OFF in cmake, it will then attempt to get ITK via http.

**Comment by sujithnairsl** [comment]
That helped, Thanks @cookpa
