### ISSUE TITLE
No Install step for ANTS

### ISSUE THREAD

**Issue by sujithnairsl** [stnava/ANTs#219]
at the end of make process i am getting the following logs. Is that indicating a problem?

[100%] Built target sa
[ 94%] No install step for 'ANTS'
[100%] Completed 'ANTS'

Also my antsRegistration command doesnt work. Also what must be my ANTSPATH?

**Comment by gdevenyi** [comment]
I reported this before, got a NOTABUG see #131

**Comment by sujithnairsl** [comment]
Thanks @gdevenyi 

I will try with 'make install'

I guess the environment variable $ANTSPATH will have value after successful installation. Is that correct?

**Comment by stnava** [comment]
https://en.wikipedia.org/wiki/Environment_variable


brian

**Comment by sujithnairsl** [comment]
When i try to install from ANTS-build directory it is giving me the following error

 Installing: /usr/local/lib/libantsUtilities.a
CMake Error at Examples/cmake_install.cmake:36 (FILE):
  file INSTALL cannot copy file "/home/snair/antsBin/lib/libantsUtilities.a"
  to "/usr/local/lib/libantsUtilities.a".
Call Stack (most recent call first):
  cmake_install.cmake:37 (INCLUDE)

Any idea?

manually copying over the files to /usr/local will work?

**Comment by cookpa** [comment]
Assuming you built without shared libraries, you can relocate the contents of antsBin/bin wherever you like, such as /usr/local/bin.

You might need superuser privileges to copy things to /usr/local on some systems.

After copying the binaries, you can optionally copy the scripts from the ANTs source directory, ANTs/Scripts/.

To make the scripts work properly, you need to set the environment variable.

  ANTSPATH=/usr/local/bin/

Note the trailing slash - this is required for ANTSPATH.

You'll need to Google how to set environment variables for your particular operating system and shell. You can get the shell type on most systems by typing

  echo $SHELL

in a terminal.

**Comment by sujithnairsl** [comment]
Thanks Cookpa, let me try this out.
