### ISSUE TITLE
Feature Request:  ThresholdAtMeanIntensityOn() in ImageMath HistogramMatching

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#221]
I have run into certain badly padded MR images which act weirdly when trying to use the HistogramMatching in ImageMath.

There is an option for this filter to threshold the image beforehand "ThresholdAtMeanIntensityOn()"
http://www.itk.org/Doxygen/html/classitk_1_1HistogramMatchingImageFilter.html

This is a request to add this an option for the interface.

When I have time I will attempt to implement this myself and submit a PR, in the meantime, track the request here.

**Comment by ntustison** [comment]
[Added](https://github.com/stnava/ANTs/commit/a131c4af182d07150cae63a7b95ada6fb3319778).
