### ISSUE TITLE
Compiled ANTs very slow on Ubuntu 14.04 (but fine on OSX 10.10)

### ISSUE THREAD

**Issue by michaelbernier** [stnava/ANTs#225]
Hello!

I have two computer systems; one running Mac OSX Yosemite, the other running Ubuntu 14.04 with similar hardwares. On mac, computational speed is fine, but on linux it can take 4 hours to compute a rigid transformation. I've used the source code from github and installation intruction from https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/ . Is there a configuration flag to set or something similar? Thank you!

**Comment by stnava** [comment]
set build type to release

http://www.cmake.org/pipermail/insight-users/2009-September/032799.html


brian

**Comment by michaelbernier** [comment]
It was already set to release, but I managed to find the issue:

When using the cmake-gui, toggle the advanced configuration. The "CMAKE_C_FLAGS" were set correctly, but the "CMAKE_CXX_FLAGS" were blank on ubuntu (but filled on OSX). In other words, even if 'Release' was selected, it was compiling in debug. I've copy pasted the flags from "CMAKE_C_FLAGS", recompiled and it works fine!

(Still don't know why the flags are not set by default on my ubuntu...)
