### ISSUE TITLE
Mask for interpolator in WarpImageMultiTransform

### ISSUE THREAD

**Issue by chrisadamsonmcri** [stnava/ANTs#227]
Everybody,

Would it be possible to use a mask to limit which voxels are used for interpolation when warping an image?

**Comment by stnava** [comment]
we recommend using antsApplyTransforms over WIMT.

but neither have the mask / limit you request.

what is your motivation for wanting this feature?

e.g. would you be willing to pay for this feature

or, perhaps, to implement yourself and contribute to ants?


brian

**Comment by chrisadamsonmcri** [comment]
My motivation is that I am warping DWI images from native to T1 space and I want to not contaminate WM voxels with GM values. I can warp a label image from T1 space to create a mask in native space. I would definitely like to implement it myself. Is there any documentation for the interpolators work or how the coordinates of the images are changed using the warp fields and affine transforms or what would be a good starting point for this?

**Comment by stnava** [comment]
we use ITK inside of ANTs.

see the linear interpolator within itk and its code.

the majority of such contamination is a fundamental part of the image
collection process.


brian

**Comment by chrisadamsonmcri** [comment]
Thanks, I will look in there to see if I can find what I’m looking for.
