### ISSUE TITLE
Build instructions for Mac OS X

### ISSUE THREAD

**Issue by stevenroose** [stnava/ANTs#229]
Please provide build instructions for OS X.

**Comment by stnava** [comment]
did you see the README.md which has a link that reads

Build ANTs from: Source-Code (recommended)

**Comment by stevenroose** [comment]
Does it work for OSX as well?

Hmm, ok, thanks. A friend of mine is having trouble, she probably lacks one of the dependencies then..

**Comment by cookpa** [comment]
Once you run ccmake it will tell you if you are missing anything else. 

You should be good as long as you have the a recent XCode developer tools.
