### ISSUE TITLE
[RFC] Naming ANTs as package in Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [stnava/ANTs#237]
In Fedora we already have ants package which is game, so we need to name package somehow differently. What do you think? I have some ides:
- ANTools
- an-tools

**Comment by stnava** [comment]
ANTs  ( if it is case sensitive )

or maybe

advancednormalizationtools ?




brian

**Comment by ignatenkobrain** [comment]
it is case sensitive, but I think it will confuse people. AdvancedNormalizationTools is looks OK, but too much letters I think :D

**Comment by stnava** [comment]
i'd prefer AdvancedNormalizationTools

tab-completion makes it less painful


brian

**Comment by hjmjohnson** [comment]
I prefer AdvancedNormalizationToolkit.

Hans


From:  Igor Gnatenko
Reply-To:  stnava/ANTs
Date:  Monday, November 2, 2015 at 12:28 PM
To:  stnava/ANTs
Subject:  Re: [ANTs] [RFC] Naming ANTs as package in Fedora (#237)


it is case sensitive, but I think it will confuse people. AdvancedNormalizationTools is looks OK, but too much letters I think :D

**Comment by stnava** [comment]
AdvancedNormalizationToolkit

versus

A(dvanced)N(ormalization)T(ool)s

only the latter is inline with historical naming and is also eponymous.


brian

**Comment by ignatenkobrain** [comment]
OK. Then I will use AdvancedNormalizationTools =) Thanks for your feedback!
