### ISSUE TITLE
rename 'sa'

### ISSUE THREAD

**Issue by ignatenkobrain** [stnava/ANTs#242]
`/usr/sbin/sa` provided by `psacct` which is well-known utility and should be renamed in ANTs.

**Comment by stnava** [comment]
@ntustison - how about renaming "sa" to "adaBoostSegmentation" or
"adaBoostSegmentationRefinement"  ?


brian

**Comment by ntustison** [comment]
Either one is fine with me.  Probably should go with the second, though, since it's more descriptive of actual functionality.

**Comment by ignatenkobrain** [comment]
used second option and sent pull request #245.
