### ISSUE TITLE
antsMotionCorrDiffusionDirection doesn't support Rigid transformation

### ISSUE THREAD

**Issue by fmorency** [stnava/ANTs#246]
I suspect the tool doesn't support anything other than Affine transformation. In the case of Rigid, the tool fails with

```
Read direction data of size: 31 x 3
Read motion correction data of size: 31 x 8
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /opt/miscelaneous/binary_ants/ITKv4-install/include/ITK-4.7/itkMatrixOffsetTransformBase.hxx:609:
itk::ERROR: AffineTransform(0x2291eb0): Error setting parameters: parameters array size (6) is less than expected  (NInputDimensions * NOutputDimensions + NOutputDimensions)  (3 * 3 + 3 = 12)
Aborted
```

**Comment by cookpa** [comment]
Hi, 

I have added support for rigid motion correction. Would you mind checking out this branch and testing?

https://github.com/stnava/ANTs/tree/antsMocoDiffDirRigidTrans

Thanks

**Comment by fmorency** [comment]
@cookpa It works! Thanks! Ship it.

**Comment by cookpa** [comment]
Great I will put in a pull request. Thanks for the report and testing the fix.
