### ISSUE TITLE
Benchmark Script/Dataset for ANTs?

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#247]
Similar to the TravisCI, is there anything around to test whether ANTs is getting faster/slower with commits?

I'm investigating some compiler things so I was wondering if anyone had looked into this before.

**Comment by ntustison** [comment]
No.  The closest thing we have are the timing tests that are done as part of the ITKv4 regression platform.  For example, you can see timing for a specific test which exercises N4 bias correction

https://open.cdash.org/testDetails.php?test=373086722&build=4114509

and then select "Display graphs:  Test time."
