### ISSUE TITLE
ANTs with system ITK installaton

### ISSUE THREAD

**Issue by TheChymera** [stnava/ANTs#248]
How can I tell ANTs not to compile ITK and use the system install instead?

My distribution provides `itk-4.5`. as the newest version, will thate be new wnough for ANTs (it seems to ship with `itk-4.9` - which is weird, since I only find sources up to [`itk-4.8`](http://www.itk.org/ITK/resources/software.html)).

**Comment by ntustison** [comment]
ANTs source tracks the latest ITK source pretty closely so, no, you can't use the current ANTs with ITK 4.5.  

You can use the cmake option USE_SYSTEM_ITK to not use the superbuild mechanism for ITK 4.9 installation.

**Comment by TheChymera** [comment]
@ntustison can I use ANTs with `itk-4.8.1`? I can't find the 4.9 sources anywhere.

The reason I really want to use the system itk is actually that the build system seems to have an issue somewhere.

I am getting this error when I am calling an ANTs command from nipype:

```
Standard error:
terminate called after throwing an instance of 'itk::MemoryAllocationError'
what():  /var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/ITKv4-install/include/ITK-4.9/itkImportImageContainer.hxx:199:
Failed to allocate memory for image.
Return code: -6
Interface ApplyTransforms failed to run. 
```

And since that is a directory in my package manager path, and gets created before compile time and deleted after the install is finished, I am guessing something is wrong with how the ANTs compiler links against ITK? What do you think might cause that path to still be remembered somewhere by ANTs?

**Comment by ntustison** [comment]
> @ntustison can I use ANTs with itk-4.8.1? I can't find the 4.9 sources anywhere.

No.  For the superbuild-ing of ITK, we specify the git tag and that tag was changed about a week to reflect some recent work I did in ITK proper which was reflected back to ANTs.  

> I am getting this error when I am calling an ANTs command from nippy:

I don't work with nipype so I can't help you with that.  Are you able to reproduce the error using the compiled ANTs programs directly?

**Comment by TheChymera** [comment]
@ntustison  not yet, which is why I brought nipype into the discussion. However, there is no way nipype knows about the compilation path of ANTs and ITK - so this error is coming from the ANTs side of things. I asume CMake set up some dynamic linking using the compile-time absolute path of some ITK component...

@kiwifb @ jlec - could you guys maybe give me an opinion on this?

**Comment by ntustison** [comment]
I'm guessing this is a system-specific set-up problem as opposed to an ANTs problem.

**Comment by TheChymera** [comment]
Alternatively:

* would the very latest ANTs work with the very latest ITK? (both live from github, ITK being [this](https://github.com/InsightSoftwareConsortium/ITK))
* what tag of ANTs would work with `itk-4.5.1` or `itk-4.8.1`?

**Comment by ntustison** [comment]
> would the very latest ANTs work with the very latest ITK? (both live from github, ITK being this)

It should.

> what tag of ANTs would work with itk-4.5.1 or itk-4.8.1?

I don't know if there's any git magic to answer this.  Perhaps someone like @hjmjohnson or @stnava  would know.

**Comment by cookpa** [comment]
Isn't the original error just antsApplyTransforms running out of memory? Can this error be reproduced with a small image and simple transform?

**Comment by cookpa** [comment]
Here's how to grep for a particular ITK version:

```
git log -G "ITK_VERSION_ID ITK-4.8" SuperBuild/External_ITKv4.cmake
```

This will show where the ITK version got changed. Thus it should give you the first and last + 1 commits where a particular ITK version is used.

I don't think that 4.8.1 ever got used in a commit. I guess you could try a version that works with 4.8. But I suspect this error:

```
Standard error:
terminate called after throwing an instance of 'itk::MemoryAllocationError'
what():  /var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/ITKv4-install/include/ITK-4.9/itkImportImageContainer.hxx:199:
Failed to allocate memory for image.
Return code: -6
Interface ApplyTransforms failed to run. 
```

is not a matter of system ITK or not. Unless ANTs got built with shared libraries, it shouldn't need ITK at run time.

**Comment by ntustison** [comment]
Thanks Phil.  That's good to know.
