### ISSUE TITLE
Using SyN for the first time

### ISSUE THREAD

**Issue by Metasoliton** [stnava/ANTs#251]
I am trying to use ANTs for the first time and would like to check SyN performance on a few very challenging datasets. I have already tried [rigid->affine->non-linear] and DARTEL transformation sequences which performed poorly. So, now I am looking for the most advanced normalization possible, to normalize T1 images and fMRI data from a few patients with early Alzheimer's Disease into an MNI template. Processing time is not an issue...

Assuming that what I want to accomplish is:

1) normalize a patient´s T1 (lets call it T1.nii) to the MNI template (lets call it MNI.nii) by obtaining a transformation matrix (lets call it T1_to_MNI)

2) applying the T1_to_MNI matrix to T1.nii 

3) applying the T1_to_MNI matrix to the fMRI.nii data from the same patient (that have already been pre-registered to the respective T1.nii) 

could one of the developers please suggest what code to intersect in my bash-based FSL pipeline? 

Looking forward to experiencing the power of the ultimate normalization algorithm,
Stav

**Comment by stnava** [comment]
https://github.com/stnava/ANTs/wiki/simple-case:-T1-to-MNI-mapping-for-both-structure-and-pre-registered-fMRI


brian

**Comment by Metasoliton** [comment]
Thank you both very much!

The improvement from the normalization methods I was using previously was
dramatic!
I think I am switching to SyN for good and shall probably get back in touch
once I have studied the rest of the ANTs manual.

In the meantime, I would like to point out a typo you have made in the
suggested solution, before the issue gets permanently closed:

in
antsApplyTransforms -d 3 -r MNI.nii.gz -i fMRI.nii.gz -e 3 -t -t
XXX1Warp.nii.gz -t XXX0GenericAffine.mat

there are three -t transform files expected, yet only two given, which
leads to a crash:
"Transform file does not exist: 1
Can't read initial transform 1"

Of course the solution was trivial, although it might be confusing to any
future readers of the thread if they treat it as an official document.

Many thanks again & all the best,
Stavros

**Comment by Metasoliton** [comment]
p.s. also, the -o argument is missing from both calls to antsApplyTransforms which can be confusing to new users as well.

**Comment by stnava** [comment]
fixed


brian
