### ISSUE TITLE
Combined --masks [fixedImageMask,movingImageMask] improperly limiting region of interest for SyN registration steps

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#254]
Using ANTs built from HEAD as of Today (23-11-2015), I'm running into the following issue:

When running a SyN registration between two images and specifying masks for both brains, the SyN registration is being limited to an ROI much smaller than the intersection of the masks. This is after confirming that the affine registration step was successful by visualizing the affine transformed moving image.

Calling SyN like this:
```
--transform SyN[0.5,3,0] --metric CC[$fixedfile,$movingfile,1,4] --convergence [100x100x0x0,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 4x2x1x0vox --masks [$fixedmask,$movingmask]
```

This was confirmed by generating and visualizing the Jacobian image from the Warp field.

Full example, including input files, script, log output and outputs found at https://www.dropbox.com/s/rokp44n7ghoxrm0/example.tar.bz2?dl=0

**Comment by gdevenyi** [comment]
Followup:

It appears to be that the movingmask is not having the prior (affine) transformations applied to it before the SyN registration takes place.

I determined this by visualizing the two masks along with the Jacobian field image, to find that the nonlinear field is only computed within the intersection of the masks in their initial space prior to any affine transformations.

**Comment by ntustison** [comment]
Thanks Gabriel, I'll try to take a look at this later this week.  Since you already have the visualization/testing set up, can you run a similar experiment using the ``GaussianDisplacementField`` transform (you can just use the same parameters as the SyN transform).  I don't care about the quality of the registration.  I just want to know if you see a similar effect.

**Comment by gdevenyi** [comment]
Can do!

**Comment by gdevenyi** [comment]
Running the same script with GaussianDisplacementField and visualizing shows the field is computed over the proper ROI in that case.

**Comment by ntustison** [comment]
Very interesting and that's good to hear.  I'd like to request one more test, if you don't mind.  Can you try ``BSplineSyN``?  Parameters---you should be able to use the same gradient step but do something like 
"[$gradientStep,26,0]" if it's a typical brain image.

**Comment by gdevenyi** [comment]
BSplineSyN also only computes the nonlinear in the intersection

**Comment by ntustison** [comment]
Makes sense.  Thanks for the info.  Like I said, I'll try to get to it later this week.

**Comment by ntustison** [comment]
Current progress update:  http://review.source.kitware.com/#/c/20443/

**Comment by gdevenyi** [comment]
Thanks for the update.

I stole the patch and applied it to my local copy. Rebuilding now, will test.

**Comment by ntustison** [comment]
Perfect.  Thanks for testing.

**Comment by gdevenyi** [comment]
The patch applied to the ITK grabbed by the superbuild does not appear to resolve the intersection issue.

**Comment by ntustison** [comment]
Hmmm.  Perhaps you can share your data or create a simple 2-D example which illustrates this issue.  I tested it on my end and it seemed to work.  Before this patch, the fixed and moving masks weren't even being used in the metric.

**Comment by gdevenyi** [comment]
Data/scripts are in the dropbox link in first comment :)

**Comment by gdevenyi** [comment]
Followup, to be clear, the issue I'm having is because of a multi-stage registration, the masks are not being transformed with the brains following the affine stage (from what I can tell).

If you're feeding syn pre-registered brains and testing masking, you may not trigger my bug.

**Comment by ntustison** [comment]
Great.  I'll take a look.

**Comment by ntustison** [comment]
Right.  My tests were using multi-stage registrations.

**Comment by ntustison** [comment]
Try the latest patch.

**Comment by gdevenyi** [comment]
It certainly looks different now, the jacobian is no longer confined to the intersection of the two masks.

Having said that, I don't think the calculation of the deformations is yet correct, if I run without masks I see some (obvious) nonlinear deformations around the ventricles, and in general the deformations follow the shape of the brain (after the affine transform is applied). In the case of using two masks, I don't see a correspondence that is informative.

Let me know if I can produce/provide any more examples.

**Comment by ntustison** [comment]
The Jacobian won't be confined to the intersection of the two masks.  However, if you overlay your mask on the Jacobian, you should see strong Jacobian features align with the mask which tells me it's working.

Also, with specific reference to your problem scenario, you can't simply apply your a brain masks and get a good registration.  One of the biggest features to drive the registration are the edges between the foreground and the background and your masks are completely eliminating that feature.  

If you really want to show that this patch is not working, try simplifying your example to 2-D geometric primitives with the above in mind.

**Comment by gdevenyi** [comment]
I'll refine my statement: 
Using patchset 3, the jacobian is now generally over the FOV where the brains overlap after affine registration (as should be the case) however, I find that the strong components of the jacobian are lateralized and no not follow the brain anatomy as I would expect.

I realize in general that just blindly adding masks won't improve registrations, that's why I asked for (and you graciously added) multi-stage masking so I can do stages both with and without masks, the example scripts I have provided and pared down to allow for a minimum working example of the problem I'm having.

I have run patchset 3 on my example data, with and without masking on the final stage, and produced jacobian images. I have included the outputs and scripts at https://dl.dropboxusercontent.com/u/307000/example2.tar.bz2

I have attached a screenshot showing side-by-side the jacobian images, on the left is the jacobian produced when masking the SyN stage. Of particular interest is the lack of left-right symmetry which is far more prevalent in the unmasked registration.

I have one last guess as to where this may be arising: I'm trying to test if the --initial-moving-transform may not be integrated, but I can't get a successful affine registration without it thus far. I'm not well versed enough in the ITK code to find that code to check it.

![screenshot from 2015-12-03 13 13 32](https://cloud.githubusercontent.com/assets/3001850/11569574/a6d4192a-99c0-11e5-83f9-db747fabe834.png)

**Comment by gdevenyi** [comment]
I will endeavour to figure out a simpler 2D example.

**Comment by stnava** [comment]
question: does this resolve https://github.com/stnava/ANTs/issues/117 ?

**Comment by ntustison** [comment]
Okay, here's a simple 2-D [example](https://github.com/ntustison/antsRegistrationWithMaskExample) which demonstrates the current masking capabilities with SyN.  Registration involves two brain slices with a square in one corner and a circle in the other corner.  The fixed and moving masks only include the brain.  Registration is performed with and without masking.  With masking, the Jacobian image is zero in the circle/square region in the corner (but nonzero without masking).

**Comment by gdevenyi** [comment]
That's for the example, what command did you use to extract the slices? I'd like to build a smaller example from my dataset for testing.

**Comment by gdevenyi** [comment]
For any future readers, ImageMath's ExtractSlice worked for what I needed.

**Comment by gdevenyi** [comment]
Okay, so I have now constructed a 2D example using slices from the existing 2D dataset (mostly arbitrarily, i.e. these are not anatomically appropriate slices), and again I see the same issue as I described above. When using two masks the jacobian field is not computed for the overlap of the two brains despite the affine transformation successfully bringing them into coincidence. Without masks the jacobian is as expected.

I did one other test with the full 3D dataset to test for a difference between affine + syn multi-stage registrations with masks vs just syn with masks so I compared:
1) CoM + rigid + affine + SyN with masks
vs
2) CoM + rigid + affine (with masks) -> Apply transform to moving brain and mask -> SyN with Masks

The outputs of 1) show the issues described above in my comment with screenshots, the output of 2) is reasonable and similar to the outputs produced without a mask

This indicates to me that there still remains an issue with the internal representation of the mask as if I break up the steps to apply the transforms manually to files, I get the proper result.

**Comment by gdevenyi** [comment]
Example inputs/outputs and script for 2D https://dl.dropboxusercontent.com/u/307000/example3.tar.bz2

**Comment by ntustison** [comment]
Okay, that example is a bit difficult to work with since the registration problem is completely different between the two scenarios (without the mask also includes the skull).  However, I removed the skulls from both images and was able to isolate the problem.  I updated the patch which is in the queue for testing.

**Comment by gdevenyi** [comment]
Hrm, good point re: skullstripping. You've taught me a lot on building a minimally working example :)

Will test new code with 2D and 3D.

<I have not tested this part yet, but when the affine is resolved, this is my next test>
Something to think about next, does SyN warping get applied to the masks if there's no mask for a given stage i.e:
```
--transform SyN[0.1,3,0] --metric CC[$fixedfile,$movingfile,1,6] --convergence [100x100x0x0,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 4x2x1x0vox --masks [NULL,NULL]
--transform SyN[0.1,3,0] --metric CC[$fixedfile,$movingfile,1,4] --convergence [100x100x0x0,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 4x2x1x0vox --masks [$fixedmask,$movingmask]
```

**Comment by ntustison** [comment]
> Hrm, good point re: skullstripping. You've taught me a lot on building a minimally working example :)

Yeah, and I also took out the affine and rigid steps as they weren't necessary to illustrate the problem.  The current issue was introduced when trying to fix the original issue.  

>  Something to think about next, does SyN warping get applied to the masks if there's no mask for a given stage i.e:

Can you clarify a bit?  Are you trying to apply SyN in two successive stages?  One with a mask and one without?

**Comment by gdevenyi** [comment]
I see. I thought those were integral to the issue as when I ran the 2D example you provided it worked, and it lacked stages besides the CoM registration.

Yes, two successive stages of SyN, the first without, and the second with a mask. My (completely untested) thought is that I can do large-scale larger CC radius iterations before focusing the registration with a mask.
I haven't tested this yet, but its something I intend to try.

**Comment by gdevenyi** [comment]
Ran the newest patch set, looks correct now.

Thanks for your continued debugging.

**Comment by ntustison** [comment]
Yes, that should work if everything is specified on the command line correctly.  If it doesn't then there's a bug.

**Comment by gdevenyi** [comment]
Looks like the patch got merged, has the ANTs ITK hash been updated to reflect the merged version?

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/ace949d74fff4bf4e67b52faa43d60d7e5c95ec5

```
[ntustison@Mactatus-Logico-Philosophicus Mon Jan 11 13:01:27] $ cd ~/Pkg/ITK
[ntustison@Mactatus-Logico-Philosophicus Mon Jan 11 13:01:32] $ git show fc03bcc92b11326b87c232c14eb234fc1f791f9f
commit fc03bcc92b11326b87c232c14eb234fc1f791f9f
Merge: f952714 111114c
Author: Nick Tusison <ntustison@gmail.com>
Date:   Tue Dec 22 21:54:35 2015 -0500

    Merge topic 'MaskRegistrationMethods'
    
    111114cd ENH:  Add fixed/moving masking in reg. methods.
```
