### ISSUE TITLE
syntax error in antsRegistrationSyN.sh ????

### ISSUE THREAD

**Issue by Metasoliton** [stnava/ANTs#256]
I am registering a patient´s T1 to an MNI template via the procedure you suggested recently here:
https://github.com/stnava/ANTs/issues/251#issuecomment-159251798

The procedure seems to work great, however when I look into the nohup log I see the report pasted below.

Can this be safely ignored?

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /usr/lib/ants

 Dimensionality:           3
 Output name prefix:       test
 Fixed images:             ../Data/sMRI/mni.nii
 Moving images:            ../Data/sMRI/c114/reg_t1_c114_a.nii
 Number of threads:        1
 Spline distance:          26
 Transform type:           s
 CC radius:                4
 Precision:                d
 Use histogram matching    0
======================================================================================
antsRegistrationSyN.sh: line 367: [1,: syntax error: operand expected (error token is "[1,")
antsRegistrationSyN.sh: line 367: 1,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 1]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: [90,: syntax error: operand expected (error token is "[90,")
antsRegistrationSyN.sh: line 367: -92,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 110]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: [180,: syntax error: operand expected (error token is "[180,")
antsRegistrationSyN.sh: line 367: 218,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 182]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: {[90: syntax error: operand expected (error token is "{[90")
antsRegistrationSyN.sh: line 367: 110],: syntax error: invalid arithmetic operator (error token is "],")
antsRegistrationSyN.sh: line 367: [270: syntax error: operand expected (error token is "[270")
antsRegistrationSyN.sh: line 367: 292]}: syntax error: invalid arithmetic operator (error token is "]}")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: [1,: syntax error: operand expected (error token is "[1,")
antsRegistrationSyN.sh: line 367: 1,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 1]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: [0,: syntax error: operand expected (error token is "[0,")
antsRegistrationSyN.sh: line 367: 9999]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: 2758.21: syntax error: invalid arithmetic operator (error token is ".21")
antsRegistrationSyN.sh: line 367: .: syntax error: operand expected (error token is ".")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: el->RAS: syntax error: operand expected (error token is ">RAS")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: Metadata:: syntax error in expression (error token is ":")
antsRegistrationSyN.sh: line 367: =: syntax error: operand expected (error token is "=")
antsRegistrationSyN.sh: line 367: =: syntax error: operand expected (error token is "=")
 antsRegistration call:
--------------------------------------------------------------------------------------
/usr/lib/ants/antsRegistration --verbose 1 --dimensionality 3 --float 0 --output [test,testWarped.nii.gz] --interpolation Linear --winsorize-image-intensities [0.005,0.995] --use-histogram-matching 0 --initial-moving-transform [../Data/sMRI/mni.nii,../Data/sMRI/c114/reg_t1_c114_a.nii,1] --transform Rigid[0.1] --metric MI[../Data/sMRI/mni.nii,../Data/sMRI/c114/reg_t1_c114_a.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[0.1] --metric MI[../Data/sMRI/mni.nii,../Data/sMRI/c114/reg_t1_c114_a.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform SyN[0.1,3,0] --metric CC[../Data/sMRI/mni.nii,../Data/sMRI/c114/reg_t1_c114_a.nii,1,4] --convergence [100x100x70x50x20,1e-6,10] --shrink-factors 10x6x4x2x1 --smoothing-sigmas 5x3x2x1x0vox
--------------------------------------------------------------------------------------
=============================================================================
The composite transform is comprised of the following transforms (in order): 
  1. Center of mass alignment using fixed image: ../Data/sMRI/mni.nii and moving image: ../Data/sMRI/c114/reg_t1_c114_a.nii (type = TranslationTransform)
=============================================================================

**Comment by stnava** [comment]
use bash.


brian

**Comment by Metasoliton** [comment]
I am using bash by calling explicitly:
 nohup bash antsRegistrationSyN.sh -d 3 -f ../Data/sMRI/mni.nii  -m  ../Data/sMRI/${sub}/reg_t1_${sub}_a.nii -o test.nii

**Comment by stnava** [comment]
here is the code:

https://github.com/stnava/ANTs/blob/master/Scripts/antsRegistrationSyN.sh#L367

maybe you can figure this out for yourself.


brian

**Comment by ntustison** [comment]
What about ``nohup sh antsRegistrationSyN.sh...``?

**Comment by Metasoliton** [comment]
$  sh antsRegistrationSyN.sh -d 3 -f ../Data/sMRI/mni.nii  -m  ../Data/sMRI/${sub}/reg_t1_${sub}_a.nii -o test
trap: SIGINT: bad trap
antsRegistrationSyN.sh: 8: antsRegistrationSyN.sh: function: not found

--------------------------------------------------------------------------------------
Error locating ANTS
--------------------------------------------------------------------------------------
It seems that the ANTSPATH environment variable is not set. Please add the ANTSPATH
variable. This can be achieved by editing the .bash_profile in the home directory.


NOTE: 
I have pasted ANTSPATH=/usr/lib/ants
at the end of both 
.profile   and .bashrc
and because that was not effective, I define again ANTSPATH=/usr/lib/ants at the top of antsRegistrationSyN.sh
(I am using Ubuntu 12.04.5 LTS Precise Pangolin)

**Comment by Metasoliton** [comment]
@ stnava 

I always try to figure things out myself before posting here and really appreciate your time and support.

On a sidenote, in https://github.com/stnava/ANTs/wiki/simple-case:-T1-to-MNI-mapping-for-both-structure-and-pre-registered-fMRI  
the suggested commands only work properly if the structural and functional images have the same resolution, which is typically not the case, e.g. 1x1x1 and 3x3x3 in my case.
The ANTs documentation suggests that  the -s and -f arguments of antsRegistration  can be used to account for differences in resolution but when using antsRegistrationSyN -s and -f refer to different parameters! 

Do I just have to add "-s 3x3x3" at the end of line 50 in antsRegistrationSyN.sh: 
line 50: `basename $0` -d ImageDimension -f FixedImage -m MovingImage -o OutputPrefix

**Comment by stnava** [comment]
if the fmri is indeed registered to the T1 ( in the ITK definition ), then
you should have to trouble using `antsApplyTransforms`.  that program does
not care about the input image resolution - only that it is in the same
space as the T1 as per the ITK / ANTs definition of this.   we have several
comments throughout that suggest mixing FSL and ITK / ANTs can lead to
unexpected issues (often caused by FSL's idiosyncratic use of NIFTI) that
we do not support.


brian

**Comment by stnava** [comment]
ooops - should read " should have no trouble using "


brian

**Comment by Metasoliton** [comment]
I actually used LIPSIA´s preregistration, which is also based on ITK. 

Regardless, I would be happy to do the whole registration using ANTs, however, it seems that the moving image always attains the xyz dimensions of the reference image. 

Isn´t there a parameter that prevents this or could you please modify https://github.com/stnava/ANTs/wiki/simple-case:-T1-to-MNI-mapping-for-both-structure-and-pre-registered-fMRI to include the pre-registration of T1 to fMRI?

I have looked through all the examples yet it seems that this was too simple a case to include!?

**Comment by stnava** [comment]
share some data. make it very clear.


brian

**Comment by Metasoliton** [comment]
Dear Brian,

Thank you very much in advance for looking into this...

So, I am sharing the
T1 (T1.nii) and fMRI (fMRI.nii) from the most troublesome subject (even SyN failed to normalize the orbitofrontal cortex)
plus the MNI template I am using (mni.nii),

through this link:  http://we.tl/pdeLWR1uq0

The T1 and fMRI have been preregistered using the ITK-based functions of LIPSIA (https://www.cbs.mpg.de/institute/software/lipsia/index.html)


Issue A:
The T1 is in 1x1x1 and the fMRI is in 3x3x3 mm voxel resolution.

If you were to update the ANTs wiki page: https://github.com/stnava/ANTs/wiki/simple-case:-T1-to-MNI-mapping-for-both-structure-and-pre-registered-fMRI

to account for this common mismatch in voxel resolution

and/or

include the step that pre-registers the T1 to the fMRI data,

I (as well as many other novice ANTs users) would be very grateful.

(sidenote: I have noticed that you recommend normalizing the zmaps from the 1st level instead, yet this deviates somewhat from the most commonly accepted procedure. I would have trouble defending this approach - are there any papers comparing these two approaches?)


Issue B:
Does the procedure suggested on the wikipage produce a better result on your systems?
In mine it produces the attached SyN_T1.nii which is quite poor; look at the "shortage" of the orbitofrontal cortex specifically!

Are there any other parameters that can be further optimized in the implementation of the wikipage?


Issue C:
Even when antsRegistrationSyN.sh (as called in the wiki page above) works well, these errors appear in the report file:

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /usr/lib/ants

 Dimensionality:           3
 Output name prefix:       g219_
 Fixed images:             ../Data/sMRI/mni.nii
 Moving images:            ../Data/sMRI/g219/reg_t1_g219_a.nii
 Number of threads:        1
 Spline distance:          26
 Transform type:           s
 CC radius:                4
 Precision:                d
 Use histogram matching    0
======================================================================================
antsRegistrationSyN.sh: line 367: [1,: syntax error: operand expected (error token is "[1,")
antsRegistrationSyN.sh: line 367: 1,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 1]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: [90,: syntax error: operand expected (error token is "[90,")
antsRegistrationSyN.sh: line 367: -92,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 110]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: [180,: syntax error: operand expected (error token is "[180,")
antsRegistrationSyN.sh: line 367: 218,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 182]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: {[90: syntax error: operand expected (error token is "{[90")
antsRegistrationSyN.sh: line 367: 110],: syntax error: invalid arithmetic operator (error token is "],")
antsRegistrationSyN.sh: line 367: [270: syntax error: operand expected (error token is "[270")
antsRegistrationSyN.sh: line 367: 292]}: syntax error: invalid arithmetic operator (error token is "]}")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: [1,: syntax error: operand expected (error token is "[1,")
antsRegistrationSyN.sh: line 367: 1,: syntax error: operand expected (error token is ",")
antsRegistrationSyN.sh: line 367: 1]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: [0,: syntax error: operand expected (error token is "[0,")
antsRegistrationSyN.sh: line 367: 9999]: syntax error: invalid arithmetic operator (error token is "]")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: 2758.21: syntax error: invalid arithmetic operator (error token is ".21")
antsRegistrationSyN.sh: line 367: .: syntax error: operand expected (error token is ".")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: el->RAS: syntax error: operand expected (error token is ">RAS")
antsRegistrationSyN.sh: line 367: :: syntax error: operand expected (error token is ":")
antsRegistrationSyN.sh: line 367: Metadata:: syntax error in expression (error token is ":")
antsRegistrationSyN.sh: line 367: =: syntax error: operand expected (error token is "=")
antsRegistrationSyN.sh: line 367: =: syntax error: operand expected (error token is "=")
 antsRegistration call:
--------------------------------------------------------------------------------------
/usr/lib/ants/antsRegistration --verbose 1 --dimensionality 3 --float 0 --output [g219_,g219_Warped.nii.gz] --interpolation Linear --winsorize-image-intensities [0.005,0.995] --use-histogram-matching 0 --initial-moving-transform [../Data/sMRI/mni.nii,../Data/sMRI/g219/reg_t1_g219_a.nii,1] --transform Rigid[0.1] --metric MI[../Data/sMRI/mni.nii,../Data/sMRI/g219/reg_t1_g219_a.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[0.1] --metric MI[../Data/sMRI/mni.nii,../Data/sMRI/g219/reg_t1_g219_a.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform SyN[0.1,3,0] --metric CC[../Data/sMRI/mni.nii,../Data/sMRI/g219/reg_t1_g219_a.nii,1,4] --convergence [100x100x70x50x20,1e-6,10] --shrink-factors 10x6x4x2x1 --smoothing-sigmas 5x3x2x1x0vox
--------------------------------------------------------------------------------------
=============================================================================
The composite transform is comprised of the following transforms (in order): 
  1. Center of mass alignment using fixed image: ../Data/sMRI/mni.nii and moving image: ../Data/sMRI/g219/reg_t1_g219_a.nii (type = TranslationTransform)
=============================================================================

(I am using Ubuntu 12.04)

All the best,
Stav

**Comment by stnava** [comment]
hi stav

thanks for sharing the data.  this makes it much easier to respond.

issue A:  the wiki example is correct.  you may be using some old code that
had a bug in the `antsApplyTransforms -e 3 ` option.  try the source
version of ANTs.

sub-issue A:  mni is a highly distorted space and, if you do statistics in
that space, you are embedding substantial distortion and resampling-induced
issues into your study. however, if you do not care about individual level
fidelity, then you can ignore the subject space and just work in group
space.  personally, i like to see individual level activation in a
subject-specific template space that is distorted only by the
machine/session, not by additional transformations that make already
challenging data even more difficult to analyze and interpret.  but i am
interested in, also, having high fidelity maps between structure and
function whereas most studies ignore the structural contributions to their
activation/connection maps.

Issue B:  the wiki example also suggests:

" 2 stages of registration: T1 to customTemplate to MNI and then
concatenating these via antsApplyTransforms"

​long ago, we recommended *not* trying to go directly to MNI and we still
maintain this position ... mapping whole head images direct to MNI is a
particularly unreliable strategy.  better to perform brain extraction.
see the ants cortical thickness paper for more motivation / explanation.

​
​issue C: i cant help with your shell.​
