### ISSUE TITLE
Converting Warps into SPM format

### ISSUE THREAD

**Issue by andreashorn** [stnava/ANTs#257]
Hello ANTs devs,

@stnava told me to post this question here:

I'd like to convert *1Warp.nii and *0GenericAffine.mat files into a joint "SPM-like" Deformation field (6D nifti file). Does anyone have information/code on how to do so?
Any help would be much appreciated!

Thanks a lot, Andy

**Comment by stnava** [comment]
[nipype](http://nipy.org/nipype/) is one possible approach but i do not know it well enough to say much more ... perhaps @satra or the [nipype documentation](http://nipy.org/nipype/documentation.html) would help.

**Comment by satra** [comment]
@andreashorn - this is going to take some work. in nipype an example dataflow can takes things out of spm, runs with ants including applying the deformations and then brings things back into spm.

however converting deformation fields across software requires understanding the way these are represented and they all vary across major packages. we have in the past considered a common deformation format, but that discussion really did not go anywhere!

**Comment by stnava** [comment]
This is not really an ANTs issue as evidenced by lack of international consensus on transformation standards.  So, closing issue.  Happy to reopen a new issue on this topic if someone wants to write a specific utility for conversion between ANTs/ITK space and other systems.
