### ISSUE TITLE
Bug in CalculateJacobianDeterminantImage (geometric option)

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTs#259]
Just for documentation:  

(from Brian) 

a user alerted me to this issue ... basically, the story is this:

a warp field has the following direction in its header:

  Direction Cos Mtx. : 
-1 0 0
0 -1 0
0 0 1

if i change this to:

 Direction 
1 0 0
0 -1 0
0 0 1

​i get different jacobian results for the geometric jacobian.

here is the R code:

library(ANTsR)
 j1=antsImageRead("/tmp/j1.nii.gz")
 j0=antsImageRead("/tmp/j0.nii.gz")
 j1b=antsImageRead("/tmp/j1b.nii.gz")
 j0b=antsImageRead("/tmp/j0b.nii.gz")
 mk=thresholdImage( abs(j1), 0, Inf )
 cor( j1[mk==1], j0[mk==1] )   # outputs: -0.67
 cor( j1b[mk==1], j0b[mk==1] ) # outputs: 0.53
 cor( j1[mk==1], j1b[mk==1] )  # outputs: -0.1
 cor( j0[mk==1], j0b[mk==1] )  # outputs: 1
​
​these are the calls to CreateJacobian ...​

CreateJacobianDeterminantImage 3 S64944_shapeshift_1Warp.nii.gz /tmp/j0.nii.gz 1 0 

CreateJacobianDeterminantImage 3 S64944_shapeshift_1Warp.nii.gz /tmp/j1.nii.gz 1 1 &

CreateJacobianDeterminantImage 3 testWarp.mha /tmp/j1b.nii.gz 1 1 &

CreateJacobianDeterminantImage 3 testWarp.mha /tmp/j0b.nii.gz 1 0 &

**Comment by ntustison** [comment]
Okay, I think I'm pretty sure I [fixed](https://github.com/stnava/ANTs/commit/c4e1ba47653bfc3482d5241fd3b2ebb7a76b9d9c) it.  The problem was that the vector interpolator was returning the _local vector_ which is not rotated with the image domain.

**Comment by ntustison** [comment]
This commit might not have fixed the problem.  Brian and I are working on testing the latest [solution](https://github.com/stnava/ANTs/commit/08e24e5e8c0e294406f84b115ef2886989e46987).

**Comment by cookpa** [comment]
Bump, @ntustison, did you ever conclude whether this was fixed?

**Comment by stnava** [comment]
see https://github.com/stnava/jacobianTests

**Comment by cookpa** [comment]
Thanks. geometric vs finite diff look the same for me.
