### ISSUE TITLE
Wishlist: <outputwarpedimage> for secondary metrics

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#262]
Very much a wishlist idea since antsApplyTransforms can do this.

When I run a multi-spectral, multi-metric registration (e.g. T1 and T2 or FA and MD) the <outputWarpedImage> only warps the first moving image.

It would be nice (tm) if there were an option to warp all metric moving files and the end of the registration.

**Comment by ntustison** [comment]
I would vote against this as an instance of [feature creep](https://en.wikipedia.org/wiki/Feature_creep).  It would possibly add another option/flag to the command line.  Different sets of images could be used to obtain the different transforms at each stage of the registration and we'd have to decide what set of images to warp.  For me, it's not a clean and simple addition to ``antsRegistration`` and, as you mention, one that could be easily handled by scripting and the use of ``antsApplyTransforms``.

**Comment by gdevenyi** [comment]
The multi-stage thing makes sense. Thanks.

Closing.
