### ISSUE TITLE
antsJointLabelFusion.sh SLURM bug with fix

### ISSUE THREAD

**Issue by Trevh5** [stnava/ANTs#263]
Just wanted to give you a heads up that while running antsJointLabelFusion.sh using SLURM, I ran into a strange error. The final antsJLF.sh script kept quitting without any specific errors. Eventually, I changed line 1078 to allocate more memory to the job and that fixed the issue. I think this change should be sufficient for most jobs, but I will let you make that call.
"--mem=8192M" --> "--mem=16384M".

**Comment by njhunsak** [comment]
Same here!! I just changed the code throughout the antsJointLabelFusion.sh script and it's running now. Keep your fingers crossed.

**Comment by ntustison** [comment]
Yeah, I've been meaning to add a couple options (similar to what I did [here](https://github.com/stnava/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L166-L170)).  I'll try to get to that soonish.

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/639e6f995e5aa59a14561312c100747df4f49bf2

**Comment by ntustison** [comment]
Additional mods:  https://github.com/stnava/ANTs/commit/f84fdb8b1cfd30b32cefd64a16ce78506071ba14

**Comment by Tokazama** [comment]
I think line 1116 needs to be  `"$maskCall" >> $qscript2`. Until I made this change I couldn't get the joinFusion part to run.

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/427a2352387bb4640960c652ee065ab1aeb6cf95
