### ISSUE TITLE
BUG: --minc option throws error trying to write out transforms

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#264]
Calling @vfonov since he had the original PR which added this feature.

Running latest master branch, just went into config and enabled MINC as per https://github.com/stnava/ANTs/pull/198

Run antsRegistration with --minc, throws the following error:
```
Can't write transform file temp//OASIS_OAS1_0001_MR1_t1.mnc-OASIS_OAS1_0001_MR1_t1.mnc0_GenericAffine.xfm
Exception Object caught: 

itk::ExceptionObject (0x3681f30)
Location: "unknown" 
File: /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.9/itkTransformFileWriter.hxx
Line: 143
Description: itk::ERROR: TransformFileWriterTemplate(0x36b12e0): Can't Create IO object for file temp//OASIS_OAS1_0001_MR1_t1.mnc-OASIS_OAS1_0001_MR1_t1.mnc0_GenericAffine.xfm


Can't write transform file temp//OASIS_OAS1_0001_MR1_t1.mnc-OASIS_OAS1_0001_MR1_t1.mnc1_NL.xfm
Exception Object caught: 

itk::ExceptionObject (0x3697a00)
Location: "unknown" 
File: /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.9/itkTransformFileWriter.hxx
Line: 143
Description: itk::ERROR: TransformFileWriterTemplate(0x36b12e0): Can't Create IO object for file temp//OASIS_OAS1_0001_MR1_t1.mnc-OASIS_OAS1_0001_MR1_t1.mnc1_NL.xfm


Can't write transform file temp//OASIS_OAS1_0001_MR1_t1.mnc-OASIS_OAS1_0001_MR1_t1.mnc1_inverse_NL.xfm
Exception Object caught: 

itk::ExceptionObject (0x3697a00)
Location: "unknown" 
File: /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.9/itkTransformFileWriter.hxx
Line: 143
Description: itk::ERROR: TransformFileWriterTemplate(0x36b12e0): Can't Create IO object for file temp//OASIS_OAS1_0001_MR1_t1.mnc-OASIS_OAS1_0001_MR1_t1.mnc1_inverse_NL.xfm
```

**Comment by vfonov** [comment]
Did you build ITK with minc support?

**Comment by gdevenyi** [comment]
Running latest master branch, just went into config and enabled MINC as per #198

**Comment by vfonov** [comment]
Well, looks like your build doesn't have MINC Transform IO registered

**Comment by gdevenyi** [comment]
I guess I'm missing an option in the superbuild patch I wrote, do you know what the transform option is?

**Comment by vfonov** [comment]
Module_ITKIOMINC:BOOL=ON
Module_ITKIOTransformMINC:BOOL=ON

**Comment by gdevenyi** [comment]
Cheers,  I will patch the superbuild.

**Comment by gdevenyi** [comment]
@vfonov Slightly related issue. It looks like if I build without any MINC support enabled (aka the default config) --minc is still an option in antsRegistration.

**Comment by vfonov** [comment]
MINC support in ITK?

**Comment by gdevenyi** [comment]
Yes, specifically, building the ANTs SuperBuild wihtout enabling MINC as per https://github.com/stnava/ANTs/pull/198

So ITKv4 is getting built without MINC support, but antsRegistration sill has a --minc command.
