### ISSUE TITLE
ImageMath Mattes bug

### ISSUE THREAD

**Issue by mattcieslak** [stnava/ANTs#266]
Not sure if this is worthy of a pull request, but I believe https://github.com/stnava/ANTs/blob/master/Examples/ImageMath.cxx#L12032 should be uncommented.

**Comment by ntustison** [comment]
It's unclear if this was fixed or not.  Going to close for now and depend on future clarification to reopen.

**Comment by gdevenyi** [comment]
Line has moved to https://github.com/stnava/ANTs/blob/master/Examples/ImageMath.cxx#L12058

Looks like right now, the image metric commands return their value, but nothing is ever done with it? Its not printed, and value is never used?

**Comment by stnava** [comment]
we made a pass through to remove all std::cout and this was a victim


brian

**Comment by gdevenyi** [comment]
So, looks like this needs to be reopened and broadened to all ImageMetric outputs.

**Comment by cookpa** [comment]
The cout purge also causes the brainvols.csv in antsCorticalThickness.sh to be blank. I uncommented the relevant lines in the metric function and the "total" / "vtotal" functions.
