### ISSUE TITLE
ERROR:  Invalid flag provided verbose

### ISSUE THREAD

**Issue by Metasoliton** [stnava/ANTs#267]
Dear Brian & Nick, 

I am still trying to get ANTs to work here. Following your previous suggestions I changed operating system and moved from Ubutnu 12.04 to 14.04.

After an unsuccessful attempt to built from binaries, I installed Linux_Ubuntu14.04.tar.bz2 from https://github.com/stnava/ANTs/releases

and tried to run:
bash antsRegistrationSyN.sh -d 3 -f ../Data/SyN/sMRI/mni.nii  -m  ../Data/SyN/sMRI/${sub}/reg_t1_${sub}_a.nii -o ${sub}_

The output was:

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /usr/lib/ants

 Dimensionality:           3
 Output name prefix:       c101_
 Fixed images:             ../Data/SyN/sMRI/mni.nii
 Moving images:            ../Data/SyN/sMRI/c101/reg_t1_c101_a.nii
 Number of threads:        1
 Spline distance:          26
 Transform type:           s
 CC radius:                4
 Precision:                d
 Use histogram matching    0
======================================================================================
 antsRegistration call:
--------------------------------------------------------------------------------------
/usr/lib/ants/antsRegistration --verbose 1 --dimensionality 3 --float 0 --output [c101_,c101_Warped.nii.gz] --interpolation Linear --winsorize-image-intensities [0.005,0.995] --use-histogram-matching 0 --initial-moving-transform [../Data/SyN/sMRI/mni.nii,../Data/SyN/sMRI/c101/reg_t1_c101_a.nii,1] --transform Rigid[0.1] --metric MI[../Data/SyN/sMRI/mni.nii,../Data/SyN/sMRI/c101/reg_t1_c101_a.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[../Data/SyN/sMRI/mni.nii,../Data/SyN/sMRI/c101/reg_t1_c101_a.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[../Data/SyN/sMRI/mni.nii,../Data/SyN/sMRI/c101/reg_t1_c101_a.nii,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox
--------------------------------------------------------------------------------------
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.

[end of output]

Any suggestions would be greatly appreciated.

Best of wishes for the new year,
Stav

**Comment by stnava** [comment]
this is the recommended method of installation:

https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/

binaries are rarely updated.

your error reads:

ERROR: Invalid flag provided verbose
ERROR: Invalid command line flags found! Aborting execution
so you might remove the verbose option, which probably did not exist at the
time of the binary release.


brian

**Comment by HarrisNami** [comment]
Hello, 

I am running the antsMultivariateTemplateConstruction2.sh script and I am getting a similar error with the verbose as you will see below. I just cloned and installed ANTs today so I am using the latest version. 

--------------------------------------------------------------------------------------
 Creating template TD_template0.nii.gz from a population average image from the inputs.
   test1.nii.gz test2.nii.gz
--------------------------------------------------------------------------------------
 fn test1.nii.gz
 bigimage 4 curr_image 4 size [244, 335]
 fn test2.nii.gz
 bigimage 4 curr_image 5 size [244, 335]
 Setting physcal space of output average image based on largest image 
 Averaging 2 images with dim = 2 vector components 1
 reading test1.nii.gz
 reading test2.nii.gz
 writing output ./job_0_qsub.sh
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
./job_1_qsub.sh
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.

/usr/local/ants/AverageImages 2 TD_template0.nii.gz 1 ./rigid0_0_test1.nii.gz ./rigid1_0_test2.nii.gz
./antsMultivariateTemplateConstruction2.sh: line 270: 22977 Segmentation fault: 11  ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}

--------------------------------------------------------------------------------------
 Start to build templates: TD_template0.nii.gz
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /usr/local/ants

 Dimensionality:           2
 Do N4 bias correction:    0
 Back up each iteration:   0
 Similarity metric:        CC
 Gradient step:            0.25
 Transformation:           SyN
 Max iterations:           100x100x70x20
 Smoothing factors:        3x2x1x0
 Shrink factors:           6x4x2x1
 Output prefix:            TD_
 Template:                 TD_template
 Template update steps:    4
 Template population:      test1.nii.gz test2.nii.gz
 Number of modalities:     1
 Madality weights:         
 Image statistic:          1
--------------------------------------------------------------------------------------
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
ERROR:  Invalid flag provided verbose
ERROR:  Invalid command line flags found! Aborting execution.
ls: TD_*Warp.nii.gz: No such file or directory
ls: TD_*GenericAffine.mat: No such file or directory
shapeupdatetotemplate()

--------------------------------------------------------------------------------------
 shapeupdatetotemplate---voxel-wise averaging of the warped images to the current template
Mon 30 Oct 2017 15:48:39 EDT
--------------------------------------------------------------------------------------
ls: TD_template0*WarpedToTemplate.nii.gz: No such file or directory
ERROR shapeupdatedtotemplate - imagelist length is 0


Thanks,
Harris

**Comment by ntustison** [comment]
Please try running these [examples](https://github.com/ntustison/TemplateBuildingExample), particularly the ones that call ``antsMultivariateTemplateConstruction2.sh`` and let me know if you run into any problems.

**Comment by HarrisNami** [comment]
Hello Nick,

I ran both examples with the commands that call antsMultivariateTemplateConstruction2.sh and they worked.

**Comment by ntustison** [comment]
I don't see it above but do you notice any differences in your command call with the command calls found in the examples?  Note that you should use absolute paths.

**Comment by HarrisNami** [comment]
I just applied the same format of calling the function to my dataset I was testing and it works now too. I believe it may have been an issue with either the parameters or just the way of calling it. I'm looking into it a bit more to distinguish the differences, but at least it works! Thanks for your help!
