### ISSUE TITLE
antsRegistration ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS scaling results

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#268]
I was running some thead scaling results (running the same command with different numbers of threads) to optimize my cluster jobs so I'd thought I'd report them:

```
antsRegistration --dimensionality 3 --float 0 --collapse-output-transforms 1 --verbose \
  --output [$outputdir/$(basename $movingfile)-$(basename $fixedfile)] \
  --winsorize-image-intensities [0.01,0.99] --use-histogram-matching 1 \
  --initial-moving-transform [$fixedfile,$movingfile,1] \
  --transform Rigid[0.5] --metric Mattes[$fixedfile,$movingfile,1,32,Random,0.5] --convergence [2000x2000x2000x2000x0,1e-6,10] --shrink-factors 16x8x4x2x1 --smoothing-sigmas 4x3x2x1x0vox \
  --transform Affine[0.1] --metric Mattes[$fixedfile,$movingfile,1] --convergence [10000x10000x10000x10000,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox \
  --transform BSplineSyN[0.5,52,0] --metric CC[$fixedfile,$movingfile,1,4] --convergence [400x200x100x50x25,1e-6,10] --shrink-factors 16x8x4x2x1 --smoothing-sigmas 5x4x2x1x0vox
```

| Threads | walltime | ants_walltime | kb_memory | 
|---------|----------|---------------|-----------| 
| 1       | 03:34:54 | 1.29E+04      | 6805420   | 
| 2       | 02:07:19 | 7.60E+03      | 6815844   | 
| 3       | 01:17:57 | 4.64E+03      | 6827188   | 
| 4       | 00:59:36 | 3.54E+03      | 6837972   | 
| 5       | 00:58:04 | 3.44E+03      | 6849004   | 
| 6       | 00:45:21 | 2.68E+03      | 6806424   | 
| 7       | 00:47:30 | 2.80E+03      | 6806508   | 
| 8       | 00:44:32 | 2.63E+03      | 6826284   | 
| 9       | 00:44:02 | 2.60E+03      | 6838512   | 
| 10      | 00:42:57 | 2.54E+03      | 6850352   | 
| 11      | 00:43:18 | 2.56E+03      | 6809008   | 
| 12      | 00:43:14 | 2.55E+03      | 6807856   | 

Some observations:
- walltime drops quickly until 6 threads, then levels off
- memory usage linearly increases 1-5 threads, then drops for 6-7, then increases again to 10, then drops for 11-12, it's only 42Mb, but still interesting.

**Comment by gdevenyi** [comment]
Followup:

Cores 0-6 are physical cores, 7-12 are hyperthreaded, so, it looks like hyperthreading has zero benefit on this workload

**Comment by dorianps** [comment]
Very good to know.

**Comment by hjmjohnson** [comment]
Here is a nice explanation for why this is happening:
http://www.agner.org/optimize/blog/read.php?i=6

The problem is that this work load per thread is too homogeneous (I.e. Every thread requires the same cpu resources), so every 2 threads are competing for the same resources, and therefore each thread is working at 50% efficiency. 

If two threads have different resource needs (I.e. One does floating point work, another is reading from disk) then having hyper threads can be good use of resources.

Hans

**Comment by gdevenyi** [comment]
Thanks for the explanation link @hjmjohnson 

I have access to some systems with the intel compiler, so I will do similar testing for scaling with intel optimizations to see if it can induce any hyperthreading performance improvements
