### ISSUE TITLE
BUG: When ITK_BUILD_MINC_SUPPORT enabled, antsRegistration can't write out non-minc warp transform files

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#270]
Calling @vfonov who implemented this

Related to #264 I believe.

If I build plain ANTs superbuild without ITK_BUILD_MINC_SUPPORT=OFF, antsRegistration works as expected.

If I set ITK_BUILD_MINC_SUPPORT=ON, antsRegistration will write out MINC-style transforms when ``--minc`` is specified on the command line.

Similarly, without ``--minc`` antsRegistration will successfully write out ``.mat`` files for affine-like transforms.

However, when antsRegistration tries to write the warp transform:
```
 Can't write transform file test1Warp.nii.gz
 Exception Object caught: 
 
 itk::ImageFileWriterException (0x4d54690)
 Location: "unknown" 
 File: /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.9/itkImageFileWriter.hxx
 Line: 151
 Description:  Could not create IO object for writing file test1Warp.nii.gz
   Tried to create one of the following:
     NiftiImageIO
     NrrdImageIO
     GiplImageIO
     HDF5ImageIO
     JPEGImageIO
     GDCMImageIO
     BMPImageIO
     LSMImageIO
     PNGImageIO
     TIFFImageIO
     VTKImageIO
     StimulateImageIO
     BioRadImageIO
     MetaImageIO
     MRCImageIO
     GE4ImageIO
     GE5ImageIO
     MINCImageIO
     MGHImageIO
   You probably failed to set a file suffix, or
     set the suffix to an unsupported type. Can't write transform file test1Warp.nii.gz
 Exception Object caught: 
```

I'm looking through PR #202 trying to find where the confusion might be generated, but I can't see it.

**Comment by vfonov** [comment]
it's because latest version of libminc has niftiio library inside of it , with ZLIB somehow disabled. So, when ITK is built with MINC library it recieves two versions of niftiio , one with support for .gz and another one without. I recently fixed it in libminc: https://github.com/BIC-MNI/libminc/commit/dcb93a5f50d2038fbe723874bb1407ef86363cdb , but it didn't make it into ITK yet.

**Comment by gdevenyi** [comment]
Ah yes, I believe I reported that bug at https://github.com/BIC-MNI/minc-toolkit-v2/issues/11

**Comment by vfonov** [comment]
http://review.source.kitware.com/#/c/20663/

**Comment by gdevenyi** [comment]
Weirdly, when I update the git commit id in the ANTs superbuild to that and build, I run into this error, even though it passed the build bot on ITK:
```
[ 90%] Building C object Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/libsrc2/hyper.c.o
/home/cic/devgab/projects/ANTs/build/ITKv4/Modules/ThirdParty/MINC/src/libminc/libsrc2/hyper.c:64:1: error: redefinition of ‘round’
 round(double x)
 ^
make[5]: *** [Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/libsrc2/hyper.c.o] Error 1
make[4]: *** [Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/all] Error 2
```

Any thoughts?

**Comment by vfonov** [comment]
did you remove previous build directory? I had similar issue building ITK and the solution was to wipe it's build directory and start from the fresh.

**Comment by gdevenyi** [comment]
this was a fresh clone/download/modify and a fresh build directory

**Comment by vfonov** [comment]
basically it means that cmake could not detect presense of round function,
for some reason.


On Fri, Jan 15, 2016 at 4:43 PM, Gabriel A. Devenyi <
notifications@github.com> wrote:

> Weirdly, when I update the git commit id in the ANTs superbuild to that
> and build, I run into this error, even though it passed the build bot on
> ITK:
>
> [ 90%] Building C object Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/libsrc2/hyper.c.o
> /home/cic/devgab/projects/ANTs/build/ITKv4/Modules/ThirdParty/MINC/src/libminc/libsrc2/hyper.c:64:1: error: redefinition of ‘round’
>  round(double x)
>  ^
> make[5]: *** [Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/libsrc2/hyper.c.o] Error 1
> make[4]: *** [Modules/ThirdParty/MINC/src/libminc/CMakeFiles/itkminc2.dir/all] Error 2
>
> Any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stnava/ANTs/issues/270#issuecomment-172102668>.
>



-- 
Best regards,

 Vladimir S. Fonov ~ vladimir <dot> fonov <at> gmail <dot> com

**Comment by gdevenyi** [comment]
Ah I see, so HAVE_ROUND isn't defined for some reason and so that code is exposed, trying to refine the version from math.h I would guess.

**Comment by gdevenyi** [comment]
CMakeCache reports:
```
//Have function round
HAVE_ROUND:INTERNAL=
```

Which I guess means:
https://github.com/InsightSoftwareConsortium/ITK/commit/9065cb589528d3e8f8c95c7cb79a1f1f572a5374#diff-d0cdea94ab23e3f861eee1a10196ff5aR106

Isn't working as intended?

**Comment by vfonov** [comment]
Works when I compile ITK stand-alone.

**Comment by gdevenyi** [comment]
Fixed via correction to CMake config change for libminc.

Needs merging at https://github.com/BIC-MNI/libminc/pull/67 and then merging into ITK

**Comment by gdevenyi** [comment]
Paging @vfonov can you push my libminc patch into ITK so I can update the ANTs superbuild hash?

**Comment by gdevenyi** [comment]
Waiting on merge of http://review.source.kitware.com/#/c/20741/1 to fix build

**Comment by gdevenyi** [comment]
Sorry to bother again @vfonov it looks like that update had some build bot problems and now needs to be rebased, can you look into it?

**Comment by vfonov** [comment]
ok, I tried again:  http://review.source.kitware.com/#/c/20827/

**Comment by gdevenyi** [comment]
Thanks @vfonov it looks like the build-bot is failing it on tests totally unrelated to your changes?

Maybe another ITK guy can take a quick look, @stnava ?
