### ISSUE TITLE
export warped NIfTI in original resolution (not template resolution)

### ISSUE THREAD

**Issue by TheChymera** [stnava/ANTs#273]
I am using a highly resolved anatomical template, but I am dealing with data sets (from different experiments) with varying resolutions. I would like to use the same template across all experiments, without having to resize copies of it to all resolutions, and without inflating my moving image resolution.

I think this could be easily done if the transformation software had an option to keep/apply the resolution of the moving image for the warped result. Does ANTs have such a feature?

**Comment by stnava** [comment]
yes - just use ANTs as is - it is designed that way ... e.g. via antsRegistrationSyNQuick.sh or antsRegistrationSyN.sh with the target ( low-res ) image as the fixed image.

**Comment by TheChymera** [comment]
I am using the following command to compute the registration:

```
antsRegistration 
--float 
--collapse-output-transforms 1 
--dimensionality 3 
--initial-moving-transform [ template.nii.gz, EPI_temporal_mean.nii.gz, 1 ] 
--initialize-transforms-per-stage 0
--interpolation Linear 
--output [ output_, output_warped_image.nii.gz ] 
--transform Rigid[ 0.1 ] 
--metric Mattes[ template.nii.gz, EPI_temporal_mean.nii.gz, 1, 32, Regular, 0.3 ] 
--convergence [ 10000x11110x11110, 1e-08, 20 ] 
--smoothing-sigmas 4.0x2.0x1.0vox 
--shrink-factors 3x2x1 
--use-estimate-learning-rate-once 1 
--use-histogram-matching 0 
--transform Affine[ 0.1 ] 
--metric Mattes[ template.nii.gz, EPI_temporal_mean.nii.gz, 1, 32, Regular, 0.3 ] 
--convergence [ 10000x11110x11110, 1e-08, 20 ] 
--smoothing-sigmas 4.0x2.0x1.0vox 
--shrink-factors 3x2x1 
--use-estimate-learning-rate-once 1 
--use-histogram-matching 0 
--transform SyN[ 0.2, 3.0, 0.0 ] 
--metric Mattes[ template.nii.gz, EPI_temporal_mean.nii.gz, 0.5, 32 ] 
--metric CC[ template.nii.gz, EPI_temporal_mean.nii.gz, 0.5, 4 ] 
--convergence [ 100x30x20, -0.01, 5 ] 
--smoothing-sigmas 1.0x0.5x0.0vox 
--shrink-factors 4x2x1 
--use-estimate-learning-rate-once 1 
--use-histogram-matching 1 
--verbose 1 
--winsorize-image-intensities [ 0.005, 0.995 ]  
--write-composite-transform 1
```

and the following command to perform the wrap:

```
antsApplyTransforms 
--default-value 0 
--input EPI.nii.gz 
--input-image-type 3 
--interpolation Linear 
--output EPI_warped.nii.gz 
--reference-image template.nii.gz 
--transform [output_Composite.h5,0]
```

And I am obtaining an `EPI_warped.nii.gz` file at the same resolution as my template.

I have looked over the individual options for the registration command, but as far as I can tell from the help text, none of them is specifying the output resolution. Might it be an indirect consequence of one of them?

**Comment by ntustison** [comment]
The output resolution is defined by the fixed image.

**Comment by gdevenyi** [comment]
Create a resampled template with a lower resolution and use it as the
reference for antsapplytransform

**Comment by ntustison** [comment]
@gdevenyi - you could do that but you would also have to resample any displacement field transforms as they are also defined by fixed image domain.

**Comment by gdevenyi** [comment]
Good to know.

@thec

**Comment by gdevenyi** [comment]
@thechymera if you're willing to dip into the minc toolchain, ants can save minc style transforms and mincresample has had this feature for a long time

**Comment by stnava** [comment]
just to be clear ( using ANTsR shorthand for the same things in ANTs ), here are several ways of getting low/high res output ... the difference between the two registration calls is the scale at which the transformation is computed/store.

```
     fi <- antsImageRead(getANTsRData("r16") ,2)
     mi <- antsImageRead(getANTsRData("r64") ,2)
     mytx <- antsRegistration(fixed=fi, moving=mi, typeofTransform = c('SyN') )
     fiLow<-resampleImage(fi,c(60,60),1,0)
     mywarpedimageLow <- antsApplyTransforms( fixed=fiLow, moving=mi,
       transformlist=mytx$fwdtransforms )
     mywarpedimage <- antsApplyTransforms( fixed=fi, moving=mi,
         transformlist=mytx$fwdtransforms )
     mytxLow <- antsRegistration(fixed=fiLow, moving=mi, typeofTransform = c('SyN') )
     mywarpedimageLow2 <- antsApplyTransforms( fixed=fiLow, moving=mi,
       transformlist=mytxLow$fwdtransforms )
     mywarpedimage2 <- antsApplyTransforms( fixed=fi, moving=mi,
       transformlist=mytxLow$fwdtransforms )
     plot( mywarpedimage  )     
     plot( mywarpedimage  )     
     plot( mywarpedimageLow  )     
     plot( mywarpedimageLow2  )     
```

**Comment by TheChymera** [comment]
@stnava I guess this is the answer to my initial question, but I see two issues:

* if I apply the transform using a down-sampled fixed image, won't some of the transform parameters no longer apply (as I believe @ntustison hinted)?
* if I compute the transform to a down-sampled image, won't my transform accuracy suffer?

@gdevenyi I am still coming to terms with ANTs proper, sad to say, I think my powers of comprehension would atm not suffice to meddle with the toolchain :-/

**Comment by stnava** [comment]
re: 1)  no

re: 2) yes
