### ISSUE TITLE
Using initial guess in antsRegistrationSyn.sh

### ISSUE THREAD

**Issue by pog87** [stnava/ANTs#276]
Hello. I am currently trying image registration using antsRegistrationSyn.sh. I made my first try with affine registration using

```bash
bash $ANTSPATH/antsRegistrationSyN.sh -d 3 -f reference.nii.gz -m input.nii.gz -t a -o Output
```
and obtained the files "OutputWarped.nii.gz" and "Output0GenericAffine.mat"

I now would like to register another image (say "input2.nii.gz") to "reference.nii.gz" using "Output0GenericAffine.mat" as initial guess for affine matrix.
How can I do that?

Thanks a lot.

**Comment by pog87** [comment]
I figured out by myself but I am not sure this is correct. I modified as follow "$ANTSPATH/antsRegistrationSyN.sh" and renamed in "$ANTSPATH/antsRegistrationSyN_init.sh"

from line 256
```bash
while getopts "d:f:h:j:m:n:o:p:r:s:t:i:" OPT
  do
  case $OPT in
      h) #help
   Help
   exit 0
   ;;
      d)  # dimensions
   DIM=$OPTARG
   ;;
      f)  # fixed image
   FIXEDIMAGES[${#FIXEDIMAGES[@]}]=$OPTARG
   ;;
      j)  # histogram matching
   USEHISTOGRAMMATCHING=$OPTARG
   ;;
      m)  # moving image
   MOVINGIMAGES[${#MOVINGIMAGES[@]}]=$OPTARG
   ;;
      n)  # number of threads
   NUMBEROFTHREADS=$OPTARG
   ;;
      o) #output name prefix
   OUTPUTNAME=$OPTARG
   ;;
      p)  # precision type
   PRECISIONTYPE=$OPTARG
   ;;
      r)  # cc radius
   CCRADIUS=$OPTARG
   ;;
      s)  # spline distance
   SPLINEDISTANCE=$OPTARG
   ;;
      t)  # transform type
   TRANSFORMTYPE=$OPTARG
   ;;
      i) # initial guessing .mat files
   INIT=$OPTARG
   ;;
     \?) # getopts issues an error message
   echo "$USAGE" >&2
   exit 1
   ;;
  esac
done
```

and in line 410
```bash
RIGIDSTAGE="--initial-moving-transform $INIT [${FIXEDIMAGES[0]},${MOVINGIMAGES[0]},1] \
            --transform Rigid[0.1] \
            --metric MI[${FIXEDIMAGES[0]},${MOVINGIMAGES[0]},1,32,Regular,0.25] \
            --convergence $RIGIDCONVERGENCE \
            --shrink-factors $RIGIDSHRINKFACTORS \
            --smoothing-sigmas $RIGIDSMOOTHINGSIGMAS"
```

**Comment by stnava** [comment]
yes - that is good progress. something like that is correct but you will
have to verify your code yourself.


brian

**Comment by pog87** [comment]
the code seems fine, 

maybe putting in line 410
```bash
RIGIDSTAGE="--initial-moving-transform $INIT \
            --transform Rigid[0.1] \
            --metric MI[${FIXEDIMAGES[0]},${MOVINGIMAGES[0]},1,32,Regular,0.25] \
            --convergence $RIGIDCONVERGENCE \
            --shrink-factors $RIGIDSHRINKFACTORS \
            --smoothing-sigmas $RIGIDSMOOTHINGSIGMAS"
```
is better for my purpose.

I am afraid that with this modify the argument "-i" becomes mandatory, so I kept "$ANTSPATH/antsRegistrationSyN.sh" and "$ANTSPATH/antsRegistrationSyN_init.sh" as separate scripts.

Thank you for checking

**Comment by stnava** [comment]
yes - i think that is a good solution for your case.


brian
