### ISSUE TITLE
antsBrainExtraction Failure

### ISSUE THREAD

**Issue by chriscrosscutler** [stnava/ANTs#278]
I'm trying to run antsBrainExtraction.sh on a subject that has been preprocessed up to this point and keep experiencing the same error. Running the script in test mode said-

 `The registration component of the extraction step didn't complete properly.
The transform file /fslhome/ccutle25/compute/1304_082907/BrainExtractionPrior0GenericAffine.mat does not exist.`

Here is my code:
`sh /fslhome/ccutle25/bin/antsbin/bin/antsBrainExtraction.sh -d 3 -a /fslhome/ccutle25/compute/1304_082907/n4_resampled.nii.gz -e /fslhome/ccutle25/templates/OASIS/OASIS-30_Atropos_template/T_template0.nii.gz -m /fslhome/ccutle25/templates/OASIS/OASIS-30_Atropos_template/T_template0_BrainCerebellumProbabilityMask.nii.gz -o /fslhome/ccutle25/compute/1304_082907/`

I've checked for trailing spaces, correct file paths and have run the script in the correct subject folder.

Any idea where the BrainExtractionPrior0GenericAffine.mat file could be? Or why it is being deleted prematurely?

The other steps up to registration finished successfully except for this part:

`BEGIN >>>>>>>>>>>>>>>>>>>>
/fslhome/ccutle25/bin/antsbin/bin//antsAffineInitializer 3 /fslhome/ccutle25/compute/1304_082907/BrainExtractionInitialAffineFixed.nii.gz /fslhome/ccutle25/compute/1304_082907/BrainExtractionInitialAffineMoving.nii.gz /fslhome/ccutle25/compute/1304_082907/BrainExtractionInitialAffine.mat 15 0.1 0 10
 bad det -1 v 1 u -1
 bad det -1 v 1 u -1 new 1
END   <<<<<<<<<<<<<<<<<<<<`

Is this playing a part in the error too? 

Thanks for your help!

**Comment by ntustison** [comment]
Hi Chris,

I just started working on a new system a week ago.  While running the ``antsCorticalThickness.sh`` pipeline I ran into the exact same issue this morning where it seg faults at the ``antsAffineInitializer`` call and I haven't been able to figure out the issue yet.  I can download the same files to my mac pro and it works.  I can also download a simple 2-D example to the new system and it works.  As soon as I figure it out, I'll post what I find.

Nick

**Comment by chriscrosscutler** [comment]
Nick,

Thanks! I'm glad to hear that this wasn't just an issue on my account. 

Chris

**Comment by stnava** [comment]
does antsAI help?

**Comment by ntustison** [comment]
I've been meaning to replace ``antsAffineInitializer`` with ``antsAI`` but just haven't done it yet.  Perhaps this will be the motivation.  Still working on it, though.

**Comment by chriscrosscutler** [comment]
Is antsAI an executable that I could run instead of antsAffineInitializer? Where can I find the arguments to pass into it?

**Comment by ntustison** [comment]
[It](https://github.com/stnava/ANTs/blob/master/Examples/antsAI.cxx) is.  Brian wrote ``antsAffineInitializer`` originally and ``antsAI`` was meant to replace it.  It uses the ANTs command line interface and has some other features that Brian wrote and put in ``ImageMath``.    However, given that I wrote it and that Brian's program works, I've been reluctant to replace it in ``antsBrainExtraction.sh``.  But I guess we should see if that'll fix the problem.  I'm trying to get it in tonight but I'll update here when I do.

**Comment by chriscrosscutler** [comment]
Sounds good, I’ll try replacing it in antsBrainExtraction too, and see if that fixes the problem.

Thanks,

Chris

**Comment by ntustison** [comment]
Hey @stnava , 

I replaced ``antsAffineInitializer`` with ``antsAI`` and it's segfaulting in the same place (the call of the multi-start optimizer).  I'll have to do some more investigating. 

Nick

**Comment by ntustison** [comment]
And to make this bug even more frustrating, the exact ``antsAI`` call using the exact same data works on my machine just like ``antsAffineInitializer``.

**Comment by ntustison** [comment]
Okay, I figured it out.  The default gcc on the new system is 4.8.1 but my mac is using something like 4.2.1.  After loading gcc 4.2.1 on the new system and re-compiling, the ``antsAI`` call works now as does the corresponding ``antsAffineInitializer``call.  I'm leaving ``antsAI`` in ``antsBrainExtraction.sh`` for now but we'll have to keep a close eye on it to make sure that it's working properly.

**Comment by chriscrosscutler** [comment]
I’ll have to look at what version gcc is running on my account. Thanks for your help!! I’ve been stuck on this issue for days.

Chris
