### ISSUE TITLE
antsMultivariateTemplateConstruction.sh  parameters

### ISSUE THREAD

**Issue by Metasoliton** [stnava/ANTs#279]
Dear Nick & Brian,

I am using antsMultivariateTemplateConstruction.sh to create a custom brain template (for usage with antsRegistrationSyn.sh in a study involving healthy and demented subjects).

You are suggesting to reference  http://www.ncbi.nlm.nih.gov/pubmed/20851191 which describes buildtemplateparallel.sh so is it safe to assume that antsMultivariateTemplateConstruction.sh does the same thing?

Furthermore, the help sections of both scripts are not specifying the default and optional values of 
-s:  Type of similarity metric used for registration.  
&
-t:  Type of transformation model used for registration.

Would you please clarify which ones they are?

Many thanks in advance,
Stav

**Comment by ntustison** [comment]
``antsMultivariateTemplateConstruction.sh`` does everything ``btp`` does but with the added capabilities of multivariate templates.  Default is ``-s CC -t GR``.

**Comment by Metasoliton** [comment]
Thank you for the swift response. The paper suggests MI to perform better than CC for whole-head images but which similarity metric would you recommend for skull-stripped images?

**Comment by ntustison** [comment]
Where do you see MI outperforming CC?

**Comment by ntustison** [comment]
Regardless, CC is our go-to metric for producing quality templates (skull-stripped or not).

**Comment by cookpa** [comment]
The paper says MI is better for affine registration. It's also much faster. We recommend MI for rigid + affine, and then CC for deformable registration.

The template scripts will use MI for the affine part, the user chooses the deformable metric with -s

**Comment by Metasoliton** [comment]
That´s clear now. 
Thank you very much.
