### ISSUE TITLE
Feature Request? Tool to generate deformation field from Affine transforms?

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#280]
For various reasons I'd like to be able to generate an "equivalent" deformation field from a .mat file (i.e. the warp field has the same value at all points, calculated from the affine parameters)

It looks like I can go the other way with ``ANTSUseDeformationFieldToGetAffineTransform``
``CreateDisplacementField`` looks related by constructs the field from other 3D volumes

Does a tool like this exist?

If so, I'll leave this here as a feature request instead.

**Comment by ntustison** [comment]
antsApplyTransforms

**Comment by gdevenyi** [comment]
Thanks for the help...

For future users, this is what @ntustison was referring to:

  -o, --output warpedOutputFileName
                  [warpedOutputFileName or **compositeDisplacementField,\<printOutCompositeWarpFile=0\>]**
                  Linear[genericAffineTransformFile,<calculateInverse=0>]
          One can either output the warped image or, **if the boolean is set, one can print 
          out the displacement field based on the composite transform and the reference 
          image.**
