### ISSUE TITLE
ANTs Compile Error OSX

### ISSUE THREAD

**Issue by Trevh5** [stnava/ANTs#281]
I have been trying to install the latest ANTs software on two different mac computers and I am running into a strange error. The same thing shows up on both computers even though I follow the recommended installation steps. Here is the error:

/usr/local/ANTs/Examples/iMath.cxx:531:16: error: no matching function for call to
      'iMathHistogramEqualization'
      output = iMathHistogramEqualization<ImageType>(input, alpha, beta );
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ANTs/Examples/iMath.cxx:953:19: note: in instantiation of function template
      specialization 'ants::iMathHelperAll<2>' requested here
  int returnval = iMathHelperAll<2>(argc,argv);
                  ^
/usr/local/ANTs/Examples/iMathFunctions.hxx:549:1: note: candidate function template
      not viable: requires 4 arguments, but 3 were provided
iMathHistogramEqualization( typename ImageType::Pointer image, double alpha, d...
^
[ 46%] Linking CXX static library /usr/local/antsbin/lib/libl_KellyKapowski.a
[ 46%] Built target l_KellyKapowski
Scanning dependencies of target l_WarpImageMultiTransform
[ 46%] Building CXX object Examples/CMakeFiles/l_WarpImageMultiTransform.dir/WarpImageMultiTransform.cxx.o
/usr/local/ANTs/Examples/iMath.cxx:531:16: error: no matching function for call to
      'iMathHistogramEqualization'
      output = iMathHistogramEqualization<ImageType>(input, alpha, beta );
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ANTs/Examples/iMath.cxx:969:19: note: in instantiation of function template
      specialization 'ants::iMathHelperAll<3>' requested here
  int returnval = iMathHelperAll<3>(argc,argv);
                  ^
/usr/local/ANTs/Examples/iMathFunctions.hxx:549:1: note: candidate function template
      not viable: requires 4 arguments, but 3 were provided
iMathHistogramEqualization( typename ImageType::Pointer image, double alpha, d...
^
/usr/local/ANTs/Examples/iMath.cxx:531:16: error: no matching function for call to
      'iMathHistogramEqualization'
      output = iMathHistogramEqualization<ImageType>(input, alpha, beta );
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ANTs/Examples/iMath.cxx:989:19: note: in instantiation of function template
      specialization 'ants::iMathHelperAll<4>' requested here
  int returnval = iMathHelperAll<4>(argc,argv);
                  ^
/usr/local/ANTs/Examples/iMathFunctions.hxx:549:1: note: candidate function template
      not viable: requires 4 arguments, but 3 were provided
iMathHistogramEqualization( typename ImageType::Pointer image, double alpha, d...
^
3 errors generated.
make[5]: *** [Examples/CMakeFiles/l_iMath.dir/iMath.cxx.o] Error 1
make[4]: *** [Examples/CMakeFiles/l_iMath.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 47%] Linking CXX static library /usr/local/antsbin/lib/libl_antsSliceRegularizedRegistration.a
[ 47%] Built target l_antsSliceRegularizedRegistration
[ 47%] Linking CXX static library /usr/local/antsbin/lib/libl_TimeSCCAN.a
[ 47%] Built target l_TimeSCCAN
[ 48%] Linking CXX static library /usr/local/antsbin/lib/libl_WarpImageMultiTransform.a
[ 48%] Built target l_WarpImageMultiTransform
make[3]: *** [all] Error 2
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
make: *** [all] Error 2

Let me know if you have any thoughts. Maybe i'm missing something?

**Comment by stnava** [comment]
this is my fault - it should be fixed now.   my apologies.

**Comment by Trevh5** [comment]
Thanks! That worked great.
