### ISSUE TITLE
Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by Trevh5** [stnava/ANTs#282]
I know this issue has come up a few times but I wanted to report that I am having the same problem even after the ITK fix. Specifically, it pops up while running antsJointLabelFusion.sh. This is the error:

Running antsJointFusion for 3-dimensional images.

Exception caught: 
itk::ExceptionObject (0x7f93548bea08)
Location: "unknown" 
File: /usr/local/antsbin/ITKv4-install/include/ITK-4.9/itkImageToImageFilter.hxx
Line: 250
Description: itk::ERROR: WeightedVotingFusionImageFilter(0x7f9354874820): Inputs do not occupy the same physical space! 
InputImage Origin: [8.7500000e+01, 7.9959869e+01, -6.1974251e+01], InputImage_41 Origin: [8.7500000e+01, 7.9959869e+01, -6.1974247e+01]
	Tolerance: 1.0000000e-06

This error is not unique to just one system. I ran the same images on my mac desktop (Mac OS X Lion 10.7.5) and on a Linux distribution (Red Hat Enterprise Linux Server release 6.6 (Santiago)) and I got the same error. Hopefully this helps you find a permanent solution, but is there a temporary fix that I can implement to get the code to run?

**Comment by ntustison** [comment]
Try the updated ``antsJointLabelFusion.sh`` script and see if that solves your problem.

**Comment by Trevh5** [comment]
same error comes up

**Comment by ntustison** [comment]
Can you upload one of the .sh files that's created to register the images to the target?

**Comment by Trevh5** [comment]
Is this what you are looking for?

#!/bin/sh
/fslhome/huff6/bin/ANTSTEST/antsbin/bin//antsRegistrationSyNQuick.sh                           -d 3                           -p d                           -j 1                           -t s                           -f /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/antsextract_BrainExtractionBrain.nii.gz                           -m /fslhome/huff6/Templates/OASIS-TRT-20_volumes/OASIS-TRT-20-1/t1weighted_brain.nii.gz                           -o /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_ > /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_log.txt
/fslhome/huff6/bin/ANTSTEST/antsbin/bin//antsApplyTransforms                           -d 3                           --float 1                           -i /fslhome/huff6/Templates/OASIS-TRT-20_volumes/OASIS-TRT-20-1/OASIS-TRT-20-1_DKT31_CMA_labels.nii.gz                           -r /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/antsextract_BrainExtractionBrain.nii.gz                           -o /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_WarpedLabels.nii.gz                           -n NearestNeighbor                           -t /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_1Warp.nii.gz                           -t /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_0GenericAffine.mat >> /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_log.txt
/fslhome/huff6/bin/ANTSTEST/antsbin/bin//CopyImageHeaderInformation                          /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/antsextract_BrainExtractionBrain.nii.gz                          /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_Warped.nii.gz                          /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_Warped.nii.gz 1 1 1
/fslhome/huff6/bin/ANTSTEST/antsbin/bin//CopyImageHeaderInformation                           /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/antsextract_BrainExtractionBrain.nii.gz                           /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_WarpedLabels.nii.gz                           /fslhome/huff6/compute/dataFromNate/subjects/s1580_Day2/labels/t1weighted_brain_0_WarpedLabels.nii.gz 1 1 1

**Comment by ntustison** [comment]
Yes.  I want to verify that the headers are actually different.  Please run ``PrintHeader`` on the target image and on the image which is throwing the ITK exception.

**Comment by Trevh5** [comment]
I believe this is what you are looking for. Correct me if I am wrong.

-bash-4.1$ PrintHeader antsextract_BrainExtractionBrain.nii.gz 
 Spacing [1, 1.0005, 1.00098]
 Origin [87.5, 80.5639, -96.7914]
 Direction 
-1 0 0
0 -1 0
0 0 1

 Size : 176 204  200

  Image Dimensions   : [176, 204, 200]
  Bounding Box       : {[87.5 80.5639 -96.7914], [263.5 284.665 103.404]}
  Voxel Spacing      : [1, 1.0005, 1.00098]
  Intensity Range    : [0, 920.326]
  Mean Intensity     : 96.8402
  Direction Cos Mtx. : 
-1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 3
    dim[1] = 176
    dim[2] = 204
    dim[3] = 200
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    pixdim[0] = 1
    pixdim[1] = 1
    pixdim[2] = 1.0005
    pixdim[3] = 1.00098
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 2
    qoffset_x = -87.5
    qoffset_y = -80.5639
    qoffset_z = -96.7914
    quatern_b = 0
    quatern_c = 0
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 1
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 1 0 -0 -87.5
    srow_y = 0 1.0005 -0 -80.5639
    srow_z = 0 0 1.00098 -96.7914
    toffset = 0
    vox_offset = 352

-bash-4.1$ PrintHeader labels/t1weighted_brain_0_Warped.nii.gz 
 Spacing [1, 1.0005, 1.00098]
 Origin [87.5, 80.5639, -96.7914]
 Direction 
-1 0 0
0 -1 0
0 0 1

 Size : 176 204  200

  Image Dimensions   : [176, 204, 200]
  Bounding Box       : {[87.5 80.5639 -96.7914], [263.5 284.665 103.404]}
  Voxel Spacing      : [1, 1.0005, 1.00098]
  Intensity Range    : [0, 1977.44]
  Mean Intensity     : 237.566
  Direction Cos Mtx. : 
-1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    bitpix = 64
    cal_max = 0
    cal_min = 0
    datatype = 64
    dim[0] = 3
    dim[1] = 176
    dim[2] = 204
    dim[3] = 200
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    pixdim[0] = 1
    pixdim[1] = 1
    pixdim[2] = 1.0005
    pixdim[3] = 1.00098
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 2
    qoffset_x = -87.5
    qoffset_y = -80.5639
    qoffset_z = -96.7914
    quatern_b = 0
    quatern_c = 0
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 1
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 1 0 -0 -87.5
    srow_y = 0 1.0005 -0 -80.5639
    srow_z = 0 0 1.00098 -96.7914
    toffset = 0
    vox_offset = 352

**Comment by ntustison** [comment]
Yep, thanks.  Unfortunately, I don't see anything wrong.  The headers are being copied properly so they should be identical.  I'd have to look at your data to diagnose the problem further.  

If you're looking for a kludge, you can change the origin of the target image to [0,0,0] and try re-running.

**Comment by Trevh5** [comment]
Ok I tried manually setting the origin of the target image and it didn't help. This is the new output:

Running antsJointFusion for 3-dimensional images.

Exception caught: 
itk::ExceptionObject (0x20b95290)
Location: "unknown" 
File: /fslhome/huff6/bin/ANTSTEST/antsbin/ITKv4-install/include/ITK-4.9/itkImageToImageFilter.hxx
Line: 248
Description: itk::ERROR: WeightedVotingFusionImageFilter(0x1e44f50): Inputs do not occupy the same physical space! 
InputImage Origin: [0.0000000e+00, 0.0000000e+00, 0.0000000e+00], InputImage_21 Origin: [8.7500000e+01, 7.3887894e+01, -9.5513031e+01]
	Tolerance: 1.0000000e-06

**Comment by ntustison** [comment]
Are you deleting _all_ the files between runs?  The origin for InputImage_21 looks like it's from an unregistered image.  If not, you need to delete the images.  If you are then there's nothing else I can do without seeing the data myself.

**Comment by Trevh5** [comment]
I was deleting all of the files between runs but I realized that I had only changed the origin for the target image and not the mask as well. Once I changed it for both, it ran without problem. Probably not the best solution, but this will work for now. Thanks for your help.

**Comment by Trevh5** [comment]
Also, if you want to see the data, I can send you the images that I was having trouble with to see if you can recreate the problem. Let me know if you are interested.

**Comment by ntustison** [comment]
Thanks for the offer but since this error tends to be system-specific and you're able to kludge a solution, I think I'll pass as I probably wouldn't be able to recreate the problem anyway.  

Despite the fact that this issue continues to persist in various forms, I'm going to close this one since I don't plan on doing anything more for this particular instance.
