### ISSUE TITLE
Inconsistent Masking Behavior

### ISSUE THREAD

**Issue by hjmjohnson** [stnava/ANTs#288]
Nick @ntustison,

We are looking at how antsJointFusion works, and we noticed that

There is a class variable called m_MaskLabel that can only have the value
NumericTraits<LabelType>::OneValue()

Furthermore, masking occurs only if the value is exactly equal to 1.  If an image has other values, it can not be used.

In the rest of ITK, masking operations have a more liberal meaning that if the image has a non-zero value, it is in the mask.

==========
In antsAtroposSegmentationImageFilter, You CAN set m_MaskLabel,

In itkN3MRIBiasFieldCorrectionImageFilter.hxx you CANNOT set m_MaskLabel.
In itkWeightedVotingFusionImageFilter.hxx you CANNOT set m_MaskLabel.

===========
NOTE: For antsRegistration, any non-zero value would be used as inside the mask.

===========
So…. Would it be OK change the behavior of itkWeightedVotingFusionImageFilter.hxx so that any non-zero voxel location is considered inside the mask?

The advantage is that you don’t need to write out a binary image from a label map for use as a mask.

This would save us a lot of disk space, and would bring this into consistent format with many other features in ITK (I.e. The registration process).

Thanks,
Hans

**Comment by ntustison** [comment]
I thought I got the use of a mask label from ITK.  For example, N4 uses a mask label

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.h#L195-L207

Also, the denoising filter uses a mask label although you currently cannot set it just like the others.  I'm all for consistency.  Is there a wiki page where this is discussed for ITK?

**Comment by hjmjohnson** [comment]
Nick,

Generically in ITK proper, masks are usually defined as “SpatialObjects” for generality so that any valid SpatialObject can be used.  This is the case for all of ITK’s registration (namely ImageToImageMetric).

Importantly, the IsInside function for itkImageMaskSpatialObject.hxx only checks for Non-Zero as the test case.

 76   typedef typename InterpolatorType::OutputType InterpolatorOutputType;

 77   const bool insideMask = (

 78     Math::NotExactlyEquals( DefaultConvertPixelTraits<InterpolatorOutputType>::GetScalarValue(this->m_Interpol    ator->EvaluateAtContinuousIndex(index)),

 79     NumericTraits<PixelType>::ZeroValue() ) );

 80   return insideMask;



Hans

**Comment by ntustison** [comment]
I see.  That makes sense.  Then it's fine with me if you change it.  However, if you do, can you go through and change it for all the filters mentioned above in ANTs proper so that usage is consistent?  I can change the N4 filter since it would be a different submit.

**Comment by hjmjohnson** [comment]
Nick,

I’d be happy to.  

Hans

**Comment by ntustison** [comment]
Thanks Hans.

**Comment by ntustison** [comment]
I think this has been resolved with the recent ANTs and ITK commits.
