### ISSUE TITLE
buildtemplateparallel and antsMultivariateTemplateConstruction2 issues

### ISSUE THREAD

**Issue by chrisadamsonmcri** [stnava/ANTs#291]
Dear ANTS experts

There are two issues we'd like to request help with. We're constructing rigid body, affine, and nonlinear templates with T1 and T2 scans.

First, in constructing affine and linear templates using buildtemplateparallel.sh, we've noted that the output for each of these appears switched around. i.e., the rigid body template appears as if scaling has been performed, and has clean edges, whereas the affine template shows transparent edges of multiple brains of different sizes overlaid, as one would expect from a rigid body transformation. Please see attached images for example. We've checked the scripts used several times, and have been unable to produce any different results using, e.g., increased iterations.

For affine (see affine_t2_btp.png attached):

buildtemplateparallel.sh -d 3 -o affine -c 1 -t RA -s MI -r 1 $images

For rigid (see rigid_t2_btp.png attached):

AverageImages 3 init_template.nii.gz 1 $images
buildtemplateparallel.sh -d 3 -o rigid -c 1 -t RI -s MI -m 0 -z init_template.nii.gz  $images

The second issue occurs when using antsMultivariateTemplateConstruction2.sh (or antsMultivariateTemplateConstruction.sh) with T1 and T2 images as below. The template for one modality looks good, but the template for the other modality doesn't appear as though registration has occurred (see attached).

antsMultivariateTemplateConstruction.sh -d 3 -o SyN -c 1 -m 30x50x20 -t GR -s CC -y 0 -z /t2/flirt/affine_dof12/iteration_4/affinetemplate.nii.gz -k 2 t1t2.txt
(for this the T2 template appears good, and the T1 appears unregistered)

or

antsMultivariateTemplateConstruction2.sh -d 3 -o SyN -c 1 -b 1 -t SyN -m CC -y 0 -k 2 -z /t1/flirt/affine_dof12/iteration_4/affinetemplate.nii.gz -z /t2/flirt/affine_dof12/iteration_4/affinetemplate.nii.gz t1t2.txt
(for this, the T1 template appears good, and the T2 appears unregistered)

the input text file reads,

/t1/031.nii.gz,/t2/031.nii.gz
/t1/032.nii.gz,/t2/032.nii.gz

and so on.

The input images have been bias corrected using N4ITK, and brain extracted using BET, though there's some skull remaining over parietal cortex on the T1s. We're wondering the different modalities need to first be resampled to the same voxel size, any other preprocessing required, any changes to the usage above, or otherwise.

Any suggestions on these issues would be much appreciated.

Thanks,
Chris Adamson

![affine_t2_btp](https://cloud.githubusercontent.com/assets/9276757/13767078/5351a8ac-eabb-11e5-9751-8112e23881e5.png)
![rigid_t2_btp](https://cloud.githubusercontent.com/assets/9276757/13767081/5357e960-eabb-11e5-80c1-7138bc31ec31.png)
![t1_template_multi](https://cloud.githubusercontent.com/assets/9276757/13767082/5358d398-eabb-11e5-9d5e-7efce3070c77.png)
![t1_template_multi-2](https://cloud.githubusercontent.com/assets/9276757/13767080/53573e3e-eabb-11e5-94a7-8911ffca657b.png)
![t2_template_multi](https://cloud.githubusercontent.com/assets/9276757/13767079/535462a4-eabb-11e5-82d9-a4e570b0223a.png)
![t2_template_multi-2](https://cloud.githubusercontent.com/assets/9276757/13767083/5358fee0-eabb-11e5-89e4-13b84384cbc1.png)

**Comment by ntustison** [comment]
Make sure that your repository is updated.  There was an [issue](https://github.com/stnava/ANTs/blob/master/Scripts/antsIntroduction.sh) concerning rigid-only registration in btp.sh which was fixed within the last week.  Also, we encourage use of the antsMVT.sh and antsMVT2.sh scripts over btp.sh use.  

Regarding the use of the latter---all the images for a single subject need to be mutually aligned prior to using the antsMVT*.sh scripts.

Also, you might want to look at the antsBrainExtraction.sh script which we prefer over BET.

**Comment by chrisadamsonmcri** [comment]
Thanks Nick.
