### ISSUE TITLE
Problem using antsAtroposN4.sh

### ISSUE THREAD

**Issue by eal09** [stnava/ANTs#296]
I have been attempting to perform segmentation using antsAtroposN4 on an average template created using antsBTP.sh. My goal was to use priors manually drawn on the template to help the segmentation, and ideally to also use distance priors. However, I'm finding that I get virtually identical (Pearson r > .98 for posterior prob images) results regardless of whether I call antsAtroposN4 with priors specified or without. I wonder if I am making an error in the commands?

without priors:
${ANTSPATH}/antsAtroposN4.sh -d 3 -a fast_btp_template.nii -c 5 -o temp_seg_

with priors and distance priors:
${ANTSPATH}/antsAtroposN4.sh -d 3 -a fast_btp_template.nii -c 5 -b Aristotle[1] -l 3[1,.5] -l 5[3,.5] -y 1 -y 2 -y 3 -y 4 -y 5 -p [labels4Atropos%01d.nii] -o temp_seg_

Also, I've noticed that in the command line output, as the function runs, the call to Atropos is as follows:

/cygdrive/c/ANTs/bin//Atropos -d 3 -x -c [5,0.0] -a temp_seg_Segmentation0N4.nii.gz -l 3[1,.5] -l 5[3,.5] --verbose 1 -i kmeans[5] -k Gaussian -m [0.1,1x1x1] -o [temp_seg_Segmentation.nii.gz,temp_seg_SegmentationPosteriors%01d.nii.gz] -r 1 -p **Socrates[0]**

and this appears to be the same for either call.

Any help is much appreciated, 
Thanks,
Elliot

**Comment by ntustison** [comment]
``-p Socrates[0]`` is always used on the first N4 <---> Atropos iteration (see [here](https://github.com/stnava/ANTs/blob/master/Scripts/antsAtroposN4.sh#L500-L504)).  However, for subsequent iterations, ``Aristotle`` should kick in.  Can you verify that this actually occurs?

**Comment by eal09** [comment]
I see, yes, it looks like it is working in later iterations: 

BEGIN >>>>>>>>>>>>>>>>>>>>
/cygdrive/c/ANTs/bin//Atropos -d 3 -x -c [5,0.0] -a temp_seg_Segmentation0N4.nii.gz -l 3[1,.5] -l 5[3,.5] --verbose 1 -i PriorProbabilityImages[5,temp_seg_SegmentationPosteriors%01d.nii.gz,0.0] -k Gaussian -m [0.1,1x1x1] -o [temp_seg_Segmentation.nii.gz,temp_seg_SegmentationPosteriors%01d.nii.gz] -r 1 -p Aristotle[1]
END   <<<<<<<<<<<<<<<<<<<<

I did notice a possible error which occurs in the next outputs after this:

/cygdrive/c/ANTs/bin//antsAtroposN4.sh: line 556: bc: command not found
BEGIN >>>>>>>>>>>>>>>>>>>>
/cygdrive/c/ANTs/bin//ImageMath 3 temp_seg_SegmentationWeightMask.nii.gz PureTissueN4WeightMask temp_seg_SegmentationPosteriors1.nii.gz temp_seg_SegmentationPosteriors2.nii.gz temp_seg_SegmentationPosteriors3.nii.gz temp_seg_SegmentationPosteriors4.nii.gz temp_seg_SegmentationPosteriors5.nii.gz
 cannot find operation : PureTissueN4WeightMask
END   <<<<<<<<<<<<<<<<<<<<

BEGIN >>>>>>>>>>>>>>>>>>>>
/cygdrive/c/ANTs/bin//ImageMath 3 temp_seg_Segmentation0N4.nii.gz TruncateImageIntensity fast_btp_template.nii 0.025 0.995 256 1
 bad file name 1
Lower quantile: 0.222004
Upper quantile: 4.14152
END   <<<<<<<<<<<<<<<<<<<<

What is "PureTissueN4WeightMask" specifying here?

Thanks,
Elliot

**Comment by ntustison** [comment]
How recent is your repository?  That has been there for quite some time in ``ImageMath`` (see [here](https://github.com/stnava/ANTs/blob/master/Examples/ImageMath.cxx#L14529-L14533)).  Also cf Equation (1) in this [2014 paper](http://www.ncbi.nlm.nih.gov/pubmed/24879923).

**Comment by cookpa** [comment]
I think you need to include

```
  -w <prior weight>
```

in your call to antsAtroposN4.sh see any difference. By default, the prior weight is 0. This means the priors are used to initialize the classes, but they don't have any further influence.

**Comment by eal09** [comment]
Thanks, I will try this soon and make sure my ImageMath function is up to date.

**Comment by eal09** [comment]
I wanted to update that I've gotten this working. I think that the main issue was not specifying the -x mask argument, which I didn't realize was required. I created a binary mask eroded slightly from the original image size, and it worked fine.

2 other small questions:

I've noticed that AtroposN4 seems to order the output "SegmentationPosterior" images in order of least to greatest mean intensity (whereas this does not seem to be the case for Atropos). Is the "-l " label propagation argument applying to the order of the segmentation prior images input, or in terms of the output order?

My other question is whether there is any easy way to alter the script to run using Aristotle[1] for initialization rather than Socrates[0]? 

Thanks,
Elliot

**Comment by ntustison** [comment]
> I've noticed that AtroposN4 seems to order the output "SegmentationPosterior" images in order of least to greatest mean intensity (whereas this does not seem to be the case for Atropos). Is the "-l " label propagation argument applying to the order of the segmentation prior images input, or in terms of the output order?

For univariate segmentation, ``Atropos`` orders the labels the same way if the priors aren't specified.   Label propagation is done on a label-by-label basis (cf the help menu, particularly the ``-l`` option).

> My other question is whether there is any easy way to alter the script to run using Aristotle[1] for initialization rather than Socrates[0]?

Just do a search-and-replace in the ``antsAtroposN4.sh`` script.
