### ISSUE TITLE
Affine option in BTP.sh appears to have used rigid-only transformation

### ISSUE THREAD

**Issue by BonnieAlexander** [stnava/ANTs#297]
Hi, 

Following from the fixed bug re rigid-only transformations mentioned here https://github.com/stnava/ANTs/issues/291, we've updated the repository and BTP.sh does now produce rigid templates for us. However, affine templates now appear as though a rigid-only transformation has been applied. Our usage for affine is:

buildtemplateparallel.sh -d 3 -o affine -c 1 -t RA -s MI -z /SyN/SyNtemplate1.nii.gz $images

Any suggestions welcome. 

Thanks, 

Bonnie.

Affine option:
![affine_issue_affine_t2](https://cloud.githubusercontent.com/assets/11053443/14373606/24c78b82-fd8f-11e5-9ac3-78ce9c4e9723.png)

Rigid option:
![affine_issue_rigid_t2](https://cloud.githubusercontent.com/assets/11053443/14373611/2d4f4d58-fd8f-11e5-8977-8326b5ed6382.png)

**Comment by ntustison** [comment]
Try

``buildtemplateparallel.sh -d 3 -o affine -c 1 -t GR -m 0 -s MI -z /SyN/SyNtemplate1.nii.gz $images``
