### ISSUE TITLE
SyN registration  eats up memory

### ISSUE THREAD

**Issue by tanchaozhen** [stnava/ANTs#302]
I used Affine +SyN registration method to deal with my data,and I found ANTs eats up lots of memory.
fixedImage=9MB,movingImage=3MB,8bit/pixel.in the affine process ,ANTs takes 600MB,while in the SyN process, it takes 1600MB.
and I tried more data,fixedImage=1.1GB,movingImage=450MB,it takes almost 230GB.
I read the source code, found that ANTs support foat and double precision for computations , but even float, it also consumes too much memory.I tried to change the TComputeType to unsigned char, ,Or data type to be unsigned char, precision for computations to be float,but Error occurred.
Any suggestions for  reducing memory consumption,would be greatly appreciated.

**Comment by stnava** [comment]
a few options

* downsample your images beforehand (e.g. using `ResampleImage`)

* do not use full resolution SyN ( see the -f option )

* crop your images to remove extraneous image content ( background, etc )

you will not be able to compile syn with u/char types


brian

**Comment by tanchaozhen** [comment]
thanks for your help.I've been read "Symmetric diffeomorphic image registration with
cross-correlation".But I don't understand the detailed  of registration process and the code, is there any detailed technical documents for code implementation？

**Comment by stnava** [comment]
this might give you some insight: http://www.cplusplus.com/doc/tutorial/templates/ 

or maybe the [ITK software guide](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjw2suKtovMAhXIkx4KHbQFAogQFggfMAA&url=http%3A%2F%2Fwww.itk.org%2FItkSoftwareGuide&usg=AFQjCNEz2N8Kn90ZtSuLSbn5Y2W1jPeKTg&sig2=thULwisHM3SJLWR3F61ySw)
