### ISSUE TITLE
Usage 'N4BiasFieldCorrection' utilty

### ISSUE THREAD

**Issue by jimalexopoulos** [stnava/ANTs#303]
I'm trying to use the ANTs 'N4BiasFieldCorrection' utility on a neonatal T2-weighted MR image of the brain. When I simply run 'N4BiasFieldCorrection' with no options, I see the command usage/options. However, I can't seem to run it on an image using the following command shown below. I do not have a binary mask image.

jimalex>N4BiasFieldCorrection -c [100x100x100x100,0] -b [200] -s 3 -i T2image.nii.gz -o T2image_N4.nii.gz
N4BiasFieldCorrection: No match.

**Comment by cookpa** [comment]
I suspect you are running a c shell, which doesn't like square brackets. Try:

```
bash
N4BiasFieldCorrection -c [100x100x100x100,0] -b [200] -s 3 -i T2image.nii.gz -o T2image_N4.nii.gz
```

**Comment by jimalexopoulos** [comment]
Indeed. That worked like a charm, Thnx.

**Comment by cookpa** [comment]
Someone on Sourceforge reported the same issue, apparently quoting the string also helps.
