### ISSUE TITLE
How to use ANTs utilities in a C++ project?

### ISSUE THREAD

**Issue by LongXie** [stnava/ANTs#307]
I tried to use the adaptive none local mean denoise filter (itkAdaptiveNonLocalMeansDenoisingImageFilter.h in Utilities folder) in ANTs in my C++ project. Attached is the source code (main.cpp), Cmakefile of my project. I got some errors (Error_Message.doc) when I build the project. It seems like I would need to include some other dependancies in ANTs. Could you let me know how to configure the cmakefile in order to make it work? 

Thank you in advance for the help! 
[attached.zip](https://github.com/stnava/ANTs/files/224521/attached.zip)

**Comment by ntustison** [comment]
Although I could be wrong, I don't think you're setting up the cmake file correctly.  Can you test if the same error occurs if you try to include another class instead of the itkAdaptiveNonLocalMeansDenoisingImageFilter.h?

**Comment by LongXie** [comment]
I tried itkVarianceImageFilter.h before and got no error. Could you give me some suggestions about how to configure the cmake file? Thanks!

**Comment by ntustison** [comment]
Yeah, the variance image filter has minimal ITK dependencies compared with the denoising filter so I'm not surprised.  I'm actually getting ready to leave to meet Brian right now but will look more at your question probably tomorrow or Wednesday, if you haven't figured it out by then.

**Comment by LongXie** [comment]
Just take your time. Thank you for helping me with this!

**Comment by ntustison** [comment]
Okay, the problem is your inclusion of the ITK/VTK glue component in your CMakeLists.txt file.  Once I took that out, your program compiled without a problem.  If you need to include that for your project, I would recommend seeking help from the ITK list as I don't have much experience with that.

**Comment by hjmjohnson** [comment]
ITK recently fixed a problem with using ITK/VTK glue and then subsequently needing VTK in your own project.  There was an error where the find_package(VTK .....) inside ITK was clobbering previous calls to find_package(VTK) for private packages.

**Comment by LongXie** [comment]
It works now! Thanks!
