### ISSUE TITLE
How to restrict transformation?

### ISSUE THREAD

**Issue by rshkarin** [stnava/ANTs#309]
Hello,

I would like to restrict a Similarity transformation on rotation (use only translation + scaling).
Is it possible?

Thanks!

**Comment by ntustison** [comment]
Look at the '-g' option.  The serialization of the similarity transform parameters is described [here](http://www.itk.org/Doxygen/html/classitk_1_1Similarity3DTransform.html).  The first 3 parameters are rotation followed by the three translation parameters with the last parameter describing the scaling.  So, the following is what you want

```
antsRegistration -d 3 ... -g 0x0x0x1x1x1x1 ... -t Similarity[...
```

**Comment by rshkarin** [comment]
Thank you!
