### ISSUE TITLE
ANTs not finding VTK

### ISSUE THREAD

**Issue by weedavy** [stnava/ANTs#310]
Hello, am posting this here on the advice of Brian after sharing a few messages on the ANTs discussion site.

Am trying to build ANTs with VTK so that I can use antssurf. Ave been trying for over a week first on a CENTOS VM and then on Neurodebian. The basic gist of the error message is that ants make can't find VTK whether I add the VTK directory to my path or explicitly define the VTK path in make.

Any suggestions on best practice for installing and building VTK/ANTS+VTK would be much appreciated. 

Thank you very much and aw the best, David.

**Comment by hjmjohnson** [comment]
There was a problem with when ITK was built with ITKVTKGlue where including ITK after VTK would clobber the VTK library definitions.  You may want to try find_package(ITK) first followed by find_package(VTK)


find_package(VTK REQUIRED NO_MODULE )
include(${VTK_USE_FILE})
include_directories(${VTK_INCLUDE_DIRS})
set(INIT_VTK_LIBRARIES ${VTK_LIBRARIES})

## ITK must be found before VTK
## ITK calls find_package(VTK with limited components)
## and that creates a limited ${VTK_LIBRARIES} call
find_package(ITK REQUIRED NO_MODULE )
include(${ITK_USE_FILE})
## THERE IS A BUG IN ITK that clobbers the VTK_LIBRARIES
## variable when ITK was built with itkVTKGlue
set(VTK_LIBRARIES ${INIT_VTK_LIBRARIES})
unset(INIT_VTK_LIBRARIES)

This is just a guess.

Hans

**Comment by weedavy** [comment]
Thank you very much Hans, I'll give that a go.

Aw the best, David.

**Comment by imraghs** [comment]
Hi,

I am getting the same error: `VTK_DIR-NOTFOUND`

Although I have installed VTK.

When I set: `VTK_DIR: \usr\local\lib\cmake\vtk-7.1'

which is the same path which ITK is using, when I compile it with `Module_ItkVtkglue ON`

I am getting follwing error 

` CMake Error at SuperBuild/External_VTK.cmake: 201 (find_package): Could not find a configuration file for package "VTK" that is compatible with requested version "6.2" `

`The following configuration files were considered but not accepted:`
     `/usr/local/lib/cmake/vtk-7.1/VTKConfig.cmake, version: 7.1.0`
     `/usr/local/lib/cmake/vtk-7.1/VTKConfig.cmake, version: 7.1.0`
     `/usr/lib/cmake/vtk-6.0/VTKConfig.cmake, version: 6.0.0 `

ANTs configuration: 
![ants_cmake_config](https://cloud.githubusercontent.com/assets/13105636/15267145/f1a5f108-19d6-11e6-8dd1-82fde22b6f9f.png)

ANTs Error Msg: 
![ants_error](https://cloud.githubusercontent.com/assets/13105636/15267144/f1a59190-19d6-11e6-8431-020ac4be1cb4.png)

Can you tell me how to solve this issue?

**Comment by stnava** [comment]
i dont think this has been resolved.  it may be specific to linux as i
havent seen the same thing on osx.


brian

**Comment by gdevenyi** [comment]
I have a little bit of info for this, in the case of the Superbuild, turning on VTK has some issues:
1) VTK is configured to build **after** ITK, so ITK build breaks looking for it, I worked around this was a ``make -j5`` build, which starts the VTK build in parallel.
2) ITK can't find VTK until I add the VTK-install path to CMAKE_PREFIX_PATH (after successfully getting VTK built via the trick in 1

**Comment by hjmjohnson** [comment]
There was a bug in earlier versions of ITK that caused problems when both ITK and VTK were used.

 

It was addressed on April 5th in b64b0e7c49ebd14f98b47c5d67558adb26a74d24

 

You may want to verify that ITK is new enough to include that fix.

 

Hans

**Comment by gdevenyi** [comment]
To be clear, I'm saying it works, with my workarounds.

I'm just using the Superbuild. If it's not up-to-date, then it's missing the "fixes"

**Comment by weedavy** [comment]
I think I may have something useful to add here. The ANTs superbuild tries to get VTK4.0 from git but it appears that git no longer houses VTK4.0 (they are at version 7 now apparently) and so the build crashes here. But when you try to use a system VTK with a version other than 4.0 it won't even start because the superbuild looks for v4.0. It might then be useful to update/set the superbuild to accept newer releases of VTK, i.e., v7.


Peace,


David

________________________________

**Comment by gdevenyi** [comment]
I resolved this in PR #355
