### ISSUE TITLE
Problem with eigenanatomy decomposition and cortical thickness data

### ISSUE THREAD

**Issue by joebathelt** [stnava/ANTs#313]
Dear ANTs experts,
I'm working with some developmental data (children between 6 and 14 years) and wanted to apply eigenanatomy decomposition to reduce the dimensionality of the data for further analysis of the relationship between eigenanatomy components and cognitive test scores. The analysis of FA images worked really well, but I'm having some difficulties with cortical thickness data.

For pre-processing of T1-weighted volumes, I applied rigid co-registration to a T1-template and removed all images with excessive motion artefact. Then, I ran the images through the antsCorticalThickness (ANTs v1.9.2) pipeline with priors from the OASIS dataset - following your publication [1]:

antsCorticalThickness.sh \
    -a T1_file.nii.gz \
    -e T_template0.nii.gz \
    -m T_template0ProbabilityMask.nii.gz \
    -f T_template0 \
    -p priors%d.nii.gz
    -o T1_file-

The resulting cortical thickness masks looked reasonable to me.

![preview](https://cloud.githubusercontent.com/assets/9948570/14849445/026a75e6-0c6b-11e6-9d08-2b71b87d8314.jpg)

But I cannot find the expected effect of decreased cortical thickness with age with a t-test comparison across all voxels.

![preview-2](https://cloud.githubusercontent.com/assets/9948570/14849446/083cd9fa-0c6b-11e6-93ee-1f89199696ef.jpg)

Then, I used the 'CorticalThicknessNormalizedToTemplate' images produced by antsCorticalThickness for eigenanatomy decomposition in ANTsR v0.3.2. Here, I used the setting described in [2], i.e. 32 components, 1/32 sparsity, 20 iterations, 1 smoothness, 1000 voxels per cluster:

sparseDecom(inmatrix = mat,
                     inmask = mask,
                     nvecs = 32,
                     sparseness = 1/32,
                     its = 20,
                     smooth = 1,
                     cthresh = 1000,
                     ell1 = 0.5,
                     verbose = TRUE)

However, the decomposition could only explain 83% of the variance (FA-based decomposition from the same sample explained 94%). Further, the resulting decomposition is dissimilar to published results [2] and makes little anatomical sense (see attached ‘CorticalThicknessEanatDecomp’).

![preview-3](https://cloud.githubusercontent.com/assets/9948570/14849454/11914612-0c6b-11e6-8daa-94c93c834326.jpg)

I would be extremely grateful for any advice on what might be going wrong here.
 ________
 [1] Tustison, N. J., Cook, P. A., Klein, A., Song, G., Das, S. R., Duda, J. T., et al. (2014). Large-scale evaluation of ANTs and FreeSurfer cortical thickness measurements. NeuroImage, 99, 166–179. http://doi.org/10.1016/j.neuroimage.2014.05.044

 [2] Cook, P. A., McMillan, C. T., Avants, B. B., Peelle, J. E., Gee, J. C., & Grossman, M. (2014). Relating brain anatomy and cognitive ability using a multivariate multimodal framework. NeuroImage, 99, 477–486. http://doi.org/10.1016/j.neuroimage.2014.05.008

**Comment by stnava** [comment]
What type of model are you using to detect developmental effects?  something like this might be good:

```
mdl = lm(  mat ~  age * gender + I(age^2) * gender + ICV + ... )
bmdl = bigLMStats( mdl, 0.001 )
tvals = bmdl$beta.t["age",]
```
or something along those lines ( note use of ICV ) .... regardless of covariates, i am not too surprised that the multiple comparisons correction leads to relatively few voxels surviving the significance threshold.  you might visualize uncorrected values just to see if the pattern of effects is reasonable.

re: `sparseDecom` (or maybe `eanatDef` ), you probably should pass `scale(mat)` into the function if you have not done so already.  you may also try `scale( mat, scale=FALSE )` ... the function produces different results depending on if/how you scale the input data, similar to SVD vs PCA.   note also that the paper: http://www.ncbi.nlm.nih.gov/pubmed/24852460 provides a method for "customizing" ROI sets based on your prior notions and this method is available in `eanatDef` ... generally speaking, one would not expect a largely data-driven method to recapitulate the traditional conception of how neuroanatomy should be divided ... eanat takes into account (for better or worse) variability in the matrix that may included other effects such as signal reliability, scale, etc.

overall, your current results look like they are in the ballpark of what one would expect.

**Comment by joebathelt** [comment]
Thank you very much for your help! Unfortunately, I'm still not getting much of an age effect in this sample (linear or quadratic), even in the uncorrected image. Linear effect shown: 

![uncorrected_age_effect](https://cloud.githubusercontent.com/assets/9948570/14880424/a002f538-0d26-11e6-9cfc-a7ce4e9f6491.png)

Model:
``` R
gmat = imageListToMatrix(ilist, mask)
mdl = lm(gmat ~  Age_in_months*Gender + I(Age_in_months^2)*Gender + ICV, data=regressors)   
mdl = bigLMStats(mdl)  
gmstats = mdl$beta.pval["Age_in_months",]  
gqvimg = makeImage(mask, 1-gmstats)  
antsImageWrite(gqvimg, 'uncorrected_age_effect.nii.gz')
````

However, going back to literature, it could be that the age range is just too narow to detect an age effect with this sample size. 

Regarding the scaling in the eigenanatomy script, the analysis is still running, but I was a bit surprised that the explained variance is only around 28% when running sparseDecom with the scaled data. Is that possibly indicating that something is going awry? 

Thank you again for your help

**Comment by stnava** [comment]
the model looks reasonable ... did you smooth your data at all before performing the GLM?   something like

```
list = imageFileNamesToImageList( ... )
for ( i in 1:length( list ) ) {
  smoothImage( ... )    # 6mm FWHM
  resampleImage( ... ) # to 2mm
  }
```

could "help".  this just changes the spatial scale you are studying and may reduce some of the random effects of anatomical variability.

you may also find that this helps your eanat analysis, at least in terms of speed.  

our estimated variance explained indeed goes down when you scale the data in this way, due to the positivity constraint.    it's not something to worry about ... you can compute the "real" variance explained after the fact with standard linear regression.  what's used inside the function is a quick proxy.

**Comment by stnava** [comment]
also ref: http://www.nature.com/articles/sdata20153/figures/3
