### ISSUE TITLE
AverageImages Laplacian sharpening reference

### ISSUE THREAD

**Issue by jmtyszka** [stnava/ANTs#314]
We have a manuscript in revision where we used ANTs to generate a multivariate template for an atlas. We went with the AverageImages normalization flag = True in the template construction script, so the final templates are mean normalized and Laplacian edge enhanced. We'll need to justify going with this normalization in the manuscript.

Intuitively, it makes sense to edge enhance the template in order to emphasize boundaries in the optimization, but I'm having trouble finding any references to cite on this. Did the ANTs team ever publish this approach? Also, do you know the weight for the Laplacian filtered image used by ITK (sharpened image = original image + weight * Laplacian filtered image)? 

Great fan of ANTs BTW! Using it almost exclusively for mid-space and group template generation.

**Comment by stnava** [comment]
this is the method

http://www.ncbi.nlm.nih.gov/pubmed/19818860

it's not exactly what's in nick's script but the basic idea is there .... i do not believe there is any laplacian filtering going on.

**Comment by stnava** [comment]
maybe you are referring to our approach to "inverting" the averaging process ... as you can see in the reference above, we attempt to re-estimate a *shape* and *appearance* average image, iteratively.  this involves both (short time/approximate) inversion of the average diffeomorphism and also inversion of the blurring induced by intensity averaging (soft sharpening).  these two steps together producer a sharper template.

**Comment by jmtyszka** [comment]
Thanks for the quick response and the citation!

Both antsMultivariateTemplateConstruction.sh and antsMultivariateTemplateConstruction2.sh seem to default to using the mean of normalized intensities to generate intermediate and final templates from the warped image sets (eg https://github.com/stnava/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L94).

So normalizei is true in AverageImages.cxx and the final mean image is Laplacian sharpened at https://github.com/stnava/ANTs/blob/master/Examples/AverageImages.cxx#L155.

Is the Laplacian filtering/sharpening just a practical implementation of the the blurring inversion (soft sharpening) in the reference?

**Comment by stnava** [comment]
interesting ... see:

https://github.com/stnava/ANTs/blob/master/Examples/AverageImages.cxx#L150

which is commented out ... anyway, the only difference is that the laplacian filter moves too aggressively towards the next step so it's a minor difference, probably.

but yes it is a practical implementation of what we were doing in that paper.

**Comment by jmtyszka** [comment]
Thanks for clarifying - this all makes a lot more sense, particularly with the background from the hippocampus paper, which we'll definitely be citing in the revision. Thanks again for the quick responses!
