### ISSUE TITLE
How to apply transformation to mesh?

### ISSUE THREAD

**Issue by rshkarin** [stnava/ANTs#316]
Hello, how can I apply a transformation to a mesh data?
I have created the mesh of the moving image, now I want to apply the transformation to produce the mesh of the fixed image.

**Comment by stnava** [comment]
use antsApplyTransformToPoints

On Monday, May 2, 2016, Roman Shkarin <notifications@github.com> wrote:

> Hello, how can I apply a transformation to a mesh data?
> I have created the mesh of the moving image, now I want to apply the
> transformation to produce the mesh of the fixed image.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stnava/ANTs/issues/316>
>


-- 

brian
