### ISSUE TITLE
ants h5 composite transform inverse

### ISSUE THREAD

**Issue by satra** [stnava/ANTs#326]
we have been generating h5 composite transforms and using them. in one situation, we currently don't have access to the inverse, see below, so we were assuming antsApplyTransforms would compute it automatically, but it doesn't.

@hjmjohnson - is there a quick way to invert the transform?

```
antsApplyTransforms --float --default-value 0 --input mask.nii --input-image-type 0 --interpolation NearestNeighbor --output mask1.nii.gz --reference-image median.nii.gz --transform [affine.txt, 1] --transform [output_Composite.h5, 1]
Using single precision for computations.
Input scalar image: /om/project/read/task_fmri/scripts/mask_exploration_TMC/left_occipital_temporal.nii
Reference image: /gablab/p/READ/openfmri_task/l1output/model001/task001/READ_1002/mean/median.nii.gz
Inverse does not exist for output_Composite.h5
```

**Comment by satra** [comment]
@hjmjohnson - a quick ping here as this is a bit urgent. otherwise we will just rerun the registration and save the inverse_composite transform

**Comment by stnava** [comment]
​hi satra - i doubt that the inverse can be computed on the fly.  most of
the deformable methods we use in ants do not have analytical inverse.​


brian

**Comment by satra** [comment]
@stnava - thanks brian - we will start rerunning and saving the inverse transform. closing this for now.

**Comment by stnava** [comment]
yes - you would have to save those final maps ... if you want the internal
state of the registration ( which would, presumably, allow one to
reconstruct all transforms in both directions ), you might explore options
that i have not used:  --restore-state  and --save-state


brian
