### ISSUE TITLE
ENH: allow iMath to use FlatStructuringElement instead of BinaryBallStructuringElement

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTs#327]
I was looking into iMathFunctions and it seems as though iMathME and iMathMD use balls of a certain radius, where the radius is defined by the user.  

I don't know ITK enough to implement (hence the ENH), but I think using FlatStructuringElement may allow for more flexible kernels (I'm mainly interested in box kernels) for dilation/erosion/smoothing.  If you can smooth/erode/dilate with a box kernel using ANTsR otherwise, this may be a moot point.

**Comment by jeffduda** [comment]
A quick look at the documentation suggests that this should be a pretty straight forward implementation. I can take a closer look this week.

**Comment by jeffduda** [comment]
Ok, finally made the updates for this. I need to update the relevant code in ANTsR to take advantage of the new options, but all of the updates to ANTs code should be done.

**Comment by stnava** [comment]
is the idea to add this to antsr?

**Comment by jeffduda** [comment]
Yes, working on that addition now.

**Comment by jeffduda** [comment]
the iMath in ANTs is really nothing more than a testing ground for
functions that will end up in ANTsR. It makes the development process
faster: write and test the function in ANTs then once that is good, all
that is needed is a wrapper in ANTsR and updating the ANTs commit version
used in ANTsR

**Comment by stnava** [comment]
yeah, plus updating iMathOperations csv file and man file


brian

**Comment by jeffduda** [comment]
and updating vignette

**Comment by jeffduda** [comment]
Ok, just added this to ANTsR, see the new "morphology" function for details. The structuring elements are also available via iMath, but the morphology function provides a more "R-like" interface.

**Comment by stnava** [comment]
looks good - would be nice to have more meaningful example(s) in  `?morphology`
