### ISSUE TITLE
convergenceThreshold=0 not honoured

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#332]
I'm trying to do a "worst case" benchmark of antsRegistration for some job scripting by specifying a convergence threshold of 0 to ensure all iterations of of set of stages execute.

On *some* of my inputs, this seems to work as expected, but on others it doesn't.

Is there some other condition overriding the convergence stoppage?

**Comment by ntustison** [comment]
No (not considering system issues, e.g., excessive memory consumption).

**Comment by stnava** [comment]
Set to -inf

On Friday, June 17, 2016, Nick Tustison <notifications@github.com> wrote:

> No (not considering system issues, e.g., excessive memory consumption).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/stnava/ANTs/issues/332#issuecomment-226815362>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AATyfhb3TUnraDdLpEJ9km9a0rj8EU1Dks5qMspZgaJpZM4I4f-n>
> .
>


-- 

brian

**Comment by gdevenyi** [comment]
Sadly, both -inf and -Inf break the command-line parser:
```
itk::ExceptionObject (0x3eb6e70)
Location: "unknown" 
File: /opt/quarantine/ANTs/git/src/ANTs/Utilities/antsCommandLineParser.h
Line: 126
Description: itk::ERROR: CommandLineParser(0x3e481e0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '-inf' to type 'd' as double
```

**Comment by gdevenyi** [comment]
Looks like -1 forces it to do all iterations.

**Comment by ntustison** [comment]
Not necessarily.  That simply means that the convergence threshold value didn't go to -1.

**Comment by gdevenyi** [comment]
Okay, so the question remains, how can I force a given number of iterations?

**Comment by ntustison** [comment]
Specify a large convergence threshold value.

**Comment by ntustison** [comment]
A large _negative_ value.
