### ISSUE TITLE
Question: Do ants* use the qform/sform headers in Analyze/NIFTI files?

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#333]
In ANTS this option is available:
```
       --use-rotation-header 
              use rotation matrix in image headers: true (default) / false 
              <VALUES>: false
```

I can't find a mention of this in the (antsRegistration, antsApplyTransforms) tools.

Do these tools interpret the Analyze/NIFTI transform headers?

**Comment by spinicist** [comment]
ITK uses the qform when reading a NIFTI image. The sform can store transformations that can't be represented by itk::Image's spacing+direction+origin properties, so it is ignored.

Toby

**Comment by gdevenyi** [comment]
Cheers thanks!
