### ISSUE TITLE
imagemath float bug

### ISSUE THREAD

**Issue by mattcieslak** [stnava/ANTs#336]
Hello,

I think there is a small bug in ImageMath that prevents ReplicateDisplacement from working when the TR is not an integer (currently on line 9913):

unsigned int tr = atof(argv[argct]); argct++;

**Comment by ntustison** [comment]
Thanks.  [Fixed](https://github.com/stnava/ANTs/commit/bf62aff2764863a6181b043f8807e62db9e349f1).
