### ISSUE TITLE
Windows Release antsRegistration error: Joint PDF summed to zero, Too many samples map outside moving image buffer

### ISSUE THREAD

**Issue by DanielLeee** [stnava/ANTs#340]
Hi ANTs Team,
    Excuse me. I am a student from BUAA, who is doing research on brain image segmentation.
    When I use antsRegistration to register images that I cut from EADC-ADNI data set, 99% of the images are registered successfully but there are three pairs of them not working. I cut the original brain images into a 64*64*64 one according to the location of hippocampus.
    Could you please point out where my problems might be in? I use the tools in ANTs 2.1.0 Windows Release. I have sent an email to stnava@gmail.com but Mr. Avants told me that I should open an issue here and I should use nifti format instead of analyze75. I also tried the nifti format but the problem is still there. The command parameters are the same as MICCAI2012_MultiAtlasLabeling_Challenge runRegistrations.pl script.
    Thank you. Much appreciated.

        Command 1:
    antsRegistration.exe -d 3 -o ["trans_MCI028_NL040_L_","warpedimg_MCI028_NL040_L.img"] -u 1 -w [0.025,0.975] -r ["orig_MCI028_L.img","orig_NL040_L.img",1] -t Rigid[0.1] -m MI["orig_MCI028_L.img","orig_NL040_L.img",1,32,Regular,0.1] -c [2000x2000x2000,1e-9,15] -s 2x1x0 -f 4x2x1 -t Affine[0.1] -m MI["orig_MCI028_L.img","orig_NL040_L.img",1,32,Regular,0.1] -c [2000x2000x2000,1e-9,15] -s 2x1x0 -f 4x2x1 -t SyN[0.15,3.0,0.0] -m CC["orig_MCI028_L.img","orig_NL040_L.img",1,4] -c [100x100x100x50,1e-9,15] -s 3x2x1x0 -f 6x4x2x1

    Output 1:
    ...
    Exception caught:
itk::ExceptionObject (000000BFDE38AC58)
Location: "unknown"
File: c:\users\dp\desktop\ants210binary\itkv4-install\include\itk-4.7\itkMattesMutualInformationImageToImageMetricv4.hxx
Line: 397
Description: itk::ERROR: MattesMutualInformationImageToImageMetricv4(00000280D36A2ED0): Joint PDF summed to zero

    Command 2:
    antsRegistration.exe -d 3 -o ["trans_MCI028_NL006_L_","warpedimg_MCI028_NL006_L.img"] -u 1 -w [0.025,0.975] -r ["orig_MCI028_L.img","orig_NL006_L.img",1] -t Rigid[0.1] -m MI["orig_MCI028_L.img","orig_NL006_L.img",1,32,Regular,0.1] -c [2000x2000x2000,1e-9,15] -s 2x1x0 -f 4x2x1 -t Affine[0.1] -m MI["orig_MCI028_L.img","orig_NL006_L.img",1,32,Regular,0.1] -c [2000x2000x2000,1e-9,15] -s 2x1x0 -f 4x2x1 -t SyN[0.15,3.0,0.0] -m CC["orig_MCI028_L.img","orig_NL006_L.img",1,4] -c [100x100x100x50,1e-9,15] -s 3x2x1x0 -f 6x4x2x1

    Output 2:
    ...
    Exception caught:
itk::ExceptionObject (00000026B5B0B1A8)
Location: "unknown"
File: c:\users\dp\desktop\ants210binary\itkv4-install\include\itk-4.7\itkMattesMutualInformationImageToImageMetricv4.hxx
Line: 430
Description: itk::ERROR: MattesMutualInformationImageToImageMetricv4(000001F3C5CA5600): Too many samples map outside moving

**Comment by ntustison** [comment]
Can you post one of the problematic image pairs?

**Comment by DanielLeee** [comment]
Hi ntustison,
I have uploaded some of the problematic data to https://drive.google.com/open?id=0B55j6LZg-BCXQWJ6YzNDSjRvN0k
MCI028_L is the fixed image, others are the moving image. Scripts and outputs are included.
Thank you.

**Comment by ntustison** [comment]
Your images are small and so, with only a 10% sampling rate in the MI similarity metric, that's probably the reason you're not getting enough samples.  Try increasing the MI sampling to 0.25 particularly in the rigid stage, i.e.

```
antsRegistration -d 3 -v 1 -o [trans_MCI028_NL040_L_,warpedimg_MCI028_NL040_L.img] -u 1 -w [0.025,0.975] -r [orig_MCI028_L.img,orig_NL040_L.img,1] -t Rigid[0.1] -m MI[orig_MCI028_L.img,orig_NL040_L.img,1,32,Regular,0.25] -c [2000x2000x2000,1e-9,15] -s 2x1x0 -f 4x2x1 -t Affine[0.1] -m MI[orig_MCI028_L.img,orig_NL040_L.img,1,32,Regular,0.25] -c [2000x2000x2000,1e-9,15] -s 2x1x0 -f 4x2x1 -t SyN[0.15,3.0,0.0] -m CC[orig_MCI028_L.img,orig_NL040_L.img,1,4] -c [100x100x100x50,1e-9,15] -s 3x2x1x0 -f 6x4x2x1
```
