### ISSUE TITLE
--default-value negative number

### ISSUE THREAD

**Issue by nilgoyyou** [stnava/ANTs#344]
It's currently impossible to give a negative number for the default value on **MS Window**. I tried with cmd and powershell. `-v -1000` is always interpreted as a new "-10" flag. I tried with quotes, slashes, double dashes like bash, backquotes, etc. Nothing works.

Is there a trick? Or it was simply never tested and it doesn't work?

**Comment by ntustison** [comment]
Okay, I think it's fixed now with this [commit](https://github.com/stnava/ANTs/commit/a48537a9d3cfda51693e5dcb2d04d5267ccbc994#diff-a3fc1ccde37fa2cd748446794c59ba71).

**Comment by gdevenyi** [comment]
Does it make sense to perhaps switch to a standardized command line parsing library?

This library http://tclap.sourceforge.net is pure header so no special linking

**Comment by ntustison** [comment]
No.  The command line is custom for a reason.

**Comment by dorianps** [comment]
Just to put it there, the fix may need a new compile in Windows. The usual
release doesn't have it.
