### ISSUE TITLE
how can I calculate the coordinates of one certain voxel after transformation?

### ISSUE THREAD

**Issue by farrellsc** [stnava/ANTs#345]
I know it's kind of silly... but I've been confused by this problem for more than a week...
After I have applied antsRegistrationSyN to my raw data ( I shall call it origin.nii.gz), I got 3 files for transformation process, GenericAffine, Warp.nii.gz and InverseWarp.nii.gz.
So how exactly can I calculate the coordinates of a certain voxel after transformation?
Say GenericAffine.mat contained [a b c d e f g h i j k l] 
If I wish to calculate the coordinates of the voxel which originates in (x0,y0,z0) before transformation, how do I do it?
I tried to calculate it by [a b c; d e f; g h i]*[x0; y0; z0]+[j; k; l] for affine transformation only, yet the result went straight out of bound.
PLEASE DO HELP ME!

**Comment by stnava** [comment]
use antsApplyTransformsToPoints and see this example

https://github.com/stnava/chicken


brian

**Comment by farrellsc** [comment]
Thanks! Problem solved!
