### ISSUE TITLE
SLURM Errors on Certain Subjects When Running JLF

### ISSUE THREAD

**Issue by chriscrosscutler** [stnava/ANTs#346]
Recently there have been a handful of subjects that do not complete when running ANTs JointLabelFusion. I can't seem to identify why this only occurs with certain subjects and not others even though they are all running the same script.

Here is the script:

`#!/bin/bash
#SBATCH --time=50:00:00 # walltime
#SBATCH --ntasks=2 # number of processor cores (i.e. tasks)
#SBATCH --nodes=1 # number of nodes
#SBATCH --mem-per-cpu=32768M # memory per CPU core
#SBATCH -o /fslhome/ccutle25/logfiles/output_rerun_jlf9.txt
#SBATCH -e /fslhome/ccutle25/logfiles/error_rerun_jlf9.txt
#SBATCH -J "rerun_jlf9" # job name
#SBATCH --mail-user=chris.b.cutler@gmail.com # email address
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
name=Bigler_Repeatability_0009Bh_Le3
files=/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3
ARTHOME=/fslhome/ccutle25/apps/art/
export ARTHOME
export ANTSPATH=/fslhome/ccutle25/bin/antsbin/bin/
PATH=${ANTSPATH}:${PATH}
mkdir $files/labels/
sh ${ANTSPATH}antsJointLabelFusion.sh -d 3 -c 5 -o $files/labels/ -p $files/labels/Posteriors%02d.nii.gz -t $files/BrainExtractionBrain.nii.gz -x $files/BrainExtractionMask.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-1/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-1/OASIS-TRT-20-1_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-2/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-2/OASIS-TRT-20-2_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-3/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-3/OASIS-TRT-20-3_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-4/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-4/OASIS-TRT-20-4_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-5/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-5/OASIS-TRT-20-5_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-6/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-6/OASIS-TRT-20-6_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-7/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-7/OASIS-TRT-20-7_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-8/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-8/OASIS-TRT-20-8_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-9/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-9/OASIS-TRT-20-9_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-10/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-10/OASIS-TRT-20-10_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-11/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-11/OASIS-TRT-20-11_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-12/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-12/OASIS-TRT-20-12_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-13/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-13/OASIS-TRT-20-13_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-14/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-14/OASIS-TRT-20-14_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-15/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-15/OASIS-TRT-20-15_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-16/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-16/OASIS-TRT-20-16_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-17/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-17/OASIS-TRT-20-17_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-18/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-18/OASIS-TRT-20-18_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-19/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-19/OASIS-TRT-20-19_DKT31_CMA_labels.nii.gz -g /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-20/t1weighted_brain.nii.gz -l /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-20/OASIS-TRT-20-20_DKT31_CMA_labels.nii.gz -k 1
` 

Here is the log file:

--------------------------------------------------------------------------------------
 Start JLFization
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
 Parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /fslhome/ccutle25/bin/antsbin/bin/

 Dimensionality:           3
 Output prefix:            /fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/
 Posteriors format:        /fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/Posteriors%02d.nii.gz
 Target image:             /fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/BrainExtractionBrain.nii.gz
 Atlas images:             /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-1/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-2/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-3/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-4/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-5/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-6/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-7/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-8/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-9/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-10/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-11/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-12/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-13/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-14/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-15/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-16/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-17/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-18/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-19/t1weighted_brain.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-20/t1weighted_brain.nii.gz
 Atlas labels:             /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-1/OASIS-TRT-20-1_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-2/OASIS-TRT-20-2_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-3/OASIS-TRT-20-3_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-4/OASIS-TRT-20-4_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-5/OASIS-TRT-20-5_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-6/OASIS-TRT-20-6_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-7/OASIS-TRT-20-7_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-8/OASIS-TRT-20-8_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-9/OASIS-TRT-20-9_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-10/OASIS-TRT-20-10_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-11/OASIS-TRT-20-11_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-12/OASIS-TRT-20-12_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-13/OASIS-TRT-20-13_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-14/OASIS-TRT-20-14_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-15/OASIS-TRT-20-15_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-16/OASIS-TRT-20-16_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-17/OASIS-TRT-20-17_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-18/OASIS-TRT-20-18_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-19/OASIS-TRT-20-19_DKT31_CMA_labels.nii.gz /fslhome/ccutle25/templates/OASIS/OASIS-TRT-20-20/OASIS-TRT-20-20_DKT31_CMA_labels.nii.gz
 Transformation:           s

 Keep all images:          1
 Processing type:          5
 Number of cpu cores:      1
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
 Starting JLF on SLURM cluster. 
--------------------------------------------------------------------------------------
  Waiting for 20 jobs: 11044683 11044684 11044685 11044686 11044687 11044688 11044689 11044690 11044691 11044692 11044693 11044694 11044695 11044696 11044697 11044698 11044699 11044700 11044701 11044702
    Job 11044690 is in state PENDING
    Job 11044688 is in state PENDING
    Job 11044699 is in state PENDING
    Job 11044689 is in state PENDING
    Job 11044683 is in state RUNNING
    Job 11044702 is in state PENDING
    Job 11044701 is in state PENDING
    Job 11044691 is in state PENDING
    Job 11044684 is in state RUNNING
    Job 11044693 is in state PENDING
    Job 11044695 is in state PENDING
    Job 11044687 is in state PENDING
    Job 11044694 is in state PENDING
    Job 11044698 is in state PENDING
    Job 11044700 is in state PENDING
    Job 11044697 is in state PENDING
    Job 11044686 is in state PENDING
    Job 11044685 is in state PENDING
    Job 11044692 is in state PENDING
    Job 11044696 is in state PENDING
  (Mon Aug  8 18:18:21 MDT 2016) Still waiting for 20 jobs

    Job 11044688 is in state RUNNING
    Job 11044702 is in state RUNNING
    Job 11044687 is in state RUNNING
    Job 11044686 is in state RUNNING
    Job 11044696 is in state RUNNING
  (Mon Aug  8 18:28:21 MDT 2016) Still waiting for 5 jobs

  No more jobs in queue

/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_0_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_1_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_2_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_3_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_4_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_5_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_6_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_7_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_8_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_9_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_10_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_11_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_12_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_13_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_14_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_15_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_16_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_17_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_18_Warped.nii.gz
/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/t1weighted_brain_19_Warped.nii.gz
  Waiting for 1 jobs: 11044891
    Job 11044891 is in state PENDING
  (Mon Aug  8 18:38:22 MDT 2016) Still waiting for 1 jobs

  No more jobs in queue

--------------------------------------------------------------------------------------
 Done creating: /fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3/labels/Labels.nii.gz
 Script executed in 1814 seconds
 0h 30m 14s
--------------------------------------------------------------------------------------

The interesting bit is that it says that it created the Labels.nii.gz, but in that location there are only the files that JLF creates while running and not the Labels.nii.gz file.

Here is the error log file:

mkdir: cannot create directory `/fslhome/ccutle25/compute/Repeatability/Dehydration/Rerun/Bigler_Repeatability_0009Bh_Le3': File exists
slurm_load_jobs error: Invalid job id specified

Our supercomputer is also saying that several of the jobs that JLF creates while running on SLURM underutilize resources severely. For example, one of the jobs ran by this particular subjects used none of the requested memory or CPUs that JLF requested.

Is this something that you have seen before? Also note that it says that JLF ran in 30 minutes on the subjects that failed which is very short for JLF. How can I find exactly where it failed?

**Comment by ntustison** [comment]
Can't say that I've seen this before and it sounds like it could be a system-specific thing.  Those issues are hard to diagnose.  Also, run times of 30 minutes isn't necessarily short for JLF.  I would try finding a minimal example (i.e., target image with a minimum number of inputs which fail) and see if you can run it locally to try to reproduce the error.  You can also set up your own scripts and perform JLF outside the script ``antsJointLabelFusion.sh`` since all it does is register all the atlas images to the target image and then runs ``antsJointFusion``.

**Comment by chriscrosscutler** [comment]
I'll try that and see if it works. I didn't know that JLF could have such short run times.
