### ISSUE TITLE
why is there an antsr email in the README doc?

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTs#347]
From the MD Anderson tutorial, I don't want to see the antsr email on the website.

Thank you,
Nick

**Comment by stnava** [comment]
thanks for the reminder @ntustison  - will fix right away


brian

**Comment by stnava** [comment]
here is the commit that fixes the issue:  876ea612e737829acf5aca97f448abe1bbf36d8f

**Comment by ntustison** [comment]
Leave a comment
