### ISSUE TITLE
atlas buliding

### ISSUE THREAD

**Issue by chaohstat** [stnava/ANTs#350]
I have an atlas file. But the new dataset is in a different dimension. How could I make the atlas suitable for the new data set?

Thanks!

**Comment by ntustison** [comment]
Can you explain your atlas situation more in detail?  Unless it's 2-D vs. 3-D, different dimensions (or sizes) aren't a problem.

**Comment by chaohstat** [comment]
The atlas is 256*256*256, while the new data is 79*95*69

**Comment by ntustison** [comment]
Depending on what you're trying to do, that's not a problem.  Do you want to register the new data to the atlas?

**Comment by chaohstat** [comment]
Actually, I just want to register the atlas to the data, i.e., make the atlas into 79 95 69.

**Comment by ntustison** [comment]
Then just do

```
$ antsRegistrationSyN.sh -d 3 -f newData.nii.gz -m template.nii.gz -o templateWarpedToNewData
```

The warped template will be called "templateWarpedToNewDataWarped.nii.gz" and will be of size 79x95x69.

**Comment by chaohstat** [comment]
One more question, since my atlas is a roi labeling map, if  I do it in this way, the roi labels would be changed in the registered image, right?

**Comment by ntustison** [comment]
So what images to you have?  Does your atlas (i.e., roi labeling map) have an associated intensity image?  If this is the case, you should do

```
$ antsRegistrationSyN.sh -d 3 -f newData.nii.gz -m templateIntensity.nii.gz -o templateWarpedToNewData

$ antsApplyTransforms -d 3 -i templateRoiLabels.nii.gz -r newData.nii.gz -o templateRoiLabelsWarpedToNewData.nii.gz -n GenericLabel[Linear] -t templateWarpedToNewData1Warp.nii.gz -t templateWarpedToNewData0GenericAffine.mat
```
