### ISSUE TITLE
CC metric and shrinking/smoothing parameters

### ISSUE THREAD

**Issue by rshkarin** [stnava/ANTs#351]
Are there any recommendations on optimal shrinking/smoothing and CC radius parameters?
Does the CC radius depend on the size of structures presented on the data?
Should be the size on the first shrinking level be bigger than CC radius? 

Something that can answer these questions.

**Comment by stnava** [comment]
i like to think of these interactions in terms of scale-space.

we keep the CC radius constant across scale but change the underlying
sampling/smoothing to allow the metric to focus on (at coarse resolution)
large features, mid-size features at mid-resolution and fine scale features
at full resolution.

you can control all of this by adjusting the smoothing parameters with our
without downsampling.

if you do not have some idea about what features you want to match in your
data - then just use the default parameters that we provide in
antsRegistrationSyN.sh


brian

**Comment by rshkarin** [comment]
@stnava okay, then I will try to play around with constant CC radius and change shrink levels.
I have noticed that you double each next level (e.g. 10x6x4x2x1 or 8x4x2x1), should it produce better results (at least theoretically) if I specify levels like (10x9x8x7x6x5x4x3x2x1)? or computations on 3,5,7,8,9 levels will be redundant?

**Comment by stnava** [comment]
i think you would have to 

(a)  specify what you mean by "better"

(b)  have a quantitative method to test if you achieve better results

e.g. some people would say "better" means almost as good but much faster.
