### ISSUE TITLE
N4BiasFieldCorrection - ITK: A spacing of 0 is not allowed

### ISSUE THREAD

**Issue by JohRausch** [stnava/ANTs#353]
I am trying to apply N4BiasFieldCorrection to a set of different nifti volumes:
`N4BiasFieldCorrection -d 3 --input-image /path/inputfile.nii --output /path/outputfile.nii -v
`
For some volumes following error message occurs:
> Running N4 for 3-dimensional images.
> 
> Mask not read.  Creating Otsu mask.
> 
> Exception caught: 
> itk::ExceptionObject (0x34ca530)
> Location: "unknown" 
> File: /home/jr/git/antsbin/ITKv4-install/include/ITK-4.11/itkImageBase.hxx
> Line: 187
> Description: itk::ERROR: Image(0x34c9790): A spacing of 0 is not allowed: Spacing is [357.175, 357.175, 0]

The actual NIfTI header shows non-zero z-dimension and spacing:

```
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : 
dim_info        : 57
dim             : [  3 512 512   5   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [  1.           0.70309979   0.70309985  10.99967384   7.02799988   1.           1.
   1.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 18
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : 
aux_file        : 
qform_code      : unknown
sform_code      : aligned
quatern_b       : -0.743847370148
quatern_c       : 0.357479691505
quatern_d       : 0.518826365471
qoffset_x       : 77.9617004395
qoffset_y       : 220.897994995
qoffset_z       : 189.559005737
srow_x          : [  0.14488149  -0.53660524  -6.73670006  77.96170044]
srow_y          : [ -2.11249202e-01  -4.53479826e-01   7.72900009e+00   2.20897995e+02]
srow_z          : [ -6.54776633e-01   2.75726989e-02  -3.98399997e+00   1.89559006e+02]
intent_name     : 
magic           : n+1
```

I saw a similar issue on https://sourceforge.net/p/advants/discussion/840261/thread/7be9bf77/
but the error seems to have occurred for a different reason in that case.

**Comment by ntustison** [comment]
The default behavior is to shrink the image by a factor of 4 (``-s 4``) in each dimension.  It looks like you might need to adjust that parameter.

**Comment by JohRausch** [comment]
Thank you for the advice. Using a shrinking factor of 2 resolved the issue for the affected volumes.

**Comment by ntustison** [comment]
Great.  Glad it worked.
