### ISSUE TITLE
OSX compilation : ITK_DIR-NOTFOUND

### ISSUE THREAD

**Issue by markusgschwind** [stnava/ANTs#356]
Hi,
I followed the description of how to compile on OSX.

ccmake ~/ANTS, 

but when hitting c, it stops at an error saying that ITK_DIR was not found. 

Do I need to install ITK first? 
Thanks!

**Comment by stnava** [comment]
did you follow these instructions?

https://github.com/stnava/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

note the part about the git protocol.

you should not download itk separately.


brian

**Comment by markusgschwind** [comment]
Hi Brian,

Thanks for getting back to me.

Yes, exactly.

This is what I get when hitting ccmake ~/code

BUILD_ALL_ANTS_APPS              ON
>
> BUILD_SHARED_LIBS                ON
>
> BUILD_STYLE_UTILS                ON
>
> BUILD_TESTING                    ON
>
> CCACHE_PROGRAM                   CCACHE_PROGRAM-NOTFOUND
>
> CMAKE_BUILD_TYPE                 Release
>
> CMAKE_INSTALL_PREFIX             /usr/local
>
> CMAKE_OSX_ARCHITECTURES          x86_64
>
> CMAKE_OSX_DEPLOYMENT_TARGET
>
> CMAKE_OSX_SYSROOT
>
> EXTERNAL_PROJECT_BUILD_TYPE      Release
>
> FORCE_EXTERNAL_BUILDS            OFF
>
> ITK_BUILD_MINC_SUPPORT           OFF
>
> ITK_DIR                                              ITK_DIR-NOTFOUND
>
> ITK_VERSION_MAJOR                4
>
> OLD_BASELINE_TESTS               ON
>
> RUN_LONG_TESTS                   OFF
>
> RUN_SHORT_TESTS                  ON
>
> SuperBuild_ANTS_USE_GIT_PROTOC   OFF
>
> USE_SYSTEM_Cppcheck              OFF
>
> USE_SYSTEM_ITK                   OFF
>
> USE_SYSTEM_KWStyle               OFF
>
> USE_SYSTEM_SlicerExecutionMode   OFF
>
> USE_SYSTEM_Uncrustify            OFF
>
> USE_VTK                          OFF



This is the error message

 CMake Error at SuperBuild/External_ITKv4.cmake:31 (message):
>    ITK_DIR variable is defined but corresponds to non-existing directory ()
>  Call Stack (most recent call first):
>    CMake/SlicerMacroCheckExternalProjectDependency.cmake:69 (include)
>    SuperBuild.cmake:205 (SlicerMacroCheckExternalProjectDependency)
>    CMakeLists.txt:60 (include)



Thanks for help,
Markus



2016-08-30 13:58 GMT+02:00 stnava <notifications@github.com>:

**Comment by stnava** [comment]
perhaps remove everything and start again, following the instructions
exactly.

also make sure you have the latest version of ants, etc.


brian

**Comment by markusgschwind** [comment]
Thanks, Brian,

It worked. I have restarted using the git command (before I had downloaded
using the download button), I am not sure if it was this.

It seems functional now. Thanks!
Markus

2016-08-30 14:34 GMT+02:00 stnava <notifications@github.com>:
