### ISSUE TITLE
Tensor registration with ANTs

### ISSUE THREAD

**Issue by nadluru** [stnava/ANTs#357]
Hello ANTs team,

Not sure if I should post this as an issue but please bare with my question.

Based on the available ANTs code and documents it seems that there are tools to warp tensor images using estimated transformations but is there code to estimate the transformations directly from tensors? Using some notion of similarity between tensors? I know DTI-TK offers such a thing but wanted to know if ANTs has similar features.

Thanks so much.
Sincerely,
Nagesh

**Comment by ntustison** [comment]
I don't believe that capability exists in ANTs.

**Comment by nadluru** [comment]
I see. Thanks for the prompt reply Nick.

**Comment by stnava** [comment]
"some notion of similarity between tensors" is possible.

e.g. it would be fairly easy to use the multivariate similarity functions +
-r capabilities to do something based on tensors, log tensors or principal
directions.

not ideal, obviously, but one could iterate:

1. transform moving tensor image by current map
2. run a few iterations of multivariate similarity driven registration
based on fixed and warped moving
3. compose new solution with old to get new current map
4. go to 1 until satisfied


brian

**Comment by nadluru** [comment]
Yeah that makes sense Brian. I will explore if it is better to play with DTI-TK code directly or ANTS code to tweak the similarities etc.

Thanks so much for the prompt replies Nick and Brian!
