### ISSUE TITLE
itk::ERROR: SubtractImageFilter(0x7f5b59695750): Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by anuragdixit84** [stnava/ANTs#359]
I'm getting an error While applying itk::N4BiasFieldCorrectionImageFilter filter -
itk::ERROR: SubtractImageFilter(0x7f5b59695750): Inputs do not occupy the same physical space!
InputImage Origin: [-2.4511679e+02, -2.4511679e+02, -5.1912396e+02], InputImage_1 Origin: [-3.4355304e+02, -3.4355304e+02, -6.3352289e+02]
        Tolerance: 7.8124000e-06
InputImage Spacing: [7.8124000e+00, 7.8124000e+00, 1.0399902e+01], InputImage_1 Spacing: [9.8436241e+01, 9.8436241e+01, 9.3599121e+01]
        Tolerance: 7.8124000e-06

 Caught in exception handler itk::ERROR: SubtractImageFilter(0x7f5b59695750): Inputs do not occupy the same physical space!
InputImage Origin: [-2.4511679e+02, -2.4511679e+02, -5.1912396e+02], InputImage_1 Origin: [-3.4355304e+02, -3.4355304e+02, -6.3352289e+02]
        Tolerance: 7.8124000e-06
InputImage Spacing: [7.8124000e+00, 7.8124000e+00, 1.0399902e+01], InputImage_1 Spacing: [9.8436241e+01, 9.8436241e+01, 9.3599121e+01]
        Tolerance: 7.8124000e-06
I tried to get rid of this exception by settling the coordinate and direction tolerance but didn't get any success.
This filter I used with ShrinkImageFilter filter with shrink factor 4.
I am using ITK 4.7.2 toolkit.

**Comment by ntustison** [comment]
It doesn't appear that your two images are even close to occupying the same space.  Can you post the command line call?

**Comment by imalone** [comment]
I've run into this too with some images at particular settings. Convergence 0.0002, FWHM 0.05, iterations 1000x1000x1000x1000, ShrinkImageFilter factor 2 used, with a mask provided. The fitting gets to level 4, iteration 128 of 1000 before delivering:
```
  Iteration 127 (of 1000).   Current convergence value = 0.000222542 (threshold = 0.0002)
  Iteration 128 (of 1000).   Current convergence value = 0.000221617 (threshold = 0.0002)

itk::ExceptionObject (0x2bb3480)
Location: "unknown" 
File: /build/src/niftymidas-nightly-release/ITK/install/include/ITK-4.7/itkImageToImageFilter.hxx
Line: 248
Description: itk::ERROR: SubtractImageFilter(0x277db40): Inputs do not occupy the same physical space! 
InputImage Origin: [8.9000000e+01, 1.2500000e+02, -7.1000000e+01], InputImage_1 Origin: [2.2250000e+01, 2.6750000e+01, -2.2250000e+01]
        Tolerance: 2.0000000e-06
InputImage Spacing: [2.0000000e+00, 2.0000000e+00, 2.0000000e+00], InputImage_1 Spacing: [2.2250000e+01, 2.6750000e+01, 2.2250000e+01]
        Tolerance: 2.0000000e-06
```
It works with fewer iterations per level, so this seems to be something happening during the filter application, rather than a mismatch in input images.

I'm using a command line tool that someone else has wrapped around the N4BiasFieldCorrectionImageFilter, currently trying to see if I can reproduce this with the filter test driver. If you want to look at the files I've uploaded them to UCL's dropbox (BrainWeb derived images), pick-up URL: https://wwwapps-live.ucl.ac.uk/cgi-bin/dropbox/dropbox.cgi?state=pickup_info&id=66978a08 and https://wwwapps-live.ucl.ac.uk/cgi-bin/dropbox/dropbox.cgi?state=pickup_info&id=54791e9 passcode 54766962

**Comment by ntustison** [comment]
I was able to run

```
$ N4BiasFieldCorrection -d 3 -o test.nii.gz -i subject18_t1w_p4_rf20_A_11_05.nii -x subject18_t1w_p4_rf20_A_11_05_mask.nii -t [0.05] -c [1000x1000x1000x1000,0.0002] -v 1
``` 

and it finished without incident.  Can you try reproducing with the ``N4BiasFieldCorrection`` program?

**Comment by imalone** [comment]
Thanks for checking. It appears to have worked okay (I haven't tried it directly before, it reports a lot of pipeline information on completion, but no exceptions and an image is produced). ANTs likes building ITK itself, version 4.11, while the ITKBiasCorrectionTestDriver from version 4.7 eventually failed in the same way as the tool I was using previously, just at a different iteration. Possibly this was something fixed between 4.7 and 4.11? I'll try building the tool I'm using against ITK 4.11.

**Comment by imalone** [comment]
Building with ITK v4.10.1 works, so it was apparently a change in ITK that fixed my problem at some point. It may not be the same problem as anuragdixit84 had. I might have to find the cause to backport it, so will post it here if I do. Thanks for your help!

**Comment by ntustison** [comment]
Hey @stnava, @cookpa, @gdevenyi  Just an FYI since we've been bitten by this bug before but @blowekamp  found a likely culprit and submitted a [fix](https://github.com/InsightSoftwareConsortium/ITK/pull/1375).

**Comment by cookpa** [comment]
@stnava @ntustison @gdevenyi worth bumping the ITK version to fix this? I can test this afternoon, though I don't have any images that produce this bug reliably

https://github.com/InsightSoftwareConsortium/ITK/pull/1375

**Comment by ntustison** [comment]
I think so.  There should be a slight performance improvement anyway.  I was going to do it but have been working on the compiler warnings.  So if you can do it, that would be great.

**Comment by gdevenyi** [comment]
I also don't have anything to test this, but I support a bump.
