### ISSUE TITLE
ANTs and VTK

### ISSUE THREAD

**Issue by melrobin** [stnava/ANTs#365]
I'm having a problem building ANTs with VTK 7.  Here is the output of the build:
-- Building ANTS version "2.1.0.post691-g9bc18"
CMake Error at /usr/local/lib/cmake/vtk-7.1/vtkModuleAPI.cmake:120 (message):
  Requested modules not available:

```
vtkRenderingVolumeOpenGL
```

Call Stack (most recent call first):
  /usr/local/lib/cmake/vtk-7.1/VTKConfig.cmake:89 (vtk_module_config)
  ANTS.cmake:57 (find_package)
  CMakeLists.txt:65 (include)

-- Configuring incomplete, errors occurred!
See also "/home/melrobin/packages/ANTs/build/ANTS-build/CMakeFiles/CMakeOutput.log".
See also "/home/melrobin/packages/ANTs/build/ANTS-build/CMakeFiles/CMakeError.log".
CMakeFiles/ANTS.dir/build.make:108: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-configure' failed
make[2]: **\* [ANTS-prefix/src/ANTS-stamp/ANTS-configure] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[1]: **\* [CMakeFiles/ANTS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: **\* [all] Error 2

So the problem is with the vtkRenderingOpenGL module.  This module is not present in VTK 7.  In fact, there is a migration link here:  http://www.vtk.org/Wiki/VTK/Build_System_Migration  

I'm a little unsure of how to make changes to ANTs CMake files to get the build to finish.  

Any ideas on how I should proceed?

**Comment by gdevenyi** [comment]
See PR #363

**Comment by gdevenyi** [comment]
Fixed.
