### ISSUE TITLE
Building ants with Minc support

### ISSUE THREAD

**Issue by muratmaga** [stnava/ANTs#367]
Hi,
I am trying to build ANTS with MINC support, and enabled the
ITK_Build_MINC_Support. ccmake configures without an error but at the
compile time I am getting this error. 

-- Adding -fPIC compiler flag to generate position independent code.
CMake Error at Modules/ThirdParty/MINC/src/libminc/CMakeLists.txt:364
(EXPORT):
export called with target "itkminc2" which requires target
"hdf5_cpp-static" that is not in the export list.

If the required target is not easy to reference in this call, consider
using the APPEND option with multiple separate calls.

-- Configuring incomplete, errors occurred!
make[2]:
[ITKv4-prefix/src/ITKv4-stamp/ITKv4-configure] Error 1 make[1]:
[CMakeFiles/ITKv4.dir/all] Error 2
make: **\* [all] Error 2

I looked at thread https://github.com/stnava/ANTs/pull/198 but didn't
find a solution. Ants with default settings builds fine.

**Comment by gdevenyi** [comment]
Update your cmake version, it's tool old

**Comment by muratmaga** [comment]
Yep, that fixed it. Thanks.

**Comment by gdevenyi** [comment]
Related to #306
