### ISSUE TITLE
Impossibility to use CreateDTICohort with a schemeFile

### ISSUE THREAD

**Issue by ldealmei** [stnava/ANTs#369]
I tried using CreateDTICohort with a scheme file as described in the documentation  : 

"-w, --dwi-parameters [B0Image,directionFile,bvalue]
                                        **[B0Image,schemeFile]**
          [..]
          Alternatively, one can specify a scheme file where each direction is specified 
          followed by a b-value for that direction, i.e. <x1> <y1> <z1> <bvalue1> ... 
          <xN><yN><zN><bvalueN>. "

However I can't get it to work and always get the error (I attempted a bunch of formats for the scheme file) :  
"ERROR:  Number of directions does not match the data file."

By getting a closer look at the source code, it seems that if we don't use the first option ([B0Image,directionFile,bvalue]), the variable numberOfDirections is set at 0 and is not modified afterwards, inevitably failing the test leading to the above error.

Is this an option left unimplemented?

Thank you

**Comment by ntustison** [comment]
It is implemented although not incrementing the ``numberOfDirections`` is a bug in the original code.  After publishing this [tech report](http://www.insight-journal.org/browse/publication/837), I don't think it's gotten much use so thanks for taking a look.  This recent [commit](https://github.com/stnava/ANTs/commit/2464dea9a2ad17ccfa5b48830f9ac6e928ee556b) should fix the issue.

**Comment by ldealmei** [comment]
Great, thank you.

I forgot to mention in my original post, this : 

` if( dwiOption->GetFunction( 0 )->GetNumberOfParameters() < 2 )` (line 507 & line 519)

Isn't  the `<2` inadequate since there are 2 parameters `[B0Image, schemeFile]` ?
I am not sure about the `GetNumberOfParameters()` function but earlier, `GetNumberOfParameters() > 2` is used to detect if this input  `[B0Image,directionFile,bvalue]` was used in the call.

**Comment by ntustison** [comment]
Yeah, that's right.  It should be fixed now.
