### ISSUE TITLE
Rigid + Affine

### ISSUE THREAD

**Issue by TheChymera** [stnava/ANTs#370]
Is it in any situation required/beneficial to use both Rigid and Affine transformations? As I understand it, Rigid transformations are a subset of affine transformations, yet in [this example script](https://github.com/stnava/ANTs/wiki/Anatomy-of-an-antsRegistration-call) I see both are being used.

What is the benefit of doing so?

**Comment by gdevenyi** [comment]
Restricting the space of possible transforms during registration ensures you don't end up in incorrect local minina.

It is typical to start an affine registration with a rigid stage for that reason.

**Comment by TheChymera** [comment]
Would this still be the case if the images are significantly different in size and/or resolution?

**Comment by gdevenyi** [comment]
This is a general principle. I can't comment any further without knowing anything about the data.
