### ISSUE TITLE
VTK build broken again

### ISSUE THREAD

**Issue by melrobin** [stnava/ANTs#377]
Hello,

Now I get this error message on the ANTs build:  
[ 30%] Linking CXX executable ../../bin/GetMeshAndTopology
../../lib/libl_GetMeshAndTopology.so.2.1.0: undefined reference to `vtkScalarBarActor::New()'
../../lib/libl_GetMeshAndTopology.so.2.1.0: undefined reference to`vtkSTLWriter::New()'

I believe these were the same errors I was receiving in a previous issue.

**Comment by ntustison** [comment]
Did you completely remove your current build including any VTK or ITK superbuilds?  If not, you probably want to  start with a fresh checkout as there's been some recent VTK-related changes.

**Comment by gdevenyi** [comment]
Fixed via #383

**Comment by melrobin** [comment]
OK, I can verify that this has been fixed.
