### ISSUE TITLE
Stacking initial transforms

### ISSUE THREAD

**Issue by spinicist** [stnava/ANTs#378]
Hello,

I'd like to confirm how `--initial-moving-transform` works for multiple arguments.

I am registering pre-clinical (rat) images to an atlas. Sometimes the atlases are rotated 180 degrees about the Y axis (you can put a rat in the scanner either forwards or backwards). Currently, I use a hand-crafted ITK transform file with antsApplyTransforms to write out a rotated moving image, and then call antsRegistration with that and the atlas. antsRegistration is then called with `--initial-moving-transform [fixed,moving,1]` to match the CoG of the images.

If I instead use the original input, and add an extra `--initial-moving-transform my_file.tfm`, will that be applied to the moving image before the CoG calculation? As its worded I'm concerned that the CoG will be calculated on the raw (unrotated) moving image, which seems wrong.

Thanks.

**Comment by ntustison** [comment]
You can specify any number of ``initial-moving-transform`` options.  However, we didn't write it to initialize the center-of-gravity based on any previous transforms.  When you specify that particular choice on the command line, you have to specify a pair of images and it is that pair of images that are going to be used to calculate the transform.   What you can do is apply the transform(s) to your image(s) before the ``antsRegistration`` call, write them to disk, and use those rotated images to generate a center-of-gravity translation.

**Comment by spinicist** [comment]
Thanks Nick, that makes sense.
