### ISSUE TITLE
Interpolation-less Rigid transformation?

### ISSUE THREAD

**Issue by TheChymera** [stnava/ANTs#381]
I would like to register a functional image to a structural image. I notice they are already very well aligned, except that the functional image is shifted slightly upwards in the phase encoding direction. I am curious whether I could constrain my transformation so that:

* it only tries to move the image in the data matrix direction(s) and only voxel-per voxel.

In addition to not trying to rotate my image, this would also mean that there would be no need for interpolation, which I guess would lose less signal, and also lead to a faster warp.

If this is not possible, is it at least possible to constrain the Rigid transformation, so that it only does translation (no rotation)?

**Comment by ntustison** [comment]
Look at the ``-g, --restrict-deformation`` option.

**Comment by TheChymera** [comment]
I don't think I understand what P,Q, and R are. Nor do I really understand the example, so what exactly does `-g  '1x1x0x1x1x0'` do for a rigid transformation? How is this extended to translation? The example seems to only refer to rotation.

**Comment by ntustison** [comment]
You create a vector where each element corresponds to a transform parameter.  For example, a [3-D rigid transform](https://itk.org/Doxygen/html/classitk_1_1Euler3DTransform.html) has 6 parameters.  The link explains the ordering of the transforms.  You can find similar documentation for all ITK transforms.  

Also, I just looked more closely at your question---why not just use a translation transform directly (``-t Translation[gradientStep]``)?

**Comment by TheChymera** [comment]
That helped address my issue, thank you. In what units is the gradientstep given?

**Comment by ntustison** [comment]
Voxel spacing.

**Comment by aghayoor** [comment]
@TheChymera : Also this might be interesting to you:
http://www.insight-journal.org/browse/publication/770

**Comment by TheChymera** [comment]
Thank you.
