### ISSUE TITLE
How to use ResampleImage

### ISSUE THREAD

**Issue by lihengbit** [stnava/ANTs#388]
Hi, all.
I want to perform resample on a brain image. And  I performed:
 ResampleImage 3 T_template.nii.gz T_template_resize.nii.gz 256x256x128 [size=1,spacing=0] [2]
However, the output image is only of 1 kb.
How can I correctly use the command ResampleImage?

Thank you.

**Comment by ntustison** [comment]
The call should be:

```
$ ResampleImage 3 T_template.nii.gz T_template_resize.nii.gz 256x256x128 1 2
```

**Comment by lihengbit** [comment]
Great, thank you, Nick

**Comment by xiaojieguo** [comment]
Is there a tool to resample an image, which pixel type is a vector, such as a DVF?

**Comment by ntustison** [comment]
No, but you can split the image into components, resample the component images, and then merge the components back into a single image.
