### ISSUE TITLE
Question about "a large deformation example"

### ISSUE THREAD

**Issue by shansiliu** [stnava/ANTs#389]
Hi, I am new to ANTs, I have tried for one week to run this simple example(http://stnava.github.io/C/) without success. The system reports "Segmentation Fault" all the time.

I'm using the Windows Release version.

Here is my c_example.sh file:

dim=2
m=./data/c.nii.gz 
f=./data/chalf.nii.gz
its=[1200x1200x100x20x0,0,5]
smth=8x6x4x2x1vox
down=8x6x4x2x1
./antsRegistration -d $dim  \
                        -m demons[ $f,$m, 0.5, 0 ] \
                        -m meansquares[ $f,$m, 1, 0 ] \
                        -t TimeVaryingVelocityField[ 2.0, 8, 1,0.0, 0.05,0 ] \
                        -c $its  \
                        -s $smth  \
                        -f $down \
                       -u 1 \
                       -o [output/ex_,output/ex_diff.nii.gz,output/ex_diff_inv.nii.gz] 
./CreateWarpedGridImage $dim output/ex_0InverseWarp.nii.gz output/grid.nii.gz 
./ConvertToJpg output/grid.nii.gz figures/grid.png 
./CreateJacobianDeterminantImage 2 output/ex_0Warp.nii.gz output/jac.nii.gz 0 1
./CreateJacobianDeterminantImage 2 output/ex_0InverseWarp.nii.gz output/jac_inv.nii.gz 0 1

This is the output of the system:
$ /cygdrive/d/ANTs_2.1.0_Windows/Release/c_example.sh
All_Command_lines_OK
Using double precision for computations.
  number of levels = 5
  fixed image: ./data/chalf.nii.gz
  moving image: ./data/c.nii.gz
  fixed image: ./data/chalf.nii.gz
  moving image: ./data/c.nii.gz
Dimension = 2
Number of stages = 1
Use Histogram Matching true
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
   Image metric = Demons
     Fixed image = Image (000001BC56DA30A0)
  RTTI typeinfo:   class itk::Image<double,2>
  Reference Count: 2
  Modified Time: 619
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 440
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  BufferedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  RequestedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction:
1 0
0 -1

  IndexToPointMatrix:
1 0
0 -1

  PointToIndexMatrix:
1 0
0 -1

  Inverse Direction:
1 0
0 -1

  PixelContainer:
    ImportImageContainer (000001BC56D77000)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned long,double>
      Reference Count: 1
      Modified Time: 437
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 000001BC56DA91C0
      Container manages memory: true
      Size: 22500
      Capacity: 22500

     Moving image = Image (000001BC56DA33F0)
  RTTI typeinfo:   class itk::Image<double,2>
  Reference Count: 2
  Modified Time: 620
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 617
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  BufferedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  RequestedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction:
1 0
0 -1

  IndexToPointMatrix:
1 0
0 -1

  PointToIndexMatrix:
1 0
0 -1

  Inverse Direction:
1 0
0 -1

  PixelContainer:
    ImportImageContainer (000001BC56D78710)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned long,double>
      Reference Count: 1
      Modified Time: 614
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 000001BC56DD9690
      Container manages memory: true
      Size: 22500
      Capacity: 22500

     Weighting = 0.5
     Sampling strategy = none
     Number of bins = 32
     Radius = 4
     Sampling percentage  = 1
   Transform = TimeVaryingVelocityField
     Gradient step = 2
     Update field sigma (voxel space) = 1
     Total field sigma (voxel space) = 0.05
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 8
     Number of time point samples = 8
Registration using 1 total stages.

Stage 0
  iterations = 1200x1200x100x20x0
  convergence threshold = 0
  convergence window size = 5
  number of levels = 5
  using the Demons metric (weight = 0.5)
  preprocessing:  histogram matching the images
  using the MeanSquares metric (weight = 1)
  preprocessing:  histogram matching the images
  Shrink factors (level 1 out of 5): [8, 8]
  Shrink factors (level 2 out of 5): [6, 6]
  Shrink factors (level 3 out of 5): [4, 4]
  Shrink factors (level 4 out of 5): [2, 2]
  Shrink factors (level 5 out of 5): [1, 1]
  smoothing sigmas per level: [8, 6, 4, 2, 1]
  Using default NONE metricSamplingStrategy
/cygdrive/d/ANTs_2.1.0_Windows/Release/c_example.sh: 行 15:  9268 Segmentation fault      ./antsRegistration -d $dim -m demons[ $f,$m, 0.5, 0 ] -m meansquares[ $f,$m, 1, 0 ] -t TimeVaryingVelocityField[ 2.0, 8, 1,0.0, 0.05,0 ] -c $its -s $smth -f $down -u 1 -o [output/ex_,output/ex_diff.nii.gz,output/ex_diff_inv.nii.gz]
/cygdrive/d/ANTs_2.1.0_Windows/Release/c_example.sh: 行 17:  5624 Segmentation fault      ./ConvertToJpg output/grid.nii.gz figures/grid.png

**Comment by ntustison** [comment]
Are you able to run the example script, i.e.

```
$ sh c_example.sh
```

?

**Comment by shansiliu** [comment]
I can, I'm using  Cygwin64 Terminal on Windows 10.

**Comment by ntustison** [comment]
The call looks very similar, if not identical.  What is the difference between the two files?

**Comment by shansiliu** [comment]
Sorry....which two files?

**Comment by ntustison** [comment]
You said you were able to get the github example [file](https://github.com/stnava/C/blob/master/c_example.sh), ``c_example.sh``, to run.  I was asking you to compare it with the file that you are trying to run described in your initial posting.

**Comment by dorianps** [comment]
A side note, you can install ANTs in Windows 10 using Windows Linux
Subsystem. The benefit is that you can go straight the the latest code and
get updates immediately. Windows releases of ANTs are not that recent.

Instructions for installing ANTs in WLS are at the end of this page
<https://github.com/stnava/ANTsR/wiki/Installing-ANTsR-in-Windows-10-(along-with-FSL,-Rstudio,-Freesurfer,-etc).>
.

Dorian

**Comment by shansiliu** [comment]
Thanks for all your advices! I try the Ubuntu release version on Linux, and everything goes well.
