### ISSUE TITLE
antscorticalthickness.sh

### ISSUE THREAD

**Issue by tli3** [stnava/ANTs#391]
Hello,
I found that examples of antscorticalthickness.sh usually uses 4 or 6 ROIs. Do you provide some ROI template with more than 30 ROIs that for us to download? Or if I have such a ROI template (ROI value=1,2,...30), usually how could I generate the prior files for it? 
If I use 30 ROIs, will it cost lots of time to run? For example, 5 times slower than 6 ROIs?

Thx!

**Comment by ntustison** [comment]
Here's an [example](https://github.com/ntustison/antsCookTemplatePriorsExample) of the protocol for "cooking" the template priors.  We do not provide an ROI template for greater than 30 ROIs as there's not a need for such data to compute cortical thickness and I don't know why you would want to.  Having said that, it might be important to calculate the thickness in multiple cortical ROIs but generating those masks is performed after obtaining the cortical thickness maps.  Please see our
[paper](https://www.ncbi.nlm.nih.gov/pubmed/24879923) for more information.

**Comment by tli3** [comment]
Thank you, ntustison. It helps me a lot. So in your paper you first generate thickness map using 6 labeled (WM,GM,CSF,deep GM,brain stem and cerebellum) template, and then calculate the 62 DKT regional thickness using this thickness map as in Fig.5. Is this done by registering the Desikan-Killiany-Tourville atlas to the 6 ROI template?

**Comment by ntustison** [comment]
> So in your paper you first generate thickness map using 6 labeled (WM,GM,CSF,deep GM,brain stem and cerebellum) template, and then calculate the 62 DKT regional thickness using this thickness map as in Fig.5. Is this done by registering the Desikan-Killiany-Tourville atlas to the 6 ROI template?

The thickness map for each subject (see Figure 1, far right) is created using the templates and corresponding probability images which are available [here](https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436).  Once the thickness maps are created, we propagate the 62 labels of the DKT protocol using the OASIS 20 data from the MindBoggle website and joint label fusion.

**Comment by tli3** [comment]
Sorry, I send this email by mistake. Just ignore this one...


Best
Tengfei

**Comment by tli3** [comment]
Thank you a lot for your help, ntustison. Another question. Can we obtain ROI-wise and voxel-wise volumes based on the output of antscorticalthickness.sh? Is there an output RAVENS image?

**Comment by ntustison** [comment]
The transformation to the template can be calculated (see ``-t`` option).  From that transformation, the log jacobian map is computed.

**Comment by tli3** [comment]
Thank you, ntustison. Now I have processed some T1 images using this pipeline. I wonder is there a quality control protocol for me to check the segmentation quality manually, like freesurfer? Or quality control has been done automatically? as I find that the 6 stages of ACT to run are:
1: brain extraction; 2: template registration; 3: tissue segmentation; 4: template registration (improved, optional);  5: DiReCT cortical thickness;  6: qc, quality control and summary measurements

**Comment by ntustison** [comment]
A couple of .png files are generated showing the segmentation and cortical thickness overlaid on the T1 image in a mosaic arrangement so that one can do a quick quality check.  Anything more than that requires actually looking at the images using something like ITK-SNAP.  If you're running this pipeline for the first time, I would certainly recommend looking closely at the results.

**Comment by tli3** [comment]
I'm running this pipeline for the first time, Nick. Thank you so much for
your help.
Do you think is there some problem in the following segmentation? I use the
oasis-30 template and the 6 priors.
[image: Inline image 3]

Best
Tengfei

**Comment by ntustison** [comment]
I don't see anything.

**Comment by tli3** [comment]
This one.
![image](https://cloud.githubusercontent.com/assets/24256423/20989586/cd7ccd08-bc9a-11e6-9dad-e2e265f4f49f.png)

**Comment by ntustison** [comment]
That looks as expected.

**Comment by tli3** [comment]
Sorry Nick, I have one more question. I have downloaded OASIS-TRT-20_jointfusion_DKT31_CMA_labels_in_OASIS-30_v2.nii.gz and I find this one is in the same space with the Oasis template in the link you give me. But I cannot find the corresponding ROI names.  Where can I find the label name? I want to apply Equation (5) linear regression just as in that paper. I will calculate the mean intensity value of the output "antsCorticalThicknessNormalizedToTemplate.nii.gz"  in each ROI. Am I correct?   Millions of thanks!

**Comment by ntustison** [comment]
There are actually 20 Oasis images which have been labeled using the same DKT protocol---I'm guessing you need to search more.  The label names should be in the same location.  You use those images and ``antsJointLabelFusion.sh`` to label each T1-weighted image in its native space.  The ``{outputPrefix}CorticalThicknessNormalizedToTemplate.nii.gz`` image is suitable for voxel-based analyses but I would use the native space images for ROI-based analysis.

**Comment by tli3** [comment]
Hi, Nick. What's the difference between antsJointLabelFusion.sh and antsMalfLabeling.sh. Are they the same?

**Comment by ntustison** [comment]
No, they're not the same.  We should probably get rid of the Malf one since we no longer support the jointfusion.cxx program.

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/eecbffee87e59324e821f76cf1bbe13eed35e968

**Comment by tli3** [comment]
Thank you very much, Nick.
I found that on our old server Red hat linux rhel6,  antsJointLabelFusion.sh got the error message:
/software/x86_64/ANTs/2.1.0.post681-g09854//PrintHeader: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /software/x86_64/ANTs/2.1.0.post681-g09854//PrintHeader)
/software/x86_64/ANTs/2.1.0.post681-g09854//PrintHeader: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /software/x86_64/ANTs/2.1.0.post681-g09854//PrintHeader)
but antsMalfLabeling.sh.
antsJointLabelFusion.sh works on rhel6. 
On our new server rhel7, antsJointLabelFusion.sh works well.
It seems that antsJointLabelFusion.sh works on rhel7 and the old one antsMalfLabeling.sh works on rhel6. is it the case?

**Comment by ntustison** [comment]
rhel6 vs. rhel7 is irrelevant.  antsMalfLabeling.sh won't work since it calls the jointfusion.cxx program which is no longer included in the ANTs toolkit.

**Comment by tli3** [comment]
Hi, Nick. Besides ROI volume and cortical thicknesses, is there some functions to calculate the surface area?
Many thx!

**Comment by ntustison** [comment]
Try `LabelGeometryMeasures` which employs this [IJ contribution](http://www.insight-journal.org/browse/publication/852) which, in my experience, works better than alternatives such as marching cubes followed by surface area estimation.  It's not susceptible to things such as resampling.
