### ISSUE TITLE
multimodal normalization

### ISSUE THREAD

**Issue by pdeman** [stnava/ANTs#392]
Hello,

I am trying to normalize (into the MNI) my data.
I have a 3D T1 (full head) and a partial T2, around the STN.
Is that possible to do the normalization using both modality ?

Regards,

**Comment by ntustison** [comment]
Yes.  To make it easy, you can try ``antsRegistrationSyNQuick.sh``, i.e.

```
$ antsRegistrationSyNQuick.sh -d 3 -o ${outputPrefix} -f ${firstFixedImage} -m ${firstMovingImage}  -f ${secondFixedImage} -m ${secondMovingImage}
```
