### ISSUE TITLE
Questions about how to calculate an index for registration quality

### ISSUE THREAD

**Issue by GigiGAO** [stnava/ANTs#395]
Hello!
    I used antsRegistrationSyN.sh to register，how can I calculate the registration quality, I don't mean to check the figure of registration.

**Comment by ntustison** [comment]
Image registration assessment is an ongoing research [question](http://lmgtfy.com/?q=medical+image+registration+assessment).  We don't have any specific tools within ANTs to do such automated analyses but, rather, generally rely on visual inspection.
