### ISSUE TITLE
N4BiasFieldCorrection Inputs do not occupy the same physical space! (again)

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTs#396]
Just updated ANTs and enountered the old problem of the physical space tolerance. Both of the images are well aligned and with same headers (checked with `fslhd`)

If I remember well, this can be fixed by changing something in ITK and recompiling ANTs, but don't remember where.

```
dpustina@compute-0-17:dwibiascorrect-tmp-U0TQ0P$ N4BiasFieldCorrection -d 3 -i mean_bzero.nii -w mask.nii -o [corrected.nii,bias.nii] -s 2 -b [150] -c [200x200,0.0] -v

Running N4 for 3-dimensional images.

Mask not read.  Creating Otsu mask.

Specified spline distance: 150mm
  original image size:  [96, 96, 52]
  padded image size:  [126, 126, 61]
  number of control points:  [5, 5, 4]

Exception caught:
itk::ExceptionObject (0x2cd7580)
Location: "unknown"
File: /home/dpustina/antsbin/ITKv4-install/include/ITK-4.11/itkImageToImageFilter.hxx
Line: 250
Description: itk::ERROR: N4BiasFieldCorrectionImageFilter(0x2cc8040): Inputs do not occupy the same physical space!
InputImage 		Origin: [1.0820725e+02, 1.2572048e+02, -3.0397421e+01], InputImage_2 	Origin: [1.0820726e+02, 1.2572048e+02, -3.0397421e+01]
        Tolerance: 4.7916598e-06
```

**Comment by ntustison** [comment]
They don't have the same headers---look at the first element of the origin vector.  You can use ``CopyImageHeaderInformation`` to ensure that the headers are the same which is something we do frequently in various scripts (e.g., ``antsCorticalThickness.sh``).  You used to be able to change the default value in ``itkImageToImageFilter.hxx`` but Brad changed things to make things more accessible on an application level (cf [here](https://cmake.org/pipermail/insight-users/2016-September/053876.html).  You can read more about the changes [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkImageToImageFilter.h#L78-L92).  It looks like you can currently change the values in ITK [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/src/itkImageToImageFilterCommon.cxx#L26-L27).

**Comment by dorianps** [comment]
Great, thanks Nick.
