### ISSUE TITLE
Wrong output of ResampleImage

### ISSUE THREAD

**Issue by lihengbit** [stnava/ANTs#401]
Hi,
I tried to resample an image of nii with command ResampleImage 3 Input.nii.gz Output.nii.gz 256x256x150.
But the output is a file of only 1kb.
What is the problem?

Thank you

**Comment by ntustison** [comment]
You can access the help for the program for ``ResampleImage`` by typing just the program name, i.e.,

```
$ ResampleImage
Usage: ResampleImage imageDimension inputImage outputImage MxNxO [size=1,spacing=0] [interpolate type]
  Interpolation type: 
    0. linear (default)
    1. nn 
    2. gaussian [sigma=imageSpacing] [alpha=1.0]
    3. windowedSinc [type = 'c'osine, 'w'elch, 'b'lackman, 'l'anczos, 'h'amming]
    4. B-Spline [order=3]
```

Since you didn't specify the sixth argument, the program assumes you're specifying the geometry of the image by spacing which is probably not what you want.

**Comment by lihengbit** [comment]
Hi, Nick.
Actually, I tried ResampleImage 3 AX_T1.nii.gz AX_T1_RS.nii.gz 256x256x150 [size=1,spacing=0] as well. But just got ResampleImage: No match.

**Comment by ntustison** [comment]
Actual usage should be

```
$ ResampleImage 3  AX_T1.nii.gz AX_T1_RS.nii.gz 256x256x150 1
```

**Comment by lihengbit** [comment]
It works now. 
Thanks a lot, Nick!

**Comment by ntustison** [comment]
Great.
