### ISSUE TITLE
reporting fMRI results

### ISSUE THREAD

**Issue by Metasoliton** [stnava/ANTs#403]
Is there a function/script that takes a NIfTI image featuring finalized fMRI results (e.g. z-map clusters, following correction for multiple comparisons) as input and produces a table with local minima and anatomical labels? One would expect this to be the last step in the ANTs fMRI pipeline - perhaps the answer would be a useful addition to the wiki.

**Comment by stnava** [comment]
in ANTsR - see:

?getTemplateCoordinates


?getMultivariateTemplateCoordinates


brian
