### ISSUE TITLE
ADC-registration to MNI using ANTs

### ISSUE THREAD

**Issue by Phelax** [stnava/ANTs#404]
Hello, for a stroke project I need to register ADC images into MNI-Space using ANTs. I tryed an approach with concatinated rigid, affine and different types non-linear registration but the results were always not good, especially in infratentorial regions and the upper slices I find large proportions of distortion.
So I would like to know if there is a way of direct registration of ADC or B0 (what is better?) into MNI-Space and which parameters would be worth testing. Unfortunatly we don't have the option of using intraindividual anatomical image for this.
Thanks in advance!

I uploaded one sample ADC Data we tried to register to MNI152 T1 1mm

[WS013FU2_ADC.nii.zip](https://github.com/stnava/ANTs/files/738591/WS013FU2_ADC.nii.zip)

**Comment by stnava** [comment]
the first issue i see with this is that the anatomical orientation is not correct. 

the right approach, here, is to fix the header so that when you open the image it has the correct orientation.  use itk snap if you want something that is consistent with ants understanding of orientation in nifti images.

otherwise, try something like this:

https://github.com/stnava/ANTsR/wiki/Multistart-optimization-for-challenging-registration-problems

```
library( ANTsR )
nout = 10
thetas = seq( from = 0, to = 360, length.out = nout )[1:(nout-1)]
f = antsImageRead( "WS013FU2_ADC.nii.gz" ) %>% resampleImage( rep(4,3) )
m = antsImageRead( getANTsRData("ch2") ) %>% resampleImage( rep(4,3) )
mytx = "/tmp/best.mat"
mival<-invariantImageSimilarity( f, m,
  thetas=thetas, thetas2=thetas, thetas3=thetas,
  localSearchIterations=10, txfn=mytx )
w = antsApplyTransforms( f, m, transformlist=mytx )
plot( f, w )
```

note that the better/safer approach is to fix the header - then we might be able to get somewhere.

**Comment by stnava** [comment]
here is a reasonable approach that is a work-around but i do not recommend.

```
library( ANTsR )
mfull = antsImageRead( getANTsRData("mni") )
ffull = antsImageRead( "WS013FU2_ADC.nii.gz" )
msk = getMask( ffull )
ffull2 = ffull * msk
f = resampleImage(ffull2, rep(4,3) )
m = resampleImage( mfull, rep(4,3) )
mytx = "/tmp/best.mat"
nout = 30
thetas = seq( from = 0, to = 360, length.out = nout )[1:(nout-1)]
mival<-invariantImageSimilarity( f, m,
  thetas=thetas, thetas2=thetas, thetas3=thetas,
  localSearchIterations=0, txfn=mytx, transform='Affine' )
w = antsApplyTransforms( mfull, ffull2, transformlist=mytx, whichtoinvert=TRUE )
plot( mfull, w, axis=3 )
areg = antsRegistration( ffull2, mfull, initialTransform = mytx, typeofTransform='Affine' )
w = antsApplyTransforms( mfull, ffull2, transformlist=areg$invtransforms, whichtoinvert=c(TRUE) )
plot( mfull, w, axis=3 )
```

**Comment by stnava** [comment]
also - `getMask` works in the above case but it is very simple and may not work well, in general cases.
