### ISSUE TITLE
ANTs concatenate transformation matrix and multi-step reg

### ISSUE THREAD

**Issue by vanderLo** [stnava/ANTs#405]
Hi! I would like to concatenate different transformation matrices (instead of calling antsApplyTransforms for every step) so that I may transform from source to target space.

antsApplyTransforms.....-t 23.mat -t 1.warp -t 1.mat

I was trying CompositeTransformUtil to combine/assemble 23.mat from 2.mat and 3.mat. However, antsApplyTransforms fires an error then.  When I use antsApplyTransforms and list each matrix file, then there seems to be a grid-misalignment, probably (?) because the reference for each step was not given.

antsApplyTransforms.....-t 2.mat -3.mat -t 1.warp -t 1.mat 
(I ensured that input was given in the correct order)

So what is the best way have least interpolation and adequate results?

**Comment by stnava** [comment]
registration is all about getting the details right.     it is very common for us to do the following:

* register A to B

* register B to C 

* register C to D

* map A to D via antsApplyTransforms

this sounds like what you are trying, but failing, to do.    if you share code and details, then maybe someone can help.   or rethink your process and try to debug what you've done on your own, breaking down each step until there is no longer uncertainty into the source of the problem.

**Comment by vanderLo** [comment]
Thanks :)) Problem solved. Input was a 4D volume, while the script expected a 3D volume. Would be convenient if N4BiasFieldCorrection (without -d flag) would check the dim4/pixdim4 value and decide whether the input is 4D.

**Comment by ntustison** [comment]
>  would check the dim4/pixdim4 value and decide whether the input is 4D.

ITK handles more than just the nifti format.  We do an initial [read](https://github.com/stnava/ANTs/blob/master/Examples/N4BiasFieldCorrection.cxx#L889-L922) of the dimension, if possible, but that's not foolproof.
