### ISSUE TITLE
ants Surf blank display window

### ISSUE THREAD

**Issue by stnava** [stnava/ANTs#409]
i am  looking for feedback on a new issue that i've encountered regarding antsSurf.  data is attached and example command line calls are below.   

**the problem**

a blank display window or blank png file is output

**what else i know**

* compiled with the automated vtk download but also against my own externally compiled version of vtk7

* initially thought this would be osx specific but same problem on osx and centos7

* used to work as of a few-ish months ago 

* i believe there were some changes to ants internal download/compile of vtk since then but cant think of anything else that would lead to this

* antsSurf does produce a nice stl file that i can load and view in meshlab

[wmt.nii.gz](https://github.com/stnava/ANTs/files/761433/wmt.nii.gz)
[wm.nii.gz](https://github.com/stnava/ANTs/files/761443/wm.nii.gz)

any help appreciated.   none of below work for me.

```
antsSurf -s [ wmt.nii.gz,255x255x255]  -d antsSurfEx1.png[0x5x180,255x255x255] -i 10 
antsSurf -s [ wmt.nii.gz,255x255x255]  -d 1 -i 10 
antsSurf -s [ wm.nii.gz,255x255x255]  -d 1
```

first encountered when i tried to reproduce these examples

https://github.com/stnava/antsSurf

**Comment by ntustison** [comment]
Hey Brian, here's my output  for your first command:
```
antsSurf -s [ wmt.nii.gz,255x255x255]  -d antsSurfEx1.png[0x5x180,255x255x255] -i 10
```
![antssurfex1](https://cloud.githubusercontent.com/assets/324811/22749662/fb753654-ede2-11e6-8fc4-be91e9e5aa86.png)

I did make this recent [change](https://github.com/stnava/ANTs/commit/7b3f66d3679993eb54e1290b5879d8b48e6d2e4e) which could have an effect but I believed I accounted for the two option specifications.  I remember that I did have to reinstall a fresh VTK after this change but I don't know if that's your problem.

**Comment by stnava** [comment]
ok - what version of vtk did  you use?   when you say "fresh install" does that mean remove all of ants and all vtk and allow automated vtk download / install?   or did you link to the external library?

**Comment by stnava** [comment]
ok - this seemed to work:

```
 antsSurf -s [ wm.nii.gz,255x255x255x125] -d 1 -i 20
```

note the use of `125`  to get transparency ...  i.e. the "units" seem to be in 0 to 255

similarly for an overlay

```
 antsSurf -s [ wm.nii.gz,255x255x255x255] -f [ overlay_rgb.nii.gz, kblob.nii.gz, 125 ] -i 
25 -d 1
```

[kblob.nii.gz](https://github.com/stnava/ANTs/files/762025/kblob.nii.gz)

**Comment by stnava** [comment]
probably the source of the problem here:

https://github.com/stnava/ANTs/blob/master/Examples/antsSurf.cxx#L479

**Comment by ntustison** [comment]
Sorry, Brian, between my [run](https://www.strava.com/activities/859891424) this morning and my turn to run carpool, I'm only getting to this now.  Yep, that's definitely the problem.  I'll work on that now and submit a fix (unless, of course, you already have a fix).  Sorry about that.

**Comment by stnava** [comment]
i didnt fix it b/c i only found the one location ... the other would be for
the overlay.

should they all be in [0,255] or no?   doesnt matter to me as long as its
documented / consistent


brian

**Comment by ntustison** [comment]
> should they all be in [0,255] or no?

I'll take a look but I remember I had to treat the alpha differently.  I'll make sure it's consistent, though.

**Comment by ntustison** [comment]
Okay, I think [this](https://github.com/stnava/ANTs/commit/f8bcbc7c9380a1ed6858e70cbea2a255e0dc37a4) should fix it.  And it's consistent with the hep menu.

**Comment by stnava** [comment]
cool - thx!
