### ISSUE TITLE
ANTs Compile Error macOS Sierra

### ISSUE THREAD

**Issue by milesseidel** [stnava/ANTs#413]
Hello,

I'm attempting to install and compile ANTs on a mac.  When calling "$ make -j 4" I receive the following errors:

[ 28%] Building CXX object Examples/CMakeFiles/l_MemoryTest.dir/MemoryTest.cxx.o
/bin/sh: /private/var/folders/1t/9xvrbc6d2bd5v9f7rgn2yrwr0000gp/T/AppTranslocation/02290A40-187D-444A-BECF-6BE1E8D1CA3D/d/CMake.app/Contents/bin/cmake: No such file or directory
make[5]: *** [/Users/milesseidel/bin/ants/lib/libl_KellySlater.a] Error 127
make[4]: *** [Examples/CMakeFiles/l_KellySlater.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
/bin/sh: /private/var/folders/1t/9xvrbc6d2bd5v9f7rgn2yrwr0000gp/T/AppTranslocation/02290A40-187D-444A-BECF-6BE1E8D1CA3D/d/CMake.app/Contents/bin/cmake: No such file or directory
make[5]: *** [/Users/milesseidel/bin/ants/lib/libl_MemoryTest.a] Error 127
make[4]: *** [Examples/CMakeFiles/l_MemoryTest.dir/all] Error 2
/bin/sh: /private/var/folders/1t/9xvrbc6d2bd5v9f7rgn2yrwr0000gp/T/AppTranslocation/02290A40-187D-444A-BECF-6BE1E8D1CA3D/d/CMake.app/Contents/bin/cmake: No such file or directory
make[5]: *** [/Users/milesseidel/bin/ants/lib/libl_simpleSynRegistration.a] Error 127
make[4]: *** [Examples/CMakeFiles/l_simpleSynRegistration.dir/all] Error 2
/bin/sh: /private/var/folders/1t/9xvrbc6d2bd5v9f7rgn2yrwr0000gp/T/AppTranslocation/02290A40-187D-444A-BECF-6BE1E8D1CA3D/d/CMake.app/Contents/bin/cmake: No such file or directory
make[5]: *** [/Users/milesseidel/bin/ants/lib/libl_antsSliceRegularizedRegistration.a] Error 127
make[4]: *** [Examples/CMakeFiles/l_antsSliceRegularizedRegistration.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
make: *** [all] Error 2

Any idea what I am doing wrong? Help is much appreciated.

Thanks,
Miles

**Comment by ntustison** [comment]
That doesn't look like the entire screen dump.  Please try ``make`` (without the ``-j 4``) and then copy and paste the entire printout.

**Comment by milesseidel** [comment]
Hi Nick,

 

Compilation without the “-j 4” was successful. Thank you for the help and prompt reply.

 

Miles
