### ISSUE TITLE
Resampling transform files

### ISSUE THREAD

**Issue by michaelbernier** [stnava/ANTs#415]
Hi, I need to register a bunch of different modalities into a template space, with various resolutions for a group analysis. By example, I have some SWI images (0.6mm isotropic) and fMRI files (3mm iso) with their transform files to put them in their T1 referential (1mm). I also have the transform files for the T1 (1mm) to OASIS (1mm). If I want to apply these transforms to my SWI files, I'll end with a registered SWI of 1mm isotropic (loss of details). One idea was to upsample the T1 and OASIS template and redo the registration the SWI on them, but I wondered if there was a method to apply this resampling to the affine and warp files.

**Comment by ntustison** [comment]
You can use ``ConvertImage ... 10`` to separate the warp files into their component scalar images.  You can then resample those scalar images, using ``ResampleImage`` and then put them back together using ``ConvertImage ... 9``.  The affine files are not based on image resolution so you wouldn't need to changes those files.

**Comment by stnava** [comment]
in antsApplyTransforms , the -r option controls the resolution.  so you can
just resample your reference image to whatever resolution you prefer - may
not need to change the transformations.


brian

**Comment by dorianps** [comment]
I did something similar in ANTsR recently. All it takes is resample the
refrenece image to the desired resolution and apply transforms using the
newly resampled image as reference.

Dorian

**Comment by michaelbernier** [comment]
Thanks guys, '-r option' indeed makes the job easy. I thought that I needed to upsample the warp files, but it's automagically done. Good job!
