### ISSUE TITLE
make install failling because antsMalfLabeling.sh is missing 

### ISSUE THREAD

**Issue by NPann** [stnava/ANTs#417]
Hi all,
Posting this here as I could not find any related issue. 

./Scripts/antsMalfLabeling.sh is missing from master branch.
Consequently, `make install` fails during installation: script not found whereas listed in Examples/CmakeLists.txt (line 199).

Thanks,

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/f6e1f0bbc1fd08bef87e365677ce5aea1e801cc1

**Comment by NPann** [comment]
@ntustison Thanks !
