### ISSUE TITLE
ANTs configuration issue on a cluster using GCC5.4.0

### ISSUE THREAD

**Issue by lekshmideepu** [stnava/ANTs#423]
Hi all,

 I faced a series of issues when trying to build ANTs for the cluster using a build automation tool. Instead of the stable release version 2.1.0, I have cloned the master branch of ANTs and patched the file _ANTs-2.1.0/SuperBuild/External_ITKv4.cmake_ in order to use the latest version of ITK so that it supports GCC5.x (5.4.0). Also faced some issue with CXX_DISABLE_OPTIMIZATION_FLAG and patched the file _ANTs/Cmake/ITKSetStandardCompilerFlags.cmake_

Unfortunately now I am getting the following error which is  not very informative 

-- antsUtilitiesTesting 
-- Configuring incomplete, errors occurred!
See also "/../ANTs/2.1.0/gpsolf-2016b/easybuild_obj/ANTS-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-configure] Error 1
make[2]: Leaving directory `/..ANTs/2.1.0/gpsolf-2016b/easybuild_obj'
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
make[1]: Leaving directory `/../ANTs/2.1.0/gpsolf-2016b/easybuild_obj'
make: *** [all] Error 2

Anyone could help with this issue?

Many thanks in advance.

**Comment by ntustison** [comment]
Can you include the entire build log?

**Comment by lekshmideepu** [comment]
Please find it below:
https://gist.github.com/lekshmideepu/3071a5d8cbd0f8a8d202e59a5e9a9d0c

**Comment by ntustison** [comment]
What about the earlier error?  

> CMake Error at CMake/ProjectSourceVersion.cmake:38 (include):
>   include could not find load file:
>
>     /dev/shm/slns005/ANTs/2.1.0/gpsolf-2016b/ANTs-2.1.0/CMake/ProjectSourceVersionVars.cmake
> Call Stack (most recent call first):
>   Version.cmake:17 (include)
>   ANTS.cmake:16 (include)
>   CMakeLists.txt:57 (include)
>
> 
> -- Building ANTS version "2.1.0-gGITDIR-NOTFOUND"


Did you investigate?

**Comment by lekshmideepu** [comment]
Oh yes. Forgot to add that. I could see that this issue has been already fixed in your repo. #235 
I solved the problems by using the clone of the master as the source file  as the release version (2.1.0)  is buggy. Thanks!
