### ISSUE TITLE
N4 Failures

### ISSUE THREAD

**Issue by hjmjohnson** [stnava/ANTs#424]
I am getting very strange behavior from ANTs N4BiasFieldCorrection.  I am running identical commands on Mac (clang-800.0.42.1 ) and Linux (gcc 4.8.5), but the Linux version is giving very poor results (identical source code versions from git).

N4BiasFieldCorrection --bspline-fitting [ 200 ] -d 3 --input-image /Shared/nopoulos/63537016/46_T1_COR_ants_denoised.nii.gz --convergence [ 500x500x300x200, 1e-06 ] --output 46_T1_COR_N4_BFC.nii.gz --shrink-factor 3 

=============
During the spline estimation process, the linux version is giving very poor convergence behavior, where the mac version is stable (see linux log at bottom of message):

![antsconvergencefailures](https://cloud.githubusercontent.com/assets/313970/24084450/9ae255c0-0cb8-11e7-929e-62b8873fcd5b.png)

=============

My initial guess was a memory initialization problem, but valgrind is not reporting any problems.

============

I would appreciate any suggestions of where to look.

Thanks,
Hans

Start of Lmod init/bash script to define the module command
End of Lmod init/bash script to define the module command

Running N4 for 3-dimensional images.

Mask not read.  Using the entire image as the mask.

Specified spline distance: 200mm
  original image size:  [256, 236, 256]
  padded image size:  [364, 365, 364]
  number of control points:  [5, 5, 5]

Current level = 1
  Iteration 1 (of 50).   Current convergence value = 0.0172719 (threshold = 1e-06)
  Iteration 2 (of 50).   Current convergence value = 0.0109587 (threshold = 1e-06)
  Iteration 3 (of 50).   Current convergence value = 0.0221438 (threshold = 1e-06)
  Iteration 4 (of 50).   Current convergence value = 0.0146183 (threshold = 1e-06)
  Iteration 5 (of 50).   Current convergence value = 0.0244244 (threshold = 1e-06)
  Iteration 6 (of 50).   Current convergence value = 0.0123688 (threshold = 1e-06)
  Iteration 7 (of 50).   Current convergence value = 0.012639 (threshold = 1e-06)
  Iteration 8 (of 50).   Current convergence value = 0.0136056 (threshold = 1e-06)
  Iteration 9 (of 50).   Current convergence value = 0.0294014 (threshold = 1e-06)
  Iteration 10 (of 50).   Current convergence value = 0.0086168 (threshold = 1e-06)
  Iteration 11 (of 50).   Current convergence value = 0.032194 (threshold = 1e-06)
  Iteration 12 (of 50).   Current convergence value = 0.0183735 (threshold = 1e-06)
  Iteration 13 (of 50).   Current convergence value = 0.0106015 (threshold = 1e-06)
  Iteration 14 (of 50).   Current convergence value = 0.0162072 (threshold = 1e-06)
  Iteration 15 (of 50).   Current convergence value = 0.0158802 (threshold = 1e-06)
  Iteration 16 (of 50).   Current convergence value = 0.0106697 (threshold = 1e-06)
  Iteration 17 (of 50).   Current convergence value = 0.0311721 (threshold = 1e-06)
  Iteration 18 (of 50).   Current convergence value = 0.036156 (threshold = 1e-06)
  Iteration 19 (of 50).   Current convergence value = 0.0677558 (threshold = 1e-06)
  Iteration 20 (of 50).   Current convergence value = 0.0164121 (threshold = 1e-06)
  Iteration 21 (of 50).   Current convergence value = 0.0152358 (threshold = 1e-06)
  Iteration 22 (of 50).   Current convergence value = 0.0320422 (threshold = 1e-06)
  Iteration 23 (of 50).   Current convergence value = 0.0404662 (threshold = 1e-06)
  Iteration 24 (of 50).   Current convergence value = 0.0369694 (threshold = 1e-06)
  Iteration 25 (of 50).   Current convergence value = 0.0212535 (threshold = 1e-06)
  Iteration 26 (of 50).   Current convergence value = 0.00686457 (threshold = 1e-06)
  Iteration 27 (of 50).   Current convergence value = 0.0136722 (threshold = 1e-06)
  Iteration 28 (of 50).   Current convergence value = 0.00837844 (threshold = 1e-06)
  Iteration 29 (of 50).   Current convergence value = 0.0189572 (threshold = 1e-06)
  Iteration 30 (of 50).   Current convergence value = 0.0232924 (threshold = 1e-06)
  Iteration 31 (of 50).   Current convergence value = 0.00846201 (threshold = 1e-06)
  Iteration 32 (of 50).   Current convergence value = 0.0236281 (threshold = 1e-06)
  Iteration 33 (of 50).   Current convergence value = 0.00395733 (threshold = 1e-06)
  Iteration 34 (of 50).   Current convergence value = 0.0252396 (threshold = 1e-06)
  Iteration 35 (of 50).   Current convergence value = 0.00774153 (threshold = 1e-06)
  Iteration 36 (of 50).   Current convergence value = 0.00131872 (threshold = 1e-06)
  Iteration 37 (of 50).   Current convergence value = 0.0105761 (threshold = 1e-06)
  Iteration 38 (of 50).   Current convergence value = 0.0128874 (threshold = 1e-06)
  Iteration 39 (of 50).   Current convergence value = 0.0163397 (threshold = 1e-06)
  Iteration 40 (of 50).   Current convergence value = 0.00336785 (threshold = 1e-06)
  Iteration 41 (of 50).   Current convergence value = 0.0379893 (threshold = 1e-06)
  Iteration 42 (of 50).   Current convergence value = 0.00919143 (threshold = 1e-06)
  Iteration 43 (of 50).   Current convergence value = 0.0605996 (threshold = 1e-06)
  **Iteration 44 (of 50).   Current convergence value = 0.0109369 (threshold = 1e-06)
  Iteration 45 (of 50).   Current convergence value = 0.0234743 (threshold = 1e-06)
  Iteration 46 (of 50).   Current convergence value = 0.00870673 (threshold = 1e-06)
  Iteration 47 (of 50).   Current convergence value = 0.0215941 (threshold = 1e-06)**
  Iteration 48 (of 50).   Current convergence value = 0.0225251 (threshold = 1e-06)
  Iteration 49 (of 50).   Current convergence value = 0.00431966 (threshold = 1e-06)
  Iteration 50 (of 50).   Current convergence value = 0.00954715 (threshold = 1e-06)
Current level = 2
  Iteration 1 (of 50).   Current convergence value = 0.0222439 (threshold = 1e-06)
  Iteration 2 (of 50).   Current convergence value = 0.0291451 (threshold = 1e-06)
  Iteration 3 (of 50).   Current convergence value = 0.00636903 (threshold = 1e-06)
  Iteration 4 (of 50).   Current convergence value = 0.0765106 (threshold = 1e-06)
  Iteration 5 (of 50).   Current convergence value = 0.0746784 (threshold = 1e-06)
  Iteration 6 (of 50).   Current convergence value = 0.0100812 (threshold = 1e-06)
  Iteration 7 (of 50).   Current convergence value = 0.0449385 (threshold = 1e-06)
  Iteration 8 (of 50).   Current convergence value = 0.0444552 (threshold = 1e-06)
  Iteration 9 (of 50).   Current convergence value = 0.0261967 (threshold = 1e-06)
  Iteration 10 (of 50).   Current convergence value = 0.0126405 (threshold = 1e-06)
  Iteration 11 (of 50).   Current convergence value = 0.0376234 (threshold = 1e-06)
  Iteration 12 (of 50).   Current convergence value = 0.0697378 (threshold = 1e-06)
  Iteration 13 (of 50).   Current convergence value = 0.0238269 (threshold = 1e-06)
  Iteration 14 (of 50).   Current convergence value = 0.0283404 (threshold = 1e-06)
  Iteration 15 (of 50).   Current convergence value = 0.0151564 (threshold = 1e-06)
  Iteration 16 (of 50).   Current convergence value = 0.0128622 (threshold = 1e-06)
  Iteration 17 (of 50).   Current convergence value = 0.0265004 (threshold = 1e-06)
  Iteration 18 (of 50).   Current convergence value = 0.0338271 (threshold = 1e-06)
  Iteration 19 (of 50).   Current convergence value = 0.0271282 (threshold = 1e-06)
  Iteration 20 (of 50).   Current convergence value = 0.01764 (threshold = 1e-06)
  Iteration 21 (of 50).   Current convergence value = 0.0254594 (threshold = 1e-06)
  Iteration 22 (of 50).   Current convergence value = 0.0307858 (threshold = 1e-06)
  Iteration 23 (of 50).   Current convergence value = 0.0256209 (threshold = 1e-06)
  Iteration 24 (of 50).   Current convergence value = 0.030798 (threshold = 1e-06)
  Iteration 25 (of 50).   Current convergence value = 0.00901162 (threshold = 1e-06)
  Iteration 26 (of 50).   Current convergence value = 0.0406254 (threshold = 1e-06)
  Iteration 27 (of 50).   Current convergence value = 0.0579952 (threshold = 1e-06)
  Iteration 28 (of 50).   Current convergence value = 0.0346796 (threshold = 1e-06)
  Iteration 29 (of 50).   Current convergence value = 0.0116663 (threshold = 1e-06)
  Iteration 30 (of 50).   Current convergence value = 0.0110093 (threshold = 1e-06)
  Iteration 31 (of 50).   Current convergence value = 0.0293285 (threshold = 1e-06)
  Iteration 32 (of 50).   Current convergence value = 0.0100809 (threshold = 1e-06)
  Iteration 33 (of 50).   Current convergence value = 0.0286105 (threshold = 1e-06)
  Iteration 34 (of 50).   Current convergence value = 0.0166501 (threshold = 1e-06)
  Iteration 35 (of 50).   Current convergence value = 0.00581846 (threshold = 1e-06)
  Iteration 36 (of 50).   Current convergence value = 0.125856 (threshold = 1e-06)
  Iteration 37 (of 50).   Current convergence value = 0.0317425 (threshold = 1e-06)
  Iteration 38 (of 50).   Current convergence value = 0.0446937 (threshold = 1e-06)
  Iteration 39 (of 50).   Current convergence value = 0.044999 (threshold = 1e-06)
  Iteration 40 (of 50).   Current convergence value = 0.0318478 (threshold = 1e-06)
  Iteration 41 (of 50).   Current convergence value = 0.0554268 (threshold = 1e-06)
  Iteration 42 (of 50).   Current convergence value = 0.0185811 (threshold = 1e-06)
  Iteration 43 (of 50).   Current convergence value = 0.0237141 (threshold = 1e-06)
  Iteration 44 (of 50).   Current convergence value = 0.0155342 (threshold = 1e-06)
  Iteration 45 (of 50).   Current convergence value = 0.00745891 (threshold = 1e-06)
  Iteration 46 (of 50).   Current convergence value = 0.00886809 (threshold = 1e-06)
  Iteration 47 (of 50).   Current convergence value = 0.0887442 (threshold = 1e-06)
  Iteration 48 (of 50).   Current convergence value = 0.0148994 (threshold = 1e-06)
  Iteration 49 (of 50).   Current convergence value = 0.0199752 (threshold = 1e-06)
  Iteration 50 (of 50).   Current convergence value = 0.018332 (threshold = 1e-06)
Current level = 3
  Iteration 1 (of 30).   Current convergence value = 0.0871863 (threshold = 1e-06)
  Iteration 2 (of 30).   Current convergence value = 0.0875245 (threshold = 1e-06)
  Iteration 3 (of 30).   Current convergence value = 0.0203699 (threshold = 1e-06)
  Iteration 4 (of 30).   Current convergence value = 0.0233732 (threshold = 1e-06)
  Iteration 5 (of 30).   Current convergence value = 0.124553 (threshold = 1e-06)
  Iteration 6 (of 30).   Current convergence value = 0.0630904 (threshold = 1e-06)
  Iteration 7 (of 30).   Current convergence value = 0.0955206 (threshold = 1e-06)
  Iteration 8 (of 30).   Current convergence value = 0.0263884 (threshold = 1e-06)
  Iteration 9 (of 30).   Current convergence value = 0.0137696 (threshold = 1e-06)
  Iteration 10 (of 30).   Current convergence value = 0.108262 (threshold = 1e-06)
  Iteration 11 (of 30).   Current convergence value = 0.0373697 (threshold = 1e-06)
  Iteration 12 (of 30).   Current convergence value = 0.0156007 (threshold = 1e-06)
  Iteration 13 (of 30).   Current convergence value = 0.150026 (threshold = 1e-06)
  Iteration 14 (of 30).   Current convergence value = 0.0119277 (threshold = 1e-06)
  Iteration 15 (of 30).   Current convergence value = 0.0459375 (threshold = 1e-06)
  Iteration 16 (of 30).   Current convergence value = 0.0310663 (threshold = 1e-06)
  Iteration 17 (of 30).   Current convergence value = 0.0506366 (threshold = 1e-06)
  Iteration 18 (of 30).   Current convergence value = 0.0129269 (threshold = 1e-06)
  Iteration 19 (of 30).   Current convergence value = 0.0170725 (threshold = 1e-06)
  Iteration 20 (of 30).   Current convergence value = 0.0235148 (threshold = 1e-06)
  Iteration 21 (of 30).   Current convergence value = 0.0157677 (threshold = 1e-06)
  Iteration 22 (of 30).   Current convergence value = 0.0384411 (threshold = 1e-06)
  Iteration 23 (of 30).   Current convergence value = 0.0251765 (threshold = 1e-06)
  Iteration 24 (of 30).   Current convergence value = 0.145631 (threshold = 1e-06)
  Iteration 25 (of 30).   Current convergence value = 0.0110467 (threshold = 1e-06)
  Iteration 26 (of 30).   Current convergence value = 0.0128286 (threshold = 1e-06)
  Iteration 27 (of 30).   Current convergence value = 0.00626081 (threshold = 1e-06)
  Iteration 28 (of 30).   Current convergence value = 0.0212038 (threshold = 1e-06)
  Iteration 29 (of 30).   Current convergence value = 0.00412019 (threshold = 1e-06)
  Iteration 30 (of 30).   Current convergence value = 0.00720077 (threshold = 1e-06)
Current level = 4
  Iteration 1 (of 20).   Current convergence value = 0.0109164 (threshold = 1e-06)
  Iteration 2 (of 20).   Current convergence value = 34.4406 (threshold = 1e-06)
  Iteration 3 (of 20).   Current convergence value = 0.0205986 (threshold = 1e-06)
  Iteration 4 (of 20).   Current convergence value = 0.0245846 (threshold = 1e-06)
  Iteration 5 (of 20).   Current convergence value = 0.0226677 (threshold = 1e-06)
  Iteration 6 (of 20).   Current convergence value = 0.0125729 (threshold = 1e-06)
  Iteration 7 (of 20).   Current convergence value = 0.0321048 (threshold = 1e-06)
  Iteration 8 (of 20).   Current convergence value = 0.0147074 (threshold = 1e-06)
  Iteration 9 (of 20).   Current convergence value = 0.0191906 (threshold = 1e-06)
  Iteration 10 (of 20).   Current convergence value = 0.024504 (threshold = 1e-06)
  Iteration 11 (of 20).   Current convergence value = 0.0241588 (threshold = 1e-06)
  Iteration 12 (of 20).   Current convergence value = 0.0257105 (threshold = 1e-06)
  Iteration 13 (of 20).   Current convergence value = 0.0194202 (threshold = 1e-06)
  Iteration 14 (of 20).   Current convergence value = 0.0277125 (threshold = 1e-06)
  Iteration 15 (of 20).   Current convergence value = 0.0529938 (threshold = 1e-06)
  Iteration 16 (of 20).   Current convergence value = 0.0236904 (threshold = 1e-06)
  Iteration 17 (of 20).   Current convergence value = 0.0309397 (threshold = 1e-06)
  Iteration 18 (of 20).   Current convergence value = 0.0319192 (threshold = 1e-06)
  Iteration 19 (of 20).   Current convergence value = 0.0328165 (threshold = 1e-06)
  Iteration 20 (of 20).   Current convergence value = 0.0149742 (threshold = 1e-06)
   N4BiasFieldCorrectionImageFilter (0x1a0cf50)
     RTTI typeinfo:   itk::N4BiasFieldCorrectionImageFilter<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u> >
     Reference Count: 1
     Modified Time: 458
     Debug: Off
     Object Name: 
     Observers: 
       IterationEvent(Command)
     Inputs: 
       Primary: (0x1a1bed0) *
       _1: (0x1a15cd0)
     Indexed Inputs: 
       0: Primary (0x1a1bed0)
       1: _1 (0x1a15cd0)
     Required Input Names: Primary
     NumberOfRequiredInputs: 1
     Outputs: 
       Primary: (0x1a02890)
     Indexed Outputs: 
       0: Primary (0x1a02890)
     NumberOfRequiredOutputs: 1
     Number Of Threads: 56
     ReleaseDataFlag: Off
     ReleaseDataBeforeUpdateFlag: Off
     AbortGenerateData: Off
     Progress: 0
     Multithreader: 
       RTTI typeinfo:   itk::MultiThreader
       Reference Count: 1
       Modified Time: 134
       Debug: Off
       Object Name: 
       Observers: 
         none
       Thread Count: 56
       Global Maximum Number Of Threads: 128
       Global Default Number Of Threads: 56
     CoordinateTolerance: 1e-06
     DirectionTolerance: 1e-06
     Mask label: 1
     Number of histogram bins: 200
     Wiener filter noise: 0.01
     Bias field FWHM: 0.15
     Maximum number of iterations: [50, 50, 30, 20]
     Convergence threshold: 1e-06
     Spline order: 3
     Number of fitting levels: [4, 4, 4]
     Number of control points: [5, 5, 5]
     CurrentConvergenceMeasurement: 0.0149742
     CurrentLevel: 4
     ElapsedIterations: 21
     LogBiasFieldControlPointLattice: 
       Image (0x2a70df0)
         RTTI typeinfo:   itk::Image<itk::Vector<float, 1u>, 3u>
         Reference Count: 1
         Modified Time: 942184675
         Debug: Off
         Object Name: 
         Observers: 
           none
         Source: (none)
         Source output name: (none)
         Release Data: Off
         Data Released: False
         Global Release Data: Off
         PipelineMTime: 0
         UpdateMTime: 0
         RealTimeStamp: 0 seconds 
         LargestPossibleRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [19, 19, 19]
         BufferedRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [19, 19, 19]
         RequestedRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [19, 19, 19]
         Spacing: [24.786, 24.7501, 24.786]
         Origin: [-24.786, -24.7501, -24.786]
         Direction: 
1 0 0
0 1 0
0 0 1

         IndexToPointMatrix: 
24.786 0 0
0 24.7501 0
0 0 24.786

         PointToIndexMatrix: 
0.0403454 0 0
0 0.0404038 0
0 0 0.0403454

         Inverse Direction: 
1 0 0
0 1 0
0 0 1

         PixelContainer: 
           ImportImageContainer (0x1a17490)
             RTTI typeinfo:   itk::ImportImageContainer<unsigned long, itk::Vector<float, 1u> >
             Reference Count: 1
             Modified Time: 942184676
             Debug: Off
             Object Name: 
             Observers: 
               none
             Pointer: 0x2a71080
             Container manages memory: true
             Size: 6859
             Capacity: 6859
Elapsed time: 64.0682

**Comment by ntustison** [comment]
That is definitely some ugly convergence.  [Here's](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx#L694-L746) where we calculate the convergence measurement which is pretty straightforward.  One historical item of interest is that the coefficient of variation proposed in the original N3 paper for convergence was not actually used in the code.  Only the numerator was used but when I included the denominator, the convergence was similarly erratic which was one of the evidences for why the N4 iteration scheme was an improvement.   

Anyway, I don't think that's the issue.  Do you have a brain mask for that data and, if so, could you include it and run the tests again?  I doubt that this would resolve the issue but I'd just like confirmation before digging in deeper.

**Comment by hjmjohnson** [comment]
@ntustison Nick thanks.  I'll keep digging. You help in identifying where to look is helpful.

More information from an afternoon of investigations:

Linux, gcc 4.8.5 Debug ---> FAILED
Linux, gcc 4.8.5 Release ---> FAILED
Linux, Intel 2017.3 compilers Release ---> Reasonable results, no convergence issues
Mac, clang Release ---> Reasonable results, no convergence issues


I'm beginning to think this is a problem with gcc 4.8.5 in some way.

**Comment by ntustison** [comment]
I'm pretty sure this [ITK patch](http://review.source.kitware.com/#/c/22463/) addressed the issue.  Thanks again @hjmjohnson .
