### ISSUE TITLE
NeuroBattery DTI

### ISSUE THREAD

**Issue by ntraut** [stnava/ANTs#428]
In the DTI processing the script `antsNeuroimagingBattery` looks for a file with the pattern `$dwiparts[0]_ref.nii.gz`:
```
  # Find expected averagedwi image
  my @dwiparts = split( "_dt.nii.gz", $dtfile );
  my $dwi = "$dwiparts[0]_ref.nii.gz";
  if ( ! -s "$dwi" ) {
    print( "Could not find $dwi\n");
    print( "Unable to align $dtfile\n");
  }
```
but it fails to find it:
```
DTI Image - ../data/input/PEDS012/20131101/DTI/PEDS012_20131101_DTI_dt.nii.gz 
Could not find ../data/input/PEDS012/20131101/DTI/PEDS012_20131101_DTI_ref.nii.gz
Unable to align ../data/input/PEDS012/20131101/DTI/PEDS012_20131101_DTI_dt.nii.gz
```
The DTI folder was generated with the command `sh ${PIPEDREAMPATH}/nii2dt/nii2dt.sh --dwi ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0013_DTI_1_1x0_30x1000.nii.gz   ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0019_DTI_1_1x0_30x1000.nii.gz --bvals ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0013_DTI_1_1x0_30x1000.bval ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0019_DTI_1_1x0_30x1000.bval --bvecs ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0013_DTI_1_1x0_30x1000.bvec ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0019_DTI_1_1x0_30x1000.bvec --outroot PEDS012_20131101_DTI_ --outdir ../data/input/PEDS012/20131101/DTI` but in the script `nii2dt.pl` the file with the suffix _ref.nii.gz is created in temporary folder and then deleted.

**Comment by jeffduda** [comment]
Updating to the latest ANTs and ANTsR should fix this issue. Give it a try
and let me know.

**Comment by ntraut** [comment]
Sorry, I don't know what I'm doing wrong, but when I re-compile ANTs, there is no more antsNeuroimagingBattery in the folder antsbin/bin (and many other scripts are also missing). Maybe I missed something in the ccmake parameters...

**Comment by jeffduda** [comment]
The scripts are in the source tree at ANTs/Scripts. I think in the past
there may have been an option to copy them to the bin folder. I usually
just create a directory like ~/bin/ants/ that is full of symbolic links to
all of the files in ANTs-build/bin and ANTs/Scripts/. You could also just
add ANTs/Scripts to your PATH.

**Comment by cookpa** [comment]
I've found it's safest to copy the scripts to wherever ANTSPATH is, because some scripts will look for other ANTs scripts under ANTSPATH.

**Comment by ntraut** [comment]
OK, I followed your instructions and everything ran without error. The summary pdf was generated correctly.
Thanks.
