### ISSUE TITLE
antsApplyTransforms fails silently without --verbose

### ISSUE THREAD

**Issue by gdevenyi** [stnava/ANTs#429]
Trying:
```sh
> antsApplyTransforms -d 3 -i ../new-minc/T1/renorm/reshape/N4/no_name_20111229_143010_100_mri.mask.mnc -t no_name_20111229_143010_100_mri.mnc-brain1_t1_norm.mnc0_GenericAffine.xfm -n GenericLabel -o masks/no_name_20111229_143010_100_mri.mask.mnc
```

Fails silently, note the missing "--verbose"
It does provide a return code of 1.

Adding it:
```sh
> antsApplyTransforms -d 3 -i ../new-minc/T1/renorm/reshape/N4/no_name_20111229_143010_100_mri.mask.mnc -t no_name_20111229_143010_100_mri.mnc-brain1_t1_norm.mnc0_GenericAffine.xfm -n GenericLabel -o masks/no_name_20111229_143010_100_mri.mask.mnc --verbose
Using double precision for computations.
Input scalar image: ../new-minc/T1/renorm/reshape/N4/no_name_20111229_143010_100_mri.mask.mnc
A reference image is required.
```

**Comment by cookpa** [comment]
Is your ANTs up to date? 

https://github.com/stnava/ANTs/blob/master/Examples/antsApplyTransforms.cxx#L280-L287

Looks like it should return failure. And it does for me.

**Comment by gdevenyi** [comment]
As above:

Fails silently

It does provide a return code of 1.

**Comment by cookpa** [comment]
Right you are, sorry.

I think this was by design because of ANTsR. @stnava, is it the policy to have no output without a verbose flag, even on error?

**Comment by ntustison** [comment]
Since I had to do much of the code rewrite, I can confirm that, yes, the policy is to have no output without a verbose flag even in the case of an error.

**Comment by cookpa** [comment]
OK, thanks Nick.
