### ISSUE TITLE
creating hippocampus  mask from T1

### ISSUE THREAD

**Issue by Metasoliton** [stnava/ANTs#431]
Is there a script that can take a T1.nii as input and produce a mask of the subject's hippocampi (preferably a mask that is weighted based on cytoarchitectonic probabilities rather than binary)?

If someone could point me in the right direction, that would be appreciated very much.

Best wishes,
Stav

**Comment by gdevenyi** [comment]
https://github.com/CobraLab/antsRegistration-MAGeT + https://github.com/cobralab/atlases is one option

Another is antsJointLabelFusion with appropriate atlases.

**Comment by Metasoliton** [comment]
Thank you very much - those were great tips and exactly what I was looking for!
antsJointLabelFusion in particular is more appropriate in this case.

I tried antsJointLabelFusion using 2 of the CobraLab atlases and it actually worked well.
However, the other three atlases were giving errors when trying to convert from .mnc  to .nii
using all options I could think of, i.e.: 
- mnc2nii from MINC-tools (Error: Out of memory) 
- 3dAFNItoNIFTI (Error: ** NetCDF error: Can't open HDF5 attribute ** Program compile date = Aug 31 2016)
- mri_convert from FreeSurfer (Error ~ ncopen: filename brain3_labels.mnc": Not a netCDF file)
- MINC Import Utility from SPM (Error: "This is a newer version of MINC that SPM can not yet read.")

The latter three errors were actually given for all *_labels.mnc files, whereas mnc2nii from MINC-tools worked only on brain1_labels.mnc and brain5_labels.mnc but not on the other 3 mnc files.

Any suggestions on how to convert all 5 CobraLab atlases to NIfTI and/or suggestions on what other appropriate atlases/labels to use with antsJointLabelFusion would be greatly appreciated.

**Comment by gdevenyi** [comment]
Looks like you're using an old minc tools with only MINC1. These are MINC2 (HDF5) files

**Comment by gdevenyi** [comment]
Alternatively, http://cobralab.net/files/brains_t1_nifti.zip http://cobralab.net/files/atlases-nifti.zip I did the conversion and these are lightly tested as "correct"

**Comment by Metasoliton** [comment]
That was very kind of you and it seems to have worked like a charm.

Many thanks again for your valuable help!
