### ISSUE TITLE
ImageMath CropBinaryImage

### ISSUE THREAD

**Issue by jeffduda** [stnava/ANTs#433]
Any reason this is non-functional? If no, happy to implement it as I would like to use it.
https://github.com/stnava/ANTs/blob/master/Examples/ImageMath_Templates.hxx#L8620

**Comment by ntustison** [comment]
Is that functionality similar to this?  https://github.com/stnava/ANTs/blob/master/Examples/ExtractRegionFromImage.cxx

**Comment by jeffduda** [comment]
ExtractRegionFromImage is what i want. So I guess we can remove CropBinaryImage since it silently does nothing.

**Comment by ntustison** [comment]
Fine with me.  I think Brian uses Extract for cropImage.R.

**Comment by ntustison** [comment]
https://github.com/stnava/ANTs/commit/3069d9c1048a2e4fe091ebda36afd0c24ca745d3
