### ISSUE TITLE
Feature request: KappaStatisticsImageToImageMetric

### ISSUE THREAD

**Issue by kvrd18** [stnava/ANTs#435]
Is there a plan to include [KappaStatisticsImageToImageMetric](https://itk.org/Doxygen/html/classitk_1_1KappaStatisticImageToImageMetric.html) for registration? If not, can you please incorporate it into the current registration framework as it is handy for registering binary images quickly.

**Comment by ntustison** [comment]
There is not currently a plan to incorporate Kappa into ANTs.  However, if you want to do it, that would be a welcome contribution.
