### ISSUE TITLE
Joint Intensity Fusion

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTs#436]
I have been using joint intensity fusion (`jointLabelFusion`) in ANTsR to impute some T1 images from a group a controls. This works great after the [latest updates](https://github.com/stnava/ANTsR/commit/a79151f2b071f6ed2c7f6b4324d8694e58c72535#commitcomment-20297457) by @stnava . Now I am trying to do the same in ANTs using bash scripting. But both `jointfusion` and `jointLabelFusion.sh` require atlas labels. What would be the corresponding joint intensity fusion to run in shell, so I can get imputation of an image instead of label fusion?

**Comment by ntustison** [comment]
``jointfusion`` and ``jointLabelFusion.sh`` are no longer in the ANTs repository and don't support joint intensity fusion.  They were replaced by ``antsJointFusion`` and ``antsJointLabelFusion.sh``.  The former supports JIF.

**Comment by dorianps** [comment]
Thanks Nick.

I updated ANTs today without removing the old files, that's why maybe I still see the old binaries.
