### ISSUE TITLE
Dump transformation matrices (avoid saving)

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTs#438]
Quick, hopefully not too dumb, question. Is there a way to avoid saving the transformation matrices in `antsRegistration`. I tried `-o [ ,$outimg]` (note the empty argument in front of the comma) but that still saves them in the current directory. I don't think /dev/null would be helpful here.

**Comment by ntustison** [comment]
You can save the transformation files to a temp directory but there's no way to avoid saving them.

**Comment by dorianps** [comment]
Thanks.

**Comment by gdevenyi** [comment]
/dev/shm is a temp ramdisk to save on I/o
