### ISSUE TITLE
Issue Moving Freesurfer Parcellation to MNI Space

### ISSUE THREAD

**Issue by hermeckerogg** [stnava/ANTs#446]
Admittedly new to ANTs so I apologize if this is an easy fix.

I'm trying to warp the following 2 Freesurfer Parcellations to the FSL_MNI152_2mm standard template using antsRegistrationSyN.sh to flip the Freesurfer oriented MNI152 to FSL's 2mm template.

https://surfer.nmr.mgh.harvard.edu/fswiki/StriatumParcellation_Choi2012
http://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation_Yeo2011

I rant the following to flip from one template to the next:
antsRegistrationSyN.sh -d 3 -f MNI152_T1_2mm_brain.nii.gz -m FSL_MNI152_FreeSurferConformed_1mm.nii.gz -o FreesurferConformedtoFSL152MNI2mm

And used the resulting output to fit the parcellations to the template using the following:
antsApplyTransforms -r MNI152_T1_2mm_brain.nii.gz -i Yeo2011_17Networks_MNI152_FreeSurferConformed1mm.nii.gz -t FreesurferConformedtoFSL152MNI2mm0GenericAffine.mat -t FreesurferConformedtoFSL152MNI2mm1Warp.nii.gz -o AntsWarped_Yeo2011_17Networks_MNI152_FreeSurferConformed1mm.nii.gz -v 1

It looks great for the most part, but I noticed that some of the (1-17) values in the mask have changed and ideally that is not what I would like (pictures compared to the FSL transform attached).

Any idea what might have caused the values to change or how I could address it?

Thanks

![antsfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26163306/df6ba58e-3aee-11e7-87da-09566841937a.png)
![fslfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26163307/df740350-3aee-11e7-844e-b8c8a569107b.png)

**Comment by cookpa** [comment]
If you want to preserve labels as integers, you need to specify the `-n` option to `antsApplyTransforms`. You can choose nearest neighbor (fast) or multilabel interpolation.

**Comment by hermeckerogg** [comment]
Thank you.

I checked both of those and from what I can (poorly) see is that it looks like the Nearest Neighbor is the more conservative between the 2.

Do you have any recommendations or personal opinions as to which would be the better to use?

Also feel free to close the issue at your convenience.

![antsfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26164336/01fb351c-3af2-11e7-97f0-1a599649c60e.png)
![antsmlfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26164338/021cb7c8-3af2-11e7-9d91-b5b8cc35aa75.png)
![antsnnfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26164337/02189576-3af2-11e7-8e61-6975e43a01a6.png)

**Comment by hermeckerogg** [comment]
Thank you.

I checked both of those and from what I can (poorly) see is that it looks like the Nearest Neighbor is the more conservative between the 2.

Do you have any recommendations or personal opinions as to which would be the better to use?

Also feel free to close the issue at your convenience.
![antsmlfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26164396/258feafe-3af2-11e7-9c19-442da0e40205.png)
![antsnnfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26164398/25a164dc-3af2-11e7-8217-4be43b4f1388.png)
![fslfreesurfertofslmni2mm](https://cloud.githubusercontent.com/assets/23127333/26164397/259e954a-3af2-11e7-8743-d214e858478c.png)

**Comment by gdevenyi** [comment]
GenericLabel interpolation is also implemented.

**Comment by hermeckerogg** [comment]
Oooh. Will have to try that one for the next run. Thanks!
