### ISSUE TITLE
Resample a custom template into different voxel size

### ISSUE THREAD

**Issue by younghoo** [stnava/ANTs#450]
Hi,

A custom template is made by a group of T1 images with a 1x1x1.2mm voxel size and it takes about 3 hours to register individual T1 image (1x1x1.2mm) to this custom template in my computer. As a result, 

(1) I want to resample the template into a larger voxel size (for example, 2x2x2mm) to reduce registration time. What's the potential disadvantages of a larger voxel size template? 

(2) I find that command "ResampleImage" can fulfill the above task. However, I can't figure out the meaning of "M"/"N"/"0" in option "MxNx0"? (I guess it represents the expected matrix size but the axis information is still unclear)

Any suggestions? Many thanks!

**Comment by ntustison** [comment]
> (1) I want to resample the template into a larger voxel size (for example, 2x2x2mm) to reduce registration time. What's the potential disadvantages of a larger voxel size template?

Less resolution.

> (2) I find that command "ResampleImage" can fulfill the above task. However, I can't figure out the meaning of "M"/"N"/"0" in option "MxNx0"? (I guess it represents the expected matrix size but the axis information is still unclear)

They can either specify resampling by spacing in mm (e.g., "MxNxO"="2x2x2" mm as you've specified above) or size in voxels (e.g., resample to a total size of "100x100x100" voxels).

**Comment by cookpa** [comment]
If you want to fix the voxel spacing, rather than the image dimensions, you can use `ResampleImageBySpacing`. Alternatively, you can run 0 iterations at full resolution to speed up the registration without downsampling the template. Something like:

```
antsRegistration ... -f 6x3x2x1 -s 3x1x0.5x0 -c [30x40x60x0, 1E-6, 10] 
```

**Comment by younghoo** [comment]
Thank you for all replies! Very useful! As for the first question, a larger voxel size (lower resolution) template will get a higher or lower registration accuracy, or the resolution is unrelated to registration accuracy? The question stems from the observation that in FSL the default option will register individual T1 image (usually 1mm) to 2mm MNI template instead of 1mm template.

**Comment by ntustison** [comment]
Generally speaking, lower resolution ---> lower registration accuracy.
