### ISSUE TITLE
Occipital Cutoff in antsMultivariateTemplateConstruction.sh output

### ISSUE THREAD

**Issue by hermeckerogg** [stnava/ANTs#451]
Hello again.

Recently got antsMultivariateTemplateConstruction.sh working on our cluster. Have been hoping to use it to create a template from ~332 pediatric brains from the ABIDE database for an analysis within a specific age range.

Great news is that it ran and the template looks great, but I'm noticing that a good bit of the occipital lobe in the image appears to be cut off:
![v1cutoffants](https://cloud.githubusercontent.com/assets/23127333/26409456/3c64dc98-4066-11e7-9ea9-6a3db21b5be5.png)

None of the T1 images I used as the input had occipital cutoffs if memory serves so I'm not sure what would have caused this. Any input or ideas as to how this might have happened would be greatly appreciated.

Scripts used and the output files from the workflow are in the attached zip file
[ANTs-TemplateOutput.zip](https://github.com/stnava/ANTs/files/1025962/ANTs-TemplateOutput.zip)

Gdrive link to template image output:
https://drive.google.com/open?id=0B0cZmtBTp5f6cFRkdTVRTnBwMlE

Happy to send any other files from the workflow if needed.

**Comment by cookpa** [comment]
This is a result of the template shape update. The template is transformed to better reflect the average shape and orientation of the input data, but differences in image origins or positioning can cause the template to get shifted outside of the image volume.

You can try to reduce this by padding the template, re-centering it every few iterations, or turning off the rigid part of the shape update with `-y`.

**Comment by hermeckerogg** [comment]
Thank you.

I'll try turning off the rigid bit with -y first and see where that goes.

Admittedly still new to this package so would you mind if I asked how to adjust the workflow to re-center every few iterations? That sounds like the better fix.

**Comment by hermeckerogg** [comment]
Also I don't see a -y flag on the antsMultivariateTemplateConstruction.sh page, is it just a blank flag to give as part of the command?

**Comment by cookpa** [comment]
You'd probably have to do the re-centering manually by cropping / padding the image. On the command line, I'd use `c3d` (from ITK-SNAP) to do that, or ANTsR. It could be automated if you can reliably segment the template, because then you could use the bounding box of the head to figure out the placement of the image boundaries. Be sure to continue to leave space on all sides of the template to help the registration.

If you don't see `-y`, you have an older version of the script that doesn't support it.

**Comment by hermeckerogg** [comment]
Seems to be running with the -y flag but if it dies I'll tinker with the workflow a bit and see if I can reliably get the image to re-center.

You think appending the relevant c3d command it to the end of each SLURM job generated would do it? Or is there one call specific part of the workflow that you think would mitigate needing to do that in the rest of the pipeline?

**Comment by hermeckerogg** [comment]
It looks better with the -y flag but its still cut off at the very back.
![v1cutoffantswithflag](https://cloud.githubusercontent.com/assets/23127333/26462905/3dde6e44-4148-11e7-88d5-ff80760f19d8.png)

I actually had very little luck with c3d. I thought the -mbb function with some adjustments here and there might be useful in fixing the issue but I haven't been able to get that to work on my local machine (which will be even more of an issue transferring it and ITK-SNAP to our computing cluster).

Would it be a silly idea to maybe increase the bounding boxes of the input images (say by x1.5 or x1.25 in all dims) and run the template workflow on those images and hope the template uses the extra space or do you believe the truncation would still be an issue?

**Comment by stnava** [comment]
easy fix


ImageMath 3  newtemplate  PadImage template  50

then run one iteration of template building with -z newtemplate


brian

**Comment by spinicist** [comment]
Just a minor check @hermeckerogg - you did specify ```-y 0```? By default it's set to 1, so you have to switch it off.

**Comment by cookpa** [comment]
> Would it be a silly idea to maybe increase the bounding boxes of the input images (say by x1.5 or x1.25 in all dims) and run the template workflow on those images and hope the template uses the extra space or do you believe the truncation would still be an issue?

You definitely want to leave space around the template on all sides, this improves the alignment in general. It looks like your bounding box is large enough if the template was properly centered, but you can try making the initial template BB larger with `ImageMath` as Brian suggested. The template might settle at a final location without shifting any part of the head outside the bounding box. Beware that padding will increase the size of warp fields and thus the memory requirements of registration. 

If you like, you can remove the extra space after you're done, but leave some space on all sides (I use a minimum of 20mm). If the edge of the image volume is too close to the brain, boundary conditions can interfere with registration.

If the drift continues, it may become necessary to add `-y 0` - but it's good to run some iterations without that option first anyway, to minimize bias towards any particular rigid alignment.

**Comment by hermeckerogg** [comment]
The workflow created with @stnava's suggestion is finishing up right now. Will know in a few hours what it looks like.

I did NOT specify  -y 0 (I just put the flag there and left it) so I will try it again without the padding once this workflow is done to see if it fixes the issue for future runs.

**Comment by hermeckerogg** [comment]
Well good news is that fixed the issue with the occipital cutoff.

Bad news is it created a different problem:
![antswithtemplate](https://cloud.githubusercontent.com/assets/23127333/26515474/aa285b52-4240-11e7-928f-158bc69daf1a.png)

Going to try that suggestion from @spinicist (fixing the -y flag) and see what that does.

**Comment by cookpa** [comment]
This looks like the rigid initialization is running but the rest of the iterations are not. Increasing the size of the input volumes is going to require more RAM, and if you don't have enough available then the jobs will fail and the template won't get updated.

I also see from this that your initial template is very close to the posterior end of the bounding box, even with padding. I recommend centering it before continuing with `-y 0`. 

This is how I do it:

`c3d input.nii.gz -pad AxBxCvox DxExFvox 0 -o output.nii.gz`

where A-F are integers that add voxels to the lower (A,B,C) and upper (D,E,F) ends of the bounding box. Thus you can add more voxels on the posterior end and less (or zero or negative to subtract) voxels on the anterior end, to move the template brain.

Depending on how your voxel space is constructed, you might need to experiment with which dimension moves the template in the right direction.

**Comment by hermeckerogg** [comment]
@cookpa,

Got the template as close to the center as I believe I am able to get it (mostly just lined up to AC).

Running it now. Should have some results tomorrow.

**Comment by hermeckerogg** [comment]
Got the output from the workflow this morning:

![latesttemplate](https://cloud.githubusercontent.com/assets/23127333/26553299/a03163fc-4450-11e7-93c2-f15721c04d7e.png)

Looks great in my humble opinion.

Thank you all!
