### ISSUE TITLE
N4BiasFieldCorrection changes QForm Code w.r.t. the input nifti file

### ISSUE THREAD

**Issue by oesteban** [stnava/ANTs#452]
I have noticed that headers slightly change from input to output with `N4BiasFieldCorrection`. Using `nibabel`, I have these headers for one T1w image from the ABIDE dataset:

```
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 176 256 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.          1.          1.          1.          1.59000003  0.          0.
  0.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL4.1'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 88.8559341430664
qoffset_y       : -66.66102600097656
qoffset_z       : -143.27117919921875
srow_x          : [ -1.           0.           0.          88.85593414]
srow_y          : [  0.         1.         0.       -66.661026]
srow_z          : [   0.           0.           1.        -143.2711792]
intent_name     : b''
magic           : b'n+1'
```

However, for the bias-corrected image:

```
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 176 256 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  0.  0.  0.  0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : aligned
sform_code      : scanner
quatern_b       : -0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 88.8559341430664
qoffset_y       : -66.66102600097656
qoffset_z       : -143.27117919921875
srow_x          : [ -1.          -0.           0.          88.85593414]
srow_y          : [ -0.         1.        -0.       -66.661026]
srow_z          : [   0.           0.           1.        -143.2711792]
intent_name     : b''
magic           : b'n+1'
```

- First of all, the image data type changes. I think that would be best not changing (or having a specific option to copy the output data type from the input). But I don't think that's very worrisome. The description field is rewritten, but this is not a problem at all (even though it could be kept since software like afni will use this field to keep some provenance).
- Pixel dimensions & `xyzt_units` are also changed. This is IMHO more problematic, but still acceptable.
- The real problem is the change of the `qform_code` field. That would change the orientation of the image to the eyes of the downstream pipeline.

**Comment by cookpa** [comment]
Much of the I/O is determined by ITK, rather than specific to ANTs, so it's unlikely to change. I put some notes about this on the wiki:

https://github.com/stnava/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by ntustison** [comment]
Also, adding to what Phil wrote:

> First of all, the image data type changes. I think that would be best not changing (or having a specific option to copy the output data type from the input). But I don't think that's very worrisome. The description field is rewritten, but this is not a problem at all (even though it could be kept since software like afni will use this field to keep some provenance).

Real type operations are required for performing bias correction.  If someone wants to convert back to an integer type with the resulting loss of information, that should be done outside of the program.

**Comment by oesteban** [comment]
@cookpa, @ntustison  thanks a lot for the prompt answer.

If I understand correctly,
- the qform issue would replicate with any of ANTs binaries because of ITK,
- and casting back to the original type is one user's responsibility.

Thanks!

**Comment by ntustison** [comment]
Yes, both are correct.

**Comment by oesteban** [comment]
Thanks :+1:
