### ISSUE TITLE
Restrict Deformation Bug?

### ISSUE THREAD

**Issue by spinicist** [stnava/ANTs#456]
Hi,

I happened to glance at the restrict deformation code out of curiosity. Shouldn't https://github.com/stnava/ANTs/blob/master/ImageRegistration/itkANTSImageRegistrationOptimizer.cxx#L788

read:
```updateFieldInv->SetPixel(index, tempInv);```

instead of:
```updateFieldInv->SetPixel(index, temp);```

Also - can't the ```SetPixel``` calls go after the ```for``` loops, rather than being called multiple times?

If I'm right I can put together a PR, if I'm wrong sorry to waste your time - I'm guessing at how the algorithm works here.

**Comment by stnava** [comment]
PR would be good  -  we dont maintain that function.   Recommend using
antsRegistration.


brian

**Comment by spinicist** [comment]
Ah - I see now. I am using antsRegistration. I was grepping through my ANTs directory to find the file where ```restrict-deformation``` is processed, and I stopped at the first one I found without realising that was old ANTs.

The actual problem that I was trying to diagnose was that I was trying to restrict only the SyN stage of my registration, and it didn't seem to be working. Now I've looked at the code, I understand that all stages up to the one you want have to have the option specified, even if you specify e.g. ```1x1x1x1x1x1``` so they aren't actually restricted.

I am wondering if a different PR, to change the wording of the option to something like:
```     -g, --restrict-deformation PxQxR
          This option allows the user to restrict the optimization of the displacement 
          field, translation, rigid or affine transform on a per-component basis. For 
          example, if one wants to limit the deformation or rotation of 3-D volume to the 
          first two dimensions, this is possible by specifying a weight vector of '1x1x0' 
          for a deformation field or '1x1x0x1x1x0' for a rigid transformation. 
          Low-dimensional restriction only works if there are no preceding 
          transformations. All stages up to and including the desired stage must have 
          this option specified, even if they should not be restricted (in which case
          specify 1x1x1...)
```

**Comment by ntustison** [comment]
Sure.

**Comment by spinicist** [comment]
Done - see #457 

Thanks!
