### ISSUE TITLE
Five dimension output after using registration script

### ISSUE THREAD

**Issue by theasder** [stnava/ANTs#461]
Hello, dear ANTs experts, I have 3 dimensional structural MRI and I am trying to use antsRegistrationSyNQuick to create MRI with registration algorithm. I use as fixed image the first MRI and the rest of images as moving. As an output I get 5-dimensional Warped.nii.gz image. Why?

```fixed_img = paths[0]

out_dir = '/home/mount/neuro-t01-hdd/modified_nii_a/'
dim = 3
script_dir = '/home/mount/neuro-t01-ssd/home/theasder/ANTs/Scripts/antsRegistrationSyNQuick.sh'
threads = 10
transformation = 'a'

for path in paths[:1]:
    moving_img = path
    out = out_dir + moving_img.split('/')[-1][:-4]
    subprocess.call([script_dir, "-d", str(dim), "-f", fixed_img, "-m", moving_img, "-o", out, "-n", str(threads), 
                     "-t", transformation])
```

**Comment by ntustison** [comment]
I'm guessing your moving image is not 3-D.  The script in question is used to register one 3-D image to another.

**Comment by theasder** [comment]
Both fixed and moving images are 3-D, I checked.

**Comment by stnava** [comment]
did you read the output warped image with ITK-SNAP or ANTsR or some other
ITK program?

or look at

PrintHeader myWarped.nii.gz


brian

**Comment by theasder** [comment]
@stnava only used jupyter notebook, np.ndarray.shape

**Comment by stnava** [comment]
that's your problem.


brian

**Comment by ntustison** [comment]
Yes, please verify with ITK-based programs.  Different packages use the meta header information in different ways and we only support ITK-based usage.

**Comment by cookpa** [comment]
The method np.ndarray.shape appears to be a numpy method for manipulating arrays. So at that point the data is not even really an image any longer. In converting to an array, extra dimensions might be added. So a 2D image might go into a 3D array with dimensions (x,y,1). A 3D image could become 5D with dims (x,y,z,1,1). 

The definitive way to see how ANTs will interpret dimensionality is with `PrintHeader`.

**Comment by theasder** [comment]
@cookpa dimenstions are now (256, 256, 256, 1, 3), but they were (256, 256, 256)

**Comment by cookpa** [comment]
Are you sure you're loading the deformed image and not the warp field? The latter is a vector (5D in NIFTI) with 3 components.

If you are convinced that there is a problem with `antsRegistrationSyNQuick.sh`, please share data and the exact command that reproduces the problem.

**Comment by ntustison** [comment]
@cookpa That's what I thought originally but notice that @theasder is using an affine transform.

**Comment by ntustison** [comment]
@theasder What is the output of ``PrintHeader ${movingImage}``?  You have the program available to you if the script is working.

**Comment by theasder** [comment]
I am loading 2 nii.gz files, first is fixed nifti and second is moving nifti image

**Comment by theasder** [comment]
`PrintHeader ${movingImage}`:
```
 Spacing [0.948097, 0.94416, 1.20249]
 Origin [-97.0979, -163.58, 115.598]
 Direction 
-0 -5.08822e-10 1
-5.08822e-10 1 5.08821e-10
-1 -5.08822e-10 0

 Size : 256 256  166

  Image Dimensions   : [256, 256, 166]
  Bounding Box       : {[-97.0979 -163.58 115.598], [145.615 78.125 315.211]}
  Voxel Spacing      : [0.948097, 0.94416, 1.20249]
  Intensity Range    : [0, 2837.78]
  Mean Intensity     : 264.901
  Direction Cos Mtx. : 
-0 -5.08822e-10 1
-5.08822e-10 1 5.08821e-10
-1 -5.08822e-10 0

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_FileNotes = MPR; GradWarp; B1 Correction; N3; Scaled
    aux_file = none
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    descrip = MPR; GradWarp; B1 Correction; N3; Scaled
    dim[0] = 3
    dim[1] = 256
    dim[2] = 256
    dim[3] = 166
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    pixdim[0] = 1
    pixdim[1] = 0.948097
    pixdim[2] = 0.94416
    pixdim[3] = 1.20249
    pixdim[4] = 1
    pixdim[5] = 1
    pixdim[6] = 1
    pixdim[7] = 1
    qform_code = 1
    qoffset_x = 97.0979
    qoffset_y = 163.58
    qoffset_z = 115.598
    quatern_b = 0.707107
    quatern_c = 3.59791e-10
    quatern_d = -0.707107
    scl_inter = 0
    scl_slope = 0
    sform_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 0 0 0 0
    srow_y = 0 0 0 0
    srow_z = 0 0 0 0
    toffset = 0
    vox_offset = 352
```

**Comment by ntustison** [comment]
Thanks.  According to ITK, it [looks](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/dim.html) like a 3-D image.  If another application is reading it in a different manner, then you'll have to reconcile any discrepancies with the other application.

**Comment by ntustison** [comment]
Can you also post the output of PrintHeader on the warped image?

**Comment by theasder** [comment]
```
 Spacing [0.947528, 0.944205, 1.20231]
 Origin [-98.3686, -159.448, 96.7781]
 Direction 
-0 -9.65293e-10 1
-9.65293e-10 1 9.65293e-10
-1 -9.65293e-10 0

 Size : 256 256  166

  Image Dimensions   : [256, 256, 166]
  Bounding Box       : {[-98.3686 -159.448 96.7781], [144.198 82.2685 296.361]}
  Voxel Spacing      : [0.947528, 0.944205, 1.20231]
  Intensity Range    : [0, 1416.18]
  Mean Intensity     : 143.204
  Direction Cos Mtx. : 
-0 -9.65293e-10 1
-9.65293e-10 1 9.65293e-10
-1 -9.65293e-10 0

  Voxel->RAS x-form  : 
  Image Metadata: 
    bitpix = 64
    cal_max = 0
    cal_min = 0
    datatype = 64
    dim[0] = 3
    dim[1] = 256
    dim[2] = 256
    dim[3] = 166
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    pixdim[0] = 1
    pixdim[1] = 0.947528
    pixdim[2] = 0.944205
    pixdim[3] = 1.20231
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 2
    qoffset_x = 98.3686
    qoffset_y = 159.448
    qoffset_z = 96.7781
    quatern_b = 0.707107
    quatern_c = 6.82565e-10
    quatern_d = -0.707107
    scl_inter = 0
    scl_slope = 1
    sform_code = 1
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = -4.41448e-19 9.11434e-10 -1.20231 98.3686
    srow_y = 9.14641e-10 -0.944205 -1.16058e-09 159.448
    srow_z = -0.947528 -9.11434e-10 -5.60149e-19 96.7781
    toffset = 0
    vox_offset = 352
```

**Comment by ntustison** [comment]
Thanks.  So as far as ITK/ANTs is concerned, the warped image is also a 3-D image.
