### ISSUE TITLE
antsCorticalThickness.sh

### ISSUE THREAD

**Issue by bth22** [stnava/ANTs#462]
Hi,

I'm new to ANTS and right off the bat I'm running into an issue here.  I'm trying to run antsCorticalThickness.sh and it says I need to redefine $ANTSPATH.

```
bth22@pfc:/usr/local/pkg/ANTs$ ./antsCorticalThickness.sh 
Error:  we can't find the antsRegistration program.
Perhaps you need to \(re\)define $ANTSPATH in your environment.
```
So I type : `ANTSPATH=/usr/local/pkg/ANTs/` 

But I still get the same error, and checking the source code, it seems that it's looking for the directory where antsRegistration is, and I've verified that is present in that folder, so I'm not sure what to do.  I guess it could be an issue with the arguments not being present but it should give me a usage dialog, right?

Any help is much appreciated, thank you!

**Comment by cookpa** [comment]
ANTSPATH requires a trailing slash.

**Comment by bth22** [comment]
Sorry I did use a trailing slash when I typed it on the command line.

**Comment by jeffduda** [comment]
I think the command you need is:
export ANTSPATH=/usr/local/pkg/ANTs/

**Comment by bth22** [comment]
Ah, that's it, thank you!
