### ISSUE TITLE
Segmentation Fault during apply transforms for Timeseries

### ISSUE THREAD

**Issue by hermeckerogg** [stnava/ANTs#464]
Hello.

Sorry to ask what I believe may be a question that's answered before but I haven't found anything clear on the forums.

I'm trying to co-register some EPI data to a participant's (Skullstripped and bias corrected) T1, so I've been taking the mean EPI image for that subject and running the following:

antsRegistrationSyNQuick.sh -d 3 -o sub_28853_coreg_params -f bias_corr_3dSkullstrip_brain_csub-28853_T1w.nii.gz -m meanusub-28853_task-rest_bold.nii

After which I have been attempting to run antsApplyTransforms on the 4d data. It looks likes its running at first, but then right when it is about to write the files it dies:

antsApplyTransforms -d 3 -r sub_28853_coreg_paramsWarped.nii.gz -i ausub-28853_task-rest_bold.nii -e 3 -t sub_28853_coreg_params1Warp.nii.gz -t sub_28853_coreg_params0GenericAffine.mat -o coreg_ausub-28853_task-rest_bold.nii -v 1

.........
  Applying transform(s) to time point 175 (out of 180).
  Applying transform(s) to time point 176 (out of 180).
  Applying transform(s) to time point 177 (out of 180).
  Applying transform(s) to time point 178 (out of 180).
  Applying transform(s) to time point 179 (out of 180).
Output warped image: coreg_ausub-28853_task-rest_bold.nii
Segmentation fault (core dumped)

Any idea what might be causing this?

Running ANTs _GIT_VERSION_HASH "64645" according to the ProjectSourceVersion on Windows 10 (4.4.0-43-Microsoft) Ubuntu 16.04.2 LTS

Thanks!

**Comment by ntustison** [comment]
Can you post the data?

**Comment by hermeckerogg** [comment]
Of course.

My apologies.

https://drive.google.com/open?id=0B0cZmtBTp5f6R0R4aWJTeW5KWjg

**Comment by ntustison** [comment]
I was able to run it without a problem.  Are you sure you have write privileges for that output directory?  If not, you might want to update your ANTs copy.

**Comment by cookpa** [comment]
+1 write permission and also memory and disk space. You're upsampling a 180-volume data set to T1 resolution and saving it as uncompressed .nii. It will be a large file.

**Comment by ntustison** [comment]
Dovetailing on what Phil said---my output ``coreg_ausub-28853_task-rest_bold.nii`` is over 16 GB.

**Comment by hermeckerogg** [comment]
Well the size would explain that.

May I ask what the flag or command or flag would be to resample it to say 2mm in the process or keep the mean image at its current dimensions during the coregistration then just apply that to the timeseries?

**Comment by ntustison** [comment]
Just resample your reference image (``-r``) to the desired resolution.

**Comment by hermeckerogg** [comment]
Giving that a shot now.

**Comment by hermeckerogg** [comment]
Resampling the T1 for the participants seems to work just fine.

Out of curiosity however I tried using the mean image for the subject's EPI data as the reference image to see if it would keep those dimensions and it looks like it actually truncates the data (see image).

Any idea what might cause that?
![coregrefs](https://user-images.githubusercontent.com/23127333/27921630-ed0ff64c-623d-11e7-8cb5-91ed8886f311.png)

**Comment by cookpa** [comment]
You can't substitute an arbitrary image for the T1 with `-r`. The reference image needs to be in the same physical space as the image used in the registration, in this case the T1.

It's OK to use a resampled version of the T1 because `ResampleImageBySpacing` will preserve the bounding box and header information of the original T1.

**Comment by hermeckerogg** [comment]
Good to know for future reference.

Thank you both!
