### ISSUE TITLE
Strange box around tissue masks

### ISSUE THREAD

**Issue by hermeckerogg** [stnava/ANTs#468]
Sorry to be a pest once again but I'm noticing some white squares (with values of 1) in all my tissue segmentations (GM_norm, WM_norm, and CSF_norm in file) following transformations from native T1 to my group template.

It seems like something that could be easily fixed with ImageMaths but I'd like to know whats causing it.
![whitebox](https://user-images.githubusercontent.com/23127333/28143950-2a364608-672e-11e7-94fc-761e0c3f2e72.png)

I think its an issue with the bounding boxes on the reference image vs the original but I am having trouble narrowing down the direction.

Slurm script I used, templates for reference images, and one participant (its happening to all the participants) in the attached link.

https://drive.google.com/open?id=0B0cZmtBTp5f6SVNOV19uZW8yV1E

**Comment by ntustison** [comment]
Cross reference the ``-f`` option in ``antsApplyTransforms``.  Those voxels are being assigned the default value for voxels which map outside the image domain.  Unless you changed something, that value should be 0.  I do notice that it would appear that you're using an image viewer different from ITK-SNAP.  Please load the images in SNAP and confirm that you see the same thing (I can't download the large file from where I am currently).

**Comment by hermeckerogg** [comment]
The box is there even when I open the image in SNAP.

I didn't have the -f flag before, but I added it and set it to 0 and that seems to have fixed it.

Thank you, I will be sure to do this in the future.
