### ISSUE TITLE
Registration matrix depends on files location

### ISSUE THREAD

**Issue by rubyshamir** [stnava/ANTs#471]
Hi,
We observed slightly different results when running registration between the same images but at different folders. 
The differences start at the third digit after decimal and yield ~0.1mm variance in the specific area of interest. 
While this is insignificant with respect to the expected accuracy of the registration method and the voxel size of 0.5mm^3, we wanted to let you know about this issue.
Thank you,
Ruby

**Comment by gdevenyi** [comment]
Possibly related to https://issues.itk.org/jira/browse/ITK-3513#comment-27631 ?

**Comment by rubyshamir** [comment]
In our case, we saved the text files that represent the transform in ITK format. The only differences were the location of the files (not differences related to different file formats). So, it is hard to tell if the two issues are related. (it is possible that the differences between nii and nrrd in that post are because of their different names rather than way the format is saved, but that needs to be checked)

**Comment by ntustison** [comment]
Are you using the ``ANTS.cxx`` program or ``antsRegistration.cxx``?

**Comment by rubyshamir** [comment]
I am using ANTS (the binary)

**Comment by stnava** [comment]
multithreading causes errors of this magnitude as does random sampling in
mutual information.


brian

**Comment by rubyshamir** [comment]
Ah, this can explain it. Thanks. So sampling more data for the mutual information should reduce the variance? Can I do that?

**Comment by stnava** [comment]
​the biggest issue is multithreading.

second is sampling differences in MI.

not sure how these would manifest in the old ANTS program.

we recommend using antsRegistration which allows much better control over
such issues.



brian

**Comment by rubyshamir** [comment]
OK, thank you very much - that was helpful!

**Comment by cookpa** [comment]
Yes `ANTS` will use random sampling for the MI metric. `antsRegistration` can use either random sampling or a regular grid. 

https://github.com/stnava/ANTs/wiki/ANTS-and-antsRegistration

**Comment by rubyshamir** [comment]
Thank you!
However, when we run ANTS on the same files (located in the same folder) we get the exact same transform. Only when we move them somewhere else, the result becomes different. Therefore I suspect that the error is more related to the multithreading issue.

**Comment by cookpa** [comment]
Threading shouldn't depend on the image location. I will investigate further if you can share the commands and data.

**Comment by rubyshamir** [comment]
We use this script

`#!/bin/bash

function exit_on_error {
    local exit_code=$?
    if [ $? -ne 0 ]; then
        exit "${exit_code}"
    fi
}

ref_file=$1
input_file=$2
out_file=$3
affine_iter_num=$4
mask=$5

if [ -z "${mask}" ]; then
    mask_options=""
else
    mask_options="-x ${mask}"
fi

ANTS 3 -m MI[${ref_file},${input_file},1,64] -o ${out_file}_ --number-of-affine-iterations ${affine_iter_num} -i 0 ${mask_options}
exit_on_error`

**Comment by rubyshamir** [comment]
Thank you!

**Comment by cookpa** [comment]
OK, running this with a single thread, as 

`ANTS.sh $fixed $moving run${iteration} 1000x1000x10`

I get identical affine matrix output, regardless of image location. 

I guess it's theoretically possible they converge on the same result but more likely it means the random sampling in the ANTS MI metric is initialized from a constant seed. 

The location of the images shouldn't matter.

**Comment by rubyshamir** [comment]
Thank you. I appreciate the time you invested to test it.
Do you have the option to test it multi threaded as well?  
What environment are you using?

**Comment by rubyshamir** [comment]
And thank you guys for ANTs !! 
It works very well, flexible enough and yet easy to use!
:)

**Comment by cookpa** [comment]
I tested this on an iMac running OS 10.11 and Linux (Centos 6).

On the Mac, the ANTS affine output is fully reproducible regardless of file location or (surprisingly) number of threads. 

Closing for now, will re-open if there is a full reproducible example with data to test.
