### ISSUE TITLE
iMathGetLargestComponent permanently modifies original image

### ISSUE THREAD

**Issue by ncullen93** [stnava/ANTs#473]
This is obvious in the code - the `LabelImageType` created on line 457 in iMathFunctions.hxx never actually gets allocated/used, and you modify the original image instead on lines 546/550.

Example:

```R
img <- antsImageRead(getANTsRData('r16'))
img2 <- iMath(img, "GetLargestComponent")
plot(img)
```

i can submit a pr if needed

**Comment by cookpa** [comment]
I think this issue belongs to ANTsR?

**Comment by jeffduda** [comment]
Ok, fixed it, but the change won't propagate to ANTsR until the next time it updates the version of ANTs that is uses.
