### ISSUE TITLE
ANTs Python bindings for similarity metrics

### ISSUE THREAD

**Issue by TheChymera** [stnava/ANTs#475]
Two weeks ago, I met someone who claimed to be working on ANTs at the SciPy conference. He said that there was a new and easy way to get similarity metrics between two images via some ANTs Python bindings (something like `ants.similarity.mattes(img1, img2, *args)`). Is this true? and if so, where can I find the Python bindings? I have installed the very newest ANTs (0c138e9fac3d8e9f4bd21c7c1b9311139a571da6) and seem to not get any Python bindings with it.

If either I am entirely misremembering - or my acquaintance misrepresented the feature - could you tell me what the easiest way to get a similarity metric would be?

I would like to get this information in order to generate plots depicting the longitudinal registration quality/stability (multiple timepoint measurements in subjects where no major neuroanatomical change is to be expected) of a given registration type. If I can do this efficiently enough, I might also be looking to write an optimization script to get the best [registration parameters](https://github.com/IBT-FMI/SAMRI/blob/c7acc7118941090c76192a12a8528fbc87ad173e/samri/pipelines/nodes.py#L8).

**Comment by ntustison** [comment]
It might be through [nipype](http://nipype.readthedocs.io/en/latest/).  In ANTs proper, though, you can use MeasureImageSimilarity:

```
$ MeasureImageSimilarity

COMMAND: 
     MeasureImageSimilarity
          Program to calculate the similarity between two images using various metrics. 

OPTIONS: 
     -d, --dimensionality 2/3/4
          Dimensionality of the fixed/moving image pair. 

     -m, --metric CC[fixedImage,movingImage,metricWeight,radius,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  MI[fixedImage,movingImage,metricWeight,numberOfBins,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  Mattes[fixedImage,movingImage,metricWeight,numberOfBins,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  MeanSquares[fixedImage,movingImage,metricWeight,radius=NA,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  Demons[fixedImage,movingImage,metricWeight,radius=NA,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  GC[fixedImage,movingImage,metricWeight,radius=NA,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
          These image metrics are available--- CC: ANTS neighborhood cross correlation, 
          MI: Mutual information, Demons: (Thirion), MeanSquares, and GC: Global 
          Correlation. The "metricWeight" variable is not used. The metrics can also 
          employ a sampling strategy defined by a sampling percentage. The sampling 
          strategy defaults to 'None' (aka a dense sampling of one sample per voxel), 
          otherwise it defines a point set over which to optimize the metric. 

     -x, --masks fixedImageMask
                 [fixedImageMask,movingImageMask]
                 [fixedImageMask,NULL]
          Image masks to limit voxels considered by the metric. 

     -v, --verbose (0)/1
          Verbose output. 

     -h 
          Print the help menu (short version). 

     --help 
          Print the help menu. 
```

**Comment by satra** [comment]
perhaps through simpleitk (http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/60_Registration_Introduction.html). nipype itself is simply wrappers around ants - we try not to touch underlying software :)

**Comment by satra** [comment]
@TheChymera - i have a student who may be starting a project on binary similarity (more general than images, but starting with images as the binary blob).

**Comment by TheChymera** [comment]
> nipype itself is simply wrappers around ants - we try not to touch underlying software :)

Yes, I am fully aware ^^

[This](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/60_Registration_Introduction.html) indeed looks interesting. Does it have python bindings for the similarity functions? 

Other than that, I might as well just write a nipype wrapper for `MeasureImageSimilarity`.

@satra  I'm not sure I understand what your student will be doing. Is binary similarity a reasonable proxy for image similarity? I assume that changes in the affine and data matrix orientation, can lead to highly dissimilar binaries, which may depict identical images. Additionally - though I am a bit more unsure about this - I think that contrast, signal-to-noise ratio, and absolute value of the arbitrary intensity can affect binary similarity more strongly than for instance cross-correlation or mutual-information.

**Comment by satra** [comment]
@TheChymera -  i believe it has bindings for some of the metrics, but a wrapper for measureimagesimilarity would be welcome.

re: project - similarity is rather context dependent. whether it's hash match or image similarity depends on the context. the goal is to come up with context definitions and metrics for similarity within the scope of the context. for example, a defaced and a not defaced brain image from the same participant should be closer within the identification context (do these two blobs belong to the same individual?), but could be further from a image completeness context (do these two blobs contain a full representation of the head?). the goal for the student is to create a library of context dependent functions for similarity and using them to determine risk of identifiability of individuals based on multi-modal data.

**Comment by satra** [comment]
@TheChymera - however, if you can track down the very simple pythonic calls that you suggested in your original post, i am quite curious as to where it is implemented.

**Comment by TheChymera** [comment]
re project: sounds quite interesting, But I still don't know whether it's really aligned with what I am trying to do here. Basically I am trying to get a sense for how well the parameters (which I have spent inordinate amounts of time optimizing) actually provide uniform registration quality across a longitudinal dataset. Ideally I am looking for:

* a metric for how much they bias the inter-individual comparison. This, I think, is best covered by the standard deviation of the similarity scores between my template and all subjects in any one timepoint 
* a metric for how much they bias the intra-individual trajectory comparison. This, I think, is best covered by the standard deviation of the similarity scores between my template and all timepoints for any one subject.

Now that I actually spelled this out, it sounds a lot like an ANOVA... I'm wondering what the interaction effect between animal and timepoint would tell me, in this context. Maybe bias introduced due to slice positioning and preparation :-/

**Comment by TheChymera** [comment]
Ok, so SimpleITK seems [not entirely straightforward to build](), so in the mean time, I am trying to see what can be done with `MeasureImageSimilarity`. However, I can't seem to get it to work (see below example though I have tried many more variations). @ntustison can you maybe clarify the usage instructions?

```
chymera@host ~/src/nipype/nipype/interfaces/ants $ MeasureImageSimilarity -d 3 -m MI["/home/chymera/ni_data/templates/DSURQEc_200micron_average.nii","/home/chymera/composite/sub-4011/ses-ofM/anat/sub-4011_ses-ofM_TurboRARE.nii.gz",1,10,<samplingStrategy=Random>,<samplingPercentage=0.5>] -v 
bash: samplingStrategy=Random: No such file or directory
```

**Comment by ntustison** [comment]
Should be

```
MeasureImageSimilarity -d 3 -m MI["/home/chymera/ni_data/templates/DSURQEc_200micron_average.nii","/home/chymera/composite/sub-4011/ses-ofM/anat/sub-4011_ses-ofM_TurboRARE.nii.gz",1,10,Random,0.5] -v 1
```

**Comment by TheChymera** [comment]
@ntustison thank you :) The help text says that `metricWeight` is not used. Can I concatenate two metrics to get a compound score? I really can't tell by the results (most of the metrics seem to give me similar values with `Regular` sampling - which I need to get perfectly reproducible scores).

**Comment by ntustison** [comment]
> Can I concatenate two metrics to get a compound score?

No, it's for a single image pair.
