### ISSUE TITLE
Multi stage transform using different modalities: --inital-moving-transform per metric

### ISSUE THREAD

**Issue by adhusch** [stnava/ANTs#476]
Hi,

i would like to apply a pretty standard multi stage registration (rigid, affine, SyN) but using a different modality for the SyN stage (i.e. T2) than for the initial stages (T1) due to better contrast in the relevant ROI.

Snippet:
```
...
--transform Rigid[0.1] \
    --metric MI[$TEMPLATE_T1,$SUBJECT_T1,1,32] \
    ...
--transform Affine[0.1] \
    --metric MI[$TEMPLATE_T1,$SUBJECT_T1,1,32,Regular,0.25] \
    ...
--transform SyN[0.1,3,0] \
    --metric CC[$TEMPLATE_T2,$SUBJECT_T2inT1,1,3] \
    ...
```

This works nicely :) However, as the T1 and T2 can not be expected to be exactly aligned a priory, i had to apply a rigid registration of the T2 to the T1 space to be used in the last stage (i.e. creating a T2inT1 image), thus breaking the "only one interpolation" concept of ANTs. 

To keep the "only one interpolation" concept a method to apply the previously determined rigid transform between the T2 and the T1 space on a per metric basis in the last stage would be needed.
E.g. like:

```
...
--transform Rigid[0.1] \
    --metric MI[$TEMPLATE_T1,$SUBJECT_T1,1,32] \
    ...
--transform Affine[0.1] \
    --metric MI[$TEMPLATE_T1,$SUBJECT_T1,1,32,Regular,0.25] \
    ...
--transform SyN[0.1,3,0] \
    --metric CC[$TEMPLATE_T2,$SUBJECT_T2,1,3] \
    --initial-moving-transform trans_t2_to_t1GenericAffine.mat \
    ...
```

If this is already possible in some way i would be very grateful for a hint :) Otherwise it would be great if you could consider it as a #wouldbenice

Thank you!

Best
Andy

**Comment by ntustison** [comment]
Just call ``antsRegistration`` twice.   The first call uses the T1 to calculate the rigid + affine transform.  The second call uses the T2 the calculate SyN with the set of initial transforms being trans_t2_to_t1GenericAffine.mat and trans_from_first_call0GenericAffine.mat.

**Comment by adhusch** [comment]
Ah.. now if feel stupid :-) Great! Thanks a lot!

**Comment by ntustison** [comment]
It's not totally obvious since ``antsRegistration`` is so flexible with the permutations of command-line options available.  One might save time with I/O by allowing what you suggested and everything associated with that change would be relatively straightforward except for parsing the command line arguments.  We'd have to allow for specifying an initial-transform for each registration stage and simply asking you to call ``antsRegistration`` twice is much easier than making those required code changes.

**Comment by adhusch** [comment]
I am fine with the two calls solution. I was thinking a bit to much inside the box in the sense that multiple calls to `antsRegistration` would automatically break the "only one interpolation" idea, but that's obviously not the case when done properly. Thx again.
