### ISSUE TITLE
Motivation for Gaussian interpolation for ANTsCT images

### ISSUE THREAD

**Issue by adrose** [stnava/ANTs#477]
Hi All,

I am curious about the motivation for using Gaussian interpolation in the ANTsCt pipeline when normalizing the cortical thickness maps into template space. 

https://github.com/stnava/ANTs/blob/master/Scripts/antsCorticalThickness.sh#L1297

Thanks!

**Comment by ntustison** [comment]
I don't believe there's a scientifically vetted reason why Gaussian interpolation is being used here.  Perhaps it was because around this time Paul Yushkevich was doing some work on the interpolators which I put into [ITK](http://www.insight-journal.org/browse/publication/705) and made available in ``antsApplyTransforms`` and so I had it fresh on my mind.

**Comment by adrose** [comment]
Thanks @ntustison.

Is there a ANTs accepted method for validating interpolation techniques? Just curious, again thanks!

**Comment by ntustison** [comment]
In terms of interpolation, there's nothing that's "ANTs-accepted".  The technical papers that have appeared over the years (e.g., [Lehmann, et al.](http://ieeexplore.ieee.org/document/816070/)) are prior to ANTs and you'd have to refer to those.  Beyond any sort of technical considerations of specific pipeline components, we've gravitated towards more clinically-oriented evaluation strategies of our software.  For example, in our CT evaluation [paper](https://www.ncbi.nlm.nih.gov/pubmed/24879923) it would've been really easy (and simultaneously counterproductive) to get bogged down in performance comparisons between individual steps (such as bias correction or segmentation) and/or the fine-tuning of parameters and their effects.  Instead, many of the parameters/components are chosen based on expertise and experience accumulated over the years and with the hope that they're generally applicable to a variety of data sets/problems.

**Comment by adrose** [comment]
Thanks @ntustison! Certainly very insightful. 

Certainly don't want to get bogged down in the minutia, just noticing some weird behaviors when I register prior images as an estimate of GMD (as done by [gennatas et al.](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=XbIGdIUAAAAJ&sortby=pubdate&citation_for_view=XbIGdIUAAAAJ:1DsIQWDZLl8C) ) into template space. I was finding low values within GMD and some large values within the WM. Happy to expand on this if it the issues aren't clear.

I certainly respect the prioritization of portability over specificity in this case though.

**Comment by ntustison** [comment]
>  just noticing some weird behaviors when I register prior images as an estimate of GMD

Every once in awhile I'll come across some odd behavior with specific images so I'll switch over to linear interpolation.
