### ISSUE TITLE
Seg fault running buildtemplateparallel.sh

### ISSUE THREAD

**Issue by bth22** [stnava/ANTs#478]
Hi,

I'm running this command:

~/ANTs/Scripts/buildtemplateparallel.sh -d 3 -o template -z /mnt/mobydisk/groupshares/jhanson/HBN_mri/MNI152_T1_2mm.nii.gz -c 5 /ihome/jhanson/bth22/jhanson/HBN_mri/NDAREF893ZM8/anat/NDAREF893ZM8_T1w_MEMPRAGE_SAG_RMS.nii.gz \

Followed by 99 more T1 scans to make a template file.

It successfully submits the jobs through SLURM, but the next step fails.

--------------------------------------------------------------------------------------
 shapeupdatetotemplate 1
--------------------------------------------------------------------------------------
/ihome/jhanson/bth22/ANTs/Scripts/buildtemplateparallel.sh: line 352: 29534 Segmentation fault      (core dumped) ${ANTSPATH}/AverageImages $dim ${template} 1 ${outputname}*formed.nii.gz

Any help is much appreciated.

**Comment by cookpa** [comment]
Do the ${outputname}*formed.nii.gz files exist? If not, it indicates a problem with registration. 

We don't maintain this script any more, but similar functionality is in `antsMultivariateTemplateConstruction.sh`.

**Comment by bth22** [comment]
I moved on and used antsMultivariateTemplateConstruction2, since that was recommended in another thread, is that script roughly the same?

**Comment by ntustison** [comment]
``amvtc.sh`` uses the original ``ANTS`` program whereas ``amvtc2.sh`` uses ``antsRegistration``.

**Comment by bth22** [comment]
Okay great, thank you!

**Comment by cookpa** [comment]
Just to clarify, `buildtemplateparallel.sh` also uses ANTS, so `antsMultivariateTemplateConstruction.sh` is the closest current implementation.
