### ISSUE TITLE
antsCorticalThickness not using atlas?

### ISSUE THREAD

**Issue by SGGordon** [stnava/ANTs#482]
Hi all,

I'm trying to use ANTs to measure cortical thickness values in specific regions of cat cortex. I've created an average brain to use as a template and have the tissue priors for it. I also have an extensive 3D atlas of the cat brain. However, when I try to run

antsCorticalThickness -d 3 -a subject_scan.nii -e template_brain.nii.gz -m template_brain_mask -p templatePosteriors%d.nii.gz -t template_brain.nii.gz -k 1 -f template_brain_mask.nii.gz -r Cat_Atlas.nii.gz -o Cat1

note: I do the skull-stripping myself as it doesn't take very long and automated algorithms do a bad job on cat cortex. For this reason, I have used a skull-stripped average brain for both -e and -t.

The Cat1CorticalThickness.nii.gz file seems accurate, but I thought that Cat1brainvols.csv would have different values for each labelled region. Instead it just has one set of values for the entire brain. Is there something I'm missing, or is there another step after antsCorticalThickness?

**Comment by ntustison** [comment]
``antsCorticalThickness`` was developed specifically for humans and so it's unclear how it would do for other species.  I'm glad you got it to work but I'd want to look at the data just to make sure everything is working correctly.  You can supply pre-skull stripped images but you just have to do it correctly so that the script sees that the file is already there and skips that step or you need to specify the correct step (``-y`` option).  The brainvols.csv file should have the volumes for the gm/wm/csf etc., not just the whole brain.

**Comment by cookpa** [comment]
To skip brain extraction, copy your manual brain mask such that it matches

```
${OUTPUT_PREFIX}BrainExtractionMask.${OUTPUT_SUFFIX}
```

For segmentation, the script has hard-coded assumptions about the template posteriors being coded 1=CSF, 2="Cortical GM", 3=WM, 4="Subcortical GM". If this is not true then multiple things might go wrong, including the production of the `brainvols.csv` file.

I recommend condensing the atlas into these 4 classes, or if you want to model the usual human workflow more closely, add a fifth and sixth class for the brainstem and cerebellum respectively.

You can use the full atlas to query GM / thickness in the specific ROIs as a post-processing step.

**Comment by SGGordon** [comment]
Thank you for these quick replies.

I must have misunderstood what *brainvols.csv was supposed to contain. It does indeed contain PearsonCorrelation, BVol, GVol, WVol and ThicknessSum, but I had thought that it would use the atlas supplied in -f to break the thickness map into different ROIs and show stats on them. That is a different program? Also, does this mean that -f is just to provide the same general information as -p?

**Comment by ntustison** [comment]
The parameter descriptions are in the help menu ``antsCorticalThickness.sh -h 1``.   In addition to the help menu, you might want to read this [paper](https://www.ncbi.nlm.nih.gov/pubmed/24879923) and run this [example](https://github.com/ntustison/antsCorticalThicknessExample) to help you understand what the parameters mean.  To answer your specific question, though, the pipeline is separate from gathering stats.  Simple put the labels in the same space as your target image and use ``ImageMath`` to calculate ROI stats, cf, ``ImageMath | grep LabelStats``.

**Comment by SGGordon** [comment]
Thank you for the help, and sorry for the confusion.
