### ISSUE TITLE
antsRegistration: restricting the deformation

### ISSUE THREAD

**Issue by lennartverhagen** [stnava/ANTs#484]
Hi guys, I'm using ANTs to correct for time-varying magnetic field distortions in awake monkey fMRI. This is not conventional fMRI: we are guaranteed that the brain is not moving, but the field distortions are massive and rapidly changing. This means we cannot run "conventional" ANTs motion correction where the deformation of surrounding volumes impacts the estimation of the deformation of the current volume. In fact, we have found that we need to correct for the distortions slice-by-slice. Too bad. Because the distortions are only occurring in the phase-encoding direction, we can further restrict the deformations. We are running antsRegistration with `--dimensionality 2`, so for a `Rigid` transformation I would have expected that `--restrict-deformation 0x1x0x0` would only allow translations in the y-direction. It turns out to allow rotations as well. I did find the `Translation` option for the transformation, which I could restrict with `--restrict-deformation 0x1`. Good. Is there any way to restrict the `Affine` transformation to translation and scaling alone, not allowing any rotations?

**Comment by ntustison** [comment]
Using the ``--restrict-deformation`` requires knowledge of how the actual transform parameters are stored so your expectations could be wrong.  A 2-D rigid transform uses the [itk::Euler2DTransform](https://itk.org/Doxygen/html/classitk_1_1Euler2DTransform.html) class.  

A similarity transform is translation + scaling + rotation which would be closer to what you want vs. an affine transform.

**Comment by lennartverhagen** [comment]
Nick, thank you. This was super helpful! I hadn't realised that the `--restrict-deformation` could be anything else than `1x1x1x1x1x1` for 3D rigid transformations, or `1x1x1` for everything else. Your pointer to the ITK class is very helpful. For example, at [itk::Rigid2DTransform](https://itk.org/Doxygen/html/classitk_1_1Rigid2DTransform.html) I learned that:```The serialization of the optimizable parameters is an array of 3 elements ordered as follows: p[0] = angle p[1] = x component of the translation p[2] = y component of the translation```
Well, that corrects my assumptions :)

> A similarity transform is translation + scaling + rotation which would be closer to what you want vs. an affine transform.

Ah cool, now I realise what the `Similarity` transform is doing. Again, very helpful. I think I'm going to have a browse in the ITK documentation. I might be able to figure out what the `CompositeAffine` is and why the `Exponential` and `BSplineExponential` hardly seem to have an impact with my intuitive guesses for the parameters.

**Comment by lennartverhagen** [comment]
A quick follow-up, in case anybody else is interested: the `Similarity` transform optimises a single homogeneous scaling parameter, so you are not able to restrict the scaling to a certain dimension. See this [page](https://itk.org/Doxygen/html/classitk_1_1Similarity2DTransform.html).
```The serialization of the optimizable parameters is an array of 3 elements ordered as follows: p[0] = scale p[1] = angle p[2] = x component of the translation p[3] = y component of the translation```

**Comment by lennartverhagen** [comment]
The [itk::AffineTransform](https://itk.org/Doxygen/html/classitk_1_1AffineTransform.html) page does not explicitly specify the order of the parameters that are being optimised, so I'm going to assume it optimises the n x n transformation matrix (A) followed by the 1 x n translation vector (b). I suspect that the parameter order will be:
A = [ p[0] p[1]
         p[2] p[3] ]
b = [ p[4]
         p[5] ]
I'm going to assume that if I want to allow only translation and scaling along the y-dimension I should restrict as following: `--restrict-deformation 0x0x0x1x0x1`. Fingers crossed.

**Comment by lennartverhagen** [comment]
This works great for my purposes. Case closed.
