### ISSUE TITLE
antsMultivariateConstruction2.sh cannot access Warp/GenericAffine.mat

### ISSUE THREAD

**Issue by bth22** [stnava/ANTs#489]
**Here is the specific error I'm getting:**
 ```
(Tue Aug 22 11:23:49 EDT 2017) Still waiting for 59 jobs

    Job 445623 is in state RUNNING
    Job 445575 is in state RUNNING
    Job 445629 is in state RUNNING
    Job 445622 is in state RUNNING
    Job 445578 is in state RUNNING
    Job 445627 is in state RUNNING
    Job 445628 is in state RUNNING
    Job 445626 is in state RUNNING
    Job 445625 is in state RUNNING
    Job 445624 is in state RUNNING
    Job 445580 is in state RUNNING
    Job 445630 is in state RUNNING
  (Tue Aug 22 11:33:49 EDT 2017) Still waiting for 12 jobs

  No more jobs in queue

ls: cannot access HBN_two*Warp.nii.gz: No such file or directory
ls: cannot access HBN_two*GenericAffine.mat: No such file or directory
shapeupdatetotemplate()
--------------------------------------------------------------------------------------
 shapeupdatetotemplate---voxel-wise averaging of the warped images to the current template
Tue Aug 22 11:43:49 EDT 2017
--------------------------------------------------------------------------------------
ls: cannot access HBN_twotemplate0*WarpedToTemplate.nii.gz: No such file or directory
ERROR shapeupdatedtotemplate - imagelist length is 0

```
**Here's what I'm running, with just one subject out of 100 listed:**
```
~/ANTs/Scripts/antsMultivariateTemplateConstruction2.sh -d 3 -v 256gb -o HBN_two -c 5 -i 5 -r 1 -s 3x2x1x0x0 -g .2 -z HBNtemplate0.nii.gz \
/ihome/jhanson/bth22/jhanson/HBN_mri/NDARGB441VVD/anat/NDARGB441VVD_T1w_MEMPRAGE_SAG_RMS.nii.gz \
```

**Comment by ntustison** [comment]
Try using absolute paths for all command line options.

**Comment by bth22** [comment]
Oh right, that's probably it, will let you know.

**Comment by cookpa** [comment]
On SourceForge, someone had this problem because of file names with multiple periods. Alphanumeric (+ underscores) paths may help

https://sourceforge.net/p/advants/discussion/840261/thread/d459895d/

**Comment by bth22** [comment]
Do I also need an absolute path for the -o option?  It produced the same error when I changed it to an absolute path for the -z option.  In response to cookpa, I do have periods at the end of the file names but only for the .nii.gz extension.

**Comment by ntustison** [comment]
Try using absolute paths for __all__ command line options.

**Comment by bth22** [comment]
Okay that didn't work.

**Comment by bth22** [comment]
From the slurm output of one run, might be relevant.

ERROR:  The number of smoothing sigmas does not match the number of levels.
Using single precision for computations.
Input scalar image: /ihome/jhanson/bth22/jhanson/preproc_2/HBN_twotemplate0NDARVG461LA2_T1w_MEMPRAGE_SAG_RMSRepaired.nii.gz
Reference image: /ihome/jhanson/bth22/jhanson/preproc_2/HBN_twotemplate0.nii.gz
Transform file does not exist: /ihome/jhanson/bth22/jhanson/preproc_2/HBN_twoNDARVG461LA2_T1w_MEMPRAGE_SAG_RMS940GenericAffine.mat
Can't read initial transform /ihome/jhanson/bth22/jhanson/preproc_2/HBN_twoNDARVG461LA2_T1w_MEMPRAGE_SAG_RMS940GenericAffine.mat

**Comment by cookpa** [comment]
I think you got it - you have specified custom smoothing sigmas with five levels, but the default shrink factors (-f) and iterations (-q) have four levels.

**Comment by bth22** [comment]
Okay I'll try it just 3x2x1x0

**Comment by bth22** [comment]
Looks like that got it, thanks guys!
