### ISSUE TITLE
Current implementation of cook template priors

### ISSUE THREAD

**Issue by bth22** [stnava/ANTs#491]
Hi all,

I attempted to run the cook template priors script example on this page: https://github.com/ntustison/antsCookTemplatePriorsExample

But I found that antsMalfLabeling.sh isn't a part of the master branch anymore and I get these errors plus a lot after that.  

./antsCookTemplatePriorsCommand.sh: line 35: /usr/local/pkg/ANTs//antsMalfLabeling.sh: No such file or directory
./antsCookTemplatePriorsCommand.sh: line 56: ThresholdImage: command not found

It looks like antsCookTemplatePriors.sh is the replacement, but I'm not sure how to use it in a similar way.  I want to generate the tissue probability priors mentioned in the -p option of antsCookTemplatePriors.sh using a template I made from my subjects using antsMultivariateTemplateConstruction2.sh using the OASIS/IXI/etc. templates.  Any help is much appreciated!

**Comment by ntustison** [comment]
Should be [fixed](https://github.com/ntustison/antsCookTemplatePriorsExample/commit/b140101b462a3dba92434b59398573527071d4eb#diff-fb306c2f81a5cf0b2a4905484ca567b0) now.

**Comment by bth22** [comment]
Alright I'll give that a try, thanks Nick.

**Comment by bth22** [comment]
Getting this error with JLF:
```
/ihome/jhanson/bth22/jhanson/cookpriors_mri/Output/job_ADNI_template_masked_0.sh
Exception Object caught: 

itk::ExceptionObject (0x374ee80)
Location: "unknown" 
File: /ihome/jhanson/bth22/antsbin/ITKv4-install/include/ITK-4.12/itkImageMomentsCalculator.hxx
Line: 156
Description: itk::ERROR: ImageMomentsCalculator(0x374dce0): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.



```

Any ideas?

**Comment by ntustison** [comment]
https://github.com/ntustison/antsCookTemplatePriorsExample/commit/78519eb5e767c43727290be97b7a13b4a1b5049b

**Comment by bth22** [comment]
Yup that was my next issue, looks like the script completed now, thanks for everything!
