### ISSUE TITLE
Please define a next (2.1.0?) milestone and shuffle issues into it

### ISSUE THREAD

**Issue by yarikoptic** [stnava/ANTs#79]
to get a clue if next release is coming some time soon ;)

**Comment by armaneshaghi** [comment]
new issue is released today, I have compiled it on redhat and debian machines, and will also upload a Yosemite version. Please see github releases page.

**Comment by yarikoptic** [comment]
Great -- thanks @armaneshaghi

**Comment by armaneshaghi** [comment]
Do we need to do anything for Neurodebian?

**Comment by yarikoptic** [comment]
On Fri, 23 Jan 2015, Arman Eshaghi wrote:

>    Do we need to do anything for Neurodebian?

thanks for asking!

what is minimal ITK version I would need?

build fails for me on debian sid
http://www.onerussian.com/tmp/ants-2.1.0-debian-build.log
having 

ii  libinsighttoolkit4-dev            4.6.0-3+b2            i386

here is the initial error:

[  4%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DFloat.cxx.o
cd /home/yoh/deb/gits/pkg-exppsy/ants/obj-i586-linux-gnu/Examples && /usr/lib/ccache/c++   -DITK_IO_FACTORY_REGISTER_MANAGER -g -O0 -fstack-protector-strong -Wformat -Werror=format-security   -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel -fPIC  -I/home/yoh/deb/gits/pkg-exppsy/ants/obj-i586-linux-gnu/Examples -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/. -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/../Temporary -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/../Tensor -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/../GraphTheory -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/../ImageSegmentation -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/../ImageRegistration -I/home/yoh/deb/gits/pkg-exppsy/ants/Examples/../Utilities -I/home/yoh/deb/gits/pkg-exppsy/ants/obj-i586-linux-gnu/ITKIOFactoryRegistration -I/usr/include/hdf5/serial -I/build/insighttoolkit4-BJt_oq/insighttoolkit4-4.6.0/BUILD/Modules/ThirdParty/HDF5/src -I/usr/include/dcmtk -I/usr/include/dcmtk/oflog -I/usr/include/dcmtk/ofstd -I/usr/include/dcmtk/dcmtls -I/usr/include/dcmtk/dcmsr -I/usr/include/dcmtk/dcmsign -I/usr/include/dcmtk/dcmqrdb -I/usr/include/dcmtk/dcmpstat -I/usr/include/dcmtk/dcmnet -I/usr/include/dcmtk/dcmjpls -I/usr/include/dcmtk/dcmjpeg -I/usr/include/dcmtk/dcmimgle -I/usr/include/dcmtk/dcmimage -I/usr/include/dcmtk/dcmdata -I/usr/include/dcmtk/config -I/usr/include/i386-linux-gnu -I/usr/include/gdcm-2.4 -I/usr/include/ITK-4.6    -o CMakeFiles/antsUtilities.dir/antsRegistration3DFloat.cxx.o -c /home/yoh/deb/gits/pkg-exppsy/ants/Examples/antsRegistration3DFloat.cxx
In file included from /home/yoh/deb/gits/pkg-exppsy/ants/Examples/itkantsRegistrationHelper.h:1120:0,
                 from /home/yoh/deb/gits/pkg-exppsy/ants/Examples/antsRegistrationTemplateHeader.h:14,
                 from /home/yoh/deb/gits/pkg-exppsy/ants/Examples/antsRegistration2DDouble.cxx:1:
/home/yoh/deb/gits/pkg-exppsy/ants/Examples/itkantsRegistrationHelper.hxx: In instantiation of 'int ants::RegistrationHelper<TComputeType, VImageDimension>::DoRegistration() [with TComputeType = double; unsigned int VImageDimension = 2u]':
/home/yoh/deb/gits/pkg-exppsy/ants/Examples/antsRegistrationTemplateHeader.h:970:35:   required from 'int ants::DoRegistration(itk::ants::CommandLineParser::Pointer&) [with TComputeType = double; unsigned int VImageDimension = 2u; itk::ants::CommandLineParser::Pointer = itk::SmartPointer<itk::ants::CommandLineParser>]'
/home/yoh/deb/gits/pkg-exppsy/ants/Examples/antsRegistration2DDouble.cxx:8:46:   required from here
/home/yoh/deb/gits/pkg-exppsy/ants/Examples/itkantsRegistrationHelper.hxx:1278:13: error: 'itk::SmartPointer<itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::AffineTransform<double, 2u>, itk::Image<double, 2u> > >::ObjectType' has no member named 'SetFixedPointSet'
             affineRegistration->SetFixedPointSet( n, stageMetricList[n].m_FixedPointSet.GetPointer() );
             ^
/home/yoh/deb/gits/pkg-exppsy/ants/Examples/itkantsRegistrationHelper.hxx:1279:13: error: 'itk::SmartPointer<itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::AffineTransform<double, 2u>, itk::Image<double, 2u> > >::ObjectType' has no member named 'SetMovingPointSet'
             affineRegistration->SetMovingPointSet( n, stageMetricList[n].m_MovingPointSet.GetPointer() );

**Comment by armaneshaghi** [comment]
I used ITK current master without any problems on Debian Jessie. Will
upload the binary to github release page in a few minutes...

**Comment by yarikoptic** [comment]
On Fri, 23 Jan 2015, Arman Eshaghi wrote:

>    I used ITK current master without any problems on Debian Jessie. Will
>    upload the binary to github release page in a few minutes...

I am building off v2.1.0 tag with my debian/ on top, without superbuild, i.e. with options

                -DANTS_SUPERBUILD:BOOL=OFF \
                -DANTS_USE_GIT_PROTOC:BOOL=OFF \
                -DCOPY_SCRIPT_FILES_TO_BIN_DIR:BOOL=OFF \
                -DCMAKE_SKIP_RPATH:BOOL=OFF \
                -DUSE_SYSTEM_ITK:BOOL=ON \
                -DUSE_VTK:BOOL=OFF \
                -DBUILD_SHARED_LIBS:BOOL=ON \
                -DRUN_SHORT_TESTS:BOOL=ON \
                -DRUN_LONG_TESTS:BOOL=OFF \
                -DEXECUTABLE_OUTPUT_PATH:PATH=$(DESTBINDIR) \
                --debug-output

and tried again in a fresh clean jessie i386 using

sudo apt-get install fakeroot; git clone git://github.com/neurodebian/ANTs -b debian; cd ANTs; fakeroot debian/rules binary

with the same result:

[  1%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o
cd /tmp/ANTs/obj-i586-linux-gnu/Examples && /usr/bin/c++   -DITK_IO_FACTORY_REGISTER_MANAGER -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2   -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel -fPIC  -I/tmp/ANTs/obj-i586-linux-gnu/Examples -I/tmp/ANTs/Examples/. -I/tmp/ANTs/Examples/../Temporary -I/tmp/ANTs/Examples/../Tensor -I/tmp/ANTs/Examples/../GraphTheory -I/tmp/ANTs/Examples/../ImageSegmentation -I/tmp/ANTs/Examples/../ImageRegistration -I/tmp/ANTs/Examples/../Utilities -I/tmp/ANTs/obj-i586-linux-gnu/ITKIOFactoryRegistration -I/usr/include/hdf5/serial -I/build/insighttoolkit4-BJt_oq/insighttoolkit4-4.6.0/BUILD/Modules/ThirdParty/HDF5/src -I/usr/include/dcmtk -I/usr/include/dcmtk/oflog -I/usr/include/dcmtk/ofstd -I/usr/include/dcmtk/dcmtls -I/usr/include/dcmtk/dcmsr -I/usr/include/dcmtk/dcmsign -I/usr/include/dcmtk/dcmqrdb -I/usr/include/dcmtk/dcmpstat -I/usr/include/dcmtk/dcmnet -I/usr/include/dcmtk/dcmjpls -I/usr/include/dcmtk/dcmjpeg -I/usr/include/dcmtk/dcmimgle -I/usr/include/dcmtk/dcmimage -I/usr/include/dcmtk/dcmdata -I/usr/include/dcmtk/config -I/usr/include/i386-linux-gnu -I/usr/include/gdcm-2.4 -I/usr/include/ITK-4.6    -o CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o -c /tmp/ANTs/Examples/antsRegistration2DDouble.cxx
In file included from /tmp/ANTs/Examples/itkantsRegistrationHelper.h:1120:0,
                 from /tmp/ANTs/Examples/antsRegistrationTemplateHeader.h:14,
                 from /tmp/ANTs/Examples/antsRegistration2DDouble.cxx:1:
/tmp/ANTs/Examples/itkantsRegistrationHelper.hxx: In instantiation of 'int ants::RegistrationHelper<TComputeType, VImageDimension>::DoRegistration() [with TComputeType = double; unsigned int VImageDimension = 2u]':
/tmp/ANTs/Examples/antsRegistrationTemplateHeader.h:970:35:   required from 'int ants::DoRegistration(itk::ants::CommandLineParser::Pointer&) [with TComputeType = double; unsigned int VImageDimension = 2u; itk::ants::CommandLineParser::Pointer = itk::SmartPointer<itk::ants::CommandLineParser>]'
/tmp/ANTs/Examples/antsRegistration2DDouble.cxx:8:47:   required from here
/tmp/ANTs/Examples/itkantsRegistrationHelper.hxx:1278:13: error: 'itk::SmartPointer<itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::AffineTransform<double, 2u>, itk::Image<double, 2u> > >::ObjectType' has no member named 'SetFixedPointSet'
             affineRegistration->SetFixedPointSet( n, stageMetricList[n].m_FixedPointSet.GetPointer() );

**Comment by stnava** [comment]
Probably need itk 4.7 , possibly development itk ....

**Comment by yarikoptic** [comment]
github ate my last email reply again...

>    Probably need itk 4.7 , possibly development itk ....

ah -- the no go for debian folks atm :-/

I have filed a bug report to seek 4.7 packaged for Debian (experimental) and we might then provide backports from neurodebian.

could someone check if it is at least compatible with it and doesn't require development version?

**Comment by stnava** [comment]
OK ... iterate a couple more times and this should be worked out for the
longer  term.

**Comment by yarikoptic** [comment]
not sure if I grasped exactly what was the "this" someone should iterate and then it must be worked out: emails to github or builds for debian ;-)
